### ISSUE TITLE
Things possible in Firefox 57+ (by using CSS code in userChrome.css/userContent.css)

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#1]
**As long as userChrome.css and userContent.css are supported by Firefox, Photon UI content can be modified using CSS tweaks, but CSS code can not create entirely new items, buttons or toolbars.**

Most CSS code is _copy/pasted_ from already available 'Classic Theme Restorer' and 'Classic Toolbar Buttons' add-on code.

**_Promo screenshots (Win7s AeroBlue colors are possible on other OSs too)_**

![main_v2](https://user-images.githubusercontent.com/6013569/30641051-e85b3b62-9e05-11e7-907e-61538f7e5cee.png)
![appmenu_in_titlebar2](https://user-images.githubusercontent.com/6013569/30640889-35554a9e-9e05-11e7-9616-626e1dd6fe24.png)
![autocomplete](https://user-images.githubusercontent.com/6013569/30417515-4edfdaa8-9930-11e7-9736-45a9e6dabfde.png)
![bookmarks_menu](https://user-images.githubusercontent.com/6013569/30417518-50944bb8-9930-11e7-9ce6-50852c86ecaa.png) ![cbackfor](https://user-images.githubusercontent.com/6013569/30785107-6b66264e-a161-11e7-886e-16139acd1f2f.png)

![w10_2](https://user-images.githubusercontent.com/6013569/30324380-23717e6e-97c1-11e7-8f9c-3ea74143d3dc.png)
![menubar](https://user-images.githubusercontent.com/6013569/30417951-adadb6bc-9931-11e7-9252-f2ce544c53a4.png)
![compact_tb_padding](https://user-images.githubusercontent.com/6013569/30641703-6012a5ee-9e08-11e7-98b8-b553cf8682a6.png)

![am](https://user-images.githubusercontent.com/6013569/31349183-7bf1b2f4-ad22-11e7-8699-7037e85cb22c.png)
![pp](https://user-images.githubusercontent.com/6013569/31349182-7bee58fc-ad22-11e7-9c3e-e467fbc515e7.png)
![lbp](https://user-images.githubusercontent.com/6013569/31349185-7cc97bc6-ad22-11e7-978e-0100b5d0f513.png)

**_Tested /  confirmed working in userChrome.css/userContent.css (at the moment)_**
- [Tabs] squared tabs (with rounded top corners)
- [Tabs] custom tab height
- [Tabs] (old) tab appearance/colors for active/non-active/hovered/pending/unread tabs
- [Tabs] remove ridiculous tab toolbar gap before first tab (in normal window mode without menubar)
- [Tabs] tabs not on top: tabs toolbar after navigation and bookmarks toolbars
- [Tabs] empty tab favicon: tab icon for tabs without favicons
- [Tabs] hide tabs toolbar for tab sidebar WEs (not visible on screenshots)
- [Buttons] navigation toolbar buttons: 'classic' button appearance _(like offered by Classic Toolbar Buttons add-on)_
- [Buttons] bookmarks toolbar buttons: 'default' button appearance
- [Buttons] default browser buttons: custom icon colors
- [Buttons] application/hamburger button: move button to the left
- [Buttons] application/hamburger button: cheat button into tabs toolbar
- [Buttons] application/hamburger button: custom label ("Firefox" on screenshots)
- [Buttons] application/hamburger button: different colors (Default, Aurora, Nightly, Transparent...)
- [Buttons] bookmarks menu button: label on bookmarks toolbar
- [Buttons] bookmarks menu popup: classic appearance
- [Buttons] custom images for toolbar buttons _(like offered by Classic Toolbar Buttons add-on)_
- [Buttons] downloads button: always visible _(there is also an option for that in 'Customize...' mode)_
- [Buttons] 'more' compact navigation toolbar buttons
- [Buttons] text / icon+text modes
- [Location Bar] location bar and search bar text size
- [Location Bar] location bars dropmarker at the end
- [Location Bar] change location bars icon padding
- [Location Bar] identity box colors for secure/valid connections
- [Location Bar] width/height tweaks to location bar popup
- [Location Bar] location bar popup: classic two lined results
- [General] hiding ui elements not removable by default (e.g. action menu in location bar, private mask)
- [General] context menu item labels instead of icons for back, forward, reload, bookmark this page
- [General] lw-theme support for squared tabs and 'tabs not on top' appearance
- [General] bookmarks toolbar: old padding
- [General] bookmarks toolbar: old height
- [Add-on Manager] alternative appearance
- [Add-on Manager] add-on version number in main lists
- [Preferences] alternative appearance
...
Full list: https://github.com/Aris-t2/CustomCSSforFx/issues/2

 _Notes_
- [Buttons] application/hamburger button 'in titlebar': space before tabs has to be adjusted manually (depends on custom button title length),  'Titlebar' and 'Drag Space' checkboxes have to be disabled 'Customize...' area)
- [Buttons] application/hamburger button jumps back to nav-bar, if menubar is visible (prevents overlapping glitches)
- [Location Bar] popup width has to be adjusted manually to match location bars width for normal, maximized and fullscreen window modes

**_Already in Firefox 57+ without installing WebExtensions (compared to Firefox 56 or older)_**
- [Buttons] star/bookmark button: button in location bar
- [Buttons] bookmarks menu button: disconnected from star button (_see 'Customize...' area_)
- [Buttons] back and forward buttons: disconnected from location bar
- [Buttons] back and forward buttons: separately movable within navigation toolbar bar
- [Buttons] stop and reload buttons: buttons combined and outside location bar
- [Buttons] sidebar button: one button for bookmarks, history and synced tabs
- [Buttons] application/hamburger button: popup 'closer' to the old one _(no huge icons)_
- [Buttons] downloads button: progress indicator below icon
- [General] flexible spaces (_see 'Customize...' area_)
- [General] drag space: space above tabs toolbar (_see 'Customize...' area_)
- [General] toolbar modes: compact, normal, large (_see 'Customize...' area_)

**_Things possible by installing WebExtensions_**
- [Buttons] Old 'Firefox' menu (WIP): [Application Menu](https://addons.mozilla.org/addon/application-menu/)
- [Buttons] RSS button in location bar: [Awesome RSS](https://addons.mozilla.org/addon/awesome-rss/)
- [Buttons] Reload/stop buttons in location bar: [Reload in address bar](https://addons.mozilla.org/addon/reload-in-address-bar/?src=cb-dl-created) or [Australis-like refresh in URL bar](https://addons.mozilla.org/addon/australis-refresh-in-url-bar/)
- [General] custom 'about:newtab' page: [New Tab Override](https://addons.mozilla.org/addon/new-tab-override/)
- [Tabs] Sidebar tabs: [Tabs Center Redux](https://addons.mozilla.org/addon/tab-center-redux/) (additional CSS code in userChrome.css required to hide default tabs toolbar for now)

**_Not properly working using CSS tweaks_**
- [Tabs] custom tab widths: issues with overflow mode like on previous Fx versions, if modified through custom CSS areas

**_Not possible_**
- 'real' buttons in titlebar (moving buttons to a toolbar and cheating them into titlebar is possible)
- actually/manually moving existing buttons to different locations than toolbars (e.g. feed button in location bar, application/hamburger button to tabs toolbar)
- additional toolbars, add-ons bar, status bar 
- custom scrollbars

**Comment by motfis** [comment]
Nice! I got my 'old' firefox layout back. Still need to configure some/many things though.
Btw, I have some questions:
1. if I want to change the firefox button (top left) color (in the CTR, we have option to change the color to blue/green/grey etc), which part of the css that I need to change?
2. if I use the application menu extension, is it possible to show the menu of application menu when I click the firefox button?
3. How to move the find box (ctrl+f) from bottom to top?

Thanks for this chrome css!

**Comment by Aris-t2** [comment]
1. userChrome.css > Application/hamburger button in Firefox titlebar
2. Popup swapping is not possible. Once that extensions popup fill be final/finished, I will make CSS code for it. At the moment most menuitems are grayed out.
3. Does this happen without a theme? What HiDPI value are you using?

**Comment by Arty2** [comment]
also possible with userChrome.css:
- [Colorize URL bar in private tabs](https://gist.github.com/Arty2/4658f49ca815980b0cb2)
- [Move tabs to bottom of window](https://gist.github.com/Arty2/e6e61801531ec5ee1f9f)

**Comment by Aris-t2** [comment]
Thanks.

The mentioned list was mostly about what of CTRs features are still possible in Fx57+, so it obviously does not include any exotic tweaks.

_Colorize URL bar in private tabs_
There is a tweak to colorize location bar in this collection (although its more general, not specifically for private mode only).

_Move tabs to bottom of window_
Moving "tabs" to bottom like this, is more like moving the whole main top content to windows bottom, resulting in a not-present "Firefox titlebar", partlky visible panel popups and obviously all other toolbars being not on top anymore. Anyway, thanks for the code, the "-moz-box-direction: reverse;" rule looks very interesting.

![1](https://user-images.githubusercontent.com/6013569/31860706-b0a8e3d6-b71e-11e7-9777-34f416c99e5c.png)

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/issues/2
