### ISSUE TITLE
Win10 maximized window Tab min-height

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#10]
Window control buttons seem to be squished On Win10 (Nightly58, Drag space - ON, TitleBar - OFF) when classic_squared_tabs.css are enabled.
![wincontrols_bug](https://user-images.githubusercontent.com/32600318/31600842-92b6f6a0-b260-11e7-9860-7dd76468fcd7.png)

I believe this is happening because of 

`#tabbrowser-tabs,
#tabbrowser-tabs > .tabbrowser-arrowscrollbox,
.tabbrowser-tabs[positionpinnedtabs] > .tabbrowser-tab[pinned] {
  min-height: 26px !important;
}`
If   min-height is commented out bug becomes fixed.
![wincontrols_bug_fixed](https://user-images.githubusercontent.com/32600318/31600861-a4bbfb5c-b260-11e7-9948-c4e60615df35.png)

**Comment by Aris-t2** [comment]
Try this:
```css
.titlebar-button {
  padding: 0px 17px !important;
}
```

**Comment by Acid-Crash** [comment]
Yes, this solved the issue

**Comment by Aris-t2** [comment]
Fixed in 1.0.9.
