### ISSUE TITLE
Overflow button icon animation + buttons_on_navbar_squared_buttons_fx58

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#102]
1. Describe the issue
Finishing overflow button icon animation (changing from blue to gray color) offsets for a few pixels from left to right. Most noticeable on finishing animation state.

2. What should have happened instead?
icon should remain still during animation

3. Steps to reproduce the issue?
- enable buttons_on_navbar_squared_buttons_fx58 (was present in buttons_on_navbar_squared_buttons_fx57)
- try to add button to overflow menu
- observe how overflow button icon jumps for a few pixels from right to left during its animation

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![ofmenu](https://user-images.githubusercontent.com/32600318/35283913-1e84f08e-0062-11e8-8be1-91d9abae5139.png)

5. System information
- OS & OS version: Win 10 x64
- OS theme name: default Win10 theme
- DPI / HiDPI resolution: default (100%)
- Firefox version: FF58 and Nightly 60
- Firefox theme / lw-theme:  default
- This projects settings the issue occurs with:

**Comment by Aris-t2** [comment]
I never saw/got this animation. Tested Fx57-60, Win7-10, new profile.

![001](https://user-images.githubusercontent.com/6013569/35285517-de92c64e-005d-11e8-847e-1978866c1031.png)

**Comment by Acid-Crash** [comment]
Just to double-check, animation shows when a new button is added to overflow menu (via "pin to overflow menu" context menu).

**Comment by Aris-t2** [comment]
OK, this will be fixed on next update for Fx57-60.

**Comment by Aris-t2** [comment]
Test 1.5.9: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.5.9

**Comment by Acid-Crash** [comment]
Confirmed. It is fixed in 1.5.9
