### ISSUE TITLE
Wrong addon version in available updates section

### ISSUE THREAD

**Issue by kilara1988** [Aris-t2/CustomCSSforFx#103]
1. Describe the issue
I have some issues with the latest Ghostery addon versions so I installed an older version which works fine and disabled automatic updates for Ghostery.Now when I'm checking for addon updates i get an Updates Available section in which i check to see if a new version which fixes my issue is released so i can update again.
The CSS to show addon versions shows the wrong addon version in the Available Updates section in the addon manager.It shows the currently installed addon version instead of the version of the update that it will actually install.The release notes are for the correct update version and installing the update installs the correct update version.

2. What should have happened instead?
The CSS to show addon versions should show the update version in the Available Updates section.

3. Steps to reproduce the issue?
-Install an old version of an addon(that is not the latest version).
-Disable automatic updates for that addon.
-Check for addon updates.
-The Available Updates section shows your currently installed addon version instead of the version of the update to be installed.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![1](https://user-images.githubusercontent.com/1025376/35776132-62c2f110-099f-11e8-8899-314af377bb1d.png)
![2](https://user-images.githubusercontent.com/1025376/35776133-6679856c-099f-11e8-8b18-f971bd1f4a8c.png)

5. System information
- OS & OS version: Windows 10 Pro x64, Version 1709, Build 16299.192
- OS theme name: 
- DPI / HiDPI resolution: 
- Firefox version: 59.0b6 (64-bit)
- Firefox theme / lw-theme: 
- This projects settings the issue occurs with: addonlists_show_addon_version_number.css

**Comment by Aris-t2** [comment]
I just posted 1.6.5.1 version here: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.6.5
It should fix this issue.

You need to replace these files, if you only want this issue fixed:
```
.\css\aboutaddons\addonlists_show_addon_version_number.css
.\xml\addonversion_fx57.xml
```

**Comment by kilara1988** [comment]
Thanks for the fix it works fine now.
