### ISSUE TITLE
Icons only for bookmarks on bookmarks toolbar -> right-click>properties>remove_name

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#105]
I found only that to personalize bookmarks toolbar in userChrome.css
/* bookmarks toolbar - buttons appearance - only use one at a time ******************************/
/* old bookmarks toolbar button appearance - 'disable' for Windows 7s classic OS theme **********/
/* @import url(./css/buttons/buttons_on_bookmarks_toolbar_old_size_and_appearance.css); /**/
/* @import url(./css/buttons/buttons_on_bookmarks_toolbar_classic_appearance.css); /**/
/* @import url(./css/buttons/buttons_on_bookmarks_toolbar_classic_appearance_items.css); /**/

is it possibile to get **only icons** in the websites of bookmarks toolbar?
like in this tweak:
(1) Go to Firefox's Profile folder and Create folder "chrome"
(2) Use a text-editor to create a file "userChrome.css"
(3) Paste this code:

toolbar[mode="icons"] .toolbarbutton-text {
display:none !important;
}

(4) Save file to "chrome" folder
(5) Restart Firefox FTW

**Comment by Aris-t2** [comment]
You don't need any code to remove bookmark labels.

Right-click on a bookmark in bookmarks toolbar, go to properties, empty the "name" field and save.

**Comment by gabri25ele** [comment]
it's too slowly to rename many & many bookmarks and I did not ask for that.

**Comment by Aris-t2** [comment]
If you hide bookmark text like the posted code does, the icon won't be centered leaving a small extra space at icons right. Only removing the label like I mentioned will offer a centered.

Anyway, if you like it the way the code solves this, just add it to the end of userChrome.css or to a my_userChrome.css (which you can import through userChrome.css). I added that import a while ago for such cases, so custom code won't be overwritten once updated files are posted into chrome folder.

**Comment by Aris-t2** [comment]
After some testing I decided to add this feature to the project. Next update will offer an option using this code

```css
#PlacesToolbarItems > .bookmark-item > .toolbarbutton-icon[label]:not([label=""]) {
  margin-inline-end: 0px !important;
}

#PlacesToolbarItems > .bookmark-item > label {
  display: none !important;
}
```

**Comment by gabri25ele** [comment]
So I like you!
