### ISSUE TITLE
1px space between menu bar and on left side of tabs to much

### ISSUE THREAD

**Issue by MrGlasspoole** [Aris-t2/CustomCSSforFx#11]
There is a 1px grey line between the navigation and menu bar.
Then on the left side of the tabs is a 1px grey bar but only if Fx is maximized.

![1px](https://user-images.githubusercontent.com/2067170/31780769-f95b267c-b4f6-11e7-9f8d-9e70a0f6f7d9.jpg)
I have enabled:
```
@import url(./css/tabs/classic_squared_tabs.css);
@import url(./css/tabs/tabs_below_navigation_toolbar.css);
@import url(./css/tabs/tab_close_always_visible.css);
@import url(./css/tabs/tab_throbber_fx56.css);
@import url(./css/generalui/bookmark_icons_colorized.css);
@import url(./css/toolbars/navbar_more_compact_mode.css);
```
OS: Windows 8.1 / Default theme
Fx: 57.0b9
Theme: default
Density: compact

**Comment by Aris-t2** [comment]
Check latest release an report back.
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.1.1

**Comment by MrGlasspoole** [comment]
A big thank you. That did it.
