### ISSUE TITLE
Visual bug with "hide 'Search with...' and 'Visit...' results " CSS enabled [WORKAROUND]

### ISSUE THREAD

**Issue by kilara1988** [Aris-t2/CustomCSSforFx#110]
1. Describe the issue

When i enable the "hide 'Search with...' and 'Visit...' results" CSS i get an extra result(one more over the limit) which is completely blank and non-clickable.After the initial launch of the browser the first time you start typing the results list is fine.But if the results lists disappears once, on subsequent searches when it shows the results list you get the extra blank result.

2. What should have happened instead?

No extra blank result should appear.

3. Steps to reproduce the issue?

1: Start browser.
2: Type something in the location bar to make the results dropdown list show.
3: Delete your search keyword to make the results list go away.
4: Type something in the location bar to make the results list show up again.
5: This time the results list has extra blank result at the bottom.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![1](https://user-images.githubusercontent.com/1025376/37422329-b08d1442-27c3-11e8-9923-f8a26b09b113.png)

5. System information
- OS & OS version: Windows 10 1709
- OS theme name: 
- DPI / HiDPI resolution: 
- Firefox version: 60.0b3 (64-bit)
- Firefox theme / lw-theme: 
- This projects settings the issue occurs with: hide 'Search with...' and 'Visit...' results (ac_popup_searchwith_and_visit_items_hidden.css)

**Comment by Aris-t2** [comment]
Autocomplete popups height does not get recalculated after hiding 'Search with...' and 'Visit...' results.
This bug is present since Fx 57 and I can not fix it atm.

There is one workaround for now where you have to limit popups height manually causing a visible scrollbar in some cases. Just test a few values:

```css
#PopupAutoCompleteRichResult .autocomplete-richlistbox {
  max-height: 400px !important;
}
```

**Comment by Aris-t2** [comment]
Next update will improve this feature. The "empty" box should appear less.

**Comment by kilara1988** [comment]
The workaround works great. It is even better now since i can get more results and still limit the height of the list so it does not cover my entire screen. One very minor inconvenience is that going trough the results with the arrow keys does not force the list to scroll to the selected item. But i use my mouse scroll to browse the results and very rarely need to go down that far so it is ok.
