### ISSUE TITLE
buttons_on_navbar_squared_buttons_fx57 unnecessary

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#111]
1. Describe the issue
In userChrome there is are who lines

```
@import url(./css/buttons/buttons_on_navbar_squared_buttons_fx57.css);
@import url(./css/buttons/buttons_on_navbar_squared_buttons_fx58.css);
```

I believe 
`@import url(./css/buttons/buttons_on_navbar_squared_buttons_fx57.css);`
should be removed and its content should be combined with other one because of FF has recently updated to v59

2. What should have happened instead?
`@import url(./css/buttons/buttons_on_navbar_squared_buttons_fx57.css);`
should be removed and its content should be combined with 
`@import url(./css/buttons/buttons_on_navbar_squared_buttons_fx58.css);`

3. Steps to reproduce the issue?
When enabled 
`@import url(./css/buttons/buttons_on_navbar_squared_buttons_fx57.css); `
gives squished button icons

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![buttons](https://user-images.githubusercontent.com/32600318/37466567-be23a5e6-2866-11e8-9ed1-7ec4cdd9cc91.png)

5. System information
- OS & OS version: Win 10 x64
- OS theme name: Default
- DPI / HiDPI resolution: 100
- Firefox version: 59.0
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with:

**Comment by Aris-t2** [comment]
Files merged in 1.7.8 update.
