### ISSUE TITLE
increase_ui_font_size.css dont work

### ISSUE THREAD

**Issue by iznobe** [Aris-t2/CustomCSSforFx#112]
Hello , i ve tested your project and put the classic version in my profile /chrome and tested .
i ' ve noticed that the increase_ui_font_size.css file don ' t work .
i put 30 pt  ( before there was default value : 12 ) on the variable --general_ui_font_size and the font size reduced ...
i ' m using linux mint 18.3 cinnamon .
i ' ve tested on firefox quantum 58 , and the version 59 and 60 too , exactly same thing .

**Comment by Aris-t2** [comment]
If you are using the complete package, you have to set custom font size value inside ./config/general_variables.css and enabled ./css/generalui/increase_ui_font_size.css inside userChrome.css.

Changing the value only inside increase_ui_font_size.css will only work, if no other files are used.
