### ISSUE TITLE
[Firefox 61 2018-03-25+] 1-2 seconds white/black screen/window on startup

### ISSUE THREAD

**Issue by Pizzapops** [Aris-t2/CustomCSSforFx#115]
Is anyone else getting 2 seconds of white screen on startup of Fx61? It is not a Chrome folder problem. It also happens with my ShadoowFox setup and with a stock unmodified setup.

**Comment by Aris-t2** [comment]
I'm seeing this on Windows 7 too , but here it is a black window/screen instead of white. Looks like a rendering / hardware acceleration issue on Nightly.

![1](https://user-images.githubusercontent.com/6013569/38000698-21863808-3229-11e8-9a3b-53ab49de6ce3.png)

**Comment by krystian3w** [comment]
I tried use ShadowFox with CustomCssforFX and give up (I do not have time to modify 
occurring conflicts).

**Comment by Aris-t2** [comment]
ShadowFox is a (full) theme created for userChrome.css and this projects files are at least in terms of colors and tab shapes a theme too. Combining themes was never a good idea.
Anyways, Shadowfox is not what this "issue report" is about.

--------------------

Has anyone reported this or a similar bug on Bugzilla yet?

**Comment by Pizzapops** [comment]
I looks like Fx61 also broke **addonbar_status_in_addonbar.css**. The status shows at the bottom left corner of the active page not in the addonbar.
![addonbar_status](https://user-images.githubusercontent.com/33039961/38151188-e2524edc-3427-11e8-9483-c1c8cc1e9c4b.jpg)

**Comment by Aris-t2** [comment]
Fx61 has made `statuspanel` box a `hbox` with the actual id `#statuspanel`. Same happened for its sub content. The code for this has to be updated.

Test "v4" from here: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.8.0

**Comment by Pizzapops** [comment]
As usual, amazing fast fix. Thanks

**Comment by Aris-t2** [comment]
I could reduce the "time" this black/white screen is visible even more, by disabling every "telemetry" crap in about:config (Nightly 61).

**Comment by MarkRH** [comment]
FYI.. I see this delay in 61beta as well. In my case it's not white or black but my desktop wallpaper is visible for awhile between the window borders before the rest of window renders.

**Comment by Aris-t2** [comment]
Does anybody know, if there is something on Bugzilla about this "glitch"?

**Comment by Pizzapops** [comment]
**[Win1-Pro-64]** My search on Bugzilla showed nothing about this "glitch". The May 10 FxQ62 has made it worse. FxQ will not start in full screen. I get a white partial screen box first and then it finishes loading partial screen FxQ. I must click on top right full screen icon. It does not restart in the screen size from the previous session exit.

**Comment by MarkRH** [comment]
Looks like 61beta4 may have helped this. The startup looks the same as 60 does now.

**Comment by Aris-t2** [comment]
Looks like this is not a "big" issue anymore. Fx 60 / 61 beta and 62 Nightly only show this for like half a second now.

Lets close this for now.
