### ISSUE TITLE
[Suggestion] RSS links to open in new tab on left click

### ISSUE THREAD

**Issue by Juvencus** [Aris-t2/CustomCSSforFx#118]
Hey,

RSS bookmark/folders don't open in new tabs on left click even when "browser.tabs.loadBookmarksInTabs;true"

Is it possible to force them to behave like that?

**Comment by Aris-t2** [comment]
It is not possible with CSS tweaks of this project at least.

While holding <kbd>Ctrl</kbd> key, left click will force all bookmark to open in new tabs incl. RSS/folder bookmarks.
