### ISSUE TITLE
squared_buttons and AppButton

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#12]
On latest build when using **appbutton_on_navbar_orange** and enabling **buttons_on_navbar_squared_buttons** AppButton becomes stretched.
![orangeab](https://user-images.githubusercontent.com/32600318/31849857-07c75954-b652-11e7-83bf-af6f4e112989.png)

**Comment by Aris-t2** [comment]
Thanks for reporting.
I have to start converting old pngs to svgs. Next update will improve that images quality and fix stretched appearance.

**Comment by Acid-Crash** [comment]
Many TXH for the last update
It partially fixed the issue. 
AppButton icon (the one from appbutton_on_navbar_color_base set) is now displayed properly.
![orangeab2](https://user-images.githubusercontent.com/32600318/31853896-6b83816a-b699-11e7-8986-13c3eaaf5540.png)
However button width isn't affected by **buttons_on_navbar_squared_buttons**.
I believe this is happening because here we are using not the actual button but the toolbarbutton-badge-stack.
I have fixed that issue with the following rules.
`#main-window[uidensity=compact] #nav-bar #PanelUI-menu-button .toolbarbutton-icon {
  width: 32px !important;
}
#main-window[uidensity=compact] #nav-bar #PanelUI-menu-button .toolbarbutton-badge-stack {
  width: 32px !important;
}`

Don't know tough whether it is possible to fix this module compatibility  in better way.


P.S. IMHO uncommenting `border-radius: 2.5px !important;` from the base makes that button a bit nicer on corners

**Comment by Aris-t2** [comment]
Are you sure the button size is not affected? Have you updated all files to the latest release? Button size of appbutton and other buttons looks identical to me. 

![1](https://user-images.githubusercontent.com/6013569/31855807-fd5fe77c-b6b2-11e7-9849-b716e1b9f164.png)

![234](https://user-images.githubusercontent.com/6013569/31855829-55d03844-b6b3-11e7-8e8f-92e95e983232.png)

Not sure what causes the gap between appbutton and back button for you.

**Comment by Acid-Crash** [comment]
Ohh, deeply sorry. 
Guess my eyed played bad joke on me. Was 90% sure that the width is different.
Regarding gap between buttons. That's intentional, made it myself (in pre FF57 I had used regular spacers a lot).
Issue closed.
