### ISSUE TITLE
[Fx60+][tabs below navigation toolbar] issues with internal Light/Dark lw-themes

### ISSUE THREAD

**Issue by toad01** [Aris-t2/CustomCSSforFx#122]
Upgraded (?) to Firefox 60 and using CustomCSSforFx 1.8.5.1.1 and the Firefox Light theme . When I have the option @import url(./css/tabs/tabs_below_navigation_toolbar.css); active, the bookmark toolbar background is now dark grey and it is very difficult to read the bookmark toolbar text. Perversely, when the Default theme is selected, the background becomes lighter! Everything was fine with Firefox 59. Using Windows 7 and have made no other changes to userChrome.css.

**Comment by Aris-t2** [comment]
Please provide a screenshot.

**Comment by Aris-t2** [comment]
**Test the latest build ([1.8.6](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.8.6)).**

**Comment by toad01** [comment]
![ff prob default](https://user-images.githubusercontent.com/22851518/39967941-84f46c90-56bc-11e8-9e9f-6e313e6cf810.jpg)

**Comment by toad01** [comment]
![ff prob tabs below](https://user-images.githubusercontent.com/22851518/39967950-ac712a9c-56bc-11e8-9e9c-6fc83e38bbd9.jpg)

This is what happens when selecting tabs below.

**Comment by toad01** [comment]
Problem with the Light theme has been fixed in 1.8.6. Thank you. However, Default theme now looks almost the same, tabs black text on grey rather than white on dark blue. Fortunately I don't use that theme!

**Comment by Aris-t2** [comment]
The default theme had to be "fixed" by me for the "tabs below navigation toolbar" case. For some reason Mozilla used purple tab background color and white text for tabs on Windows 7 Aero themes only. To keep compatibility cross platforms and themes, if "tabs below navigation toolbar" is active, I had to unify the colors. Its not ideal, but better than offering another "tabs below navigation toolbar" option for Windows 7 Aero only.
