### ISSUE TITLE
[FF61b4][Win7][Classic] View Available Updates page broken with version numbers

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#123]
1. Describe the issue:
Using version 1.8.6 of the CSS with 61 beta 4, when I check for new extension updates and click the view available updates link, the Install Updates button is greyed out and now Update buttons are visible by the extensions.  

2. What should have happened instead?
The button should have been active and Update buttons next to each extension.

3. Steps to reproduce the issue?
In userContent.css, @import **./css/aboutaddons/addonlists_show_addon_version_number.css**
With this not imported, then the buttons are visible and work.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
With version numbers: 
![image](https://user-images.githubusercontent.com/8035962/39972457-f4bf50d0-56d5-11e8-8365-3987f950496b.png)

Without:
![image](https://user-images.githubusercontent.com/8035962/39972470-689b530a-56d6-11e8-8fe3-f682e71f15f9.png)

5. System information
- OS & OS version:  Windows 7 Pro 64bit
- OS theme name: Classic
- DPI / HiDPI resolution: Normal, 100%
- Firefox version: 61beta4 
- Firefox theme / lw-theme:  default
- This projects settings the issue occurs with: userContent.css, @import **./css/aboutaddons/addonlists_show_addon_version_number.css**

**Comment by Aris-t2** [comment]
[Test 1.8.6.1 release.](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.8.6)

**Comment by MarkRH** [comment]
That seems to have fixed it. Works in both 60 and 61beta4. Thanks!
