### ISSUE TITLE
How can I (or you?) do this after ff59?

### ISSUE THREAD

**Issue by ChrisShawK2** [Aris-t2/CustomCSSforFx#125]
This is from your own GH homepage:

**Old about:newtab and about:home pages (Firefox 57-59 only)**
browser.newtabpage.activity-stream.enabled
browser.newtabpage.activity-stream.aboutHome.enabled

Is it gone entirely, or is there a way to get it back?

Thanks,
--Chris
[BTW, I've already written a rant on the MZ community site...]

**Comment by Aris-t2** [comment]
Neither Firefox by itself nor this projects CSS files can recreate the "old" about:newtab page.

I also suggest the above mentioned "New Tab Tools" add-on/WebExtension.

**Comment by krystian3w** [comment]
@ChrisShawK2  Community find other workarounds? I cannot find your topic (forums.mozillazine.org / discourse.mozilla.org / support.mozilla.org/en-US/questions/all).

**Comment by ChrisShawK2** [comment]
Hi,

No, Arit-t2 said that it can’t be done via CSS (and closed the topic, which is why you can’t see it).

I’ve found this Fx add-in, which works for me (at least, until Fx decides to make breaking changes AGAIN!).
https://addons.mozilla.org/en-US/firefox/addon/new-tab-tools/

Good luck,
--Chris
