### ISSUE TITLE
Windows 10 - text only mode - non-default menubar text too low

### ISSUE THREAD

**Issue by aabatpurdue** [Aris-t2/CustomCSSforFx#127]
!

1. Describe the issue
windows 10
firefox 60.0.1 and firefox 60.0.1esr
  with the Menu Bar enabled.
CTR from June 2, 2018 

I use the CTR "text only mode" and keep some add-on buttons at the right end of the Menu Bar.  The text is displayed too low (5px?) for these add-on buttons.  Have a patch file which corrected the problem on my box and tried  to select it but do not know if I succeeded [junk.txt](https://github.com/Aris-t2/CustomCSSforFx/files/2070535/junk.txt).

Don't know if this violates #1 above.  It is sometimes difficult to determine where the text for one add-on button ends and the next one begins, i.e., the separation between the last word for one button and the first word of  the next button can be virtually identical to the spacing between multiple words of a single button.  Makes it a lot harder to read the separate button texts correctly/quickly.

--  Thanks,
--    aabatpurdue

2. What should have happened instead?
(1) Add-on button text on right side of Menu Tab should be higher (5px?).
(2) Should be (at least) a greater separation between adjacent button texts.

3. Steps to reproduce the issue?
Add buttons to the right of the Menu Bar and enable"text only mode".

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- OS & OS version:  windows 10
- OS theme name: 
- DPI / HiDPI resolution: HD for what that's worth
- Firefox version: 60.0.1/60.0.1esr
- Firefox theme / lw-theme: Quantum
- This projects settings the issue occurs with: CTR(?)

**Comment by Aris-t2** [comment]
I think you have forgotten one important step which even is in your leftover of the issue template.

**4. SCREENSHOTS**

And by the way, its not CTR anymore. ;-)

**Comment by Aris-t2** [comment]
I tested icons+text and text modes on Windows 10 and could reproduce the issue. Buttons on menubar were misplaced a few pixels. [Use the updated version 1.9.2 where this issue is fixed.](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/1.9.2)

**Comment by aabatpurdue** [comment]
Don't know how to do screenshots. The screenshot button in the dropdown for the "..." icon in the Url Bar only provides a page screenshot

not a full display screenshot.  Did I miss something?

--  Thanks
--    aabatpurdue

________________________________

**Comment by aabatpurdue** [comment]
A whole new realm to play in (:-}).


--  Thanks,

--    aabatpurdue


________________________________

**Comment by aabatpurdue** [comment]
The Navigation Bar/Address Bar/URL Bar (which one is correct?) needs a bit of separation finessing also.  Hey, even a snapshot (:-}).  The last 6 words are for 3 buttons, "Downloads", "Close Tab History Button" and "Translate".  Needs some additional separation.


--  Thanks,

--    aabatpurdue


[cid:a94cab61-49dc-4483-ad96-92b6b3895ca7]

________________________________

**Comment by Aris-t2** [comment]
The navigation toolbar contains main buttons and the address bar (also called urlbar or location bar).
Is there are question anywhere regarding the "3 buttons"? If you asking about more left and right space for some buttons labels, I will look into it.

**Comment by aabatpurdue** [comment]
1.9.2.1 works like a charm.

--  Thanks,
--    aabatpurdue

________________________________
