### ISSUE TITLE
Add to bookmarks button

### ISSUE THREAD

**Issue by dimqua** [Aris-t2/CustomCSSforFx#13]
Is it possible to add the "add to bookmarks" star icon to the urlbar, just like RSS icon with Awesome-RSS addon?

**Comment by Aris-t2** [comment]
It is there be default. No add-on required.

**Comment by dimqua** [comment]
Not exactly. Do you mean "three dots menu" button? It's not the same as the star icon.

**Comment by Aris-t2** [comment]
No, I mean its part of Firefox 57+ by default. If its missing, click on the three dots, right-click "Edit the bookmark" and select "Add to Address Bar". You can disable it the same way.

![1](https://user-images.githubusercontent.com/6013569/31852996-b8f9b33c-b681-11e7-8f3a-098e31235811.png)
