### ISSUE TITLE
CustomCSSforFx/win10 customize>themes>dark -  selected tab button not highlighted

### ISSUE THREAD

**Issue by aabatpurdue** [Aris-t2/CustomCSSforFx#130]
1. Describe the issue
If you enable the dark side via customize>themes>dark, the tab button for the displayed page is not highlighted.
I have "tabs not on top" and "text only mode" enabled,
2. What should have happened instead?
The selected tab should be highlighted, i.e., a colored bar at top of tab button (standard firefox style) or a different color/shade for the entire tab button (which happens with customize>themes>light)..

3. Steps to reproduce the issue?
customize>themes>dark

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![nohighlight](https://user-images.githubusercontent.com/21324717/41181515-fa013eae-6b3f-11e8-93d3-c65378c5fb13.png)

You may have three copies of the shot (:-{).

5. System information
- OS & OS version: win 10
- OS theme name: 
- DPI / HiDPI resolution: 
- Firefox version: 60.0.2esr
- Firefox theme / lw-theme: quantum(?)
- This projects settings the issue occurs with: CustomCSSforFx 1.9.2.1

**Comment by Aris-t2** [comment]
Actually the active tab is slightly darker and uses the same color to toolbars use (what can be seen on your screenshot too). Using a different color would make active tab not to blend in correctly.

![1](https://user-images.githubusercontent.com/6013569/41184592-adf7c43c-6b81-11e8-9b0b-6bb14541e41f.png)
![2](https://user-images.githubusercontent.com/6013569/41184593-ae0faaf2-6b81-11e8-94c7-aed7be0cc321.png)


Enable `custom_tab_color_settings.css` file in userChrome.css and modify `--default_tabs_bg_selected: linear-gradient(to bottom,#FF8800,#FFCC99);` inside the file `custom_tab_color_settings.css`. Replace values inside the variable to `--default_tabs_bg_selected: linear-gradient(to bottom,#000000,#000000);` for example.

**Comment by Aris-t2** [comment]
I can change the tab colors for Dark theme a bit on next update:

![tabs](https://user-images.githubusercontent.com/6013569/41185180-09a240a6-6b86-11e8-8cf3-f628a494aaed.png)

**Comment by aabatpurdue** [comment]
Actually I prefer something like


--- ./css/tabs/classic_squared_tabs.css_orig    2018-05-17 20:50:28.000000000 -0400
+++ ./css/tabs/classic_squared_tabs.css 2018-06-07 23:57:17.105569600 -0400
@@ -141,12 +141,12 @@
 }

 .tabbrowser-tab[selected]:-moz-lwtheme-darktext .tab-content {
-  border-top: 1px solid rgba(0,0,0,.5) !important;
+  border-top: 2px solid red !important;
   border-left: 1px solid rgba(0,0,0,.4) !important;
   border-right: 1px solid rgba(0,0,0,.4) !important;
 }
 .tabbrowser-tab[selected]:-moz-lwtheme-brighttext .tab-content {
-  border-top: 1px solid rgba(255,255,255,.6) !important;
+  border-top: 2px solid red !important;
   border-left: 1px solid rgba(255,255,255,.2) !important;
   border-right: 1px solid rgba(255,255,255,.2) !important;
 }

[cid:7a25617d-62b1-4333-8119-3c76b73b00e9]

--  Thanks,
--    aabatpurdue



________________________________

**Comment by Aris-t2** [comment]
@aabatpurdue 
You can use the given code the way you like. The colors used for the classic tabs when Dark theme is active are based on the colors the actual theme offers.

@yurikhan 
Don't worry, I made non-active tabs slightly lighter to give active tab a better contrast. There won't be real color changes there. Just compare https://github.com/Aris-t2/CustomCSSforFx/issues/130#issuecomment-395916612 and https://github.com/Aris-t2/CustomCSSforFx/issues/130#issuecomment-395919903

**Comment by yurikhan** [comment]
@Aris-t2 What do you consider “real” color changes? A theme may be designed specifically to have *no* contrast between active and inactive tabs. In that use case, any slight difference is a visual bug.

The current Firefox theming API already provides for a general tab bar background color and an active tab color.

I like CustomCSSforFx for achieving impossible things. Slight tweaks to possible things should be left to other projects.

**Comment by Aris-t2** [comment]
I meant heavy visible changes like black to red or gray to blue won't happen. In the case of the default Dark theme, which does not offer the same colors for all OSs / OS themes, I had to set a color myself when using classic squared tabs.
The chosen colors are from the default Dark theme, but the visible difference between active and non-active tabs is not big enough. If colors for non-active tabs should be exactly what Firefox offers, they would be simply black for example.

**Comment by Aris-t2** [comment]
I checked Dark theme without any custom CSS tweaks again on Win 7 and Win 10 and decided to tweak "classic squared tabs" colors a bit.

This is the result

![dark](https://user-images.githubusercontent.com/6013569/41193172-33a0aaea-6c09-11e8-80b7-f6ce5f0dfbad.png)
![dark 2](https://user-images.githubusercontent.com/6013569/41193173-3563259c-6c09-11e8-85dc-bc76842043b8.png)

**Comment by Aris-t2** [comment]
Correct Dark theme colors are now part of the latest update.
