### ISSUE TITLE
buttons_on_navbar_squared_buttons - Icon Badges

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#14]
When **buttons_on_navbar_squared_buttons** is enabled (buttons_on_navbar_classic_appearance is also enabled) Button Icon Badges are placed to high (compared to original position).
Because of this it seems that icon badge is a bit overlapped by the tabbar
![iconbadges](https://user-images.githubusercontent.com/32600318/31903336-7d8e14f4-b830-11e7-8b01-e2542456c138.png)

**Comment by Aris-t2** [comment]
Will be fixed on next update.

**Comment by Acid-Crash** [comment]
fixed in 1.13
