### ISSUE TITLE
Searching for a thread here ...

### ISSUE THREAD

**Issue by StanGets** [Aris-t2/CustomCSSforFx#142]
Hi,

Searching for threads is really a pain here at GitHub. Search sends to code, not to posts.
I know the question had been asked and answered, but after an hour or so searching for the "issue" (new and old) I'd like to get that answer back.

The point concerned adding the search engines keywords to the old Search Bar. Aris had provided a work-around I'd like to retrieve. But where is it....

Thanks.

**Comment by Aris-t2** [comment]
To be honest I do not remember anything regarding search engine keywords for the old search bar, but asking the question inside corresponding support thread might get an answer faster: https://github.com/Aris-t2/CustomCSSforFx/issues/104

Further more the general discussion threads might contain something too:
https://github.com/Aris-t2/CustomCSSforFx/issues/133
https://github.com/Aris-t2/CustomCSSforFx/issues/109
https://github.com/Aris-t2/CustomCSSforFx/issues/88
https://github.com/Aris-t2/CustomCSSforFx/issues/41
https://github.com/Aris-t2/CustomCSSforFx/issues/3

**Comment by StanGets** [comment]
@Aris-t2 OK, thanks. I had already searched among those threads, unsuccessfully. I'll reset my quest on #104
