### ISSUE TITLE
Not a bug; Github page instructions for Linux

### ISSUE THREAD

**Issue by bendover22** [Aris-t2/CustomCSSforFx#143]
This isn't terribly important (except to some newer Linux users).  Aris-t2 Github page on **Linux** instructions where to find or create the Firefox profiles' chrome folder & sub directories has a couple of syntax errors.  Some other pages show the same errors in Linux instructions.
> _Linux
> \home\ USERNAME \.mozilla\firefox\ PROFILE FOLDER NAME \
In Linux, all slashes are forward slashes_ ('/') - unlike Windows.

!! ALSO, in Linux paths, filenames, directories, etc., capitalization MATTERS. 
"/home/bob/.mozilla" isn't = "/home/Bob/.mozilla" (If user's name was setup **as "bob"**, changing to  the 2nd example path will show "_no such directory_."

Most Linux system created  files / directories are not capitalized.  
The 8 random character prefix on firefox / thunderbird profiles will be lower case & must be entered that way in Linux for searches or changing directories.

Only a few Linux system-created **user storage directories** are capitalized;  e.g., Downloads, Documents, Music, etc. 

If using a search to find files or directories, some Linux file managers don't search in hidden files or directories (EVEN when made visible),  like Nemo (Mint - Cinnamon desktop).  Users may need a secondary file mgr or search utility, that can include hidden directories and files in searches.

**Comment by Aris-t2** [comment]
Thanks for the note. Although I meant 'USERNAME' and 'PROFILE FOLDER NAME' being a temporal visual variable for those who read instructions, I think you are right and it is better to change them to lower case.

**Comment by bendover22** [comment]
You are most welcome.  As I said, some other pages on your Github site 
have these same (if not exact) "issues."
I doubt they'd present a problem to a Linux user of 6 mo or more. From 
what I read, more & more people are switching from Windows or OS X to 
Linux (more from Windows).
But, Windows is in no danger of disappearing - for now. :D

this is you're old buddy, Evan, (mozillazine user 'phkhgh')from back in 
the Noia theme days on your Mozillazine support page.
You gave me some (highly appreciated) tutoring in CSS for Fx; I gave you 
lot of bugs / suggestions & some English lessons. :D

I read you'd branched out & had a nice Github site but I couldn't seem 
to find time to visit.  I wish I'd visited sooner. There's info I could 
have used, even if not installing your entire themes, addons.

What I'm mainly concerned with is replacing TabMixPlus multi row tabs.  
I can't stand scrolling one long line of tabs.
I see there may be some problems getting multi row tabs to work 100% in 
Fx quantum (I'm on 62 in Linux).

Part of my problem may be that I'm using a Linux full, custom theme 
(that affects most apps & screens in Linux, including Fx).  It may 
interfere w/ userChrome code that does some of the same things that code 
from various sites said, "This  will make multi-row tabs work great."  
None have worked great so far, if at all.  But I haven't tried your 
muli-row code yet.

**Comment by Aris-t2** [comment]
Hi Evan aka phkhgh aka bendover22.
Yes, I remember those Noia discussions and English lessons. I think some of them are still present in my Mozillazines mailbox ;-)

I tried to make this projects files as standalone as possible, so users can take them out and use without everything else. The content you picked is very "experimental" and unstable I must say.
What CSS can do to create "multiple" tab lines is very limited and it is nowhere near to what TMP achieved using JS, but it is enough for the most basic usage.
The multi-lined tabs code of this project can not be combined with some other features. You can see which ones by reading through my comments inside userChrome.css. One major limit of the CSS solution for multi-lined tabs is dragging and dropping tabs. It is not working. And to be honest both available ways to achieve multiple tab lines are not written by me. I just modified a few things to integrate them into this project after many users asked me to.

https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_multiple_lines.css
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_multiple_lines_v2.css

There is also an additional support thread dedicated to multiple tab lines: https://github.com/Aris-t2/CustomCSSforFx/issues/39
