### ISSUE TITLE
[Lin][Fx62] UI Font Size bug

### ISSUE THREAD

**Issue by pF-arQon** [Aris-t2/CustomCSSforFx#146]
1. Describe the issue

@import "./css/generalui/increase_ui_font_size.css"; /**/
doesn't actually do what it's supposed t, for me at least. it does increase the ui font size - but only because of what appears to be a bug.  :)

no matter what size is given for general_ui_font_size, i get what looks like 12-14pt. however, if i use a CONSTANT in that css instead, it actually works correctly. (e.g. "* { font-size: 11pt !important; }" is fine).

2. What should have happened instead?

changing "general_ui_font_size: 12pt;" to "general_ui_font_size: 11pt;" should have actually changed the ui font size.

3. Steps to reproduce the issue?

as per #2

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

will attach in a bit when i can afford to restart firefox, sorry

5. System information
- OS: ubuntu mate 16.04
- DPI / HiDPI resolution: 1920x1200
- Firefox version: 62.0, x64
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: ?

**Comment by pF-arQon** [comment]
![ui_font_size_broken](https://user-images.githubusercontent.com/43844448/46464615-ad779400-c77b-11e8-8346-dedf4909f74b.png)
![ui-font-size-working](https://user-images.githubusercontent.com/43844448/46464616-ae102a80-c77b-11e8-8a45-840a035eeb96.png)

also, note in the "broken" run that the background tab color has changed: it looks like the whole css engine bugged out to at least some extent.

**Comment by Aris-t2** [comment]
If you are using the whole package, you have to set variables inside "./config/general_variables.css". Have you tried it?

**Comment by pF-arQon** [comment]
yes, i'm using the whole package. i could have sworn i changed that reference first and THEN went hunting when that didn't work, but apparently i'm just tired and stupid and forgot to save the config file change somehow.  :/

apologies for wasting your time. thanks for all the help: it's all good now.  :D
