### ISSUE TITLE
[Nightly] about:addons page changed appearance/behavior.

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#147]
1. Describe the issue
Looks like Nightly, Version 64.0a1 Build ID 20181015223336 (or sometime earlier) changed the about:addons behavior making the CSS not work.

2. What should have happened instead?
Well, be nice if it behaved like the release, 62.0.3, but that might be an impossibility

3. Steps to reproduce the issue?
Run the latest nightly with the following userContent.css:
```css
/* Aris imports */

@import "./classic210/css/aboutaddons/addonlists_show_addon_version_number.css"; /**/
@import "./classic210/css/aboutaddons/addons_manager_alternative_appearance.css"; /**/
@import "./classic210/css/aboutaddons/addonlists_compact.css"; /**/
@import "./classic210/css/aboutaddons/description_page_alternative_content_order.css"; /**/
@import "./classic210/css/aboutaddons/recentupdates_category_always_visible.css"; /**/
@import "./classic210/css/aboutpreferences/preferences_alternative_appearance.css"; /**/
```

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
Before (In release):
![image](https://user-images.githubusercontent.com/8035962/46993137-6078b380-d0d3-11e8-8b04-c88bc8cb3a54.png)

After (Nightly):
![image](https://user-images.githubusercontent.com/8035962/46993165-7c7c5500-d0d3-11e8-80c2-f7bef5d93a20.png)

5. System information
- OS & OS version: Windows 7 Pro 64bit
- OS theme name: Classic
- DPI / HiDPI resolution: Normal, 100%
- Firefox version: Nightly Version 64.0a1 Build ID 20181015223336
- Firefox theme / lw-theme:  Default
- This projects settings the issue occurs with: 
See above.

**Comment by MarkRH** [comment]
Looks like "/addonlists_show_addon_version_number.css" is causing the yellow Legacy to appear and breaks how the buttons work.  Without using any of the userContent.ss, looks like this normally now:
![image](https://user-images.githubusercontent.com/8035962/46993474-0842b100-d0d5-11e8-8b6c-29be655d43ef.png)

**Comment by Aris-t2** [comment]
I can confirm the appearance requires some modifications and yes it can almost be restored to the one pre-Fx64 offers. However I can not confirm the button issues you mention. They work fine for me.

**Comment by Aris-t2** [comment]
Test 2.1.1 release: https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by MarkRH** [comment]
That seems to work. Buttons also seem fine.

![image](https://user-images.githubusercontent.com/8035962/47011901-a1d78600-d108-11e8-9630-a1ba05eacc43.png)

Maybe a little spacing before the description after the number?

**Comment by MarkRH** [comment]
Well, doing
```css
.addon:not([pending="uninstall"])[status="installed"] .description-container {
  margin-inline-start: 5px !important;
}
```
Makes it look a bit better:
![image](https://user-images.githubusercontent.com/8035962/47012926-262b0880-d10b-11e8-9b45-f39571954806.png)

**Comment by Aris-t2** [comment]
I can add that.

**Comment by MarkRH** [comment]
That all works well. Thanks for your efforts looking into it. Will go ahead and close this.

**Comment by Pizzapops** [comment]
@Aris-t2 
I found the fix to hide the lighter graphic fragments. I changed the margin setting in addons_manager_alternative_appearance.css, line 318.

`list > .addon {
	  margin:-1px !important;
	}
`

I had commented out line 326 previously to get rid if the horizontal list dividing line.

**Comment by Pizzapops** [comment]
@Aris-t2 
Previous fix gave me some overflow and a bottom scrollbar. New fix keeps the compact spacing the same but gets rid of rounded corners that let the white background bleed thru.

`	.list > .addon {
	  margin: unset !important;
	  margin-top: -1px !important;
	  margin-bottom: -1px !important;
	  border-radius: unset !important;
	}`
