### ISSUE TITLE
[suggestion/request] An html Gui for Configuring and enable&disable css fitures 

### ISSUE THREAD

**Issue by blackcrack** [Aris-t2/CustomCSSforFx#148]
Hi Aris,
could you maybe add a config.html + engine.js
into custom_css by side of userChrome.css and userContent.css
to create a Gui for klicking on or of in these 2 files ([_]Option1 -br- [X]Option2 -br- etc.)
to have a configuration Surface for it for enable and disable this or the other function via Gui in html(5)
surface../Webpage, this could then also open with the firefox as Configuration Surface ;) in this folder
maybe call it later over a xpi plugin ..

best regards
Blacky

**Comment by Aris-t2** [comment]
Sorry, I have no plans for something like that.
You have still to manually edit text/css files. ;-)

**Comment by blackcrack** [comment]
Hi  @Aris-t2  

:) wohh how fast !!  \*vbs*

ahh why did you close it so fast, hold it open, maybe could anyone other create sum html-gui 
and can build up it, because it is give many oldy's who like the classic look and can scripting something like  this in javascript and html5 ... you must only make an call for such a person who can make something.. "[Request] we need a javascript programmer who can create a Gui for this program"
or something to have a nice surface for it ..
Speak with the peoples and they give help.. certainly even ;)

best regards
Blacky

**Comment by Aris-t2** [comment]
A configuration gui/software request comes up every now and then and if I remember correctly it happened a few times within general support threads over the last year.

I closed it fast, because these kind of requests like to arrest much attention, where people like to share they would like to have such a tool too.

Furthermore the issue template states "new issues" should not get opened for requests, only for bug reports and issues. I like to keep discussions within available discussion threads ;-)

> 
> SUPPORT AREA for features THIS project provides
> 1. This is not a 'request' area for new stuff or legacy add-on features.
> 2. ...
> 3. ...
> 4. Do not open a new issue about something this project does not offer. Instead join the 'General discussions, feedback, questions belong here' thread to chat and ask questions about what is or could be possible there.

**Comment by blackcrack** [comment]
well, also so an reason.. okey,
but not any know how work with css, this is a foreign language for some people and see it rather than tripe , something what they not understand .. .. and i want not come with the hammer of handicapped ,
but not without reason come not only peoples like me and ask for a gui and the 2nd reason it is,
with a gui it is all more fast configured .. you see it on your classic theme restorer.
And yea, i have see the template .. but to make possible to use for all peoples it is 
more important as "we hold us way and the other is no matter " to give all the possible to use that..
how ever.. it's your project.. (me-> a bit disappointed ..)
