### ISSUE TITLE
chrome_fx57_v1.1.4.zip is invalid, unable to open.

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#15]
Something happened with the chrome_fx57_v1.1.4.zip file. Windows and 7zip are unable to open it. The 1.1.3 file is fine.

**Comment by Aris-t2** [comment]
I posted a new one. Not sure what is causing the problem.

**Comment by MarkRH** [comment]
The v2 File works. Thanks.
