### ISSUE TITLE
NO ISSUE, only a Firefox CSS question

### ISSUE THREAD

**Issue by StanGets** [Aris-t2/CustomCSSforFx#150]
Hi,

No issue with _Custom CSS for Firefox_ 2.1.4 / Firefox 62.0.3 (x64) / Windows 7 (x64)
But I'm facing a setting I'd wish to fully activate when I only manage to activate it partially.

**Hiding the Min, Max, Close buttons in the Titlebar.**
I've found a very simple setting which hides them:` #titlebar-buttonbox {display: none;}`

The problem is that, if the buttonbox is indeed hidden (and space is free), the buttons remain active when hovering over their screen location, that of the buttonbox! If I have enough tabs opened to fill the Titlebar, the + (Open a new tab) button will be at the far right and clicking it in fact clicks the hidden buttonbox and consequently closes Firefox!

1- I can't understand that a Firefox component which has been hidden remains active: like a ghost!
2- I'd appreciate your comments, advice, help to understand this and to know if there's any way to fully hide this darn buttonbox.

Thanks!

**Comment by Aris-t2** [comment]
You can not fully hide caption buttons on Windows 7 AeroGlass theme. By design Window 7 will keep those buttons and their functionality intact, even if you try to "disable" them.

![324](https://user-images.githubusercontent.com/6013569/47172848-d320a380-d30c-11e8-826d-79ca2b60ece9.png)

**Comment by StanGets** [comment]
Thanks @Aris-t2 your explanation states exactly what I discovered by myself last night:

> You can not fully hide caption buttons on Windows 7 AeroGlass theme. 

I tested with Windows 7's Classic theme and caption was fully hidden.
You learn every day.

Thanks!
