### ISSUE TITLE
[macOS][Fx62] How to remove 'New Private Window' menu items?

### ISSUE THREAD

**Issue by lex072** [Aris-t2/CustomCSSforFx#152]
Hello, I'm new here.
I'm using Mac OS X mavericks and recently installed FF Quantum. I think it is FF 62. I would like to remove the menu item 'New Private Window's but was unsuccessful. 
I could remove the button from the hamburger menu though. Using some codes from stone crusher in another GitHub repository. 
I have tried experimenting in Windows FF 62 and I could remove the menu items that I want. But in Mac OS X I couldn't. 
If anyone knows please help me please. Thanks and much appreciated.

**Comment by Aris-t2** [comment]
Create a userChrome.css like described on main page.
Add this code to it:

```css
#menu_newPrivateWindow,
#appMenu-private-window-button {
	display: none !important;
}
```

Normally the above code removes the "New private window" entry from main application menu and "File" menu, but, because of macOS restrictions, the menu item might not get removed from "File" menu using CSS.

Please use the "General support threads" for questions like this.
https://github.com/Aris-t2/CustomCSSforFx/issues/133

**Comment by lex072** [comment]
Thanks very much for your reply. Sorry for posting on the wrong place.

I have tried the codes you have suggested but the menu item is still not removed. Do you have any further suggestions please?
Thanks again.

**Comment by Aris-t2** [comment]
The amount of effort to achieve this might be too high, but you can try custom JavaScript codes:
- read everything from here: https://github.com/Aris-t2/CustomJSforFx
- select and apply one for the two methods
- create a new js file with the below content
- add file names entry into the chosen methods corresponding area to import scripts
- blame Apple and macOS for making things unnecessary complicated 

Hide 'File > new private window' entry with JS script `hidePWmenuentry.uc.js`:
```js
setTimeout(function(){
	try{
	  document.getElementById("menu_newPrivateWindow").collapsed = true;
	} catch(e){}
},1000);
```

**Comment by lex072** [comment]
Hi Aris,
Thanks for your reply. I have tried method 1 but it doesn't seem to work. What I have done is:
1 copy the usechrome into the chrome folder
2 copy the userchromejs.css into chrome folder
3 copy the code into the usechrome.css
4 create the JS script in the chrome folder
5 restart FF and menu item is still there
Did I miss anything? Do I need to declare the JS script in userChrome.css? Or is the JS automatically executed when FF restarts or opens a new tab or window?

I will try method 2 also.

**Comment by Aris-t2** [comment]
**Method 1**
You have to put the code into a file like `my_script_name.uc.js`. The file belongs into `userChrome` folder, which is inside your profiles `chrome` folder.
Furthermore you have to edit your `userChrome.xml` file and change "my_script_name.uc.js", if you are using a different filename.

**Method 2**
You have to put the code into a file like `my_script_name.uc.js`. The file belongs into `userChrome` folder, which is inside your profiles `chrome` folder.
Furthermore you have to edit your `userChrome.js` file and change "my_script_name.uc.js", if you are using a different filename.

In both cases do not forget to clear your script cache: https://github.com/Aris-t2/CustomJSforFx#scriptstartup-cache-must-be-deleted-after-every-change

**Comment by lex072** [comment]
Method 1
The hidePWmenuentry.uc.js is in the userchrome folder. The name of the JS is also updated in the XML file (missed this step). Restart FF still no success of the menu entry removal.

Method 2
I can't find the FF application directory in Mac OS X. It's only a single file size of 165mb within the Application directory. 
I do a right click on the file and show package contents. Then navigate to the folder Mac OS X. Inside I see several files and I think the FF executer is there.
Do I copy the defaults folder and the config file inside this Mac OS X folder in the package contents? Or do I have to search again for the FF folder in Mac?
I'm not sure if I should add files into the package content. 
Please advise. Thanks again.

**Comment by Aris-t2** [comment]
Please test other scripts to see, if they work. It still is possible, that hiding menu bars stuff on macOS is not possible anymore in Fx57+. I have not tested it since Fx56.
Don't forget to clear you script cache.

Yes, copy the files where you think the "executer" is.

**Comment by lex072** [comment]
Method 1 works!
My mistake was the JS file was in still in the chrome folder. So I moved it to userchrome folder, restart FF and it worked! The menu item is gone.

Will try method 2 also and update you.

**Comment by lex072** [comment]
Can the JS also remove the context menu items of the Mac OS X dock item? When I left click and hold onto the FF dock icon the New Private Window menu item is there.

**Comment by Aris-t2** [comment]
No, that is part of the system ui.

**Comment by lex072** [comment]
I tried method 2 with no success.
I have copied the defaults folder and the config.js file into the MacOS directory. There is another directory called the resources folder which contains the defaults folder and in it the Prefs. Also tried copying into this resources folder but no success.

Userchrome.js edited with the JS file - checked
JS file in userchrome folder - checked
