### ISSUE TITLE
[Firefox 63][not Firefox 64+] Old search / alte Suchmaschine

### ISSUE THREAD

**Issue by qwerty963** [Aris-t2/CustomCSSforFx#156]
Hallo.

Ich habe eine Frage über die Firefox 63 Suchmaschine zusammen mit dem CustomCSSforFx Projekt, ich habe den alten Scrambler geändert (diese kleine rechte Seite). Nach dem Upgrade auf Version 63 arbeitet onba bereits nicht an typisierten Befehlen und durchsucht diese nicht. Ich habe eine Frage meinerseits, ob es eine Deaktivierung der älteren und die Einbeziehung dieser unter 63 erfordert.

**Comment by Aris-t2** [comment]
Firefox 63 benötigt eine aktualisierte Version des Codes, damit die "alte Suche" weiterhin mit Firefox 63 funktioniert.
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/oldsearch.css
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/oldsearch.xml

Wie ich erfahren habe funktioniert die alte Suche aufgrund interner Firefoxänderungen ab Firefox 64 nicht mehr.

**Comment by Aris-t2** [comment]
If the old search would work, I would not tell here, that it does not work, would I?

------------------------------

Ich hätte nicht geschrieben, dass die "alte Suche" nicht mit Fx64+ nicht funktioniert, wenn sie funktionieren würde. ;-)

**Comment by qwerty963** [comment]
In diesem Themenforum wurden einige Zeilen darüber geschrieben:

**Comment by Aris-t2** [comment]
Eine weitere Code-Aktualisierung wie von Firefox 62 auf 63 ist für Firefox 64 nicht möglich.

Deswegen auch dieser Satz hier:

> Wie ich erfahren habe funktioniert die alte Suche aufgrund interner Firefoxänderungen ab Firefox 64 nicht mehr.

**Comment by qwerty963** [comment]
Die Frage ist, ob es bald erscheinen wird.
Ich interessiere mich für den alten Browser, weil ich nach der aktuell ausgewählten Suchmaschine suche, insbesondere, wenn ich den Text auf der Seite markiere und die rechte Maustaste drücke und "Google durchsuchen ......" wähle. Es sei denn, es gibt ein Add-On.

**Comment by Aris-t2** [comment]
Tut mir leid, aber ich weiß nicht wie ich **"die alte Suche funktioniert aufgrund interner Firefoxänderungen ab Firefox 64 nicht mehr"** anders ausdrücken soll. Falls die Frage darauf abzielt, ob ich zur Zeit an einem Workaround arbeite, so muss ich diese Frage verneinen. Ob jemand anderes daran arbeitet entzieht sich leider meiner Kenntnis.

Die "Alte Suche" funktioniert wunderbar in Firefox 60 ESR oder Waterfox/Basilisk mit CTR. Das sind die einzigen mir derzeit bekannten "Optionen".

**Comment by Aris-t2** [comment]
Continue here: https://github.com/Aris-t2/CustomCSSforFx/issues/158
