### ISSUE TITLE
Aero features are now black on Windows 10

### ISSUE THREAD

**Issue by Jake1702** [Aris-t2/CustomCSSforFx#159]
I had my setup configured with all the aero features enabled. Today it got updated (It's now at 63.0.1, I'm not actually sure what version it was before) and instead of being transparent, it's completely black. 

[This is what it looked like previously.](https://media.discordapp.net/attachments/325197025719091201/507287501531119616/unknown.png)

[This is what it unfortunately looks like now.](https://media.discordapp.net/attachments/325197025719091201/507346924744212501/unknown.png)

As stated, I'm on Windows 10 (x64) and as of now I'm running FF 63.0.1.

So was something changed in the latest Firefox version that causes it not to work anymore? 

UPDATE: So I tried it on FF 60.3.0.esr as well, and the same issue is present. Perhaps it's something with my system rather than the browser then?

**Comment by LionWrathz** [comment]
Go to about:config

    Create a new Integer value named ui.systemUsesDarkTheme and set it to 0

    Restart Firefox

**Comment by Aris-t2** [comment]
Create a new browser profile and test again. Or maybe something is wrong with your AeroGlass tool.

The AeroGlass setup should look like this without Win10s AeroGlass system transparency (but does not on your screenshot):

![1](https://user-images.githubusercontent.com/6013569/47847419-7670be80-ddcb-11e8-93ee-43c515840dd5.png)

**Comment by Jake1702** [comment]
I have tried what @LionWrathz said, and it has fixed the issue. Perhaps @Aris-t2 could add this instruction to the readme.md so other users who face this issue may try it as well?

**Comment by Aris-t2** [comment]
I can add a note to userChrome.css.
