### ISSUE TITLE
[Nightly] 65 since build Nov 07 2018 no Hamburger button anymore 

### ISSUE THREAD

**Issue by Nob1960** [Aris-t2/CustomCSSforFx#165]
Hello,

since today's Nightly 65 update (Nov 07) there is no more black Hamburger button visible anymore, there is only a free place on the left side near the first tab. Windows 7 Pro, 32-bit.

Greets, Nob

**Comment by Aris-t2** [comment]
This will be fixed on next update.

**Comment by Nob1960** [comment]
Thanks for info, dear Aris.

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/releases
