### ISSUE TITLE
Firefox 64, v2.3.0, ac_popup_classic_with_two_lines_fx63.css broken

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#169]
1. Describe the issue
With Firefox 64, I am still importing **/css/locationbar/ac_popup_classic_with_two_lines_fx63.css** however, the drop-down only appears the first time I use it below the location bar:
![image](https://user-images.githubusercontent.com/8035962/49834735-c3e53180-fd62-11e8-87c3-58622042af2b.png)

The next time I type something in the location bar, nothing appears:
![image](https://user-images.githubusercontent.com/8035962/49834789-e1b29680-fd62-11e8-9d2e-63d2cee96141.png)

2. What should have happened instead?
It should keep working

3. Steps to reproduce the issue?
Firefox 64, importing **/css/locationbar/ac_popup_classic_with_two_lines_fx63.css** . Type something in location bar. Delete what typed in and try again.

4. System information
- OS & OS version: Windows 7 Pro
- OS theme name: Classic
- DPI / HiDPI resolution: Normal/100%
- Firefox version: 64 Release
- Firefox theme / lw-theme: Default, Compact
- This projects settings the issue occurs with: 
importing **/css/locationbar/ac_popup_classic_with_two_lines_fx63.css**

**Comment by MarkRH** [comment]
Well, `@import "./classic230/css/locationbar/ac_popup_url_and_title_50percent_width.css";` does the same thing.  Works first time only.  Hmmm..

**Comment by VengefulAncient** [comment]
Crude workaround I found for now: manually opening the popup (assuming you're not hiding the button needed for that) **will** display suggestions for what's typed, as expected.

**Comment by krystian3w** [comment]
I can reproduce.

**Comment by Aris-t2** [comment]
I have not tested `ac_popup_classic_with_two_lines_fx63.css` with last few Fx64 betas, but it worked fine with beta 3-4.

It became very common for Mozilla pushing Nightly changes to the last beta(s) and I believe this was the case here. Sorry, but you have to switch to `ac_popup_classic_with_two_lines_fx65.css`. It will be renamed to `ac_popup_classic_with_two_lines_fx64.css` on next update.

Continue here: https://github.com/Aris-t2/CustomCSSforFx/issues/161

**Comment by MarkRH** [comment]
Just wanted to confirm that it works now.  Thanks for all your efforts!
