### ISSUE TITLE
I think newest packages just broke my setup alltogether.

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#171]
http://prntscr.com/lv05v9
[userchrome copy.txt](https://github.com/Aris-t2/CustomCSSforFx/files/2680982/userchrome.copy.txt)

Describe the issue

What should have happened instead?

Steps to reproduce the issue?

SCREENSHOTS with/without this projects files (drag & drop images into this post)

![index](https://user-images.githubusercontent.com/6013569/50016621-fe043c80-ffc9-11e8-880f-08205af7f2b6.png)

System information

OS & OS version: Windows 7
OS theme name:
DPI / HiDPI resolution:
Firefox version:
Firefox theme / lw-theme:
This projects settings the issue occurs with:
https://github.com/Aris-t2/CustomCSSforFx/files/2680982/userchrome.copy.txt

**Comment by Aris-t2** [comment]
Use proper issue reports like mentioned in the template:

> !!! READ THIS BEFORE POSTING A NEW ISSUE REPORT !!!  
> (use template at the bottom after reading everything on this page)
> 
> SUPPORT AREA for features THIS project provides
> 1. This is not a 'request' area for new stuff or legacy add-on features.
> 2. Read 'how to report issues properly' before posting a new issue.
> --> https://github.com/Aris-t2/CustomCSSforFx/issues/4
> 3. Make sure there are no '@namespace' references anywhere in your code. They cause CSS code not to work in some cases.
> 4. Do not open a new issue about something this project does not offer. Instead join the 'General discussions, feedback, questions belong here' thread to chat and ask questions about what is or could be possible there.
> --> https://github.com/Aris-t2/CustomCSSforFx/issues/163
> 5. Use available support threads:
> - TABS BELOW CONTENT SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/33
> - MULTIROW TABS SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/39
> - ADD-ON BAR SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/73
> - OLD SEARCH SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/104
> 
> Firefox bugs (join general discussion thread to talk about Firefox bugs):
> - CSS code might not work, if multi-process mode (e10s) is disabled
> - CSS code might not work on macOS/Linux in userContent.css
> 
> 
> !!! IMPORTANT !!!  
> By submitting a new issue you confirm having read and understood the above and all 'how to report a new issue' instructions.
> Invalid issue reports will get closed without further notice to keep this projects support area clean.
> Thanks for your understanding.
> 
> ----------------------------------
> 
> Fill 1-5 below and delete this line and everything above it before submitting.
> 
> 
> 1. Describe the issue
> 
> 
> 2. What should have happened instead?
> 
> 
> 3. Steps to reproduce the issue?
> 
> 
> 4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
> 
> 
> 5. System information
> - OS & OS version: 
> - OS theme name: 
> - DPI / HiDPI resolution: 
> - Firefox version: 
> - Firefox theme / lw-theme: 
> - This projects settings the issue occurs with: 
>

**Comment by Aris-t2** [comment]
Using your userChrome.css I get this result. Have you also updated /css/ and /config/ folders?

![1](https://user-images.githubusercontent.com/6013569/50016575-ddd47d80-ffc9-11e8-9cf3-20c27fc4402d.png)

**Comment by Aris-t2** [comment]
Why did you enable `@import "./css/tabs/tabs_below_navigation_toolbar_fx65.css"`, when you are on Firefox 63 or 64? You need this one: `@import "./css/tabs/tabs_below_navigation_toolbar.css";`
