### ISSUE TITLE
Rebound last Tab at the bottom

### ISSUE THREAD

**Issue by NoCompromise** [Aris-t2/CustomCSSforFx#173]
I noticed that when you close the last tab (bottom right), the penultimate moves to the right by making a "rebound", which I find impractical. Can it be removed?

----------------------------

!!! READ THIS BEFORE POSTING A NEW ISSUE REPORT !!!  
(use template at the bottom after reading everything on this page)

SUPPORT AREA for features THIS project provides
1. This is not a 'request' area for new stuff or legacy add-on features.
2. Read 'how to report issues properly' before posting a new issue.
--> https://github.com/Aris-t2/CustomCSSforFx/issues/4
3. Make sure there are no '@namespace' references anywhere in your code. They cause CSS code not to work in some cases.
4. Do not open a new issue about something this project does not offer. Instead join the 'General discussions, feedback, questions belong here' thread to chat and ask questions about what is or could be possible there.
--> https://github.com/Aris-t2/CustomCSSforFx/issues/163
5. Use available support threads:
- TABS BELOW CONTENT SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/33
- MULTIROW TABS SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/39
- ADD-ON BAR SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/73
- OLD SEARCH SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/104

Firefox bugs (join general discussion thread to talk about Firefox bugs):
- CSS code might not work, if multi-process mode (e10s) is disabled
- CSS code might not work on macOS/Linux in userContent.css

!!! IMPORTANT !!!  
By submitting a new issue you confirm having read and understood the above and all 'how to report a new issue' instructions.
Invalid issue reports will get closed without further notice to keep this projects support area clean.
Thanks for your understanding.

----------------------------------

Fill 1-5 below and delete this line and everything above it before submitting.

1. Describe the issue

2. What should have happened instead?

3. Steps to reproduce the issue?

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- OS & OS version: 
- OS theme name: 
- DPI / HiDPI resolution: 
- Firefox version: 
- Firefox theme / lw-theme: 
- This projects settings the issue occurs with:

**Comment by Aris-t2** [comment]
Please read the issue template. It is there for a reason!

**Comment by Aris-t2** [comment]
This is default tab toolbar behavior, same happens without any code independent of where tabs toolbar is.

**Comment by NoCompromise** [comment]
With the unmodified version and with the Photon interface, it does not happen.

**Comment by Aris-t2** [comment]
Are you sure about that.

I ran some tests and the tab before the last moved to last tabs position after last tab gets closed.

(with overflow mode)
![001](https://user-images.githubusercontent.com/6013569/50421292-f6505d80-083d-11e9-988d-7a9eaa29cfe7.png)

(without overflow mode)
![002](https://user-images.githubusercontent.com/6013569/50421293-f6505d80-083d-11e9-86a4-d31bca4295a5.png)
