### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by Box313** [Aris-t2/CustomCSSforFx#177]
Cant find code to open sidebar with one klick on either StarButton for Bookmarks or ClockButton for History. Those Buttons are now in the sidebar menu, but i would like to detach them.. thank you

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/issues/163

> !!! READ THIS BEFORE OPENING A NEW ISSUE REPORT !!!
> INVALID REPORTS WILL BE CLOSED WITHOUT FURTHER NOTICE TO KEEP ISSUE AREA CLEAN.
> By submitting a new issue you confirm having read and understood the below text and all 'how to report a new issue' instructions. Thanks for your understanding.
> 
> -> use TEMPLATE at the bottom after reading everything on this page <-
> 
> SUPPORT AREA for features THIS project provides
> 1. This is not a 'request' area for new stuff or legacy add-on features. Do not open a new issue about something this project does not offer. Instead join the 'General discussions, feedback, questions belong here' thread to chat and ask questions about what is or could be possible there.
> 2. Use available support threads:
> - GENERAL TALK, FEEDBACK & QUESTIONS: --> https://github.com/Aris-t2/CustomCSSforFx/issues/163
> - TABS BELOW CONTENT SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/33
> - MULTIROW TABS SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/39
> - ADD-ON BAR SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/73
> - OLD SEARCH SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/104
> 3. Read 'how to report issues properly' before posting a new issue.
> --> https://github.com/Aris-t2/CustomCSSforFx/issues/4
> 
> Firefox bugs (join general discussion thread to talk about Firefox bugs):
> - CSS code might not work, if multi-process mode (e10s) is disabled
> - CSS code might not work on macOS/Linux in userContent.css
> - '@namespace' references might cause custom CSS code not to work sometimes
> 
> ----------------------------------
> 
> Add all information required in 1-5 and delete this line and everything above it before submitting.
> 
> 
> 1. Describe the issue
> 
> 
> 2. What should have happened instead?
> 
> 
> 3. Steps to reproduce the issue?
> 
> 
> 4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
> 
> 
> 5. System information
> - OS & OS version: 
> - OS theme name: 
> - DPI / HiDPI resolution: 
> - Firefox version: 
> - Firefox theme / lw-theme: 
> - This projects settings the issue occurs with: 
>

**Comment by Box313** [comment]
sorry

**Comment by Aris-t2** [comment]
No problem ;-)
By the way: CSS can not create new buttons.
