### ISSUE TITLE
Tabs Below Main Content Causing Gray & Black Bars

### ISSUE THREAD

**Issue by enthusiast01** [Aris-t2/CustomCSSforFx#183]
Setup: Clean install of FF 65 (no addons, no themes, etc). Win10. Latest version of the CustomCSS. 
Issue is repeatable.

Using the tabs below main content option in the CustomCSS causes a gray bar at the very bottom of fullscreen video player & black bars on the left & right side. Affects players such as YouTube, Dailymotion, vlive.tv, Twtich.tv, etc. If this option is not chosen, there is no gray bar @ the bottom or black bars on the sides in fullscreen videos. This is the only option that I have modified in the CustomCSS. This is not exclusive to FF65. It has occurred on pre 60 versions as well.

The option I am using is:
@import "./css/tabs/tabs_below_main_content_fx65.css"; /**/  /* <--- EXPERIMENTAL */ 	/* <-- tabs below main content Fx65+ */

Screenshots:

With this option enabled:

![tabs below main content fullscreen - gray bar](https://user-images.githubusercontent.com/47168768/52041457-21466500-2500-11e9-890c-aebf17c5f9db.jpg)

Without this option enabled:
![tabs below main content fullscreen - no gray bar](https://user-images.githubusercontent.com/47168768/52041489-31f6db00-2500-11e9-94bc-5c95136882a1.jpg)

**Comment by Aris-t2** [comment]
Should be gone in 2.3.8: https://github.com/Aris-t2/CustomCSSforFx/releases/

**Comment by enthusiast01** [comment]
Yes, it works! Thank you! So happy I do not have to stare at those tabs on top anymore. I use vertical tabs.
