### ISSUE TITLE
No effect after changing number of rows for multirow tabs

### ISSUE THREAD

**Issue by CoSoCo** [Aris-t2/CustomCSSforFx#184]
1. Describe the issue
Still only 3 rows of tabs.

2. What should have happened instead?
Having 5 rows of tabs.

3. Steps to reproduce the issue?
Change in tabs_multiple_lines_v2.css:
  --tabs-lines: 5; /* 3 rows, increase for more */

5. System information
- OS & OS version: Ubuntu 18.04
- OS theme name: Unity Desktop
- DPI / HiDPI resolution: 1680x1050
- Firefox version: 65
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: ???

Thanks for the great work substituting Tab Mix Plus, even if not complete.

**Comment by Aris-t2** [comment]
Works fine here up to Firefox 67.
Make sure you set variables inside `chrome\config\general_variables.css`, if you are using the whole release.

**Comment by CoSoCo** [comment]
Now it works.
Please add a hint for that in  tabs_multiple_lines_v2.css

**Comment by Aris-t2** [comment]
OK
