### ISSUE TITLE
Empty bar above navigation bar with tabs_below_navigation_toolbar

### ISSUE THREAD

**Issue by CoSoCo** [Aris-t2/CustomCSSforFx#185]
1. Describe the issue
Empty bar above navigation bar (seems to be placeholder for menu bar).
REGRESSION: I did not have this issue with CCfF 1.9.3 until FF 64.

2. What should have happened instead?
No empty bar.

3. Steps to reproduce the issue?
- Enable "Show menus in title bar of windows" in Ubuntu Unity Desktop Appearence settings.
- Changes in UserChrome.css:
@import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css"; /**/ /* only for multi-lined tabs support, causes glitches with disabled menubar */
@import "./css/tabs/tabs_multiple_lines_v2.css"; /**/  /* <--- EXPERIMENTAL */
/* @import "./css/tabs/tab_close_always_visible.css"; /**/
@import "./css/tabs/tab_close_show_on_hover_only.css"; /**/

3a. Using alternative:
@import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2_force_hidden_menubar.css"; /**/ /* only for multi-lined tabs support, no menubar with OS titlebar */
Result -> There are no menus any more at all, even in the window title bar on mouse hover.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- OS & OS version: Ubuntu 18.04
- OS theme name: Unity Desktop
- DPI / HiDPI resolution: 1680x1050
- Firefox version: 65
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with:

**Comment by Aris-t2** [comment]
The answer is right in your post:
**causes glitches with disabled menubar**

Either have menubar enabled and visible or hide it completely by using `tabs_below_navigation_toolbar_fx65_v2_force_hidden_menubar.css`.
You can'r have the old bahavior anymore with that configuration (too deep changes inside Firefox 65+ code).

**Comment by CoSoCo** [comment]
Thanks, what a pity.
But where can I enable menu bar manually? I don't see this in the FF setting any more. Maybe that would help.

**Comment by Aris-t2** [comment]
`Right-click on a toolbar > select Menubar` or
`Main menu buttons > Customize > Toolbars `
This of course only works, if you are not using the above mentioned combinations.

**Comment by CoSoCo** [comment]
> `Right-click on a toolbar > select Menubar` or
> `Main menu buttons > Customize > Toolbars `
At these places there is no "menu bar" item any more in my FF65, or do your hacks hide them intentionally.

**Comment by Aris-t2** [comment]
Of course they are there. This stuff did not change for ages.
The CSS hacks hide menubar intentionally in Fx65, because of compatibility issues.

That why there are comments about this inside userChrome.css
`@import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css"; // /* only for multi-lined tabs support, causes glitches with disabled menubar */`
---->>> **causes glitches with disabled menubar** <<<-----

`@import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2_force_hidden_menubar.css"; /**/ /* only for multi-lined tabs support, no menubar with OS titlebar */`
---->>> **force_hidden_menubar** <<<-----
---->>> **hidden menubar** <<<-----

**Comment by CoSoCo** [comment]
Hi Aris,
thanks for your explanations.
> Of course they are there. This stuff did not change for ages.

I've tested FF65 with new empty profile. There still is no menu bar any more and no option in Customize > Toolbars. The only remaining possibility I know to show a menu bar is with Ubuntu Unity Desktop in window title bar or Unity panel. I don't understand, how you come to a different opinion.

**Comment by albino1** [comment]
> I've tested FF65 with new empty profile. There still is no menu bar any more and no option in Customize > Toolbars. The only remaining possibility I know to show a menu bar is with Ubuntu Unity Desktop in window title bar or Unity global panel. I don't understand, how you come to a different opinion.

Just right-click to the side of the URL bar and the options are there:

![ff-menu-bar](https://user-images.githubusercontent.com/12164957/52095159-dc114a00-2576-11e9-9858-644d53436e67.jpg)

**Comment by Aris-t2** [comment]
@CoSoCo

Delete your chrome folder, restart Firefox, Enable menubar like shown on the screenshot. Start over with a clean /chrome/ folder setup and do not use the previous combinations, as they clearly do not offer the menubar as described further above!

**Comment by CoSoCo** [comment]
> Just right-click to the side of the URL bar and the options are there:

I know this function. Here I only have the Bookmarks Toolbar.
I appears that you do not use the Ubuntu Unity desktop. It seems, that Firefox is patched here to not show the menu item, because of the obligatory menu in window title bar or Unity panel.

> Delete your chrome folder, restart Firefox,

This is what I've had with a new empty FF profile.

**Comment by Aris-t2** [comment]
Yes you are right, there is no menubar in that configuration.
Its the same on macOS, the menubar is part of the OS and can not be enabled/disabled by Firefox.

In that case tabs_below_navigation_toolbar_fx65_v2_force_hidden_menubar.css might be something for you, because it tries to remove the gap above navigation toolbar appearing in some cases.

**Comment by CoSoCo** [comment]
> Yes you are right, there is no menubar in that configuration.
> Its the same on macOS, the menubar is part of the OS and can not be enabled/disabled by Firefox.

But does the OS menubar still work on macOS?

> In that case tabs_below_navigation_toolbar_fx65_v2_force_hidden_menubar.css might be something for you, because it tries to remove the gap above navigation toolbar appearing in some cases.

As I've written above this is no real solution for me, because it corrupts/removes the OS menubar.

Is it thinkable to create another hack like: `tabs_below_navigation_toolbar_fx65_v2_Unity_fix.css`
In about:config I fount three items dealing with menubar, which may help you:
`dom.disable_window_open_feature.menubar;false`
`ui.use_unity_menubar;true`
`browser.uiCustomization.state;{"placements":{"widget-overflow-fixed-list":[],"nav-bar":["back-button","forward-button","stop-reload-button","home-button","fireftp-button","customizableui-special-spring1","urlbar-container","search-container","customizableui-special-spring2","downloads-button","library-button","savedpasswordeditor-button","tiletabs-buttonmenu","action-button--b9db16a4-6edc-47ec-a1f4-b86292ed211d-vdh-tbbutton","https-everywhere-button","ublock0-button","toggle-button--jid1-mnnxcxisbpnsxqjetpack-pb-button","jid1-mnnxcxisbpnsxq_jetpack-browser-action","toggle-button--compatibilityaddonsmozillaorg-acr-dialog","https-everywhere_eff_org-browser-action","ublock0_raymondhill_net-browser-action","screenshots_mozilla_org-browser-action","tiletabs-we_dw-dev-browser-action","_b9db16a4-6edc-47ec-a1f4-b86292ed211d_-browser-action","formhistory_yahoo_com-browser-action","sidebar-button","sessionboss_william_wong-browser-action","rf-firefox_siber_com-browser-action"],"toolbar-menubar":["menubar-items","forecastfox-menubar-spring"],"TabsToolbar":["tabbrowser-tabs","new-tab-button","alltabs-button","tabmix-tabs-closebutton","tabmixScrollBox"],"PersonalToolbar":["personal-bookmarks","forecastfox_s3_fix_version-browser-action"]},"seen":["pocket-button","developer-button","ublock0-button","toggle-button--jid1-mnnxcxisbpnsxqjetpack-pb-button","action-button--b9db16a4-6edc-47ec-a1f4-b86292ed211d-vdh-tbbutton","jid1-mnnxcxisbpnsxq_jetpack-browser-action","toggle-button--compatibilityaddonsmozillaorg-acr-dialog","forecastfox_s3_fix_version-browser-action","webide-button","https-everywhere_eff_org-browser-action","ublock0_raymondhill_net-browser-action","screenshots_mozilla_org-browser-action","tiletabs-we_dw-dev-browser-action","_b9db16a4-6edc-47ec-a1f4-b86292ed211d_-browser-action","formhistory_yahoo_com-browser-action","sessionboss_william_wong-browser-action","rf-firefox_siber_com-browser-action","feed-button"],"dirtyAreaCache":["PersonalToolbar","nav-bar","TabsToolbar","toolbar-menubar","PanelUI-contents","addon-bar"],"currentVersion":15,"newElementCount":3}`
