### ISSUE TITLE
Icons+Text on location bar

### ISSUE THREAD

**Issue by forestsw** [Aris-t2/CustomCSSforFx#188]
1. I cannot get "Icons+text" to work, the text will not work appear on the location bar buttons. There is no text on "back", "forward", "reload", "home" etc.

2. I have enabled it in the css file and it sould be working, other options are working.

3. I recently upgraded to FF65, a lot of options did not work so I installed version 2.4 and changed some settings. Everything seems to work except the "icons+text", I have no text on the location bar buttons.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![ff65 screenshot](https://user-images.githubusercontent.com/40299051/52456838-ceceff00-2b24-11e9-9adc-2cb8a15822d5.jpg)

5. System information
- Windows 7 Professional 
- OS theme name: 
- DPI / HiDPI resolution: 
- Firefox version: 65.0
- Firefox theme / lw-theme:  Firefox 3 for Firefox 4 Windows Basic
- This projects settings the issue occurs with: "Icons+Text"

**Comment by forestsw** [comment]
Upon further testing, it appears that none of the changes I make to the location bar take affect. Any ideas what is going on? Other changes seem to work properly.

**Comment by Aris-t2** [comment]
Please check, if `@import "./css/toolbars/toolbar_mode_icons_and_text.css";` is enabled correctly in userChrome.css.
`icons+text` works fine here up to Fx67.

```css
/* TOOLBAR TEXT MODES - [only use one at a time] ************************************************/
 @import "./css/toolbars/toolbar_mode_icons_and_text.css"; /**/
/* @import "./css/toolbars/toolbar_mode_text.css"; /**/
/* [!] FIX for macOS / alternative appearance for Linux *****************************************/
/* @import "./css/toolbars/toolbar_mode_icons_and_text_and_text_only_macOS_fix.css"; /**/	/* <-- macOS fix */
```

**Comment by forestsw** [comment]
I am on FF65, it says it's up-to-date.
Yes, it seems as if it is enabled correctly, here is what I have:

/* TOOLBAR TEXT MODES - [only use one at a time] ************************************************/
@import "./css/toolbars/toolbar_mode_icons_and_text.css"; /**/
/* @import "./css/toolbars/toolbar_mode_text.css"; /**/
/* [!] FIX for macOS / alternative appearance for Linux *****************************************/
/* @import "./css/toolbars/toolbar_mode_icons_and_text_and_text_only_macOS_fix.css"; /**/	/* <-- macOS fix */


Anything else I can check?

**Comment by Aris-t2** [comment]
Very strange.
Can you verify, that all files are present and in the correct place?

**Comment by forestsw** [comment]
How should I verify? I think that I have done everything correctly. I removed the previous Chrome folder, and downloaded the new version, put the folder back in the same place and other options work. As you can see in the picture I have TABS ON THE BOTTOM, and THE ICONS have changed to what I set. For some reason none of the location bar changed take affect. 

Thoughts?

**Comment by Aris-t2** [comment]
Try to backup your folder again and extract a new copy of this projects files there and only enable the line for icons + text. If it still does not work, backup your profile folder and repeat the mentioned step.
There is probably a glitch somewhere in your profile.

**Comment by forestsw** [comment]
I downloaded and installed again and everything works. I can't thank you enough. You are the only reason I can still use FF. Thank you for everything.

Forest

**Comment by Aris-t2** [comment]
Good to hear!
