### ISSUE TITLE
[C][Fx58] buttons_on_navbar_squared_buttons.css button icons are squished.

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#19]
On latest Nightly (58.0a1 (2017-11-01)) navbar button icons are squished.
![navbar](https://user-images.githubusercontent.com/32600318/32316397-abb9b632-bfb8-11e7-8283-d4ac98037f14.png)

P.S. I may be mistaking but it looks like Mozilla has changed button height and offsets because they look taller and closer to each other comparing to previous build

**Comment by Aris-t2** [comment]
Can you confirm this only affects "compact" mode?

**Comment by Acid-Crash** [comment]
Confirming. Only compact mode is affected
![navbarall](https://user-images.githubusercontent.com/32600318/32322822-8cea9bc0-bfce-11e7-97d4-fec9c40ae8bc.png)

**Comment by Aris-t2** [comment]
Test 1.1.9. I had add a separate file for Fx58.

**Comment by Acid-Crash** [comment]
Fixed in 1.1.9
