### ISSUE TITLE
"Show All History" to the top

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#191]
I would like to open the History window with one click, but there is not a button for this 😢 (right?)
But I found a middle-solution here -> https://support.mozilla.org/it/questions/1191098

With the method of jscher2000 is possible to move **Show All History** from the bottom to the top

![2017-11-30-12-01-19-bb0dec](https://user-images.githubusercontent.com/33927879/54223315-85911700-44f7-11e9-91e8-a081501e709e.png)

is this possible to use also with CustomCSSforFx?
simply add _@import url(userChrome-ShowAllHistoryAtTheTop.css);_ at the beginning of userChrome.css or could there be contraindications with the other settings?

**Comment by Aris-t2** [comment]
Open "userChrome-ShowAllHistoryAtTheTop.css", copy the code and paste it to the bottom of your userChrome.css.

**Comment by gabri25ele** [comment]
Yesterday, I inserted this **@import url(userChrome-ShowAllHistoryAtTheTop.css);**
but I listen willingly that I can also enter directly all the text

/* SHOW ALL HISTORY AT THE TOP OF THE MENU/PANEL
   To use this file, place it in your chrome folder and either 
   (A) shorten the name to userChrome.css, or
   (B) add @import url(userChrome-ShowAllHistoryAtTheTop.css);
   as the first line in your existing userChrome.css file */

/* History Button menu */
toolbaritem#PanelUI-history > .panel-header {
  -moz-box-ordinal-group: 2 !important;
}
toolbaritem#PanelUI-history > .panel-subview-body {
  -moz-box-ordinal-group: 3 !important;
  padding-top: 0 !important;
}
toolbaritem#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton {
  -moz-box-ordinal-group: 1 !important;
}
/* Library Button menu History Panel*/
panelview#PanelUI-history > .panel-header {
  -moz-box-ordinal-group: 1 !important;
}
panelview#PanelUI-history > .panel-subview-body {
  -moz-box-ordinal-group: 3 !important;
  padding-top: 0 !important;
}
panelview#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton {
  -moz-box-ordinal-group: 2 !important;
}
/* Fix coloring/reduce height (for both buttons) */
#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton {
  background-color: transparent !important;
  border-top: none !important;
  min-height: 24px !important;
}
#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton:hover {
  background-color: var(--arrowpanel-dimmed) !important;
}

**Comment by gabri25ele** [comment]
Firefox 87, "history" has changed.

is it possible to delete this line?
![1](https://user-images.githubusercontent.com/33927879/111999759-911f6b80-8b1d-11eb-9e08-00c1ffd86f3c.png)

I think they have inserted one line in the Library button, in fact now I see two of them, there:
![2](https://user-images.githubusercontent.com/33927879/111999962-caf07200-8b1d-11eb-804f-bd43af832399.png)

**Comment by Aris-t2** [comment]
```css
.panel-subview-body #appMenuRecentlyClosedWindows + toolbarseparator,
.panel-subview-body #appMenuClearRecentHistory + toolbarseparator {
  display: none !important;
}

#PanelUI-history .panel-header {
  border-bottom: unset !important;
}
```

**Comment by gabri25ele** [comment]
starting with **userChrome-ShowAllHistoryAtTheTop.css**

should be added to the end of the existing code? (in this case it doesn't work)
it must be replaced with all previous code? (in this case it doesn't work)
which parts should be replaced with the latter?

**Comment by gabri25ele** [comment]
do I have to open a new issue or can I continue writing here?

**Comment by Aris-t2** [comment]
Sorry, I don't know where you tried do use code, but I tested it inside userChrome.css file. (At the end of it.)

**Comment by gabri25ele** [comment]
> 
> 
> Sorry, I don't know where you tried do use code, but I tested it inside userChrome.css file. (At the end of it.)

I used the code in the file ShowAllHistoryAtTheTop.css

![sshot-1](https://user-images.githubusercontent.com/33927879/112637423-70695580-8e3e-11eb-9988-f440e79c584a.png)

/* SHOW ALL HISTORY AT THE TOP OF THE MENU/PANEL
   To use this file, place it in your chrome folder and either 
   (A) shorten the name to userChrome.css, or
   (B) add @import url(userChrome-ShowAllHistoryAtTheTop.css);
   as the first line in your existing userChrome.css file */

/* History Button menu */
toolbaritem#PanelUI-history > .panel-header {
  -moz-box-ordinal-group: 2 !important;
}
toolbaritem#PanelUI-history > .panel-subview-body {
  -moz-box-ordinal-group: 3 !important;
  padding-top: 0 !important;
}
toolbaritem#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton {
  -moz-box-ordinal-group: 1 !important;
}
/* Library Button menu History Panel*/
panelview#PanelUI-history > .panel-header {
  -moz-box-ordinal-group: 1 !important;
}
panelview#PanelUI-history > .panel-subview-body {
  -moz-box-ordinal-group: 3 !important;
  padding-top: 0 !important;
}
panelview#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton {
  -moz-box-ordinal-group: 2 !important;
}
/* Fix coloring/reduce height (for both buttons) */
#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton {
  background-color: transparent !important;
  border-top: none !important;
  min-height: 24px !important;
}
#PanelUI-history > #PanelUI-historyMore.panel-subview-footer.subviewbutton:hover {
  background-color: var(--arrowpanel-dimmed) !important;
}

**Comment by gabri25ele** [comment]
> 
> I tested it inside userChrome.css file. (At the end of it.)

like this???

![sshot-1](https://user-images.githubusercontent.com/33927879/112638274-5da35080-8e3f-11eb-9dd9-cd45e5072c1e.png)

it makes no difference to me

can I see your userChrome.css file?

**Comment by LionWrathz** [comment]
@gabri25ele why don't you just try add the icon instead of using css code?  ff87 
https://i.imgur.com/d1EGYog.mp4

**Comment by Aris-t2** [comment]
I only used the default setup of this projects files and added the code to `userChrome.css` like on your screenshot.

**Comment by gabri25ele** [comment]
let me show you what I see:
![sshot-1](https://user-images.githubusercontent.com/33927879/112863543-41114d80-90b7-11eb-9068-05a7d496cb28.png)

Firefox (new profile) portable + custom_css_for_fx_v3.2.0pre1
added your code at userChrome.css
If you want to see (download) the files, the portable are here:
https://krakenfiles.com/view/cbc9e9d42f/file.html
so maybe you can tell me where I'm wrong

**Comment by Aris-t2** [comment]
Previous code removed separators shown on your previous screenshots.

If you want to remove all separators from history menu, use this:

```css
#PanelUI-history toolbarseparator {
  display: none !important;
}

#PanelUI-history .panel-header {
  border-bottom: unset !important;
}
```

**Comment by gabri25ele** [comment]
Aris.t2, I guess we don't understand each other.
I want "Show All History" to the top, as the title says.
😄
In new Firefox update, Library changed and with the code in userChrome-ShowAllHistoryAtTheTop.css (comment of 13 Mar 2019) in LIbrary we have two rows:
![111999962-caf07200-8b1d-11eb-804f-bd43af832399](https://user-images.githubusercontent.com/33927879/112956737-0c49d880-9141-11eb-988c-2e6ed2b044e5.png)
and in "Show All History to the top" (icon history) we have a row at the first
![sshot-1](https://user-images.githubusercontent.com/33927879/112956827-24b9f300-9141-11eb-971b-573ba42c41e4.png)

nothing particularly serious 😁
but I was wondering if it is possible to remove this first row:
![sshot-1](https://user-images.githubusercontent.com/33927879/112956981-49ae6600-9141-11eb-8861-f7ddef8918d5.png)

I don't want to remove all separators, too much mess on the menu.

**Comment by gabri25ele** [comment]
yes, now we have
no row 

![2](https://user-images.githubusercontent.com/33927879/113138040-93707c80-9225-11eb-9d03-d818e3abcd54.png)

and in Library **only one**

![1](https://user-images.githubusercontent.com/33927879/113138072-9b302100-9225-11eb-8833-463f3a29c78a.png)

now we can officially change name in "Manage history" to the top 😁

**Comment by gabri25ele** [comment]
With Firefox 113
SHOW ALL HISTORY AT THE TOP does not work anymore!
what will they have changed?
😭

**Comment by Aris-t2** [comment]
This will move the menuitem to the top again:

```css
#PanelUI-historyMore {
  order: -1 !important;
}
```

**Comment by gabri25ele** [comment]
only this is necessary? 
A thousand thanks. 
you should integrate this function in CustomCSSforFx

**Comment by Aris-t2** [comment]
The older code from 2021 changed a few other things inside the history menu, but basically only "order: -1" is necessary to move the item to the top.
