### ISSUE TITLE
solution for Multirow Bookmarks % Tabs on Bottom / Tabs below Bookmarks (below multirow) for Firefox 65+  userChrome.css

### ISSUE THREAD

**Issue by shiftF12ATwebDOTde** [Aris-t2/CustomCSSforFx#192]
this is a new solution MARCH 2019 for Multirow Bookmarks support and at the same time Tabs BELOW bookmarks

userChrome.css

create a file with this name and do as described in the file.

file content here:

 
[userChroment.txt](https://github.com/Aris-t2/CustomCSSforFx/files/2970057/userChroment.txt)

**Comment by Aris-t2** [comment]
The combination of `tabs_below_navigation_toolbar_fx65.css` and `bookmarks_toolbar_multiple_lines_fx66.css` works fine for Fx65+.

Please use the general talk thread or in this case the corresponding 'tabs not on top' thread to post solutions like that.
