### ISSUE TITLE
How to change auto complete dropdown url bar width similar to its url bar on FF64 and above?

### ISSUE THREAD

**Issue by zom243** [Aris-t2/CustomCSSforFx#195]
I want to change the width of auto complete dropdown address bar to the same width of its url bar on FF64, like this 

![paeRO8l](https://user-images.githubusercontent.com/36266655/54633122-1a74b100-4ab2-11e9-982d-f2a17e167bb5.jpg)

I'm using this import

> @import "./css/locationbar/ac_popup_classic_with_two_lines_fx64.css";

I notice that on FF64 and above, url bar width can't be determined directly, and only able to use fixed width.
And then I tried this import

> @import "./css/locationbar/ac_popup_classic_with_two_lines_fx63.css";

Voila! It works as I want it. The thing is I don't think this is the proper way to do it because there's already import specifically for FF64. 

My question is, will that FF63 css getting updated for future FF release? I'm concerned because there's already FF64 so that FF63 css won't be maintained.

Another thing is, I tried this JS solution https://github.com/Aris-t2/CustomCSSforFx/issues/161
But it seems the dropdown width can't same with url bar width, or maybe I did it wrong.

Thanks

**Comment by Aris-t2** [comment]
First of all switch to Fx66, no need to stay on an outdated version.

Like mentioned inside the corresponding changelog back then, the way things used to be until Fx63 is no more. Do not use `ac_popup_classic_with_two_lines_fx63.css` on Fx64 or later. It causes massive glitches and breaks location bar usage.

Without Javascript the width of the popup can not be detected automatically, so you have to set it manually:
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/config/general_variables.css#L47
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/locationbar/ac_popup_classic_with_two_lines_fx64.css#L9

The [JS solution](https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/locationbar_popup_classic_with_two_lined_results.uc.js) works fine up to Fx68 Nightly, you probably configured it wrong. Do not combine the JS script of CustomJSforFx with the css files of this project or it will not work.

[Please use the general discussion thread for these kind of question in the future.](https://github.com/Aris-t2/CustomCSSforFx/issues/189)
