### ISSUE TITLE
[win][firefox66]  The button "open a new tab" does not work

### ISSUE THREAD

**Issue by demiurge-ash** [Aris-t2/CustomCSSforFx#196]
1. Describe the issue
If enabled "tabs_below_main_content_fx65.css" and "default_tabs_round_top_borders.css" then the button "open a new tab" does not work in Firefox 66.

2. What should have happened instead?
The button should be pressed and open a new tab.

3. Steps to reproduce the issue?
Apply  "tabs_below_main_content_fx65.css" and "default_tabs_round_top_borders.css".
Try to open a new tab by clicking on the button.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![new-tabs](https://user-images.githubusercontent.com/40300551/54664927-a4466d80-4af6-11e9-8732-32eda9d5a73f.png)

5. System information
- OS & OS version: Win10 x64
- OS theme name: default
- DPI / HiDPI resolution: 1920x1080
- Firefox version: 66
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with:

**Comment by Aris-t2** [comment]
This will be fixed on next update.

**Comment by Aris-t2** [comment]
Uploaded 2.4.7
