### ISSUE TITLE
Tabs below navigation toolbar.css broken in FF66

### ISSUE THREAD

**Issue by bottleblue** [Aris-t2/CustomCSSforFx#198]
1. Describe the issue
Tabs below navigation toolbar.css no longer works in FF66. The tab bar is completely blank. Cannot see or change to other tabs (if they're even there).

2. What should have happened instead?
It should be visible and working normally.

3. Steps to reproduce the issue?
Upgrade to FF66

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
No screenshots unfortunately. I had to downgrade back to 65.0.2. 

5. System information
- OS & OS version: Win7 64
- OS theme name: ?
- DPI / HiDPI resolution: 125%
- Firefox version: currently 65.0.2
- Firefox theme / lw-theme: I am using a theme called Clouds Delight. I didn't think about it at the time but I didn't try to disable themes while testing the problem. 
- This projects settings the issue occurs with: ?

Apologies if I was supposed to post in this thread https://github.com/Aris-t2/CustomCSSforFx/issues/33
That said it was for tabs below content which I thought was different (tabs at the bottom of the screen right?)

**Comment by Aris-t2** [comment]
Are you using the latest files?
Are you using the correct option? https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L339

**Comment by bottleblue** [comment]
I tried it with the latest file which was posted 5 days ago  https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_below_navigation_toolbar_fx65.css

Does it work for you?

**Comment by Aris-t2** [comment]
Sure, works fine up to latest Nightly.
Try to setup all files inside /chrome/ folder again. Put complete CustomCSSforFx release there and only edit one line in userChrome.css.

**Comment by bottleblue** [comment]
I made a new userChrome.css file and only added the CustomCSSforFx and now it works. I can see the tab bar. So it must be some other custom setting in the old UserChrome.css that's not working correctly in FF66 that's causing the blank tab bar.  Thanks for the help!
