### ISSUE TITLE
[win][firefox66] Star icon of favorite site

### ISSUE THREAD

**Issue by Hobbix** [Aris-t2/CustomCSSforFx#199]
How to move star icon of favorite site? (see screenshot)
I use the option "ac_popup_classic_with_two_lines_fx64".
![11](https://user-images.githubusercontent.com/8199105/54860191-e276a380-4d27-11e9-99b1-5895339b8288.png)

P.S. In addition, the star icon does not appear in the drop-down menu if there is a favorite site. (list of 10 sites in the drop-down menu)

**Comment by Aris-t2** [comment]
CSS can not move the star icon there. On previous versions the content of the item was reconstructed within xml files code, which does not work anymore.

Not sure I understand what you are trying to tell me inside the P.S. part.
Bookmarks for bookmarked sites appear correctly here.

**Comment by Hobbix** [comment]
Thanks, really looking forward to.
About my P.S. (see screenshot)
![222](https://user-images.githubusercontent.com/8199105/54867722-a0377b80-4d94-11e9-8165-f410613938b3.png)

**Comment by Aris-t2** [comment]
The option has no control over bookmarked / non-bookmarked cases.
Maybe your bookmarked urls differ from current urls now, e.g `http` bookmarked, but site switched to `https`.

Next update will offer a new option to move the bookmarks star to the right/end.
For some reason I haven't though about the easiest way to achieve this "feature" before. :-)

Positions calculations will be based on the variable used inside this project files: `--ac_popup_width`.

**Comment by Aris-t2** [comment]
[Get 2.4.8.](https://github.com/Aris-t2/CustomCSSforFx/releases)

**Comment by Hobbix** [comment]
Bug after the update (see screenshot)

![444](https://user-images.githubusercontent.com/8199105/54870582-8197ab80-4db9-11e9-91de-e1b7c032edac.png)

**Comment by Hobbix** [comment]
To fix it
1. Open ac_popup_classic_with_two_lines_fx64.css
2. Find
```
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"]:-moz-locale-dir(ltr) .autocomplete-richlistitem .ac-title {
  left: 20px;
}
```
3. Change 20px to 27px
```
#PopupAutoCompleteRichResult[autocompleteinput="urlbar"]:-moz-locale-dir(ltr) .autocomplete-richlistitem .ac-title {
  left: 27px;
}
```

**Comment by Aris-t2** [comment]
The problem is I don't have that glitch with 2.4.8 values, but I get it once I change the values.
Can you test with a new profile on Fx66 and
- only ac_popup_classic_with_two_lines_fx64.css
- ac_popup_classic_with_two_lines_fx64.css + ac_popup_classic_with_two_lines_fx64_star_at_the_end.css

**Comment by Aris-t2** [comment]
I found what was causing the issue on my end. New version will be up soon.
I have to "redo" the location bar category to got some sort of system into it. Its too confusing right now.
