### ISSUE TITLE
Missing style for buttons in tab toolbar

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Aris-t2/CustomCSSforFx#200]
Now we can set style for buttons in menubar/nav/bookmarks toolbar:
```
@import "./css/buttons/buttons_on_navbar_classic_appearance.css";
@import "./css/buttons/buttons_on_bookmarks_toolbar_old_size_and_appearance.css";
@import "./css/buttons/buttons_on_menubar_toolbar_classic_appearance.css";
```
but not in tab toolbar. This was possible in past through Classic Toolbar Buttons.
![Schowek04](https://user-images.githubusercontent.com/2730894/54869192-7b8fd380-4d95-11e9-81a6-4ea2fe0162f5.gif)

**Comment by Aris-t2** [comment]
Please do not post feature requests as new issues. The discussion area is the right place for such talk.

> !!! READ THIS BEFORE OPENING A NEW ISSUE REPORT !!!
> INVALID REPORTS WILL BE CLOSED WITHOUT FURTHER NOTICE TO KEEP ISSUE AREA CLEAN.
> By submitting a new issue you confirm having read and understood the below text and all 'how to report a new issue' instructions. Thanks for your understanding.
> 
> -> use TEMPLATE at the bottom after reading everything on this page <-
> 
> SUPPORT AREA for features THIS project provides
> 1. This is not a 'request' area for new stuff or legacy add-on features. Do not open a new issue about something this project does not offer. Instead join the 'General discussions, feedback, questions belong here' thread to chat and ask questions about what is or could be possible there.
> 2. Use available support threads:
> - GENERAL TALK, FEEDBACK & QUESTIONS: --> https://github.com/Aris-t2/CustomCSSforFx/issues/189
> - TABS BELOW CONTENT SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/33
> - MULTIROW TABS SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/39
> - ADD-ON BAR SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/73
> - OLD SEARCH SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/104
> 3. Read 'how to report issues properly' before posting a new issue.
> --> https://github.com/Aris-t2/CustomCSSforFx/issues/4
> 
> General problems (join general discussion thread to talk about Firefox bugs):
> - CSS code might not work, if multi-process mode (e10s) is disabled
> - CSS code imported through userContent.css might not work on macOS/Linux 
> - no support, if code contains '@namespace' references (remove that useless stuff)

**Comment by Aris-t2** [comment]
I have not offered any styles for buttons on tabs toolbar, because in Fx57+ those styles always broke tab height especially after Mozilla started to add strange padding and margins to them, but I will look into it.

**Comment by bmazak** [comment]
Can you briefly explain  what this is physically pointing to as far as location.  @import "./css/buttons/buttons_on_bookmarks_toolbar_old_size_and_appearance.css";  Is that still there?
Now I found that my CSS code was compromised with the first part being modified like this =@import "./../buttons.....
The 89 update broke my tabs and put them at the bottom of the screen.  I replaced the code with Tabs-not-on-top, and it broke the 3+ line for the bookmark muti line CSS. Can you help?
