### ISSUE TITLE
how to enable statusbar in ff 66?

### ISSUE THREAD

**Issue by DavidXanatos** [Aris-t2/CustomCSSforFx#201]
how to enable statusbar in ff 66?

**Comment by Aris-t2** [comment]
> !!! READ THIS BEFORE OPENING A NEW ISSUE REPORT !!!
> INVALID REPORTS WILL BE CLOSED WITHOUT FURTHER NOTICE TO KEEP ISSUE AREA CLEAN.
> By submitting a new issue you confirm having read and understood the below text and all 'how to report a new issue' instructions. Thanks for your understanding.
> 
> -> use TEMPLATE at the bottom after reading everything on this page <-
> 
> SUPPORT AREA for features THIS project provides
> 1. This is not a 'request' area for new stuff or legacy add-on features. Do not open a new issue about something this project does not offer. Instead join the 'General discussions, feedback, questions belong here' thread to chat and ask questions about what is or could be possible there.
> 2. Use available support threads:
> - GENERAL TALK, FEEDBACK & QUESTIONS: --> https://github.com/Aris-t2/CustomCSSforFx/issues/189
> - TABS BELOW CONTENT SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/33
> - MULTIROW TABS SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/39
> - ADD-ON BAR SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/73
> - OLD SEARCH SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/104
> 3. Read 'how to report issues properly' before posting a new issue.
> --> https://github.com/Aris-t2/CustomCSSforFx/issues/4
> 
> General problems (join general discussion thread to talk about Firefox bugs):
> - CSS code might not work, if multi-process mode (e10s) is disabled
> - CSS code imported through userContent.css might not work on macOS/Linux 
> - no support, if code contains '@namespace' references (remove that useless stuff)
> 
>
