### ISSUE TITLE
how to enable statusbar in ff 66?

### ISSUE THREAD

**Issue by DavidXanatos** [Aris-t2/CustomCSSforFx#202]
Add all information required in 1-5 and delete this line and everything above it before submitting.

1. Describe the issue
After installing the requied files to the chrome folder, only the toolbar section of firefox 66 gets changed
but now status bar gets added!

2. What should have happened instead?
A status bar should have been created.
EDIT: i want it to look like here: http://i.imgur.com/vqQCT5U.png

3. Steps to reproduce the issue?
install as described in the read me on a fresh installation of ff 66

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![Unbenannt](https://user-images.githubusercontent.com/3890945/54877804-01f2f680-4e24-11e9-8bdd-25e1d3f55bdf.png)

5. System information
- OS & OS version: Window 10
- OS theme name: Light
- DPI / HiDPI resolution:  100%
- Firefox version:  66
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: default

**Comment by Aris-t2** [comment]
You misunderstood me. 

Questions do not belong into "new" issue threads. That is what the general discussion thread exists for:
https://github.com/Aris-t2/CustomCSSforFx/issues/189

There even is a thread for the "add-on bar":
https://github.com/Aris-t2/CustomCSSforFx/issues/73

A "simulated add-on bar" can be enabled with this projects CSS:
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L548

A "real" add-on bar can be enabled by using JavaScript:
https://github.com/Aris-t2/CustomJSforFx/
https://github.com/Aris-t2/CustomJSforFx/tree/master/scripts
https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/addonbar.uc.js
