### ISSUE TITLE
tab_close_on_active_tab_only adds close to pinned tab: suggested fix

### ISSUE THREAD

**Issue by Elmohound** [Aris-t2/CustomCSSforFx#203]
Title:  Tweak for tab_close_on_active_tab_only to prevent close icons on pinned tabs

1. Describe the issue
 The tab_close_on_active_tab_only puts close symbol on pinned tabs, which are too narrow.
The behavior differs between Windows7 and MacOS (Yosemite).
On Windows, a pinned tab with the close icon expands and overwrites any pinned tab to the right.
In other words, to tabs can overlap.

On Macintosh, the effect isn't as severe,  here a pinned tab with a close icon also expands, but it shifts all the tabs to the right so that are no overlapping tabs. 

2. What should have happened instead?
Desired behavior:  There should be no close symbol present on pinned tabs, which is "standard" for pinned tabs when using "Close on active tabs only"

Suggested fix:  Modify tab_close_on_active_tab_only.css to have a conditional clause for not([pinned]).
Mine looks like this:

#tabbrowser-tabs .tabbrowser-tab:not([pinned]):[selected="true"] .tab-close-button {
  visibility: visible !important;
  display: block !important;
}

3. Steps to reproduce the issue?
  a. Edit userChrome.css to specify:   

    @import "./css/tabs/tab_close_on_active_tab_only.css"; 

 b. Launch Firefox and make sure that there are some pinned tabs

  c. Click on one or more pinned tabs in succession in order to observe how they are drawn

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
 Trouble uploading

5. System information
- OS & OS version:  Windows 7 Pro (64),  MacOS 10.10.5 (Yosemite)
- OS theme name:  Windows Classic Shell
- DPI / HiDPI resolution: 
   Windows: 1680 x 1050
   MacOS : 1680 x 1050
- Firefox version:  Firefox 66.02.2 (64-bit) 
- Firefox theme / lw-theme: I used  this project's custom userChrom.css and only changed close behavior and  uncommented multirow bookmarks support

**Comment by Aris-t2** [comment]
Actually you are right, the close button was no meant to show up on pinned tabs.
