### ISSUE TITLE
Dragging tabs from first row to another row does not work 

### ISSUE THREAD

**Issue by aisen0921** [Aris-t2/CustomCSSforFx#205]
I'm using tabs_below_navigation_toolbar_fx65_v2.css + tabs_multiple_lines_v3.css
Is it possible to fix it?

**Comment by Aris-t2** [comment]
Its possible, look here for the fix: https://github.com/Aris-t2/CustomCSSforFx/issues/39

**Comment by tomchiverton** [comment]
It's not clear to me where in the huge #39 the fix is. I've changed from tabs_multiple_lines_v2.css to tabs_multiple_lines_v3.css and in FF68 drag and drop across lines is busted.

Where exactly are the additional fixes ?

**Comment by Aris-t2** [comment]
#39 contains a similar JavaScript fix (probably not up-to-date anymore // not mine anyways) to drag tabs in a multi-tab-row environment. The CSS is for creating the multi-tab-row environment and by that time already three different CSS code snippets could create that environment (v1-3). The result was different though (tabs size, new tab position etc...).
