### ISSUE TITLE
MacOS window buttons go on top of the menu (firefox) button

### ISSUE THREAD

**Issue by locness3** [Aris-t2/CustomCSSforFx#207]
1. Describe the issue
MacOS window buttons go on top of the menu (firefox) button.

2. What should have happened instead?
The menu (firefox) button could be pushed to the right.

3. Steps to reproduce the issue?
Open a window with the theme and see.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![Capture d’écran 2019-05-24 à 17 51 44](https://user-images.githubusercontent.com/37651007/58340733-c89f2d00-7e4c-11e9-8a43-ad13deb0c6cf.png)

5. System information
- OS & OS version: OS X el capitan
- OS theme name: wat
- DPI / HiDPI resolution: idk
- Firefox version: 67.0
- Firefox theme / lw-theme: classic
- This projects settings the issue occurs with: normal

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L318

**Comment by locness3** [comment]
oh

**Comment by locness3** [comment]
Would like to have it just a bit further from the left, but not completely at the right

**Comment by locness3** [comment]
Also, when customizing (customize in menu) 
![Capture d’écran 2019-05-24 à 18 16 26](https://user-images.githubusercontent.com/37651007/58342114-23865380-7e50-11e9-85f1-e2a7bb4040ae.png)
it's on top of the new tab button

**Comment by Aris-t2** [comment]
You would need to adjust every `-moz-padding-start` value from here, if you would want to move the button to the right for a for "a bit" further:
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/appbutton/appbutton_in_titlebar_icon_only.css

Does the new tab icon glitch only occur in customizing mode or does it always occur?

**Comment by locness3** [comment]
> You would need to adjust every `-moz-padding-start` value from here, if you would want to move the button to the right for a for "a bit" further:
> [/classic/css/appbutton/appbutton_in_titlebar_icon_only.css@`master`](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/appbutton/appbutton_in_titlebar_icon_only.css) [](/Aris-t2/CustomCSSforFx/blob/HEAD@{2019-05-24T16:35:53Z}/classic/css/appbutton/appbutton_in_titlebar_icon_only.css)
> 
> Does the new tab icon glitch only occur in customizing mode or does it always occur?

Only in customizing mode

**Comment by Aris-t2** [comment]
I think we can close this.
Fx button on the right covering the non-usable new tab + in customizing mod is not an issue. I might look into it in the future.

**Comment by locness3** [comment]
> I think we can close this.
> Fx button on the right covering the non-usable new tab + in customizing mod is not an issue. I might look into it in the future.

Eeven if it's unusable, the screen lets you drag that button.

**Comment by Aris-t2** [comment]
Can you add this to userChrome.css:


```css
#main-window[tabsintitlebar][customizing] #TabsToolbar toolbarpaletteitem:last-of-type {
  -moz-margin-end: 30px !important
}
```

**Comment by locness3** [comment]
It's still behind. Also, it's behind if you have a lot tabs open.

**Comment by Aris-t2** [comment]
```css
#main-window[tabsintitlebar] #TabsToolbar {
  -moz-padding-end: 100px !important
}
```

**Comment by locness3** [comment]
That works!
