### ISSUE TITLE
identitybox_colors in DarkTheme

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#21]
When any "Dark" theme is enabled identity boxes (their default state) look like in Active/Pressed state.
![identitybox_colors](https://user-images.githubusercontent.com/32600318/32379669-d6bfc296-c0b6-11e7-83c6-460e1b67d821.png)

Maybe this is a design choice, still it looks a bit unusual (sections look squished). 
Maybe dark theme should share styling from Light one?

**Comment by Aris-t2** [comment]
Default and light theme colors look too weak on dark theme, but I can tweak the box shadow a bit, so identity does not look like a pressed button all the time.

**Comment by Acid-Crash** [comment]
Yes, this would be great.

**Comment by Acid-Crash** [comment]
fixed in 1.2.1
