### ISSUE TITLE
[Firefox 68+][Win10] AeroGlass broken

### ISSUE THREAD

**Issue by Fanfreluche** [Aris-t2/CustomCSSforFx#217]
Since Firefox 68 update, config/color_variables_aeroglass.css no longer works :(
Window background is now black instead of translucent glass.

![fx68-aeroglass](https://user-images.githubusercontent.com/25753514/61170321-09bbdf80-a568-11e9-80b0-21677ca221f0.png)

Windows 10 1809
Aero Glass 1.5.11

**Comment by Aris-t2** [comment]
If Firefox/Mozilla removed the possibility to make window/toolbars transparent using CSS, nothing can be done about it.

**Comment by LionWrathz** [comment]
> 
> 
> Since Firefox 68 update, config/color_variables_aeroglass.css no longer works :(
> Window background is now black instead of translucent glass.
> 
> ![fx68-aeroglass](https://user-images.githubusercontent.com/25753514/61170321-09bbdf80-a568-11e9-80b0-21677ca221f0.png)
> 
> Windows 10 1809
> Aero Glass 1.5.11

 Disable Firefox hardware acceleration...

Setting "layers.acceleration﻿.disabled" to true using about﻿:config do the same result.

**Comment by Aris-t2** [comment]
This has nothing to do with hardware acceleration. Firefox now uses a solid window color, probably hardcoded on Win10.

**Comment by Fanfreluche** [comment]
> Disable Firefox hardware acceleration...
> 
> Setting "layers.acceleration﻿.disabled" to true using about﻿:config do the same result.

Thank you @LionWrathz 👍 It works!
Firefox 68 hardware acceleration breaks AeroGlass effect.

**Comment by Fanfreluche** [comment]
Firefox bug opened here: https://bugzilla.mozilla.org/show_bug.cgi?id=1564514
I suppose this ticket can be closed.
