### ISSUE TITLE
Kolor otwartej karty

### ISSUE THREAD

**Issue by qwerty963** [Aris-t2/CustomCSSforFx#219]
The question is whether it is possible to change the background color of the card that is currently open?

**Comment by Aris-t2** [comment]
English only please ;-)

Use the general discussion thread: https://github.com/Aris-t2/CustomCSSforFx/issues/211

Yes, you can change the background color of the active tab.

If using default setup, you can create own color variable files or modify existing ones. This is the default one in use: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/config/color_variables.css

**Comment by krystian3w** [comment]
Deactivate classic square tabs (radius corners).

**Comment by Aris-t2** [comment]
Fx 57+ only offers squared tabs. You can use browser default squared tab by disabling classic squared tabs here: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L344
