### ISSUE TITLE
issue (overflow_menu_horizontal_remove_text.css)

### ISSUE THREAD

**Issue by mrochaaa** [Aris-t2/CustomCSSforFx#220]
I'm using FF 67.0.4, with Multi Process disable because I have low memory, using "overflow_menu_horizontal_remove_text.css" work almost all, but when I click for instance on Stylish, I can´t see the panel, because the Overflow Bar do not expand. Have some fix?

Thanks

**Comment by Aris-t2** [comment]
Are you using the latest of this projects files?

I can not reproduce this even on Fx70.

Not sure, if this has something to with multi process settings.

Anyways, there is a thread for general questions in this repository: https://github.com/Aris-t2/CustomCSSforFx/issues/211

**Comment by mrochaaa** [comment]
I use the last code, FF 67.0.4, I tryed even disable all others CSSs, but don't worked too.

**Comment by Aris-t2** [comment]
Post screenshots with the option off and on...

**Comment by mrochaaa** [comment]
Aris, with multi process enabled the menu work perfect, just disabled which have problem see, screen when disabled, is this case I clicked in Stylish: 

![1](https://user-images.githubusercontent.com/18223292/61745176-47daaf80-ad6f-11e9-993e-d55bddd066a7.jpg)

**Comment by Aris-t2** [comment]
I can't help you with this one. There is no way to distinguish between multi-process and non-multi-process  browser states using CSS. For me this looks like a visual browser glitch.

**Comment by Aris-t2** [comment]
1. I can't answer this question. No idea what you mean. If the CSS does not work without remote tabs (=multi-process), it might be an issue with Fx, but there is nothing we can do about.

2. There are add-ons on AMO for separate min, max and close buttons. Other than that I don't know what you mean. "Old" CSS will most likely not be compatible with current Fx versions.

**Comment by mrochaaa** [comment]
thanks, Aris I have the below CSS to auto-hide sidebar, and it work, but when I try switch from bookmark to history the sidebar close, please, if possible, have something to do to keep sidebar opened when cursor is over the header and over the menu? And have someway to add bookmark and history links side by side on header? Help me if possible, thanks.

code:

:root {
  --sidebar-hover-width: 1px;
  --sidebar-visible-width: 230px;
}

#sidebar-box {
  position: relative !important;
  overflow: hidden !important;
  margin-right: calc(var(--sidebar-hover-width) * -1) !important;
  left: var(--sidebar-hover-width) !important;
  min-width: var(--sidebar-hover-width) !important;
  max-width: var(--sidebar-hover-width) !important;
}

#sidebar-box:hover {
  margin-right: calc(var(--sidebar-visible-width) * -1) !important;
  left: var(--sidebar-visible-width) !important;
  min-width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
}

#sidebar {
  opacity: 0 !important;
}

#sidebar:hover {
  opacity: 1 !important;
}

#main-window[inFullscreen] #sidebar-box {
   display:none !important;
   width: 0px !important;
}

**Comment by Aris-t2** [comment]
I don't think the above code can be tweaked to solve you issue. The moment the button popup opens the "hover" state of your sidebar is lost.

**Comment by mrochaaa** [comment]
Ok, thanks your attention

**Comment by mrochaaa** [comment]
Aris, about the overflow menu issue with multi process disabled, I got fix it with below code, the main change is "auto" in the end, now 99% of all plugins can expand the panel, but have one exception , for instance "Multithreaded Download Manager" can't expand, see my code, have some possible tweak? Thank you...

#widget-overflow:not([remote="false"]) .panel-arrowcontent,
#widget-overflow:not([remote="false"]) panelmultiview,
#widget-overflow:not([remote="false"]) .panel-viewcontainer,
#widget-overflow:not([remote="false"]) .panel-viewstack,
#widget-overflow:not([remote="false"]) .panel-subview-body {
  padding: 0 !important;
  margin: 0 !important;
  min-height: unset !important;
  height: auto !important;
  max-height: auto !important;}

**Comment by Aris-t2** [comment]
I've added the "auto" rules to current version of this projects files.
