### ISSUE TITLE
move the address bar?

### ISSUE THREAD

**Issue by morosakubek** [Aris-t2/CustomCSSforFx#23]
Hi,
Is it possible to move the address bar? When i turn on "legalcy extension" in Nightly this possibility exists.

**Comment by userOperaFF** [comment]
Hide posible is only css, I can not hide in _adjust page_.
Move where is you expect?

**Comment by Aris-t2** [comment]
This project only targets CSS tweaks to change browser ui. Making location bar movable is not possible with CSS only JavaScript or XUL overlays. Here is some "cheat" to make it possible in Firefox 57+: https://github.com/Aris-t2/CustomCSSforFx/issues/3#issuecomment-338690666

The "legacy" add-on CTR does not support Firefox 57+ officially.
