### ISSUE TITLE
[Firefox 69+] AeroGlass TOOLBARS may not work due to the XUL file change since version 69+ 

### ISSUE THREAD

**Issue by wyqy** [Aris-t2/CustomCSSforFx#230]
1. Describe the issue

"Windows 10 fix for Glass8" function in "AeroGlass TOOLBARS" chart cannot work after upgrade the browser to version 69, the tabbar cannot be transparent with Glass8 on.

2. What should have happened instead?

The tabbar should become transparent with Glass8 on.

3. Steps to reproduce the issue?

1) Run Glass8 on Windows8+, and upgrade the version of Firefox to 69+;
2) Edit userChrome.css to make the function
"./css/toolbars/general_toolbar_colors_aeroglass_windows10_glass8.css" be vaild;
3) Restart Firefox, the tabbar cannot be transparent.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- OS & OS version: Windows10
- OS theme name: Windows
- DPI / HiDPI resolution: 125%
- Firefox version: 69.0.0
- Firefox theme / lw-theme: Default
- This projects settings the issue occurs with: None.

PS: Edit the file(\chrome\css\toolbars\general_toolbar_colors_aeroglass_windows10_glass8.css), make the line 8 to be as below can solve the problem:
@-moz-document url(chrome://browser/content/browser.xhtml) {

**Comment by Aris-t2** [comment]
The fix will be included into next update.

**Comment by Aris-t2** [comment]
Fixed in 2.7.2 release.
