### ISSUE TITLE
autocomplete popup with two-lined results shows both overlayed in one line

### ISSUE THREAD

**Issue by CoSoCo** [Aris-t2/CustomCSSforFx#232]
1. Describe the issue
See subject line.
I have this problem since v2.7.2 with FF 68. Same now with v2.7.4 with FF 69.

2. What should have happened instead?
Actually see 2 text lines.

3. Steps to reproduce the issue?
Type some text in the location bar

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
[userChrome.css.txt](https://github.com/Aris-t2/CustomCSSforFx/files/3644370/userChrome.css.txt)
[userContent.css.txt](https://github.com/Aris-t2/CustomCSSforFx/files/3644371/userContent.css.txt)
![Firefox Aris-CSS corrupted location bar search](https://user-images.githubusercontent.com/14809606/65467054-cbdd1080-de60-11e9-9fe5-8d87587af58e.png)

5. System information
- OS & OS version: Ubuntu 18.04
- OS theme name: Unity
- DPI / HiDPI resolution: 1680x1050
- Firefox version: 69
- Firefox theme / lw-theme: default
- This projects settings the issue occurs with: See attachment

**Comment by Aris-t2** [comment]
You have to disable `@import "./css/locationbar/ac_popup_url_and_title_50percent_width.css";`, if you are using any other ac popup option.

**Comment by CoSoCo** [comment]
Oops, thank you.
Interesting ... with 2.5.6 I had the combination
`@import "./css/locationbar/ac_popup_url_and_title_50percent_width.css";`
`@import "./css/locationbar/ac_popup_classic_with_two_lines_fx64_star_at_the_end.css";`
... which didn't hurt.
I used 2.5.6 very long time until 2.7.2.

**Comment by CoSoCo** [comment]
Oops, thank you!
Interesting ... with 2.5.6 I had the combination:
`@import "./css/locationbar/ac_popup_url_and_title_50percent_width.css";`
`@import "./css/locationbar/ac_popup_classic_with_two_lines_fx64_star_at_the_end.css";`
... which didn't hurt.
I used 2.5.6 very long time until 2.7.2.

BTW: Is it possible to show more than 10 results with ac_popup ?

**Comment by Aris-t2** [comment]
Sure,
about:config > browser.urlbar.maxRichResults > 20 > restart Fx.
