### ISSUE TITLE
[Firefox 71+] Multiline tabs overlaps bookmarks toolbar

### ISSUE THREAD

**Issue by myname1614** [Aris-t2/CustomCSSforFx#237]
```
enabled:
@import "./css/tabs/tabs_below_navigation_toolbar_fx68.css"
@import "./css/tabs/tabs_multiple_lines_v4.css";
```
1 row example
![2019-10-17_1631](https://user-images.githubusercontent.com/34938365/67013368-abb90e00-f0fb-11e9-9c5c-7d03b64bc672.png)

2 rows:
![2019-10-17_1632](https://user-images.githubusercontent.com/34938365/67013438-c9867300-f0fb-11e9-9d1f-82543ca35fa3.png)

**Comment by Aris-t2** [comment]
This combination is not supported:
use `tabs_below_navigation_toolbar_fx65_v2.css `

**Comment by myname1614** [comment]
thanks!!!

![image](https://user-images.githubusercontent.com/34938365/67014638-d99f5200-f0fd-11e9-8f67-083d3f3b2fe7.png)
