### ISSUE TITLE
70-72: any idea how to update popup_menupopup_with_scrollbars.css?

### ISSUE THREAD

**Issue by shmediaproductions** [Aris-t2/CustomCSSforFx#240]
Can't add scrollbars to bookmarks popup anymore. I don't know if it was like this before but it seems like the menupopup contents are in shadow DOM now. But I can't even get a scrollbar to show up dynamically selecting it with CSS. I think they might be hiding the scrollbar through other means now since overflow is not automatically hidden. It's like the scrollbuttons qualify as a scrollbar somehow

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/issues/211#issuecomment-546066162

**Comment by shmediaproductions** [comment]
yeah that doesn't work for me as of 72 :s

**Comment by shmediaproductions** [comment]
actually i'm not sure which one it was but i copied the code for every version in your comment into an agent sheet and loaded it with js and it worked. for some reason doesn't work for me in either a user sheet or an author sheet

**Comment by shmediaproductions** [comment]
Turns out it was the latest one, maybe the problem was I was live editing the css so it wasn't being loaded in the shadow tree

**Comment by Aris-t2** [comment]
Strange, it worked fine for me in userChrome.css.

When using the JS css loader script the caches have to be cleared after every code/css change or the new code will get ignored and the old cached one will remain in use.
