### ISSUE TITLE
Firefox 68 ESR - Private mode purple mask icon not showing

### ISSUE THREAD

**Issue by JIPG2** [Aris-t2/CustomCSSforFx#245]
1. Describe the issue
When open a private window, purple mask icon is not showing. I have not activated the line 
/* @import "./css/generalui/private_mode_indicator_hidden.css"; /**/ in chrome.css. I have not activated the "no remember history" in privacy settings.
Removing all chrome folder (no css at all), the problem is gone.

2. What should have happened instead?
A purple mask should appear when in private mode in the right uppermost corner.

3. Steps to reproduce the issue?
Open a private window/tab.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
With css:

![2019-10-28 22_09_07-](https://user-images.githubusercontent.com/43722308/67718805-cf6c3600-f9d0-11e9-82e9-c11a0998ee28.png)

Without chrome folder:
![2019-10-28 22_13_45-](https://user-images.githubusercontent.com/43722308/67718845-e743ba00-f9d0-11e9-921b-47cecf6667e5.jpg)

5. System information
- OS & OS version: Windows 10, 1903 version
- OS theme name: none
- DPI / HiDPI resolution:   1080 screen, 15"
- Firefox version:   68.2 ESR
- Firefox theme / lw-theme:   lw-theme Strata 3.5 B
- This projects settings the issue occurs with: 

I have activated the following css:
@import "./config/general_variables.css"
@import "./config/color_variables_fx3.css"
@import "./css/buttons/buttons_on_navbar_classic_appearance.css"
@import "./css/buttons/icons_custom_icons_fx45.css"
@import "./css/buttons/buttons_on_bookmarks_toolbar_old_size_and_appearance.css"
@import "./css/buttons/bookmarks_menu_button_localized_label_on_bookmarks_toolbar.css"
@import "./css/buttons/bookmarks_menu_button_popup_classic_appearance.css"
@import "./css/buttons/forward_button_hide_when_disabled.css"
@import "./css/buttons/custom_backforward_large_kempelton.css"
@import "./css/appbutton/appbutton_popup_more_icons.css";
@import "./css/appbutton/appbutton_popup_icons_colorized.css"
@import "./css/appbutton/appbutton_in_titlebar_icon_only_browser_logo.css"
@import "./css/appbutton/appbutton_in_titlebar_autocolor.css"
@import "./css/tabs/classic_squared_tabs.css"
@import "./css/tabs/tabs_below_navigation_toolbar_fx68.css"
@import "./css/tabs/missing_tab_favicon_restored_default.css"
@import "./css/tabs/tab_throbber_blue_fx56.css"
@import "./css/tabs/tab_close_on_active_tab_only.css"
@import "./css/tabs/tab_icon_colors.css"
@import "./css/generalui/bookmark_icons_colorized.css"
@import "./css/generalui/findbar_on_bottom_close_at_findbars_start.css"
@import "./css/generalui/context_bfrsb_labels_with_icons.css"
@import "./css/generalui/close_icon_windows7v2.css"
@import "./css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css" 
@import "./css/toolbars/addonbar_status_in_addonbar.css"
@import "./css/toolbars/addonbar_content_on_the_right.css"
@import "./css/toolbars/toolbars_old_padding.css"; /**/
@import "./css/toolbars/tabs_toolbar_adjustments.css"
@import "./css/toolbars/bookmarks_toolbar_old_height.css"
@import "./css/toolbars/general_toolbar_colors.css"
@import "./css/locationbar/locationbar_adjustments.css"; /**/
@import "./css/locationbar/compact_mode_reduce_fontsize.css"
@import "./css/locationbar/locationbar_reduce_height.css"
@import "./css/locationbar/identitybox_colors.css"
@import "./css/locationbar/identitybox_padlock_icon_modern.css"
@import "./css/locationbar/icons_colorized.css"
@import "./css/locationbar/pageaction_separator_in_location_bar_hidden.css"
@import "./css/locationbar/starbutton_is_last_pageaction_button.css"; /**/
@import "./css/locationbar/starbutton_popup_preview_image_hidden.css"
@import "./css/locationbar/dropmarker_at_the_end.css"; /**/
@import "./css/locationbar/dropmarker_visible.css"
@import "./css/locationbar/ac_popup_url_and_title_50percent_width.css"
@import "./css/locationbar/ac_popup_result_font_size.css"

**Comment by Aris-t2** [comment]
Sorry, but this is intended behavior. 

The case "tabs not on top"+"OS titlebar" breaks tabs toolbar, if the indicator is present. This happened since Fx65, so the private mask got hidden.
