### ISSUE TITLE
[C][Win10][Fx58] custom back-forward observations

### ISSUE THREAD

**Issue by Pizzapops** [Aris-t2/CustomCSSforFx#25]
The current userChrome.css 1.2.2 and previous versions have a duplicated line. Both lines 66 and 69 refer to **custom_backforward_small_ff3_strata.css**. Is there a chance that the associated png can be displayed with a couple more pixels on the left and less on the right?
![fwd_bak](https://user-images.githubusercontent.com/33039961/32556274-9a02593e-c464-11e7-9100-96474111177c.jpg)

**Comment by Aris-t2** [comment]
You are right, haven't noticed that one, I will remove the duplicatede line on next update.

The back-button needs 2px padding at the left, but the forward button is fine. The gap seems so big, because the location bar also adds a big gap. You can reduce it by adding this to your userChrome.css

```css
#urlbar {
  -moz-margin-start: 0px !important;
}
```

**Comment by Pizzapops** [comment]
Thanks again!

Aris wrote:
>
> #urlbar {
> -moz-margin-start:0px !important;
> }
