### ISSUE TITLE
[Fx71] Tabs on multiple rows wind up overlapping window content with tabs below search bar.

### ISSUE THREAD

**Issue by jrowat** [Aris-t2/CustomCSSforFx#255]
1. Describe the issue
When a second or third row of tabs opens, with tabs below navigation, the tabs overlap the content of the window instead of displacing it.

2. What should have happened instead?
The tab bar should displace the window content.

3. Steps to reproduce the issue?
Install FF71. Pull down a fresh copy of CustomCSSforFX and install it in the profile/chrome folder. uncomment the 
```
@import "./css/tabs/tabs_below_navigation_toolbar_fx72.css"; /**/ 
@import "./css/tabs/tabs_multiple_lines_fx71_force_newtab_button_visibility.css"; /**/  /* Fx 71+ */
```
lines
Start firefox and open enough tabs to get multiple rows.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![image](https://user-images.githubusercontent.com/47221310/70329614-cf4e2a00-1809-11ea-95e3-4a9b6b34ba3f.png)

5. System information

-  OS & OS version: Windows 10 Pro 1909
-  OS theme name: I have no idea. It's Win10, "default"?
-  DPI / HiDPI resolution: Happens in both 1920x1080 and 4K
-  Firefox version: 71.0 64-bit default release.
-  Firefox theme / lw-theme: Mozilla default
-  This projects settings the issue occurs with:
I have enabled:

```
@import "./config/general_variables.css"; /**/
@import "./css/buttons/icons_colorized.css"; /**/
@import "./css/buttons/whatnew_button_always_hidden.css"; /**/
@import "./css/appbutton/appbutton_popup_more_icons.css"; /**/
@import "./css/appbutton/appbutton_popup_icons_colorized.css"; /**/
@import "./css/tabs/tabs_below_navigation_toolbar_fx72.css"; /**/
@import "./css/tabs/tabs_multiple_lines_fx71_force_newtab_button_visibility.css"; /**/  /* Fx 71+ */
@import "./css/tabs/missing_tab_favicon_restored_default.css"; /**/
@import "./css/tabs/tab_close_on_active_tab_only.css"; /**/
@import "./css/generalui/private_mode_indicator_hidden.css"; /**/
@import "./css/generalui/bookmark_icons_colorized.css"; /**/
@import "./css/generalui/context_bfrsb_labels_without_icons.css"; /**/
@import "./css/generalui/searchbar_glassplus_indicator_hidden.css"; /**/
@import "./css/toolbars/general_toolbar_colors.css"; /**/
@import "./css/locationbar/locationbar_adjustments.css"; /**/
@import "./css/locationbar/compact_mode_reduce_fontsize.css"; /**/
@import "./css/locationbar/identitybox_colors.css"; /**/
@import "./css/locationbar/icons_colorized.css"; /**/
@import "./css/locationbar/pageaction_separator_in_location_bar_hidden.css"; /**/
@import "./css/locationbar/starbutton_is_last_pageaction_button.css"; /**/
@import "./css/locationbar/starbutton_popup_preview_image_hidden.css"; /**/
@import "./css/locationbar/dropmarker_at_the_end.css"; /**/
@import "./css/locationbar/dropmarker_visible.css"; /**/
@import "./css/locationbar/ac_popup_url_and_title_50percent_width.css"; /**/
@import "./css/locationbar/ac_popup_result_font_size.css"; /**/
@import "./my_userChrome.css"; /**/
```

All other lines are disabled. I have not customised the other CSS files. I do not have a my_userchrome.css file.

**Comment by Aris-t2** [comment]
**tabs_below_navigation_toolbar_fx72.css** is for Firefox 72. Use the "older" one for Fx 71.

Look into userChrome.css

```css
/* - Fx 68-71 Windows/Linux (use the Fx 65+ versions for macOS) *********************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx68.css"; /**/
```

**Comment by jrowat** [comment]
Whoops.  Thanks!   Similar issue now with the FX68.css one, though:  When the second line appears, it pushes the first line *up*, under the navigation bar and buttons.  The second row looks like the first row, and the first row is invisible except for the currently-focused tab.

![image](https://user-images.githubusercontent.com/47221310/70344894-c02aa480-1828-11ea-943a-c7c93fcb2ff8.png)

**Comment by Aris-t2** [comment]
Make sure you are using the correct settings. The combination tabs below navigation bar and multiple tab rows requires very specific settings. [There is also a thread dealing with multiple tab rows.](https://github.com/Aris-t2/CustomCSSforFx/issues/39#issuecomment-562086509)

**Comment by jrowat** [comment]
Got it working by switching to the FX65 one like you suggested in that other thread.  Thanks a ton, this project is a lifesaver and I really appreciate all the work you do.
