### ISSUE TITLE
Overwriting one version with new release

### ISSUE THREAD

**Issue by Roxie2401** [Aris-t2/CustomCSSforFx#256]
I'm new to this process and have very little experience in using style sheets, etc. so forgive if this issue is addressed somewhere else.

If I have installed CustomCSSforFX version 2.8.9 and have set the options I want to use.......what is the recommended way of installing (Updating) to the latest release (2.9.0) without having to reset the previous settings (Imports)?

What I find, and am most likely missing something, it appears by just running the new version, it completely overwrite the old --- resetting everything.

What am I missing?

Thank you so much for the great development work --- my biggest use has been getting the Tabs back on the bottom and in multiple rows.

**Comment by Speravir** [comment]
See #64. 

I use Winmerge as diff tool which is able to compare inside of archives, but there are similar tools, as well. I first update the several style files by copying them from the rchive into their folders and occasionally deleting old files where there is no equivalent in the archive anymore. Then I compare `userContent,css` and `userChrome,css`. This takes some time, but is faster and much more safe than checking without such a tool.

**Comment by Aris-t2** [comment]
@Roxie2401 

This is the easiest way in my opinion:
1. Backup chrome folder
2. Replace current folders with new folders
3. If something changed in an unexpected way, look into [commits](https://github.com/Aris-t2/CustomCSSforFx/commits/master) userChrome.css and userContent.css files and copy over changed or new entries of setting you are using.
 
Continue here: https://github.com/Aris-t2/CustomCSSforFx/issues/64
