### ISSUE TITLE
No menubar

### ISSUE THREAD

**Issue by archer310** [Aris-t2/CustomCSSforFx#259]
First time posting, so bear with me.  Just updated to 2.9.1, got my tabs back where I wanted them, but I have lost my menu bar and can't figure out how to get it back.  Not sure if it's from 2.9.1.  I have tried to do the Customize in FF, but menubar is selected.  If I de-select Titlebar, part of the menubar appears, so it appears to be hidden under the Titlebar.  Is there a line in 2.9.1 that I should be activating/deactivating to make the menubar appear?  Thank you.

**Comment by Aris-t2** [comment]
Are you using `tabs_below_navigation_toolbar_fx65_v2.css`? In this case there are issues with menubar.

```css
/* - Fx 65+ v2 - mainly for multi-lined tabs (Glitches with inactive menubar!) ******************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css"; /**/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2_force_hidden_menubar.css"; /**/ /* no menubar when OS titlebar is active */
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2_macOS.css"; /**/
```

**Comment by archer310** [comment]
I'm stupid - I activated the wrong line.  Everything is fine now.  Thank you for your help.
