### ISSUE TITLE
[Win][Fx57][Compact dark theme] active tab non-distinguishable from other tabs on dark windows

### ISSUE THREAD

**Issue by userOperaFF** [Aris-t2/CustomCSSforFx#26]
![obraz](https://user-images.githubusercontent.com/33114475/32741269-ecd7e080-c8a5-11e7-876a-988fc8d5470d.png)

When use Compact Black theme.

![obraz](https://user-images.githubusercontent.com/33114475/32741333-3427245a-c8a6-11e7-998a-9b0ec25afc84.png)

I must use lighter Personas e.g. https://addons.mozilla.org/pl/firefox/addon/black-15433/, In Compat black I can not find active. I can not see bottom border is active / deactive or squeezing active tab.

**Comment by Aris-t2** [comment]
Non-active and hovered tabs will get slightly brighter colors on next update.
