### ISSUE TITLE
Address/Location Bar Size in FF71

### ISSUE THREAD

**Issue by Old-Knobby** [Aris-t2/CustomCSSforFx#261]
Another new contributor just signed up to report an issue I'm seeing. I've recently updated to FF71 and the address/location bar is now taking up most of screen width as shown in this partial screen shot:

![Screen1](https://user-images.githubusercontent.com/58953558/70934189-461eca80-2035-11ea-88b7-82b7ea2e3e16.png)

This causes my home button, search bar and add-on buttons to be demoted to the more tools button on the right. If I go into the Firefox customise toolbar option these items are shown in the locations that they used to be before the address bar 'grew', as shown:

![Screen2](https://user-images.githubusercontent.com/58953558/70934499-f12f8400-2035-11ea-816f-402ef0c1c623.png)

Any ideas what options I need to enable/disable/edit to return it to how it was? I've ensured I'm using the latest version of CustomCSSforFF (2.9.4 v2).

Other info requested:

OS & OS version: Windows 10 64-bit version 1909 build 18363.535
OS theme name: Just the standard Win 10 desktop one
DPI / HiDPI resolution: 1920 x 1080
Firefox version: 71.0 (64-bit)
Firefox theme / lw-theme: Just the standard, Default 1.0
This projects settings the issue occurs with: Not sure what's required here?

**Comment by Aris-t2** [comment]
How do things look when you keep this projects default configuration without modifying any file?
Backup your `chrome` folder and extract 2.9.4 v2 files into it. Post a screenshot.

The appbuttun in titlebar "option" caused this in the past, but its code is inactive when using OS titlebar.

**Comment by Aris-t2** [comment]
This is the result for me on Fx 71:
![001](https://user-images.githubusercontent.com/6013569/70936306-52f5eb00-2042-11ea-8297-7e0b3da5bb56.PNG)
![002](https://user-images.githubusercontent.com/6013569/70936307-52f5eb00-2042-11ea-9404-b20216a1728c.PNG)

OS & OS version: Windows 10 64-bit version 1909 build 18363.535
OS theme name: default + colorized titlebar
DPI / HiDPI resolution: 1920 x 1080
Firefox version: 71.0 (64-bit)
Firefox theme / lw-theme: default

**Comment by Old-Knobby** [comment]
Thanks for the reply. The default 2.9.4 v2 files seem to work ok in this regard:

![Screen3](https://user-images.githubusercontent.com/58953558/71013641-ebdf4180-20e8-11ea-83d8-9284348893ab.png)

It only happened when I updated Firefox to 71. It was ok with the previous version 70.<whatever>, when I was running CustomCSSforFx 2.9.2.  Since updating Firefox, 2.9.2, 2.9.3 and 2.9.4 have all exhibited this 'feature'. No doubt Mozilla changed something...

**Comment by NotoIsBest** [comment]
I was coming in to report this, but instead might as well pitch in to say I have the same problem:

![firefoxlocaitonbar](https://user-images.githubusercontent.com/30021945/71017874-08d33f00-2100-11ea-9c9e-1ba135dc15ed.png)

It's the exact same for me as it is with @Old-Knobby - it was fine on Firefox 70, using 2.9.4v2 as it is by default works fine. Changing the settings however, broke the address bar.
 
OS & OS version: Windows 10 64-bit version 1903 build 18632.535
OS theme name: dark
DPI / HiDPI resolution: 1366 x 768
Firefox version: 71.0 (64-bit)
Firefox theme / lw-theme: light

**Comment by Aris-t2** [comment]
> Changing the settings however, broke the address bar.

Which one broke the address bar?

**Comment by NotoIsBest** [comment]
> 
> 
> > Changing the settings however, broke the address bar.
> 
> Which one broke the address bar?

Okay, found it! 

 @import "./css/appbutton/appbutton_hidden.css"

If I hide the appbar, everything breaks. If I let it be there as it is by default, however.. 

![firefoxlocationbaryes](https://user-images.githubusercontent.com/30021945/71020618-5900d000-2105-11ea-941b-d49c772ea8fc.png)

It shows as it should!

**Comment by Old-Knobby** [comment]
Good spot! I've got 'appbutton_hidden.css' included too, and removing it returns the appearance back to how it was, all be it with the app button now obviously present.

**Comment by Aris-t2** [comment]
Is `appbutton_in_titlebar.css` disabled too?
It should not be active, if the button gets hidden anyway.

Its strange, that this does not happen here on Fx71-73.

**Comment by NotoIsBest** [comment]
`appbutton_in_titlebar.css` was enabled, but disabling it didnt change anything, the locationbar was still broken if I hide the appbutton. The CSS you gave to hide the button does however work with no problems!

**Comment by Aris-t2** [comment]
[2.9.5](https://github.com/Aris-t2/CustomCSSforFx/releases)

**Comment by Old-Knobby** [comment]
Now working fine for me in 2.9.5, many thanks!
