### ISSUE TITLE
[Win7] appmenu appears sometimes behind vertical taskbar

### ISSUE THREAD

**Issue by vladtepesch** [Aris-t2/CustomCSSforFx#262]
Add all information required in 1-5 and delete this line and everything above it before submitting.

1. Describe the issue
i often have the problem, that the main menu is displayed behind the taskbar
![grafik](https://user-images.githubusercontent.com/1601159/71252984-cb042f80-2326-11ea-9b19-ded3ac70a7c6.png)

however that is not always the case- i could not found a reason why this sometimes happens and sometimes not

2. What should have happened instead?
menu hould be either drawn inside the firefox window area or be the topmost item. 
firefox should respect the current screens work area rectangle and only draw items within this region

3. Steps to reproduce the issue?

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- OS & OS version: 
various windows
- OS theme name:
nothing special, taskbar at left side
- DPI / HiDPI resolution: 
1920x1080
- Firefox version:  
various (problem exist since a long time from time to time)
- Firefox theme / lw-theme: 
normal with cutomCSSforFx 
- This projects settings the issue occurs with:

**Comment by Aris-t2** [comment]
This can not be fixed. Firefox does not detect your vertical taskbar the way it should detect screens edge for example.

**Comment by Aris-t2** [comment]
I just tried to replicate this on a Win 7 VM, and everything was fine.

![w7](https://user-images.githubusercontent.com/6013569/71264802-2513ed80-2345-11ea-9213-6b64236da8df.PNG)

**Comment by vladtepesch** [comment]
> 
> 
> I just tried to replicate this on a Win 7 VM, and everything was fine.
> 
> ![w7](https://user-images.githubusercontent.com/6013569/71264802-2513ed80-2345-11ea-9213-6b64236da8df.PNG)

as i said - sometimes it works - sometimes it does not

**Comment by Aris-t2** [comment]
Well, I know, ;-)
However there is nothing I can do about this Firefox behavior.

**Comment by vladtepesch** [comment]
hmm - i think it has omething to do with connecting/disconnecting external monitors and maybe video fullscreen playing (maybe while removing external monitor)

**Comment by Aris-t2** [comment]
That is possible and would mean there is some window/screen miscalculation somewhere inside Fx code.

**Comment by vladtepesch** [comment]
> That is possible and would mean there is some window/screen miscalculation somewhere inside Fx code.

yeah thats possible - so i close this issue if this is out of scope of this project
