### ISSUE TITLE
Orange Firefox Button disappeared after upgrading to 72

### ISSUE THREAD

**Issue by piotrmil** [Aris-t2/CustomCSSforFx#267]
1. Describe the issue
Just updated Firefox to 72, now the orange Firefox button is invisible... until I start typing something in the address bar. Then it re-appears. And when I stop typing in it, it disappears again.

2. What should have happened instead?
I would like it to stay visible all the time, thank you very much.

3. Steps to reproduce the issue?
1.Have my setup from ten minutes ago.
2.Update to 72
3.Get angry at this incredibly small inconvenience easily fixed by pressing alt and accessing all the other menus.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![Clipboard01](https://user-images.githubusercontent.com/1182094/71954567-07b89d80-31e6-11ea-8e9d-a028f2497dc2.jpg)

5. System information
Windows 7
Firefox 72
Classic CSS tweaks for Firefox Quantum v2.9.6

**Comment by Aris-t2** [comment]
Strange issue.

Can you test a new setup of this projects files in a clean chrome folder without modifying anything?

**Comment by coyotefish** [comment]
I'm having the same issue.  Curious.

**Comment by Aris-t2** [comment]
Have you also tested latest complete package (2.9.7) without any other modifications inside chrome folder?

**Comment by coyotefish** [comment]
2.9.7 unmodified works.  There was some combination of other settings that was causing it to disappear, but unfortunately I didn't track them and can't seem to replicate them now.

**Comment by Aris-t2** [comment]
Most likely this was enabled: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L243

**Comment by coyotefish** [comment]
I checked that, and I've never had it enabled in any version.  Puzzling.
