### ISSUE TITLE
RSS button in address bar

### ISSUE THREAD

**Issue by Thalon77** [Aris-t2/CustomCSSforFx#270]
1. Describe the issue

Just noticed a little thing that happened after updating firefox to V72: a new RSS button in the address bar is now visible

2. What should have happened instead?

Just need a way to make it disappear (some new option in the about: config menu?)

3. Steps to reproduce the issue?

Just open firefox

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![Cattura](https://user-images.githubusercontent.com/33811707/72007946-0ec9c500-3253-11ea-988e-936be8122202.JPG)

5. System information
- OS & OS version: win10
- Firefox version: 72.0.1

**Comment by Aris-t2** [comment]
Is this caused by this projects files?

You can right-click any item and select "Remove from Address Bar"...
