### ISSUE TITLE
[Firefox 72+] my_userChrome.css stopped working

### ISSUE THREAD

**Issue by xXJOKRXx** [Aris-t2/CustomCSSforFx#272]
This is the first time that I open an issue here, so please excuse me if I make any mistakes.

**Describe the issue:**
Any code inside my_userChrome.css doesn't work, and if I put the exact same code inside userChrome.css it works just fine.
I made sure @import "./my_userChrome.css"; is included in userChrome.css.

This issue started with Firefox 72.

For example, the following code doesn't work:
`
/* Hide "Saved to Library!" bookmark confirmation popup */
#confirmation-hint { display: none !important; }
`

**What should have happened instead?**
Any code inside my_userChrome.css should work without having to put it inside userChrome.css

**System information**
- OS & OS version: Windows 10 1903 x64
- Firefox version: 72.0.1 64 bit

**Comment by Aris-t2** [comment]
I can ensure you importing `my_userChrome.css` from `userChrome.css` still works with any available version of Firefox.

Test different code, that yours, maybe the code does not work in Fx 72+ at all.

**Comment by xXJOKRXx** [comment]
Well I must've done something wrong then.

The problem is not in the code since as I mentioned before, the code works if I put it in userChrome.css, but it doesn't work if I put it in my_userChrome.css
`#confirmation-hint { display: none !important; }`

Any idea what could be the cause of this behavior?

**Comment by Aris-t2** [comment]
This can happen if syntax errors inside `userChrome.css` file cause `my_userChrome.css` file not load at all although the import code is correct.

You could try a very simple test.
1. Move everything inside `chrome` folder into a subfolder "backup" of similar.
2. Create two CSS files inside `chrome` folder.

`userChrome.css`

```css
@import "./my_userChrome.css";
```

`my_userChrome.css`

```css
toolbar {
  background: lightblue !important;
  color: red !important;
}
```

or extract these ready to use files:
[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/4058590/chrome.zip)

**Comment by xXJOKRXx** [comment]
Yup, that worked.
Sorry for the inconvenience!
