### ISSUE TITLE
[FF72] Multirow tabs disappear (auto-hide?) from 

### ISSUE THREAD

**Issue by dromhost** [Aris-t2/CustomCSSforFx#274]
1. Describe the issue

Multirow tabs disappear (auto-hide?), a few seconds after making a new tab. This started occuring after Firefox 72 was installed. Only the latest tab is displayed. See image with centered red highlighted tab only, on row 3. Row 2 and onwards is hidden.

2. What should have happened instead?

All tabs should be visible, or tab-scrolling should appear. 

3. Steps to reproduce the issue?

Unable to get rid of it while using multirow settings in css files

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

https://imgur.com/Zg2NfUC

![screen_FF72](https://user-images.githubusercontent.com/59953395/72504834-e50a3280-383e-11ea-8ef3-37cfeb9a2df5.png)

5. System information
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
UBUNTU_CODENAME=xenial

  dimensions:    1366x768 pixels (361x203 millimeters)
  resolution:    96x96 dots per inch

Firefox 72.0.1 (64-bit)
Default Theme

- This projects settings the issue occurs with: 

using
@import "./css/tabs/tabs_below_navigation_toolbar_fx72.css"
@import "./css/tabs/tabs_multiple_lines_fx71_force_newtab_button_visibility.css"

Any ideas?
Thanks

**Comment by Aris-t2** [comment]
The above combination is not supported. Use "tabs_below_navigation_toolbar_fx65_v2" in this case as mentioned in the file: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L349

Anything regarding multiple tab lines goes here: https://github.com/Aris-t2/CustomCSSforFx/issues/39
