### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by DavyRay** [Aris-t2/CustomCSSforFx#275]
I use a portable version of FF.  For some reason last night youtube videos stopped working.  I would simply get error loading.  So this morning i reinstalled FF 72.01 portable and figured i would let FF set itself up again.  did not work.  So i installed v 71.0. That worked.

I then copied the chrome folder from my "messed up" version thinking that i would get all my settings back.  Primarily tabs below menu bar.  When i load up FF it gives me an error

A script on this page may be busy or may have stopped responding....... Script: chrome://global/content/customElements.js:450

So i tried to download the latest version of the scrtip and simply remove the /* in front of "@import "./css/tabs/tabs_below_main_content_fx68.css"; /**/" as i have FF 71 on windows.  Restarted FF.... same problem.  IT does not put the tabs below and i recall when i first started the script a few months ago it changed all the icons everywhere.  Nothing happens now.

Any ideas?

**Comment by Aris-t2** [comment]
You also have to use the latest version of the script: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L372

Fx72 received "own" options...

**Comment by DavyRay** [comment]
i am using 2.9.9.  As v72 was acting up on me... i reindtalled and put v71 back in.

i also remember when i first installed this script a few months ago for the first time, it changed all the icons everywhere.  This time when i installed v71 of FF for the first time, and installed the script for the first time nothing changed. 

I remember hating some of the icons and i had to find the line in the script to disable it.  This time on a fresh install of both FF and the script, i got that error as mentioned in the original post and nothing changed visually

**Comment by DavyRay** [comment]
ok problem fixed...

i had to make sure:; toolkit.legacyUserProfileCustomizations.stylesheets' is set to 'true' or custom  ... as it was a new install of FF it was not.. that fixed the script... 

however i still have the error: I tried to put my old script back in or use the v2.9.9 and both come up and give me this error

A script on this page may be busy, or it may have stopped responding. You can stop the script now, or you can continue to see if the script will complete.

Script: chrome://global/content/customElements.js:450

**Comment by Aris-t2** [comment]
Not sure what to tell about JS scripts. They might be also incompatible to Fx 72 and require updates, if they are custom made.
