### ISSUE TITLE
[Fx 72] button in titlebar induces disappearance of buttons when resizing

### ISSUE THREAD

**Issue by Ollives** [Aris-t2/CustomCSSforFx#278]
Hello everyone,

This is my first posting here, thus I apologize in case of any mistake.
I love this work but I would like to report an annoying bug. I dont know if this was reported before.

I have saw this bug on 3 different computers running W10. I did not change anything to the userChrome.css although I know the issue is coming from lane 286 since when I remove it the bug disappear. 

Here is the bug: when i decrease the size of the firefox window or look a video full screen, then when I go back to normal size the icons left of the adress bar dont come back. I am not sure this is clear thus I put some screenshots.
1-normal situation
2-reducing windows size 
3-increasing back windows size. Icons are lost. (same result if step 2 is looking a video full screen)

Also note that as far as i remember the problem appeared with version 2.8.? It was not present with version 2.7

I hope you will find a solution !

Best regards,
1/
![FxBug-1](https://user-images.githubusercontent.com/60655394/73750504-9543ca80-475d-11ea-9ccd-c9380d2a90ee.png)
2/
![FxBug-2](https://user-images.githubusercontent.com/60655394/73750502-94ab3400-475d-11ea-9ce1-12cc9e39c00a.png)
3/
![FxBug-3](https://user-images.githubusercontent.com/60655394/73750503-9543ca80-475d-11ea-8f0e-20b7a3ebebdb.png)

**Comment by Aris-t2** [comment]
Can you reproduce this using the latest files too? [v3.0+](https://github.com/Aris-t2/CustomCSSforFx/releases)

Major Firefox code changes required to change, fix and work around things to restore the titlebar the way it should be. 2.7 and 2.8 from September and October are way too outdated now.

**Comment by Ollives** [comment]
Yes I did reproduce it on 2 different computers with v3.0.
It was already the case earlier (work computer) and I double checked right now on another computer (home computer). 

Another thing that might be interesting to you is that when you are on step 3 with disappeared icons, if you click the Resize window icon in top right corner to maximize the window and then resize back to leave full screen, then the icons come back !

Also, as I said, if you dont allow the orange button, everything is working fine.

Hope this helps.

**Comment by Aris-t2** [comment]
To fix the issue with the appbutton I have added workarounds, that seem not to cover every possible case. For testing purposes increase the values set here and report with values "fix" the problem for you: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/appbutton/appbutton_in_titlebar.css#L11

**Comment by Ollives** [comment]
I could resolve the bug by modifying the  following line :

**--space_required_for_appbutton_fix2: 4px;**

Any value superior or equal to 32 fixed the problem.

**Comment by Aris-t2** [comment]
This temporal workaround should be used till Firefox 74 is out. 
Version 74 uses an own option without fixes or workaround and the glitch does not occur.

**Comment by Ollives** [comment]
Ok! Great!
Thanks a lot !
