### ISSUE TITLE
[macOS][web content] top level image option does not work properly

### ISSUE THREAD

**Issue by mcnesium** [Aris-t2/CustomCSSforFx#28]
Let me know if I got this wrong, but I don't see the background of an image or the surrounding area resetted as in [classic/css/webcontent](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/webcontent/toplevel_image_classic_v1.css).

I tried to uncomment [v1](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userContent.css#L54) and also [v2](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userContent.css#L55), restarted Firefox 57 after every change, but opening a raw image still looks like this:

![bildschirmfoto 2017-11-14 um 20 20 41](https://user-images.githubusercontent.com/476060/32799940-5bf2fb84-c979-11e7-98cb-220efac635c5.png)

Sidenote: I also uncommented [this line](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L19) to show that I have the files in the right place. Every other `@import` in both `userChrome.css` and `userContent.css` are commented

**Comment by mcnesium** [comment]
Ok looks like `userContent.css` is not being processed in general. I added 

    @-moz-document domain("en.wikipedia.org") {
        .mw-body {
            background-color: orange !important;
        }
    }

to the file but the background on en.wikipedia.org did not change either :(

**Comment by Aris-t2** [comment]
Maybe a macOS restriction on your end? Are the styles for about:addons and about:preferences working?

Try this url:
`http://forums.mozillazine.org/static/common/images/title2.gif`

Should be like this:

![01](https://user-images.githubusercontent.com/6013569/32808241-a78a6212-c992-11e7-9944-628c40fcc17c.png)
![02](https://user-images.githubusercontent.com/6013569/32808246-aa13fb60-c992-11e7-8cbf-dd0f4018cb62.png)
![03](https://user-images.githubusercontent.com/6013569/32808248-ab8924ca-c992-11e7-8631-90a4061e0d6c.png)

**Comment by Aris-t2** [comment]
Any chance you can retest this?

**Comment by mcnesium** [comment]
oh yes it does something to `about:preferences`

![bildschirmfoto 2017-11-15 um 19 04 59](https://user-images.githubusercontent.com/476060/32852374-f9746352-ca37-11e7-9704-b0b185de1d55.png)

but your image link also looks like this does not work:

![bildschirmfoto 2017-11-15 um 19 06 31](https://user-images.githubusercontent.com/476060/32852420-2161891c-ca38-11e7-9674-b13e42b73780.png)

**Comment by mcnesium** [comment]
oh yes it does something to `about:preferences`

![bildschirmfoto 2017-11-15 um 19 04 59](https://user-images.githubusercontent.com/476060/32852374-f9746352-ca37-11e7-9704-b0b185de1d55.png)

but your image link also looks like this does not work:

![bildschirmfoto 2017-11-15 um 19 06 31](https://user-images.githubusercontent.com/476060/32852420-2161891c-ca38-11e7-9674-b13e42b73780.png)

**Comment by Aris-t2** [comment]
Maybe there are some restrictions on accessing actual web content via custom CSS on OSX 10.11 or something within your browser profile is preventing this from happening.

Test a new browser profile (backup and rename your old one first).

**Comment by Aris-t2** [comment]
There is an issue with e10s (electrolysis, multi process), that causes this problem on Linux and macOS.
https://github.com/Aris-t2/CustomCSSforFx/issues/42

**Comment by Aris-t2** [comment]
Closed in favor of #42 (duplicate)
