### ISSUE TITLE
[Fx73] NewTab Button and AllTabs Button always visible is not working

### ISSUE THREAD

**Issue by Dozer-hh** [Aris-t2/CustomCSSforFx#281]
Describe the issue:
Yesterday I updated to Firefox 73.0 and since that, 
@import "./css/tabs/newtab_button_always_visible.css" 
and
@import "./css/tabs/alltabs_button_always_visible.css"
are not working properly.

If I open less than 18 tabs, the "NewTabs" and "AllTabs" Buttons are not visible.
If I open 18 or more tabs, the "NewTabs" and "AllTabs" Buttons become visible.
If I activate @import "./css/tabs/tabs_multiple_lines_fx71_force_newtab_button_visibility.css", the "NewTabs" and "AllTabs" Buttons are visible with every count of tabs, but I don't want to use multiple tab lines.

Tested with "CustomCSSforFx v3.0.0" and "CustomCSSforFx v3.0.1".

What should have happened instead?
"NewTabs" and "AllTabs" Buttons should be visible as they were before updating to Fx73.

Steps to reproduce the issue?
Activate  @import "./css/tabs/newtab_button_always_visible.css"  and  @import "./css/tabs/alltabs_button_always_visible.css".
Open less than 18 tabs = "NewTabs" and "AllTabs" Buttons are not visible.
Open 18+ tabs = "NewTabs" and "AllTabs" Buttons are visible.
Activated @import "./css/tabs/tabs_multiple_lines_fx71_force_newtab_button_visibility.css" = "NewTabs" and "AllTabs" Buttons are visible.

System information:
- OS & OS version:  WIN 10 Pro 64-Bit
- DPI / HiDPI resolution:  1920x1080 
- Firefox version:  73.0

**Comment by Aris-t2** [comment]
This will be fixed on next release.

**Comment by Dozer-hh** [comment]
Thank you very much, that was a quick solution!
