### ISSUE TITLE
[Linux][Fx74] Glitch when titlebar is hidden

### ISSUE THREAD

**Issue by GaVenga** [Aris-t2/CustomCSSforFx#282]
Firefox 74 and custom_css_for_fx_v3.0.3v2 issue (LINUX):
@import "./css/tabs/tabs_below_navigation_toolbar_fx72.css"; /**/
AND
Titlebar hidden results in truncating the min/max/close symbols.
Without tabs below navigation toolbar everything is o.K.
(On Windoofs 10 everything works with titlebar hidden...)

**Comment by GaVenga** [comment]
Firefox 74 and custom_css_for_fx_v3.0.3v2 issue (LINUX):
@import "./css/tabs/tabs_below_navigation_toolbar_fx72.css"; /**/
AND
Titlebar hidden results in truncating the min/max/close symbols.
Without tabs below navigation toolbar everything is o.K.

**Comment by Aris-t2** [comment]
Post a screenshot.

**Comment by Aris-t2** [comment]
I might have found what is causing this in Fx 74+ on Linux.

Test custom_css_for_fx_v3.0.3v3.zip and use the "pref" required for Fx74+.

**Comment by GaVenga** [comment]
>Test custom_css_for_fx_v3.0.3v3.zip and use the "pref" required for Fx74+.

Works perfect! Thank You so much.
BTW: I was not able to upload a screenshot in .png or .jpg with Firefox 74
what is the trick?
"Something went really wrong, and we can't process that file."

**Comment by GaVenga** [comment]
test on Windows 10 pro and Firefox 74.0:
File upload screenshot  xx.png
does not work

**Comment by Aris-t2** [comment]
I just drag&drop jpg/png files into my post below the text. You can also copy your screenshot to clipboard and paste it anywhere within your text using Ctrl+V.

**Comment by GaVenga** [comment]
Test on Manjaro (branch: testing) trying ctrl + V =
x-special/nautilus-clipboard
copy
file:///home/hartmut/Bilder/Bildschirmfotos/Bildschirmfoto%20vom%202020-03-12%2013-38-24.png

**Comment by Aris-t2** [comment]
That did not work. Image code within the post would look like this:

`![image](https://user-images.githubusercontent.com/1234567/id.png)`

**Comment by GaVenga** [comment]
And my fault was: Umatrix in both, windo and Linux
Problem solved - oh me stupid...
