### ISSUE TITLE
[Fx74][tabs below nav-bar] menubars add-on buttons vertically overlap with other toolbars 

### ISSUE THREAD

**Issue by kmssd** [Aris-t2/CustomCSSforFx#283]
1. When using tabs_below_navigation_toolbar, addon buttons in the menu bar move to the left side and in a vertical order. Also you can no longer move any symbols/buttons/space in the "Customize Firefox" tab.

2. The buttons should stay where placed and you should be able to use "Customize Firefox" properly.

3. Enable any tabs_below_navigation_toolbar in userchrome.

4. SCREENSHOTS
Before, notice 4 icons at the end of menu bar
![Before](https://user-images.githubusercontent.com/47156252/76584233-bb256300-64b1-11ea-958d-5a7c1af6f6bd.png)
Now after, the 4 icons moved to the left behind other buttons and bookmarks
![After](https://user-images.githubusercontent.com/47156252/76584242-bfea1700-64b1-11ea-83af-22dfb90c09c2.png)

5. Win10 (18363.719), Firefox 74 (64 bit).

**Comment by Aris-t2** [comment]
Are you using the latest files?
Does this happen on a new browser profile too?
Where does the gap above tabs come from?

**Comment by nykoo** [comment]
Use to had same problem with an old version of UserChrome.css in profile

With last version 3.0.3 no more problem, works perfectly on my FF 74.0 (64) with:

@import "./css/toolbars/bookmarks_toolbar_multiple_lines_fx74.css"; /**/ /* <--- EXPERIMENTAL */ /*Fx74+*/

**Comment by kmssd** [comment]
@Aris-t2 
Yes, I used all the new files and edited the userChrome. I didn't try a new profile because I thought I narrowed down to the culprit. The gap comes from a code I inserted at the end of userChrome.
`#TabsToolbar { height: 90px !important; }`
Which wasn't a problem because it worked with
`@import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css";`
Then I tried the tabs below for fx72 and it conflicts with the height code I put in.

@nykoo 
Using that just made my bookmarks toolbar mutli-lined, which isn't a problem with the code. It's me, I added too many links to my toolbar...

**Comment by Aris-t2** [comment]
Too many things change between Fx versions. You can not compare Fx 65 code to Fx 72+ code.

To increase a toolbar height use top or bottom paddings, they offer better results.

**Comment by kmssd** [comment]
@Aris-t2 
So it's best to use the highest version number when selecting a code. Noted.
Also I'll have to look into the padding, I haven't used it before.

**Comment by Aris-t2** [comment]
Works like this pseudo code:

```css
#toolbar-id {
  padding-top: 20px !important;
  padding-bottom: 20px !important;
}
```

**Comment by kmssd** [comment]
@Aris-t2 
Thanks, I'll do that later.
