### ISSUE TITLE
Request: as if in Fullscreen Tabs et all Autohide

### ISSUE THREAD

**Issue by gitut2007** [Aris-t2/CustomCSSforFx#285]
Hi, it seems this useful improvement is not yet here:
Navigator-toolbox-autohide.uc.js
"Toggles visibility of the whole navigation toolbox as if you were on fullscreen, so that it's only visible when you have the mouse over it, or when hovering the mouse to the top of the screen when it's hidden." from 
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Other%20features
it has the advantages of regular Fullscreen + the immediate access to the bottom OS Taskbar to eg click to other open app. No need to ever use regular Fullscreen anymore.
Thx.

**Comment by Aris-t2** [comment]
It might be useful, but this repository deals with CSS, not with JS scripts.

**Comment by gitut2007** [comment]
I was hoping that function to be added here just with CSS,  because i don't like to have to patch Firefox as in Izheil's method [besides that in this project there's a section with similar patches for using JS], i think it opens a security risk.

The idea is using it with multirows, below content, and eg 80 tabs, that would auto-hide like in F11 .

Here is a possible CSS way [not working for me right now, i'm just seen now MrOtherGuy's method]: 
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css  

Thx.
