### ISSUE TITLE
[Firefox 75] v3.0.5: ac_popup_with_two_lines_fx72.css doesn't seem to work

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#289]
1. Describe the issue
I was updating the CSS to version 3.0.5 for Firefox 75 and decided to try out `/css/locationbar/ac_popup_with_two_lines_fx72.css"; /**/ /* default popup + two lined results*/`

It displayed single line results instead which were as wide as the browser, which I don't think it was supposed to.

2. What should have happened instead?
Two line results.

3. Steps to reproduce the issue?
I guess include `/css/locationbar/ac_popup_with_two_lines_fx72.css"; /**/ /* default popup + two lined results*/`

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
Here it is with this included:
![image](https://user-images.githubusercontent.com/8035962/78723529-34697780-78f1-11ea-9d45-ad2f005e76ed.png)

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): Yes
- OS & OS version: Windows 10 Pro [Version 10.0.18363.752]
- OS theme (if not default): Basically the default one
- DPI / HiDPI resolution: 100% - normal
- Firefox version: 75
- Firefox theme / lw-theme:  Default, compact
- This projects 'settings' the issue occurs with: See above also, my complete setup is at https://www.markheadrick.com/firefox/firefox_config.php with this one commented out and loading `/css/locationbar/ac_popup_classic_with_two_lines_fx68.css"; ` instead.  Which I just noticed is pointing to the wrong version. Sigh.

**Comment by LawfulGremlin** [comment]
Are you sure you should not be using the megabar version with your configuration?
You should if you have "about:config > browser.urlbar.update1 > true", which I believe it is by default.

Line 774

`@import "./css/locationbar/ac_popup_megabar_title_and_url_two_lines.css"; /**/ /* for tile+url only, not for heuristic items like 'visit', 'search' etc. */`

**Comment by MarkRH** [comment]
I have `browser.urlbar.update1` set to **false** like it mentions.  I might try out this megabar stuff just to see what it looks like.

**Comment by Aris-t2** [comment]
Works for me even in Fx 77 Nightly.

```css
/*  - for Firefox 72+ ('about:config > browser.urlbar.update1 > false') *************************/
 @import "./css/locationbar/ac_popup_default_with_two_lines_fx72.css"; /**/ /* default popup + two lined results*/
```

The files **ac_popup_with_two_lines_fx72.css** does not exist.

**Comment by MarkRH** [comment]
I'm an idiot.  Bad C&P or something.  Closing..
