### ISSUE TITLE
Issue with appbutton vertical position in the Firefox 75.0 title in the maximized window

### ISSUE THREAD

**Issue by AndrewUshakov** [Aris-t2/CustomCSSforFx#291]
My 64-bit Firefox just updated to the version 75.0 (Windows 7.1 64 bit), I updated this tool to the latest version 3.0.7 and uncommented lines below (plus color_variables_aero and tabs_below_navigation_toolbar_fx74) :

@import "./css/appbutton/appbutton_in_titlebar_icon_only_fx74.css"; /**/
@import "./css/appbutton/appbutton_in_titlebar_icon_only_browser_logo.css"; /**/
@import "./css/appbutton/appbutton_in_titlebar_label_and_icon.css"; /**/
@import "./css/appbutton/appbutton_in_titlebar_transparent.css"; /**/

All is Ok, but if maximize Firefox window, appbutton is noticeably shifted down (and slightly to the left?):

![image](https://user-images.githubusercontent.com/7263403/79018706-23cd3180-7b7d-11ea-8db9-dca79e61a76f.png)

Thank you

Andrew

**Comment by Aris-t2** [comment]
Default v3.0.7 setup + Fx 75 + Win 7 AeroGlass

```css
@import "./css/appbutton/appbutton_in_titlebar_icon_only_fx74.css"; /**/
@import "./css/appbutton/appbutton_in_titlebar_icon_only_browser_logo.css"; /**/
@import "./css/appbutton/appbutton_in_titlebar_label_and_icon.css"; /**/
@import "./css/appbutton/appbutton_in_titlebar_transparent.css"; /**/
@import "./css/tabs/tabs_below_navigation_toolbar_fx74.css"; /**/
```


![image](https://user-images.githubusercontent.com/6013569/79021926-1dd75080-7b7d-11ea-80fd-501dbc4115bf.png)

![image](https://user-images.githubusercontent.com/6013569/79021941-262f8b80-7b7d-11ea-8b8e-feaba7217c79.png)

**Comment by AndrewUshakov** [comment]
Below is my title in non-maximized mode.

![image](https://user-images.githubusercontent.com/7263403/79022697-3a788600-7b87-11ea-924f-0bfa8bd1bbdd.png)

Do you see differences?  May be the reason is my decreased thickness of windows border (1) border padding (0) and the height of window title (21)? 

I just tried to increase back windows border to 5 from 1 (I do not remember default value)
![image](https://user-images.githubusercontent.com/7263403/79022452-9b538e80-7b86-11ea-9380-29252e92294b.png)

and error practically disappeared.

**Comment by AndrewUshakov** [comment]
Additionally, in your screnshots, the height of the appbutton is bigger, than height of buttons in the rigth end of the window title...

**Comment by AndrewUshakov** [comment]
If decrease 

#main-window[tabsintitlebar][sizemode="maximized"] #PanelUI-button {
  top: 2px !important;
}

from 8 to 2 px in the file classic\css\appbutton\appbutton_in_titlebar_icon_only_fx74.css problem disappears:

![image](https://user-images.githubusercontent.com/7263403/79025272-ef15a600-7b8d-11ea-96cb-6f59c472f910.png)

Hmm...

**Comment by Aris-t2** [comment]
If I change the value to 2px, the button moves offscreen:
![image](https://user-images.githubusercontent.com/6013569/79037999-2e67e500-7bd6-11ea-9fb7-c18d97b2cbf4.png)

This might happen to different configurations, OS font or DPI settings etc.
I can only offer code for the results I get.

**Comment by AndrewUshakov** [comment]
> This might happen to different configurations, OS font or DPI settings etc.
I can only offer code for the results I get.

Agree, that's why I asked about your values of title height, border width and border padding. My DPI is 96.

> You can add the code to my_userChrome.css file, so you don't have to modify the default files every time they get updated.

Thank you, good idea, but I prefer to keep my branch and periodically merge changes from the master into it. In this case I can control conflicts.

Thank you once more. Please close this issue.

**Comment by Aris-t2** [comment]
OK
