### ISSUE TITLE
What files or folders have been updated?

### ISSUE THREAD

**Issue by Roxie2401** [Aris-t2/CustomCSSforFx#293]
I am relatively new to "CustomCSSforFx" but I love what has been done and the capabilities!

I keep wondering how to determine what has changed with a new update and should I overwrite my existing folders and userChrome.css each time.

When I look at the "classic" for example on the web site I can see the "version" number, i.e., 3.0.7 and then I can go one level down and see which folders have a new version; same for files within the folder.

I have then been using NotePad++ to open my existing file and the new file and running a "compare" to see what lines may have changed and then I can set the same "import" lines.

Question:  Is there a way to "see" the file and folder "version" in Windows 10 the same as on the web site?  Basically, in File Explorer I can see "Name," "Date Modified or created,"Type," "Size" and Windows gives a lot of other attributes but I never see a "Version" like on the Web.  And "Date Modified or Created" appears to be when I downloaded and not the actual date the file was updated.

Is there something I am missing in my Windows Explorer setting to see the same "Version" information, like "tabs 3.0.6., locationbar 3.0.7, generalui 3.0.3?"

I want to stay current with all the changes and improvement but want a better way rather than just loading the current files and then "tweaking" the imports, etc.

Thanks so much for the great work!

**Comment by Aris-t2** [comment]
Please use the "general discussion" thread for questions like this: https://github.com/Aris-t2/CustomCSSforFx/issues/273

There is also a thread dealing with "updating": https://github.com/Aris-t2/CustomCSSforFx/issues/64

In most cases it is enough to switch the css folder with the new one as most changes occur there, but you might also have to look into userChrome.css or userContent.css files.

Changes can be monitored using the "commits" area of a Github project so you do not have to compare all files: https://github.com/Aris-t2/CustomCSSforFx/commits/master

--------------

### The most important feature to compare what has changed between releases can be found on release page itself. Hit the "compare" button on the left of the release an select the version you want to compare the release to. ([Additional info](https://github.com/Aris-t2/CustomCSSforFx/commits/master))

**Comment by Roxie2401** [comment]
Hi - I thought I was posting in the General Discussion thread.  Sorry if I was in the wrong place.

Is there no way to see the file version in Windows 10 like on the web site?

**Comment by Aris-t2** [comment]
The release page is the download page, your were at the right place. 
https://github.com/Aris-t2/CustomCSSforFx/releases

You can not see the file version on your Desktop. OSs do not offer such features, but even, if they did, files are just zipped by me. They do not get a version tag. userChrome.css is the only file I add a version number in the header of the file.

**Comment by Roxie2401** [comment]
WOW - thanks!  That "Compare" is great - never saw that page before.

Last question - on the "Compare" is there a way to open a compare without having the files expanded --- ">" instead of all file lists opened?  I understand the "Unified" and "Split" just wondered if there was a way to see the list without each file expanded.

Your work is really impressive!   Thanks so much.

**Comment by Aris-t2** [comment]
I don't thing Github offers an option not to expand files.
