### ISSUE TITLE
FX75 How to change the color of the TAB strip background

### ISSUE THREAD

**Issue by FFnewbie** [Aris-t2/CustomCSSforFx#294]
How to change the color of the area marked with red?
What is that area called?
![Firefox_TAB_STRIP](https://user-images.githubusercontent.com/64174646/80044675-8d4a2a00-8505-11ea-991d-01fb935640ee.png)

**Comment by Aris-t2** [comment]
Colors are set within CSS files for color varialbes:
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L109

"Tabs non on top" state color ist set here for example:
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/config/color_variables.css#L19

These kind of questions belong here:
https://github.com/Aris-t2/CustomCSSforFx/issues/273
