### ISSUE TITLE
[Add-on Manager] CSS to remove category transition effect

### ISSUE THREAD

**Issue by techboyg5** [Aris-t2/CustomCSSforFx#295]
You should update the CSS to remove the button transition on the HTML sidebar.
```
.category {
transition: none !important;
}
```

**Comment by Aris-t2** [comment]
Thanks, this will be added on next update.

**Comment by Aris-t2** [comment]
[==> v3.1.1](https://github.com/Aris-t2/CustomCSSforFx/releases)
