### ISSUE TITLE
Move @import "./css/aboutaddons/addonlists_private_browsing_notice_hidden.css"; into Firefox 60-67 category and comment by default

### ISSUE THREAD

**Issue by techboyg5** [Aris-t2/CustomCSSforFx#296]
The title says it all. The notice was only on Firefox 67. It was removed in 68.
Please move `@import "./css/aboutaddons/addonlists_private_browsing_notice_hidden.css";` into the Firefox 60-67 category and comment it by default, because it only affects a single Firefox version.

**Comment by Aris-t2** [comment]
OK, this will be done on next update.

**Comment by Aris-t2** [comment]
[==> v3.1.1](https://github.com/Aris-t2/CustomCSSforFx/releases)
