### ISSUE TITLE
[Win][Fx57][Compact Dark Theme] Context menu > Replace back, forward, reload etc. buttons with labels seem to be misaligned.

### ISSUE THREAD

**Issue by ImSpecial** [Aris-t2/CustomCSSforFx#30]
I noticed while using the latest 1.2.8 version;

@ import url(./css/generalui/context_bfrsb_labels_without_icons.css);

has a slight alignment problem.

https://i.imgur.com/tq7o6D9.png

**Comment by userOperaFF** [comment]
Compact Dark Theme? I see also in Personas theme:

![image](https://user-images.githubusercontent.com/33114475/32838170-5bb0b0fc-ca10-11e7-9db2-e2a0509981d7.png)

1.2.8 on Windows in Classic Theme

**Comment by Aris-t2** [comment]
@ImSpecial
What OS and OS theme are you using?
What is high resolution mode are you using? HiDPI value?

@userOperaFF
You are using Windows 7s Windows classic theme. This one might require special adjustments.

Since Mozilla removed the @media theme/classic theme detection, you have to add this to your userChrome.css manually.

**Comment by ImSpecial** [comment]
What OS and OS theme are you using? Windows 10 Falls Creators Update, not sure what OS theme, default?
What is high resolution mode are you using? HiDPI value? My monitors are 1920x1200, I use Windows 10 custom DPI Scaling at 125%.

**Comment by Aris-t2** [comment]
OK,

I will try to fix this on next update.

Looks like browser own **layout.css.devPixelsPerPx** setting is not reliable, as it offers different results when comparing e.g. 1.25 value with OSs DPI setting of 125%, but they actually should offer the same results.

**Comment by ImSpecial** [comment]
Looks pretty fixed to me. Good Job!

https://i.imgur.com/B28mB5t.png
