### ISSUE TITLE
[Fx77+] maxRichResults now hard-limits the results instead of scrolling

### ISSUE THREAD

**Issue by ThiefMaster** [Aris-t2/CustomCSSforFx#303]
1. Describe the issue
In Firefox 76 (at least with the megabar disabled via about:config) the `maxRichResults` setting only limited the number of results displayed without scrolling, but you had the extremely useful option to scroll through more results.

As of Firefox 77 which forces the megabar (which I disabled using the rules listed below) I now see ONLY `maxRichResults` results, with no way of scrolling to see more. Increasing the amount also makes the list much bigger, which is quite ugly, and even with something crazy high I don't get a scroll bar.

2. What should have happened instead?
The old behavior of being able to scroll either through additional items regardless of the `maxRichResults` setting (not sure if possible) or showing only 10 results and scrolling to see the rest of the `maxRichResults` items.

3. Steps to reproduce the issue?
Open the address bar (possibly type something) and realize that you cannot scroll to get more than `maxRichResults` results, and when increasing the number in that setting, see an much longer list that does not scroll.

4. Screenshots
Not really applicable here but there's one showing the lack of scrollbar.
![image](https://user-images.githubusercontent.com/179599/81349547-7dfbdc80-90c0-11ea-87fa-0aa6749896d1.png)

5. System information
- latest CustomCSSforFx files: yes
- OS & OS version: win10 1903
- OS theme (if not default): default/dark
- DPI / HiDPI resolution: 2560x1440
- Firefox version: 77.0b1
- Firefox theme / lw-theme: Dark
- This projects 'settings' the issue occurs with: 
  - `megabar_expanding_breakout_disabled`
  - `ac_popup_megabar_title_and_url_two_lines`
  - `ac_popup_megabar_compact_results`
  - `ac_popup_megabar_search_engines_hidden`

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/issues/273#issuecomment-624668990
