### ISSUE TITLE
Add support for Firefox Lockwise

### ISSUE THREAD

**Issue by techboyg5** [Aris-t2/CustomCSSforFx#304]
Firefox Lockwise (about:logins) should start having styling in CustomCSSforFx.

- [x] Add styling for Firefox Lockwise

**Comment by techboyg5** [comment]
Task list:
- [ ] Add styling for Firefox Send
- [ ] Add styling for Firefox Monitor
- [ ] Add styling for Firefox Lockwise

**Comment by Aris-t2** [comment]
While I see how custom CSS might improve `about:logins`, I'm not sure about styling Firefox external pages. Improvements there are of course welcome, but since they are technically not part for Firefox, they do not look like a part of `CustomCSSforFirefox` in my opinion.

**Comment by techboyg5** [comment]
> 
> 
> While I see how custom CSS might improve `about:logins`, I'm not sure about styling Firefox external pages. Improvements there are of course welcome, but since they are technically not part for Firefox, they do not look like a part of `CustomCSSforFirefox` in my opinion.

Yes, Lockwise is part of Firefox and is an about page and definitely should be styled using CustomCSSforFx.. But Send and Monitor are still part to some extent, as they are linked to in a Firefox menu.
![FirefoxServices](https://user-images.githubusercontent.com/63317676/81963625-f55ad000-95da-11ea-950d-db0f2d329b2f.png)

**Comment by Aris-t2** [comment]
So what kind of styling do you have in mind for those pages? I'm curious.

**Comment by techboyg5** [comment]
> So what kind of styling do you have in mind for those pages? I'm curious.

"Alternative Appearance" and "Alternative Appearance Aero", like in about:addons and about:preferences.

**Comment by Aris-t2** [comment]
![001](https://user-images.githubusercontent.com/6013569/82139789-ae631980-982a-11ea-9ef2-702aa127c554.jpg)
![002](https://user-images.githubusercontent.com/6013569/82139790-aefbb000-982a-11ea-9d3f-b9832328a2b4.jpg)

**Comment by techboyg5** [comment]
Those pictures look great! How about add the same thing for Send and Monitor?

**Comment by Aris-t2** [comment]
Send and Monitor have entirely different content and layout. Things can not be restyled to look like "alternative" addon pages of this project.

![send](https://user-images.githubusercontent.com/6013569/82154281-0ae72880-986d-11ea-8398-1195c646aeb8.jpg)
![monitor](https://user-images.githubusercontent.com/6013569/82154282-0b7fbf00-986d-11ea-9c71-78c75943fe73.jpg)

**Comment by techboyg5** [comment]
> 
> 
> Send and Monitor have entirely different content and layout. Things can not be restyled to look like "alternative" addon pages of this project.
> 
> ![send](https://user-images.githubusercontent.com/6013569/82154281-0ae72880-986d-11ea-8398-1195c646aeb8.jpg)
> ![monitor](https://user-images.githubusercontent.com/6013569/82154282-0b7fbf00-986d-11ea-9c71-78c75943fe73.jpg)

OK, then if Send and Monitor would not be styled, then Lockwise should be styled as shown in the screenshots.

**Comment by Aris-t2** [comment]
[The above screenshot](https://github.com/Aris-t2/CustomCSSforFx/issues/304#issuecomment-629762963) already show the results of how 'Firefox Lockwise' options will look on next update.

**Comment by techboyg5** [comment]
> [The above screenshot](https://github.com/Aris-t2/CustomCSSforFx/issues/304#issuecomment-629762963) already show the results of how 'Firefox Lockwise' options will look on next update.

Thanks! All done!

**Comment by techboyg5** [comment]
Thanks, it has finally shipped!
