### ISSUE TITLE
Request: as if in Fullscreen, Autohide Toolbox

### ISSUE THREAD

**Issue by gitut2007** [Aris-t2/CustomCSSforFx#305]
[This is the same as https://github.com/Aris-t2/CustomCSSforFx/issues/285 (' the advantages of regular Fullscreen + the immediate access to the bottom OS Taskbar to eg click to other open app. No need to ever use regular Fullscreen anymore.')  which i made a new comment (it works with just CSS) yesterday, but since it's 'closed, idk if you would read it]:

I was hoping that function to be added here just with CSS, because i don't like to have to patch Firefox as in Izheil's method [besides that in this project there's a section with similar patches for using JS], i think it opens a security risk.

The idea is using it with multirows, below content, and eg 80 tabs, that would auto-hide like in F11.
 
Here is a possible CSS way [it's working for me, although it's difficult to 'hit the box' to make the bars appear, i have to hit top and then move a little down very slowly.]:
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css

So why not just 'use that'? well if more projects take the idea, even if at first the same, the CSS code could go different maybe better ways, and hopefully someday Mozilla and other browsers ppl would find it and realize that this as an option is better than F11 and makes it obsolete.

Thx.'

**Comment by Aris-t2** [comment]
Sorry, I can not add something like this to the project. I checked the code and it caused issues and glitches in various situation in my test scenarios and I only test one OS yet.
