### ISSUE TITLE
Expose options from tab context menus?

### ISSUE THREAD

**Issue by vaporwave9** [Aris-t2/CustomCSSforFx#306]
1. Describe the issue

![grafik](https://user-images.githubusercontent.com/64961250/83633254-ee532c00-a5a0-11ea-9ed3-5a085c373864.png)

Firefox started to needlessly cascade context menus for tabs.

2. What should have happened instead?

Expose the "close tabs to right" and "close all tabs" options as before. Power users suffer from long mouse paths and needless cascading.

3. Steps to reproduce the issue?

See image, these changes were introduced by Mozilla

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![grafik](https://user-images.githubusercontent.com/64961250/83633254-ee532c00-a5a0-11ea-9ed3-5a085c373864.png)

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']):
yes latest

- OS & OS version: 
win 10 pro build 2004
- OS theme (if not default): 
default

- DPI / HiDPI resolution: 
1920x1200

- Firefox version: 
78 developer

- Firefox theme / lw-theme: 
dark compact

- This projects 'settings' the issue occurs with: 
it's a UI issue introduced by Mozilla

Edit:

Should this require too much work, I can still use this addon and keybinds:
https://addons.mozilla.org/en-US/firefox/addon/close-tabs-shortcuts/?src=search

Really, unless you can find an easy solution I will install another hundredth addon to fix Mozilla's mistakes.

**Comment by Aris-t2** [comment]
CSS can not move menu items out of or into sub menus, sorry.

**Comment by vaporwave9** [comment]
I understand, but thanks for looking into it. I really enjoy bottom tabs and your megabar fixes though.
