### ISSUE TITLE
Multrow bookmarks are stacked vertically at the left with all else pushed off bottom of screen

### ISSUE THREAD

**Issue by jamesd1** [Aris-t2/CustomCSSforFx#310]
I applied the first css for multrow bookmarks on this page https://www.userchrome.org/what-is-userchrome-css.html

Result was that bookmaks were not horizontal as usual across top but all  stacked vertically at the far left with all else pushed off bottom of screen.   I tried another css and go the same result.

**Comment by Aris-t2** [comment]
There is no support for CSS from other projects.

Use this projects full package and enable bookmarks_toolbar_multiple_lines_fx74.css: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L644

[Support and questions regarding multiple bookmark lines can be found in this thread.](https://github.com/Aris-t2/CustomCSSforFx/issues/99)

**Comment by jamesd1** [comment]
thanks!
