### ISSUE TITLE
Searchbar dropdown is completely invisible

### ISSUE THREAD

**Issue by EveryNameIveTypedIsTakenButThisOne** [Aris-t2/CustomCSSforFx#316]
The title might be badly-worded now since I've edited this after discovering the cause of the issue (assuming it is one). The background for the search dropdown was missing leaving just text, and a few icons floating over the webpage like an eyesore as shown below.

![image](https://user-images.githubusercontent.com/69790059/90375791-6e871a80-e043-11ea-93a7-c83d228b54fa.png)

The cause of that was the setting "import "./css/locationbar/locationbar_reduce_height.css""

I'm using Firefox version 79 on Windows 10, since it said to list that information. This is my first time both using this customization, and reporting an issue, so let me know if I need to specify anything else.

**Comment by glennpc** [comment]
"./css/locationbar/locationbar_reduce_height.css" 
That location bar setting above stopped working in Firefox 77. Use the megabar setting below for Firefox 79.
"./css/locationbar/ac_popup_megabar_compact_results.css"

**Comment by Aris-t2** [comment]
@EveryNameIveTypedIsTakenButThisOne 

Like mentioned inside userChrome.css and by glennpc, some features are restricted to certain Firefox versions.
`locationbar_reduce_height.css` is one of them.


```css
/* [!] Location bar settings below will stop working in Firefox 77+. Use megabar settings! [!] **/
/************************************************************************************************/
/* LOCATION BAR - settings for 'legacy location bar / urlbar popup' (not megabar popup) *********/
/* [!] Firefox settings for Firefox 60-76 only **************************************************/
/* [!] about:config > browser.urlbar.update1 > false (present in Firefox 72-76) *****************/
/************************************************************************************************/

/* general & old location bar tweaks ************************************************************/
/* @import "./css/locationbar/locationbar_adjustments.css"; /**/
/* @import "./css/locationbar/background_color_dark.css"; /**/
/* @import "./css/locationbar/locationbar_border_roundness.css"; /**/
@import "./css/locationbar/locationbar_reduce_height.css"; /**/

/* autocomplete / history dropmarker ************************************************************/
/* @import "./css/locationbar/dropmarker_at_the_end.css"; /**/
/* @import "./css/locationbar/dropmarker_visible.css"; /**/ /* Windows only */
```
