### ISSUE TITLE
v81 broken multilining tabs

### ISSUE THREAD

**Issue by myname1614** [Aris-t2/CustomCSSforFx#317]
my old settings:

@import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css"; /**/
@import "./css/tabs/tabs_multiple_lines_fx71.css"; /**/  /* Fx 71+ */

now:

![image](https://user-images.githubusercontent.com/34938365/91435333-d6710880-e86e-11ea-897d-321c7eb4a505.png)

**Comment by glennpc** [comment]
I'm having the same issues with FF 81 and now 82 as reported here: 
https://github.com/Aris-t2/CustomCSSforFx/issues/39#issuecomment-665778451 . 
It works fine on the current version 80.

**Comment by Aris-t2** [comment]
Continue here: https://github.com/Aris-t2/CustomCSSforFx/issues/39
