### ISSUE TITLE
[Win][Fx80] Tabs toolbar background color

### ISSUE THREAD

**Issue by kalkydri** [Aris-t2/CustomCSSforFx#319]
**1. Describe the issue**
I am trying to change the background color of the tabs toolbar. In /config/color_variables.css, I changed the value of "--tabs_toolbar_color_tabs_not_on_top" to "linear-gradient(#b6b3ac,#ccc8c0)" but the tabs toolbar stayed the same color.

**2. What should have happened instead?**
I expected the tabs toolbar to change from a solid background of color #d4d0c8 to a gradient. The area I expected to change is highlighted below:
![customtabs80 ](https://user-images.githubusercontent.com/69022470/92334584-14cbac00-f055-11ea-8efd-3464b8798f92.png)

**3. Steps to reproduce the issue?**
In userChrome.css, enable /config/color_variables.css, then change the values of "--tabs_toolbar_color_tabs_not_on_top" in color_variables.css.

**4. SCREENSHOTS with/without this projects files**
This is how Firefox looks with the changes I made to /config/color_variables.css:
![colorvariables80](https://user-images.githubusercontent.com/69022470/92334541-aab30700-f054-11ea-950b-8707cacc177e.png)

And here is Firefox on my system without CustomCSSforFx:
![default80](https://user-images.githubusercontent.com/69022470/92334993-56aa2180-f058-11ea-8114-c3261b6e20ee.png)

**5. System information**
- latest CustomCSSforFx files: yes
- OS & OS version: Windows 7
- OS theme (if not default): Windows Classic
- DPI / HiDPI resolution: 1920 x 1080
- Firefox version: 80.0.1 (running with Firefox Portable 2.2.1.0)
- Firefox theme / lw-theme: Default
- This projects 'settings' the issue occurs with:

These options are enabled in userChrome.css:
/config/general_variables.css
/config/color_variables.css
/css/buttons/icons_custom_icons_fx2.css
/css/buttons/buttons_on_bookmarks_toolbar_old_size_and_appearance.css
/css/buttons/bookmarks_menu_button_localized_label_on_bookmarks_toolbar.css
/css/buttons/buttons_on_tabs_toolbar_classic_appearance.css
/css/buttons/whatnew_button_always_hidden.css
/css/appbutton/appbutton_hidden.css
/css/appbutton/appbutton_in_titlebar_fx74.css
/css/appbutton/appbutton_in_titlebar_autocolor.css
/css/tabs/classic_squared_tabs.css
/css/tabs/tabs_below_navigation_toolbar_fx74.css
/css/tabs/missing_tab_favicon_restored_default.css
/css/tabs/tab_throbber_grey_classic.css
/css/tabs/tab_close_always_visible.css
/css/tabs/tab_icon_colors.css
/css/generalui/private_mode_indicator_hidden.css
/css/generalui/bookmark_icons_colorized.css
/css/generalui/statusbar_color.css
/css/generalui/context_bfrsb_labels_without_icons.css
/css/generalui/searchbar_glassplus_indicator_hidden.css
/css/toolbars/toolbars_old_padding.css
/css/toolbars/tabs_toolbar_adjustments.css
/css/toolbars/menubar_color.css
/css/toolbars/bookmarks_toolbar_old_height.css
/css/toolbars/general_toolbar_colors.css
/css/locationbar/identitybox_colors.css
/css/locationbar/icons_colorized.css
/css/locationbar/pageaction_separator_in_location_bar_hidden.css
/css/locationbar/ac_popup_result_font_size.css
/css/locationbar/megabar_expanding_breakout_disabled.css
/css/locationbar/ac_popup_megabar_title_and_url_50percent_width.css
/css/locationbar/ac_popup_megabar_compact_results.css

Thank you for any help you can provide, and for your continued dedication to Firefox customization!

**Comment by Aris-t2** [comment]
I enabled `tabs_below_navigation_toolbar_fx74.css` and changed `--tabs_toolbar_color_tabs_not_on_top: linear-gradient(red,blue) !important;` inside `color_variables.css`.

![image](https://user-images.githubusercontent.com/6013569/92930726-bf234500-f442-11ea-8420-2d95597576fb.png)

**Comment by kalkydri** [comment]
Thank you for checking this. I tried changing all the userChrome.css settings back to the default again, then enabled tabs_below_navigation_toolbar_fx74.css, and edited color_variables.css the same as you did, but unfortunately it still doesn't seem to work for me.
![color_variables80b](https://user-images.githubusercontent.com/69022470/92986544-58714c00-f481-11ea-8ac6-b2b3a13efc92.png)
Is it possible that it has something to do with running Firefox through the PortableApps.com program?

**Comment by Aris-t2** [comment]
Test with a new setup of the latest release. I have no idea why this is not working on your system.
