### ISSUE TITLE
bookmarks toolbar problem in firefox 78.3.1

### ISSUE THREAD

**Issue by hemigary** [Aris-t2/CustomCSSforFx#320]
Add all information required in 1-5 and delete this line and everything above it before submitting.

1. Describe the issue

2. What should have happened instead?

3. Steps to reproduce the issue?

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): yes
- OS & OS version:  windows 10
- OS theme (if not default):  default
- DPI / HiDPI resolution: resolution unknown
- Firefox version: 78.3.1esr
- Firefox theme / lw-theme: ?
- This projects 'settings' the issue occurs with: 

Ihave a bookmarks toolbar with all the bookmarks arranged vertically on the left side of the page , instead of horizontally and then vertically, I tried a suggested css file but it did not work, plus it put the open tabs toolbar above the bookmarks toolbar( totally wrong place , they should be below. I would like to find a css file that keeps the tabs on the bottom and a working bookmarks toolbar. Can someone help please

**Comment by hemigary** [comment]
I have a custom css file for firefox
windows 10
default
resolution unknown
firefox version 78.3.1esr
theme ?
Ihave a bookmarks toolbar with all the bookmarks arranged vertically on the left side of the page , instead of horizontally and then vertically, I tried a suggested css file but it did not work, plus it put the open tabs toolbar above the bookmarks toolbar( totally wrong place , they should be below. I would like to find a css file that keeps the tabs on the bottom and a working bookmarks toolbar. Can someone help please

**Comment by Aris-t2** [comment]
Please explain what you are trying to achieve with this projects files.

There is no "vertical" bookmarks toolbar within this projects files.

To place tabs toolbar below other top toolbars you have to use the correct file in userChrome.css:

```css
/* - TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS / TABS NOT ON TOP *****************************/
/* [!] Note: do not use OS titlebar with 'tabs not on top' code on macOS ************************/
/* [!] Note: only ~fx65_v2 works with multi-tab lines option on Fx65+. **************************/
/* - Fx 60-64 ***********************************************************************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/ /* <-- Windows/Linux */
/* @import "./css/tabs/tabs_below_navigation_toolbar_macOS.css"; /**/ /* <-- macOS */
/* - Fx 65-67 - Windows/Linux *******************************************************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65.css"; /**/
/* - Fx 65-73 - macOS ***************************************************************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_macOS.css"; /**/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_macOS_default_tabs.css"; /**/
/* - Fx 65+ v2 - mainly for multi-lined tabs (Glitches with inactive menubar!) ******************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css"; /**/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2_force_hidden_menubar.css"; /**/ /* no menubar when OS titlebar is active */
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2_macOS.css"; /**/
/* - Fx 68-71 Windows/Linux (use the Fx 65+ versions for macOS) *********************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx68.css"; /**/
/* - Fx 72-73 Windows/Linux (use the Fx 65+ versions for macOS) *********************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx72.css"; /**/
/* - Fx 74+ Windows/Linux ***********************************************************************/
/* [!] might require overriding url bars 'selection color' --> see corresponding area ***********/ 
 @import "./css/tabs/tabs_below_navigation_toolbar_fx74.css"; /**/
/* - Fx 74+ - macOS *****************************************************************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx74_macOS.css"; /**/
/* @import "./css/tabs/tabs_below_navigation_toolbar_fx74_macOS_default_tabs.css"; /**/
```

**Comment by hemigary** [comment]
[css.txt](https://github.com/Aris-t2/CustomCSSforFx/files/5368876/css.txt)
okay, here is the file I am trying to use, but it puts all of my toolbar bookmarks in a vertical column on the left, instead of in horizontal rows. But with this css at least my tabs are on the bottom. Any suggestions please?

**Comment by hemigary** [comment]
this site is not working for me, can anybody point me to a custom css file for firefox 78.3.1 that both puts the open tabs on the bottom and restores the scrolling bookmarks toolbar

**Comment by Aris-t2** [comment]
Everything you need to know how to setup this projects files can be found on [main page](https://github.com/Aris-t2/CustomCSSforFx).

Enabling and disabling settings is what you need to do after adding [this projects full package](https://github.com/Aris-t2/CustomCSSforFx/releases) to your chrome folder.

To put tabs below navigation toolbar enable this: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L360

To use multiple bookmark toolbar line,  enable this
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L646

**Comment by Aris-t2** [comment]
Anything new regarding the mentioned issue?
