### ISSUE TITLE
Delete tab and have remaining tabs slide left

### ISSUE THREAD

**Issue by rebop** [Aris-t2/CustomCSSforFx#321]
Forgive me, I am using an older version of CSS. Have not had time to start again and check all possibilities and permutations. But I just discovered something today that surprised me. I know its in CSS as if I rename chrome the problem goes away. Just cannot pin it down and hope its so easy I'll be forgiven.

If I have 6 tabs open and close the 4th, then 5th and 6th have always slid left to fill the gap. Now they do not and it leaves an empty gap.

Can you point me?

Thanks.

**Comment by Aris-t2** [comment]
Seems to be related to (max)  tab width settings.

**Comment by rebop** [comment]
I shall look there. Thanks. Will posyt if it solves - or not :) Appreciate the reply Aris.

**Comment by rebop** [comment]
Darn you are good!!!

I had to remove the following. Is there a way to limit the max width without braking the "slide left"?

/*.tabbrowser-tab:not([pinned]) {
max-width: 125px !important;
min-width: 100px !important;
}*/

Thanks again!

**Comment by rebop** [comment]
Got it. Fixed in about:config. Thanks!
