### ISSUE TITLE
Multi-Column Bookmarks

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#322]
is it possible to integrate this function (working) in **CustomCSSforFx**?

/* Multi-Column Bookmarks for Firefox 70-73 -- menu heights broken */
:root {
  --bmkcolumncount: 6;
  --bmkcolumnwidth: 320px;
  --foldercolumncount: 5;
}

/* Bookmarks menu/toolbar -- also modifies History menu */
hbox[part="innerbox"] > .popup-internal-box > .arrowscrollbox-scrollbox, 
/* optional Bookmarks Menu toolbar button */
.panel-arrowcontainer > .panel-arrowcontent > .popup-internal-box > 
.arrowscrollbox-scrollbox,
/* Firefox 71 */
.scrollbutton-up.menupopup-scrollbutton + scrollbox, 
.scrollbutton-up.menupopup-scrollbutton + spacer + scrollbox {
  display: block !important;
/*  column-count: var(--bmkcolumncount); */
  column-width: var(--bmkcolumnwidth);
  column-rule: 1px solid #ccc;
  padding-top: 4px;
  padding-bottom: 4px;
}

/* Overall minimum width: accommodate full column count */
#bookmarksMenu menupopup, 
#BMB_bookmarksPopup,
.panel-arrowcontainer > .panel-arrowcontent > .popup-internal-box > 
.arrowscrollbox-scrollbox {
  min-width: calc(var(--bmkcolumncount) * (var(--bmkcolumnwidth) + 18px)) 
!important;
}
/* Subfolder minimum width: accommodate folder column count */
#bookmarksMenuPopup .bookmark-item[container="true"] 
menupopup[placespopup="true"], 
#BMB_bookmarksPopup menupopup[placespopup="true"],
#PlacesToolbarItems .bookmark-item[container="true"] 
menupopup[placespopup="true"] {
  min-width: calc(var(--foldercolumncount) * (var(--bmkcolumnwidth) + 
18px)) !important;
/*  column-count: var(--foldercolumncount); */
}

/* Force item widths so each has its own line */
#bookmarksMenuPopup menu, #bookmarksMenuPopup menuitem, #bookmarksMenuPopup 
menuseparator, 
#PlacesToolbarItems .bookmark-item > menupopup[placespopup="true"] menu, 
#PlacesToolbarItems .bookmark-item > menupopup[placespopup="true"] 
menuitem, 
#PlacesToolbarItems .bookmark-item > menupopup[placespopup="true"] 
menuseparator,
#PlacesChevronPopup .bookmark-item,
#PlacesChevronPopup .bookmark-item > menupopup[placespopup="true"] menu, 
#PlacesChevronPopup .bookmark-item > menupopup[placespopup="true"] 
menuitem, 
#PlacesToolbarItems .bookmark-item > menupopup[placespopup="true"] 
menuseparator,
#BMB_bookmarksPopup menu, #BMB_bookmarksPopup menuitem, #BMB_bookmarksPopup 
menuseparator {
  width: var(--bmkcolumnwidth) !important;
}

/* Clean up item and separator spacing */
#BMB_bookmarksPopup menu, #BMB_bookmarksPopup menuitem, #BMB_bookmarksPopup 
menuseparator {
  padding: 0 4px 0 12px !important;
  margin: 0 !important;
}
#PlacesToolbarItems .bookmark-item > menupopup[placespopup="true"] 
menuseparator {
  margin: 0 !important;
  padding: 0 !important;
}
.subviewbutton.panel-subview-footer {
  min-height: 22px !important;
  border-top: none !important;
}
/* Pack more in vertically */
#BMB_bookmarksPopup menu, #BMB_bookmarksPopup menuitem {
  min-height: 1.5em !important;
}
/* Remove scrolling triangles from classic menu */
#bookmarksMenuPopup .autorepeatbutton-up, #bookmarksMenuPopup 
.arrowscrollbox-overflow-start-indicator, 
#bookmarksMenuPopup .arrowscrollbox-overflow-end-indicator, 
#bookmarksMenuPopup .autorepeatbutton-down {
  display: none !important;
}

**Comment by Aris-t2** [comment]
`bookmarks_toolbar_multiple_lines_fx74.css` still works fine for me even on Fx 84.
The above code has no effect in my tests.

**Comment by gabri25ele** [comment]
not multiple lines in bookmarks bar.
multiple lines (two) in the drop-down menu

**Comment by Aris-t2** [comment]
Alright, tested again and got this result:

![image](https://user-images.githubusercontent.com/6013569/97745853-c92ffe80-1ae9-11eb-9bca-cde99d509c61.png)

**Comment by gabri25ele** [comment]
it could be a thing like this

https://forum.vivaldi.net/assets/uploads/files/1498401495625-1.png

discussion here for example (if help)
http://forums.mozillazine.org/viewtopic.php?f=38&t=2964437
https://gist.github.com/sogoo/4644583#file-gistfile1-css

**Comment by Aris-t2** [comment]
I'm sorry, this script won't be added to CustomCSSforFx project. Its way to unstable, at least in my tests.
