### ISSUE TITLE
Tabs at the bottom extra space and close buttons still appearing

### ISSUE THREAD

**Issue by mimteatr** [Aris-t2/CustomCSSforFx#324]
Hello,

I've searched on the "Tabs below" help page but since I'm using FF 82 everything there is pretty old so I'm writing this hoping you can help me, Thanks 🙏
![TabsAtBottomOnStatusBar](https://user-images.githubusercontent.com/36078037/97201424-1abf4d00-17bb-11eb-907b-17a50ccb234d.png)
!

1. Describe the issue
I've configured everything I wanted according to your "custom_css_for_fx_v3.1.7" even though most are recommended for lower versions...
a) Tabs on the Bottom - they disappear if I disable Statusbar
b) So , not disabling the statusbar show the tabs but there's a extra space above them and below the window content (see screenshot attached).
c) Close buttons didn't disappear,so I couldn't be able to show then when hovering. (can't reproduce it on a screenshot...)

2. What should have happened instead?
The reverse of what I've stated above...

3. Steps to reproduce the issue?
Just opening the browser.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
"TabsAtBottomOnStatusBar.png" attached.

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): custom_css_for_fx_v3.1.7
- OS & OS version: Windows 10 Home 1909 build 18636.1139
- OS theme (if not default): Microsoft Personal Art Premium
- DPI / HiDPI resolution: 1920 X 1080
- Firefox version: 82
- Firefox theme / lw-theme: Default
- This projects 'settings' the issue occurs with:  "tabs_below_main_content_fx74.css"; "tabs_below_main_content_fx74.css";

**Comment by Aris-t2** [comment]
Not sure how to reproduce your issue. Tabs look like this for me:
![image](https://user-images.githubusercontent.com/6013569/97742465-9d5e4a00-1ae4-11eb-9442-1cd4df54211e.png)

Keep in mind this feature is not compatible with the add-on/status bar offered by this CustomCSSforFx.
This is mentioned inside `userChrome.css`.
`/* [!] not compatible to 'toolbars - add-on bar (simulated add-on bar)' option ******************/`

**Comment by Aris-t2** [comment]
@mimteatr 

Are there any new test results?

**Comment by mimteatr** [comment]
Hello Aris,

Sorry for the late reply!

I couldn't try again, had to refresh my Windows and FF as well.

I'll let you know of any updates.

Thanks!

Maurice J. Rosenthal
+972-52-4533701
