### ISSUE TITLE
Waterfox G3 - tabs at the bottom desired UPDATED NOW WITH 3.17

### ISSUE THREAD

**Issue by rebop** [Aris-t2/CustomCSSforFx#327]
1. Describe the issue

Hello Aris,

I just  updated Waterfox Current to Waterfox G3. Been putting it off :) I believe current might have been based on Quantum 68? And now G3 on Gecko 78. I am using an old version of Custom CSS  - 2.63 but it works perfectly for me in both Waterfox Classic and Current!

Surprisingly, everything works and looks "right" in G3 as well except one thing! The tabs are below the menu bar rather than bottom of the screen.
I belive this is the line that I use in Classic and Current to get tabs at the bottom of the window:

	        @import "./css/tabs/tabs_below_main_content_fx68.css"; /**/ 
	              /* <-- tabs on bottom - Fx68+ - Windows/Linux */ /* <--- EXPERIMENTAL */

Is there an easy way to make that change here in a 78 based without making other changes just yet? 
Then when I have free time will try latest version and see what that might do for me. But honestly, with that change both Classic and Current G3 will have the look I like and I may have no reason to change.

PPS. I did try adding css/tabs/tabs_below_main_content_fx72.css and css/tabs/tabs_below_main_content_fx74.css from 3.17 and changing my import to 74 with no luck. I realize what i am using is not the current version but hoping it is trivial to point me in the right directions.

Thanks!

~Bob

**Comment by rebop** [comment]
Got it.

I am having issues getting proper tab height and widths, but I'll keep trying for that. At least now where I would like them in the browser :)

**Comment by rebop** [comment]
OK, bit the bullet and spent likely 8 or more hours updating from 2.63 to 3.17. Very tedious checking all against what I had trying to recreate it and at the same time uncovering what is new. Did pretty good but a few things not quite right and a small group of questions.

1. Note the toolbars. The megabar now is missing the globe and the dropmarker. I have the following in usercss:

@import "./css/locationbar/dropmarker_at_the_end.css"; /**/
@import "./css/locationbar/dropmarker_visible.css"; /**/
@import "./css/locationbar/identitybox_replace_i_icon_with_globe.css"; /**/

Enabled or disabled, those do not seem to make any difference.

OLD
![G3 Old](https://user-images.githubusercontent.com/13785042/102968032-042a2f00-44a8-11eb-9848-709c4406e348.JPG)

NEW

![G3 NEW](https://user-images.githubusercontent.com/13785042/102968097-1b691c80-44a8-11eb-8d8b-2f5257a2dfb0.JPG)

Forget the blue arrow. I was going to change the height of the mega and search bars but it creates issues. And while looking at globe side, would be nice to compact those three icons as in the OLD image.

2. Also, where are settings for the download icon as shown in NEW?

3. Where is the setting to change the background bar color with tabs at the bottom?

Tabs

![Tabs](https://user-images.githubusercontent.com/13785042/102968144-3176dd00-44a8-11eb-9fd3-f0b1a50451b2.JPG)

4. Can I change the color on the left side of the addons page?

Addons

![addons color](https://user-images.githubusercontent.com/13785042/102968180-418ebc80-44a8-11eb-826f-d8a64916aab9.JPG)

5. And last, is it possible to set about:config to open showing all and saving a click?


Thanks so much!

**Comment by rebop** [comment]
Found the answer to #3 above for tab bar background.

Down to 4 questions :)

**Comment by Aris-t2** [comment]
About 1.
Those three settings are for old Gecko versions only. There is no i-icon to replace anymore and the dropmarker is gone for good.

About 2.
There are settings for custom icons, but no separate settings for downloads button:
Search for "icon appearance" inside `userChrome.css`

About 3. - OK, not needed anymore ;-)

About 4 .

```css
@-moz-document url-prefix(chrome://mozapps/content/extensions/extensions.xul), url-prefix(about:addons),url-prefix(chrome://mozapps/content/extensions/aboutaddons.html) {

#sidebar,
#sidebar #categories {
  background: red !important;
}

}
```

About 5,
There is no way to save the click using CSS code, but you can bookmarks this url `chrome://global/content/config.xhtml` and still use the older version of `about:config`.

**Comment by rebop** [comment]
Thanks.

Pity on #1, but OK. I'll assume I can delete these:

@import "./css/locationbar/dropmarker_at_the_end.css"; //
@import "./css/locationbar/dropmarker_visible.css"; //
@import "./css/locationbar/identitybox_replace_i_icon_with_globe.css"; /**/

Looking forward to testing 4. Might be other places I would like that and will ask if so.

Will check about:config.

Thanks so much. You make new browsers usable and its appreciated!

**Comment by rebop** [comment]
Great stuff. All good except this one:

@-moz-document url-prefix(chrome://mozapps/content/extensions/extensions.xul), url-prefix(about:addons),url-prefix(chrome://mozapps/content/extensions/aboutaddons.html) {

#sidebar,
#sidebar #categories {
  background: red !important;
}

}

I tired in userchrome and my_userchrome with no luck. I do have a bunch of other sidebar things in my_userchrome.

Can you tell me where and how to place that?

Thanks again.

**Comment by rebop** [comment]
Got it. Boy, that was tricky :-P  But made all the difference/ Fw things I might prefer differently, but pretty good as is right now.

~Bob

**Comment by Aris-t2** [comment]
Sorry, I forgot to mention, that the code belonged into `userContent.css/my_userContent.css`.

**Comment by rebop** [comment]
No worries. I actually put it in: addons_manager_alternative_appearance_v2.css. Just moved it to UserContent.

While I am there, can I add a little space above and beyond addons - maybe even a separtor here.?

![addons](https://user-images.githubusercontent.com/13785042/103100435-6299ff00-45c7-11eb-91ee-acc7417b429c.JPG)

Thanks again.

**Comment by rebop** [comment]
And another small thing :)
I am using config/custom_tab_text_settings.css. I like all tabs EXCEPT the selected tab to be italic. Nothing I do will do that. They are either all italic or none.

Would be nice if there is a setting.

Thanks.

**Comment by Aris-t2** [comment]
The file `custom_tab_text_settings.css` was meant to show what is possible. ;-)

As long the browser sets the "[pending]" tag, `.tabbrowser-tab[pending]` will affect the tabs using that tag.

In my tests only the tabs not yet visited show italic tab text. After a browser restart with multiple opened tabs all but the selected one show italic text. It like this since the feature was introduced.

Not sure, if Waterfox works differently there.

**Comment by rebop** [comment]
Thanks. So unconfuse me please :) I should **not** be importing custom_tab_text_settings.css?  I have set the tab with focus to red text there and it does work. If not there, where should that be set?

And where is or should I put tabbrowser-tab[pending]?

Thanks.

**Comment by rebop** [comment]
OK, got the tabs text working as expected. Keep learning, I do.

But for that last for now, can I get some air around thew Extensions list items above? Or separators?

**Comment by Aris-t2** [comment]
Importing customized tab text settings is of course fine ;-)

----

Use this code to create some space around extension list items:

```css
.card.addon {
  margin: 20px 10px !important;
}
```

**Comment by rebop** [comment]
Thanks, but tried that everywhere and do not see any change. What might I be
missing?
 
 

  _____

**Comment by Aris-t2** [comment]
You have to put the code into `my_userContent.css` or `userContent.css`.

**Comment by rebop** [comment]
Thanks.  
 
Had tried that. Went back and tried in many different locations in the file,
no change. Then I found a place that did make a change, but also removed all
my other changes to Addons such as sidebar color, recommendations, Recent,
etc. SO somehow conflicting with all of those changes.
 
 

  _____

**Comment by rebop** [comment]
OK, took me quite some time to find out where in userContent this had to go
and with what margins to get a desired affect. However, once that is done I
lose my buttons and can only get the menu no matter what options I try.
 
 

  _____

**Comment by Aris-t2** [comment]
Its probably a Waterfox incompatibility with the code. What I did:

addonlists_show_buttons_instead_of_menu_popup_fx72.css + this code:

```css
.card.addon {
  margin: 20px 10px !important;
}
```
Result:
![image](https://user-images.githubusercontent.com/6013569/104724594-2b83bd00-5731-11eb-9a80-929f0226e393.png)

**Comment by rebop** [comment]
Thanks. Its not a big deal at all, but I get into tweak mode :)
 
Waterfox is based on 68 right now so I am using the following:
 
@import "./css/aboutaddons/addonlists_show_addon_version_number_fx68.css";
/**/
@import "./css/aboutaddons/addons_manager_alternative_appearance_V2.css";
/**/ 
@import "./css/aboutaddons/availableupdates_category_always_visible.css";
/**/ 
@import "./css/aboutaddons/availableupdates_category_last_category.css";
/**/ 
@import "./css/aboutaddons/search_category_always_visible.css"; /**/
@import
"./css/aboutaddons/addonlists_show_buttons_instead_of_menu_popup_compact_vie
w_fx72.css"; /**/

I also have this in userContent (leftovers from previous?)
 
@-moz-document
url-prefix(chrome://mozapps/content/extensions/aboutaddons.html) {
 .main-heading,
 .main-search {
   background: unset !important;
   max-width: unset !important;
   padding-inline-start: unset !important;
   padding-top: unset !important;
   padding-bottom: unset !important;
 }
 
 .sticky-container {
   background: -moz-Dialog !important;
   z-index: 1000 !important;
 }
 
  #sidebar,
 #sidebar #categories {
   background: #CCCCCC !important;
      }
}

And I get this:
 

 
As soon as I enable this:
 
.card.addon {
  margin: 3px  10px !important;
}

 
I get:
 

 
I can live with the former.And I keep learning. Thanks.

  _____
