### ISSUE TITLE
Tab Bar Color?

### ISSUE THREAD

**Issue by rebop** [Aris-t2/CustomCSSforFx#329]
Not an issue, latest version - hopefully very simple question!

I changed this color as shown and cannot for the life of me find where I made that change. Checked in **every** modified file. Can you point me please?

Thanks.
![1status](https://user-images.githubusercontent.com/13785042/106789087-a6d8e000-6606-11eb-9362-468d96b0caeb.JPG)

**Comment by rebop** [comment]
Updates.

Still searched everywhere and cannot find the color setting. BUT, this started when Waterfox added a status bar AND a preference for tabs above address bar, below address bar and at the bottom. If I select either top placement, color is great for my theme on the background. But when I select at the bottom, it gets dark as above. And this is with this commented out:

	/* @import "./css/tabs/tabs_below_main_content_fx74.css"; /**/ 

Examples of top and bottom:
![1 top](https://user-images.githubusercontent.com/13785042/107108939-dba88b00-67f0-11eb-8b40-926c05a54711.JPG)

![1 bottom](https://user-images.githubusercontent.com/13785042/107108944-e82ce380-67f0-11eb-9ea0-04a81c19063a.JPG)

Does that help isolate what I need to change?

Thanks.

**Comment by Aris-t2** [comment]
Using full package one has to edit the `\config\color_variables.css` file and replace the predefined colors for `--tabs_toolbar_color_tabs_not_on_top` varaible

**Comment by rebop** [comment]
Thanks - appreciate the reply, But I am SURE I made a change to that color elsewhere that I cannot find. Was not here. And when I try to make changes here, no matter what I do it makes NO change to the color.

I think I need to find where I did that previously (?) and even searching for the color string in the complete Chrome folders does not find it. AND/OR the new status bar in Waterfox G3 is affecting this somehow.

**Comment by Aris-t2** [comment]
I can't say much about Waterfox G3. I don't run CSS tests on it.

Did you find a way to resolve your issue?

**Comment by rebop** [comment]
Thanks for asking. I did not. The funny thing is I am SURE that I set that
color using CSS and your full package but no matter how closely I look I
cannot find it. Searched hi and low. I have the color it is ion hex but
cannot find that in the Chrome folder at all. Baffling.

  _____

**Comment by Aris-t2** [comment]
I close this for now.

Feel free to reopen it, if your search is successful.

**Comment by rebop** [comment]
So sorry. I found the fix to this one:
 
#TabsToolbar 
{
    background: #F0F0F0 !important;
 }

 
I did not find a fix to the new Statusbar color, but decided to turn that
one off.

  _____
