### ISSUE TITLE
[TABS BELOW CONTENT SUPPORT THREAD] - tabs on windows bottom

### ISSUE THREAD

**Issue by gg2by2** [Aris-t2/CustomCSSforFx#33]
hello
what is the code to locate tabs at the bottom of the firefox 57 screen (just above the windows start button)?

it was suggested to try this=

/* Puts tabs on the bottom */
#TabsToolbar {
  -moz-box-ordinal-group: 2;
  border-bottom: 1px solid #888 !important; 
}
#nav-bar{ border-top-width: 0px !important; }

but the tabs are still located near the top

**Comment by userOperaFF** [comment]
Try this: 
```
/* Tab bar below Navigation & Bookmarks Toolbars 
   For best results, show Title Bar or Menu Bar */
#nav-bar { /* main toolbar */
  -moz-box-ordinal-group: 1 !important;
  border-top-width: 0 !important; 
}
#PersonalToolbar { /* bookmarks toolbar */
  -moz-box-ordinal-group: 2 !important;
}
#TabsToolbar { /* tab bar */
  -moz-box-ordinal-group: 3 !important;
}
```
![image](https://user-images.githubusercontent.com/33114475/32840088-e6721aa4-ca16-11e7-961b-0a3669743077.png)

from https://www.userchrome.org/what-is-userchrome-css.html

**Comment by Aris-t2** [comment]
@gg2by2 
You can not move tabs toolbar to windows bottom. moz-box-ordinal-group only works within top toolbar box.

The only code that can do it heavily breaks Firefox ui and is not part of this project.

**Comment by gg2by2** [comment]
The screen shot still shows tabs above the screen. Just received a response from the moderator that tabs below the screen CANNOT be done! That Firefox ui will not allow it!
--
Sent from my Android Wednesday, 15 November 2017, 09:09AM -05:00 from PL_user  notifications@github.com :

**Comment by userOperaFF** [comment]
>The screen shot still shows tabs above the screen. Just received a response from the moderator that tabs below the screen CANNOT be done! That Firefox ui will not allow it!

Try - https://developer.mozilla.org/en-US/docs/Web/CSS/transform (many bugs to **not easy** fixed), many element transform  blur fonts.

Old - position: fixed and remove bugs (also **hard** to fix).

**Comment by userOperaFF** [comment]
https://github.com/Okamoi/UserChrome-Tweaks/blob/07a8f3faee59184b3c81e60a6506ad5680352ca9/toolbars/bottom-of-window-tabbar-Windows7.css - I test morning.

about:config ➡️   _browser.tabs.drawInTitlebar_  **false**.

**Comment by Aris-t2** [comment]
Is this working better than the one available?

**Comment by userOperaFF** [comment]
Bugged with:
* dpi +100%
* no maximized window (if have appbuton on left in Windows)

And work <ins>only</ins> Windows 7 Aero / Basic (not Classic).

<table><tr><th colspan="2">browser.tabs.drawInTitlebar;true</th>
<tr>
<td>

![image](https://user-images.githubusercontent.com/33114475/33549167-e69bcb60-d8e9-11e7-890e-e9f299d82693.png "maximized") 

</td><td>

![image](https://user-images.githubusercontent.com/33114475/33549189-f701671c-d8e9-11e7-880e-8307ad25357d.png "normal")

</tr></table>


<table><tr><th colspan="2">browser.tabs.drawInTitlebar;false</th>
<tr>
<td>

![image](https://user-images.githubusercontent.com/33114475/33549210-0448bfe2-d8ea-11e7-8739-894fab920d86.png "maximized")

</td><td>

![image](https://user-images.githubusercontent.com/33114475/33549328-6c65eff0-d8ea-11e7-819f-9376e72d5f66.png "normal")


</tr></table>

**Comment by userOperaFF** [comment]
> Is this working better than the one available?

Who knows, I do not used MixTabPlus and I was not looking this tweak in `CustoCSSForFx` or other project.


---

### Bugged with:
* dpi +100% (if have appbutton on left in Windows)
* no maximized window (if have appbutton on left in Windows)
* no see menu toolbar (any value "`browser.tabs.drawInTitlebar`") 

   >    * ![image](https://user-images.githubusercontent.com/33114475/33550011-ba459fb6-d8ec-11e7-86f8-54aa66ebc5f3.png)
   >    * ![image](https://user-images.githubusercontent.com/33114475/33550041-d269c3ba-d8ec-11e7-927e-16f25a2bd7c9.png)
   >    * ![image](https://user-images.githubusercontent.com/33114475/33550094-fbe7ede8-d8ec-11e7-85bb-f54bedc57fce.png)

Test on **Windows 7 Aero / Basic / Classic** (no test on Windows 10, GNU/Linux or MacOS).

<table><tr><th colspan="2">browser.tabs.drawInTitlebar;true</th></tr>
<tr><td>Maximized</td><td>Normal</td></tr>
<tr>
<td>

![image](https://user-images.githubusercontent.com/33114475/33549167-e69bcb60-d8e9-11e7-890e-e9f299d82693.png "maximized") 

</td><td>

![image](https://user-images.githubusercontent.com/33114475/33549189-f701671c-d8e9-11e7-880e-8307ad25357d.png "normal")

</tr>
</tr><tr><td colspan="2"><div align="center"><i>Classic Windows 7</i></div></td></tr>
<tr><td>

![image](https://user-images.githubusercontent.com/33114475/33550835-9e7d0186-d8ef-11e7-930a-3c6fd5865f70.png)

</td><td>

![image](https://user-images.githubusercontent.com/33114475/33550810-8c7ea98a-d8ef-11e7-9522-5b89b4714df4.png)

</td></tr>
</table>


<table><tr><th colspan="2">browser.tabs.drawInTitlebar;false</th></tr>
<tr><td>Maximized</td><td>Normal</td></tr>
<tr>
<td>

![image](https://user-images.githubusercontent.com/33114475/33549210-0448bfe2-d8ea-11e7-8739-894fab920d86.png "maximized")

</td><td>

![image](https://user-images.githubusercontent.com/33114475/33549328-6c65eff0-d8ea-11e7-819f-9376e72d5f66.png "normal")


</tr><tr><td colspan="2"><div align="center"><i>Classic Windows 7</i></div></td></tr>
<tr><td>

![image](https://user-images.githubusercontent.com/33114475/33550648-051390d2-d8ef-11e7-9ab4-55d6b4853e5e.png "maximized")


</td><td>

![image](https://user-images.githubusercontent.com/33114475/33550673-1862d2b0-d8ef-11e7-9c89-41f9da26d69a.png "normal")

</td></tr>

</table>


---

Fonts is clear / spicy (not blur / fogged), addons iframe works ok (e.g. _uBlock Origin_ - element picker to block). Better than my first try to bottom.

**Comment by Aris-t2** [comment]
Switching `browser.tabs.drawInTitlebar` preference or changing Windows themes requires window maximizing/minimizing and/or a browser restart. Have you restarted Firefox after a change?
DPI of 200% is not officially supported on Windows. Even some default ui items don't scale properly.

**Comment by userOperaFF** [comment]
Nope, use only `about:config` tweak DPI value without restart FX.

**Comment by userOperaFF** [comment]
No works on Windows10 FCU (normal theme (no Classic, no Blur tridparty software), tomorow test with normal DPI windows 7 (reset with control panel and logout).

**Comment by Aris-t2** [comment]
With Firefox DPI set to 200% (layout.css.devPixelsPerPx; 2.0) I did not see this issue. Haven't tried within Windows settings, as I don't have a HiDPI screen and setting to such a high value would make it impossible to use Windows for tests.

I remember when using VMs layout.css.devPixelsPerPx settings does not offer the same results real DPI changes in Windows setting do. There is always something different.

**Comment by userOperaFF** [comment]
I use 125% DPI (24" Full HD monitor). I try reset for first.

**Comment by Aris-t2** [comment]
- I have set DPI to 125% in Windows 10FCU settings and rebooted
- CustomCSSforFx 1.4.6
- tested Firefox 57.0.1 and 59 Nightly
- menubar on/off
- titlebar on/off
- dark/default themes
- normal/maximized mode
- uidensity compact/normal/touch

The glitch never occurred here. Are you sure there are no hiddden buttons on your tabs toolbar. They may cause different behavior.

Some screenshots

![1](https://user-images.githubusercontent.com/6013569/33595885-0e0ed9d4-d99a-11e7-91fa-f455bcdfeaa2.png)
![2](https://user-images.githubusercontent.com/6013569/33595889-10ffb2d0-d99a-11e7-8fa2-02d590035f18.png)
![3](https://user-images.githubusercontent.com/6013569/33595891-1304f716-d99a-11e7-88e5-0a46eca2e73b.png)
![4](https://user-images.githubusercontent.com/6013569/33595893-14a27dd2-d99a-11e7-9996-1d26dca2131c.png)
![5](https://user-images.githubusercontent.com/6013569/33595895-16217bcc-d99a-11e7-8ee7-00c398218746.png)

@ALL
Does anyone else has these kind of an issue?

**Comment by userOperaFF** [comment]
I create new profile firefox, download new `chrome.zip` 1.4.6, add code marciiF, Okamoi (possible this is guilty - old code for Firefox 55-56, not 57+).

**Comment by Aris-t2** [comment]
Why did you mix "other" code with this projects code while testing? Clearly this was not what I tested. :)

Yes, both tabs_below_navigation_toolbar.css and tabs_below_main_content.css have to be enabled, for things to work properly. I was too lazy to create more variations of tabs_below_main_content.css for other toolbar colors, but this might change with a future update.

**Comment by userOperaFF** [comment]
> Why did you mix "other" code with this projects code while testing? Clearly this was not what I tested. :)

Use only outdated, no enable form `CustomCSSforFx`.

**Comment by userOperaFF** [comment]
Possible add lw-theme background instead / above black color (any position header image)?

![image](https://user-images.githubusercontent.com/33114475/33599098-5d6a2226-d9a5-11e7-9553-92b8ae68fe80.png)

**Comment by Aris-t2** [comment]
On 1.4.7 release `tabs_below_main_content.css` imports `tabs_below_navigation_toolbar.css`. The description does not tell users to import 'tabs not on top' anymore. This should make thing more understandable. As a side effect users now can chose which predefined toolbar background color they want and select the corresponding `tabs_below_main_content_XYZ.css` file.

**Comment by garywill** [comment]
I found `tabs_below_main_content.css` has problems on private window, buttons are messed.

Then simply I tried this js code
```
var tabsbar = document.getElementById("TabsToolbar");
const below_tabs = document.getElementById("browser-bottombox");
    
below_tabs.parentNode.appendChild(tabsbar, below_tabs);
```
and it works amazing. Just simply moved the entire tabbar object to bottom.
If you want to use this script, the css mustn't use `toolbarbutton` to execute js, or js will be executed repeatly when toolbar is changed.
Use
```
vbox#browser-bottombox {
  -moz-binding: url("./userChrome/userChrome.xml#execute_javascript_code");
}
```
instead.
I put the code [here](https://github.com/garywill/tabs-at-bottom)

**Comment by bendover22** [comment]
Aris,
This question doesn't fit a category.  It's about modifying an addon - any addon, for my personal use.  If you modify an icon, of course then the package signature doesn't match & you can't install it in Firefox.

Is there a relatively easy way to do something like that & repeat the signature process so Firefox doesn't say it's corrupted?  The addons are after all, open source.  Since I'm not planning on distributing anything, the only issue is what I'd actually have to do to sign the modified xpi file.

Any suggested reading on what's involved, including money?
Thanks.

**Comment by Aris-t2** [comment]
@bendover22 
The general support thread is the right place to ask questions like this, not an unrelated random support thread ;-)

https://github.com/Aris-t2/CustomCSSforFx/issues/163#issuecomment-443493111

**Comment by LilMarvellous** [comment]
Hello Aris, 
This my 1st post on this. When I 1st found this fine alternative solution working with Firefox Quantum for classic theme restorer i was so happy as it worked a long while.
Now the issue is back with Firefox 65 run on Windows 10 x64
It seems i am doing something wrong and i can't spot the flaw; it doesn't matter where i remove those "/* " from the line (i do the editing with Notepad+) the fact is tabs always stay between Menu Bar and and Navigation Bar. Yet Bookmarks Toolbar is Below Navigation Bar
The screen shot is is using the "default" _userChrome.css_ for Tabs Below option aka _@import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/_  from custom_css_for_fx_v2.3.9 pack.

![annotation 2019-02-04 195721](https://user-images.githubusercontent.com/47330633/52227115-58799500-28b7-11e9-9d25-5cd4feb16b7f.jpg)

The same result was with custom_css_for_fx_v2.3.8..
The only way to get the true tabs below was using that custom _userChrome-tabs_on_bottom_Fx65.css_ but unfortunately this last mentioned custom .css provide some very unpleasant colours- all is white- bah.. and i totally dislike that
What to do?
Please advise

**Comment by LilMarvellous** [comment]
@Aris-t2 
thks for the fast reply
I did as you said: i did edit _userChrome.css_  

![annotation 2019-02-04 214612](https://user-images.githubusercontent.com/47330633/52232984-99c57100-28c6-11e9-911c-17d8e8322e11.jpg)

- yet the FF65 is very "resilient"to follow commands it seems
it still looks the same :(

![annotation 2019-02-04 214920](https://user-images.githubusercontent.com/47330633/52233060-cbd6d300-28c6-11e9-94bb-fcb10455d275.jpg)

doesn't matter which of those 2 options i choose.. i am lost- that's why i asked for some guidance
i did try both of those, separately or together ..the tabs obstinately are staying as above... it looks they have their own will  :P

**Comment by LilMarvellous** [comment]
@Aris-t2 
Hello mate
i eventually sorted it using as text editor the humble Notepad for _userChrome.css_  from **custom_css_for_fx_v2.4.0**  instead of the sophisticated Notepad++
It worked as charm
Thks for the pack!

**Comment by cxen** [comment]
I have an issue with both "Tabs below nav bar" and "Multirow tabs".

On Firefox 68.0.1, with the same settings, CustomCSSforFx v2.6.2 is broken compared to using v2.4.9.

v2.4.9
![2 4 9](https://user-images.githubusercontent.com/46993334/61848343-15839c00-aeae-11e9-8fe8-d537e9babf41.png)

v2.6.2
![2 6 2](https://user-images.githubusercontent.com/46993334/61848347-174d5f80-aeae-11e9-874c-af785e5636eb.png)

I've switched the appropriate lines on and off to achieve the same result (i.e. "****v3 for f68+" instead of "

***v2 for f65+") but it didn't fix the issue and even trying the exact same userChrome.css setup doesn't work.

**Comment by Aris-t2** [comment]
The combination of `tabs_below_navigation_toolbar_fx65_v2.css` and `tabs_multiple_lines_v3.css` works fine here even on Fx70.

![fx](https://user-images.githubusercontent.com/6013569/61853301-e07e4600-aebb-11e9-8094-c09e44964edd.jpg)

**Comment by cxen** [comment]
I tried again with a clean chrome folder and 2.6.2 and still get a broken Firefox window with a glitchy title bar.

**Comment by Aris-t2** [comment]
Different PC, FX 68.0.1, **tabs_below_navigation_toolbar_fx65_v2.css** and **tabs_multiple_lines_v3.css**, same result as before. I use the [complete package](https://github.com/Aris-t2/CustomCSSforFx/releases) with both options enabled in `userChrome.css`, make sure you do too, not just loose files...

**Comment by cxen** [comment]
Not sure what you mean. My chrome folder has everything that the .zip file contains.

**Comment by R8s6** [comment]
In v3.0.5, when FF is unmaximized, and when `@import "./css/tabs/tabs_below_navigation_toolbar_fx74.css"; /**/` is active, the tab doesn't line up with the horizontal separator, as the tab falls below the separator line. please see screenshot below:

![](https://i.imgur.com/dSgYYWT.png)

This, however, is NOT present when the window is maximized, where the tab lines up perfectly with the separator line, as desired:
![](https://i.imgur.com/UuCLQMx.png)

Steps to reproduce:
Activate:
```
@import "./config/general_variables.css"; /**/
@import "./css/tabs/tabs_below_navigation_toolbar_fx74.css"; /**/
```
All other options inactive.

Thanks!

**Comment by Aris-t2** [comment]
This does not happen here. Which OS are you using? Tabs below navigation toolbar differentiate between macOS and Windows/Linux settings.

**Comment by R8s6** [comment]
> This does not happen here. Which OS are you using? Tabs below navigation toolbar differentiates between macOS and Windows/Linux settings.

Thanks for the reply. It’s Linux.

**Comment by Aris-t2** [comment]
Looks like this for me even on Fx77:
![image](https://user-images.githubusercontent.com/6013569/79014622-97fed980-7b6b-11ea-9331-99a52fa5a4b5.png)

Tested on Ubuntu.

**Comment by Aris-t2** [comment]
I think this does not need to be an own discussion anymore. Main thread should be enough.
https://github.com/Aris-t2/CustomCSSforFx/discussions/454
