### ISSUE TITLE
Firefox:addons colors inverted

### ISSUE THREAD

**Issue by DavyRay** [Aris-t2/CustomCSSforFx#330]
1. Describe the issue

Windows 10 is set to dark mode.  Default FF dark theme enabled.  When I go to the addon section, the colors are inverted.  The left side panel that lists themes, addons, etc is white with white writing.  I can barely see the icon on the top asking me if I want to check for app updates etc.  The addons are listed and are readable.  If I switch windows to light mode, everything comes out and is visible.

If I rename the chrome folder and restart FF with windows in dark mode, it works fine.  I am not running any dark mode addons

I had been using an old version of this script, so i installed a new one... made no changes to it and it did not matter.  So the only change I did was to put the tab bar below the bookmark bar and to remove the boxes around the addon icons.

2. What should have happened instead?

3. Steps to reproduce the issue?

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
See below

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): YES
- OS & OS version: Windows 10 20H2
- OS theme (if not default): default
- DPI / HiDPI resolution: 1920x1080
- Firefox version: FF 85
- Firefox theme / lw-theme: built in dark theme.. although i tried different themes including the plain default, and same issue
- This projects 'settings' the issue occurs with: 

![Clipboard Image](https://user-images.githubusercontent.com/44904766/106833229-2dbaa680-6661-11eb-9a2f-445ebfc34701.jpg)

**Comment by Aris-t2** [comment]
Next update will support OS dark mode and display readable colors there.

First preview already takes care of some issues: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.1.9pre1

**Comment by Aris-t2** [comment]
Fixed in [v3.1.9](https://github.com/Aris-t2/CustomCSSforFx/releases)
