### ISSUE TITLE
Aero Glass theme not working

### ISSUE THREAD

**Issue by IcedFire1337** [Aris-t2/CustomCSSforFx#336]
Turning on Aero Glass theme along with the toolbar fixes makes everything white

The windows aero glass theme shouldve appeared instead

It can be reproduced by turning on the aeroglass theme and then activating the fixes for it in the toolbar section

![image](https://user-images.githubusercontent.com/81553748/112801938-25924c80-908f-11eb-9d27-ff45dd399677.png)

Using the latest CSS
Windows 10
Firefox 87
Default theme

**Comment by Aris-t2** [comment]
Firefox does not support "transparent" windows anymore.

**Comment by IcedFire1337** [comment]
thanks
