### ISSUE TITLE
[Nightly 89] Tab size too large with compact theme and "Tabs below"

### ISSUE THREAD

**Issue by vaporwave9** [Aris-t2/CustomCSSforFx#338]
1. Describe the issue  
Firefox 89 made changes to the size of tabs, the compact theme is facing slow deprecation:

![grafik](https://user-images.githubusercontent.com/64961250/114052380-4bd59a80-988e-11eb-9257-1528d04f058b.png)

To continue using it the about:config must have set:
browser.compactmode.show = true 

2. What should have happened instead?  
I would like to ask for continued support of tabs below with the compact theme, for as long as Firefox is not fully removing the code for it. Ideally we can continue using compact theme + tabs below with Firefox ESR 91 in the future. Depending on the mercy of our Mozilla overlords.

(This only shows the working addon on the current ESR for comparison)
https://user-images.githubusercontent.com/64961250/114052819-aa9b1400-988e-11eb-903c-3efc9c749e97.png

3. Steps to reproduce the issue?  
No extra steps required, update to FF 89 to experience the changes and breakage.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)  
![grafik](https://user-images.githubusercontent.com/64961250/114052191-1e88ec80-988e-11eb-90d0-9ff02e111e7b.png)

5. System information  
- latest CustomCSSforFx files: yes tried both old and LATEST/new
- OS & OS version: Win 10 21H1 (19043.906)
- OS theme (if not default): dark
- DPI / HiDPI resolution: no
- Firefox version: 89 where the breakage occurs
- Firefox theme / lw-theme: default/official, dark+compact ON
- This projects 'settings' the issue occurs with: 
```
@import "./css/locationbar/megabar_expanding_breakout_disabled.css";
@import "./css/tabs/tabs_below_navigation_toolbar_fx74.css";
```
Minimal config. Only 2 settings are used.

**Comment by Aris-t2** [comment]
For now disabling "Proton" settings should work as a workaround. This projects files do not support the WIP-Proton-UI yet.
`browser.proton.enabled -> false`

I already did some experiments with Proton in the last few weeks. This might help you:
```css
	#main-window[uidensity="compact"]  {
	  --tab-min-height: 22px !important;
	}
```

or in general

```css
	#main-window  {
	  --tab-min-height: 22px !important;
	}
```

**Comment by vaporwave9** [comment]
Many thanks! I didn't know they still allow users to opt-out of proton.
Hopefully these switches remain in the FF 91 ESR for another year of that classic feel.

I will experiment with the CSS snippets you supplied in case they cut us off in future.
Leaving this open so other people can find this until either your workaround is final or Mozilla changes something.
Thanks again!

**Comment by Aris-t2** [comment]
I opened a new issue/thread targeting Proton settings here: https://github.com/Aris-t2/CustomCSSforFx/issues/339
