### ISSUE TITLE
addonlists_show_addon_version_number.css not working

### ISSUE THREAD

**Issue by roaminghawk** [Aris-t2/CustomCSSforFx#34]
Hi,

addonlists_show_addon_version_number.css is not working.
Just shows a blank about:addons page.

Thanks

**Comment by Aris-t2** [comment]
Works for me on Windows, Linux and macOS in Firefox 57-59.

Have you extracted this projects files correctly into chrome folder?
Have you removed any other files being in that folder?

**Comment by stonecrusher** [comment]
@roaminghawk Had the same issue. Be sure you also copied the xml folder! It contains a required file.

**Comment by roaminghawk** [comment]
Thank you.

**Comment by Aris-t2** [comment]
Issue solved.
