### ISSUE TITLE
Cosmetic problem with tab close button

### ISSUE THREAD

**Issue by Thalon77** [Aris-t2/CustomCSSforFx#340]
1. Describe the issue

Just updated Firefox to version 88.0, after the reboot I noticed a little cosmetic change (so nothing really critical or life threatening): the red button to close tabs (enabled it with @import "./css/generalui/close_icon_red.css") has shrunk.

2. What should have happened instead?

The button was a little bigger before the update (same height of the blue + on the button to create new tabs).

3. Steps to reproduce the issue?

Updating Firefox to V 88.0

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

![Cattura](https://user-images.githubusercontent.com/33811707/115458653-4aa95380-a226-11eb-9c45-57654f4ac1d4.JPG)

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): V 3.1.9
- OS & OS version: Win10
- OS theme (if not default): 
- DPI / HiDPI resolution: 1920x1080
- Firefox version: 88.0
- Firefox theme / lw-theme: no theme

**Comment by glennpc** [comment]
Same thing here using close_icon_firefox3.css on Fx88:

![Close tab](https://user-images.githubusercontent.com/54756104/115476589-05216200-a1f7-11eb-9a84-3dc6c9ab1a80.png)

The close tab buttons are now smaller. Any way to make this larger like it was on Fx87 and prior versions?

**Comment by glennpc** [comment]
For now, I'm using the close_icon_windows10redv2.css which has a larger button.

![close-tab](https://user-images.githubusercontent.com/54756104/115585508-85d87080-a280-11eb-9518-5b5568c05dc4.png)

**Comment by 2BeeOrNot** [comment]
Try adjusting the width:
.tab-close-button.close-icon { width: 24px !important; }

The close icons in this project are not all the same size so try different widths. I'm not using the close icons in this project. I tried close_icon_firefox3.css and the above width made the close icon bigger.

**Comment by glennpc** [comment]
The code above has no effect on it. The problem exists because I'm using:

@import "./css/tabs/classic_squared_tabs.css"; /**/

When I remove that, the close button is large again.

**Comment by Aris-t2** [comment]
Changing close icons width and height to 20px fixes this like glennpc mentioned.

```css
#TabsToolbar .tabbrowser-tab .tab-content .close-icon {
  width: 20px !important;
  height: 20px !important;
}
```
