### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Mte90** [Aris-t2/CustomCSSforFx#341]
1. Describe the issue

Add screenshot of Firefox with those rules so an user can see what are the changes. Maybe in the readme.

**Comment by vulpes9** [comment]
Excellent idea! So you volunteer to do this for all 387 ```@import ``` rules that exist and keep them updated for each release?
When can you start?

**Comment by literal-0x4e** [comment]
If a user can't read the rules to understand them and instead needs a visual guide to explain what it does, then maybe they aren't using the right browser for their skill level. For users of such skill level I suggest migrating to something easier, e.g. Chrome until they learn the basics.

**Comment by Aris-t2** [comment]
;-)
