### ISSUE TITLE
Version V3.2.0pre is the same as V3.1.9

### ISSUE THREAD

**Issue by GaVenga** [Aris-t2/CustomCSSforFx#343]
Version V3.2.0pre is the same as V3.1.9 ?!

**Comment by Speravir** [comment]
If you speak about `custom_css_for_fx_v3.2.0pre1.zip` which is anyay the only preview version in the moment: Not here. I see differences for `aboutaddons/addonlists_show_buttons_instead_of_menu_popup_fx72.css` and `aboutaddons/addons_manager_alternative_appearance_aero_fx75.css`.

**Comment by GaVenga** [comment]
You are correct. He forgot to change version-string - this is normal for humans

**Comment by Aris-t2** [comment]
Actually this is done on purpose, as pre leases only offer quick changes without any description or release notes. ;-)
