### ISSUE TITLE
Can the dialogue ‘Close tabs and exit’ be reverted back to the former window-formed?

### ISSUE THREAD

**Issue by CT-ABT** [Aris-t2/CustomCSSforFx#347]
![image](https://user-images.githubusercontent.com/30417426/119450686-cf0a5d00-bd23-11eb-91b8-4c5bf89880b2.png)

I mean this … ugly, Chrome-mimicking thing. Can it be reverted back to the former window-formed? Are there any about:config tweaks for this or is it just another ‘there is no going back’?

I am currently on Firefox 89.

Thank you.

**Comment by Aris-t2** [comment]
I doubt there is an option to just revert the dialog ui.

CSS should be able to 'restyle' the window, but not to restore the old ui.

**Comment by CT-ABT** [comment]
Thank you :)
