### ISSUE TITLE
Icons size in home page

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#348]
Is there an option to Fill it up the size of Icons in Home? (firefox 89)

like this

![119774062-20942280-beb1-11eb-80aa-c18dd52f18d7](https://user-images.githubusercontent.com/33927879/120202284-b9ff6380-c226-11eb-923f-67231f386bac.png)

**Comment by Aris-t2** [comment]
I don't understand your question?

There are no options to change icon sizes on about:home, if that is what you are asking.

**Comment by gabri25ele** [comment]
![sshot-1](https://user-images.githubusercontent.com/33927879/120284559-a7d00480-c2bc-11eb-8080-2ac63b90fbad.png)

in this image you can see the icon image with a blank useless border

instead 
the image that takes up all the available space is much better

![sshot-2](https://user-images.githubusercontent.com/33927879/120284766-e36ace80-c2bc-11eb-9dbf-495fc3a7d8a1.png)

**Comment by Aris-t2** [comment]
It is possible, if the icon/image supports it.

Add this to `userContent.css`/`my_userContent.css`:

```css
.top-site-outer .tile .icon-wrapper {
  position: unset !important;
}
```

**Comment by motfis** [comment]
> ![119774062-20942280-beb1-11eb-80aa-c18dd52f18d7](https://user-images.githubusercontent.com/33927879/120202284-b9ff6380-c226-11eb-923f-67231f386bac.png)

how do you enable icon on the proton? which css needs to be enabled?

**Comment by Aris-t2** [comment]
This will be added to CustomCSSforFx on next update as an own option.

**Comment by gabri25ele** [comment]
> 
> 
> This will be added to CustomCSSforFx on next update as an own option.

this I wanted to hear! 😉

**Comment by Aris-t2** [comment]
Check [3.2.2](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.2.2) release.

**Comment by gabri25ele** [comment]
they tell me from the director that there is an option in about: config
**browser.newtabpage.activity-stream.newNewtabExperience.enabled** -> FALSE

**Comment by Aris-t2** [comment]
Great find. I saw this option before, but never triggered it. So for now and as long this one exists, it does solve the issue without additional code.
