### ISSUE TITLE
No arrows in bookmark menù with Proton (Firefox 89)

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#349]
This is the bookmanrk menù without CustomCSSforFx

![1](https://user-images.githubusercontent.com/33927879/120202817-545fa700-c227-11eb-8c56-7cc6fc143886.png)

and this with CustomCSSforFx (arrow is missing)

![2](https://user-images.githubusercontent.com/33927879/120202840-5cb7e200-c227-11eb-9cc2-507ef12156e2.png)

obviously with this back in place
browser.proton.contextmenus.enabled > false (disables Proton UI of context menus)

**Comment by Aris-t2** [comment]
Using the default setup arrows are still present for me in Firefox 89/90 on Win10.
Maybe an option or custom code creates a coflict.

**Comment by Aris-t2** [comment]
So, how to reproduce this?

**Comment by gabri25ele** [comment]
> 
> 
> So, how to reproduce this?

I'm using your CustomCSSforFx, if you want I can send my css as they are configured

**Comment by Aris-t2** [comment]
Upload your chrome folder and attach it here by moving the zip file into your post.

**Comment by gabri25ele** [comment]
the problem maybe similar to https://github.com/Aris-t2/CustomCSSforFx/issues/301#event-3314834415

**Comment by gabri25ele** [comment]
this is my chrome folder with no arrows
[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/6602204/chrome.zip)

**Comment by Aris-t2** [comment]
Strange, but even with your files only, there is no missing arrow in any bookmarks area in my tests.

-------------

Can someone else confirm this?

**Comment by hopalongrock** [comment]
I have the same issue with my own profile using userchrome.css

![20210605 112108  ](https://user-images.githubusercontent.com/6840865/120886853-50010880-c5f0-11eb-91f9-545b1243abfa.jpg)

without userchrome.css

![20210605 112026  ](https://user-images.githubusercontent.com/6840865/120886869-5f805180-c5f0-11eb-8171-d5c85266bc89.jpg)

**Comment by Aris-t2** [comment]
Found the issue inside bookmark_icons_colorized.css.

The arrow disappeared only from `>>` menu, which is empty on my test profile.

Next update file fix this.

**Comment by Aris-t2** [comment]
Check [3.2.2](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.2.2) release.

**Comment by hopalongrock** [comment]
Fixed, thanks.
