### ISSUE TITLE
Classic urlbar panel delay on pasting local URL (regression, had been fixed in CTR)

### ISSUE THREAD

**Issue by pintassilgo** [Aris-t2/CustomCSSforFx#35]
In june, I reported a CTR bug about delay of ~ 1 second or more between pasting an address and pressing enter until the URL starts to load:
http://forums.mozillazine.org/viewtopic.php?p=14753308#p14753308

It was hard for you to reproduce the issue, but you finally managed to fix it:
http://forums.mozillazine.org/viewtopic.php?p=14753568#p14753568

But now, with this userChrome.css version of "Alternative appearance (classic)" (ac_popup_classic_with_two_lines.css), the bug has returned, at least if you paste a local URL like `file:///H:/Users/Pictures/Screenshot -  13, 2017 5.08 PM.png` or `H:\Users\Pictures\Screenshot -  13, 2017 5.08 PM.png`.

To reproduce this bug you must have already let the urlbar panel with suggestions appear at least once since you opened Firefox. Paste a URL like the one above, then quickly press Enter.

Firefox 58.0b1 (Developer Edition).

**Comment by Aris-t2** [comment]
I reused the code from CTR for this without changing anything in that matter.

I see no delay when using your steps to reproduce the mention issue. 
Tested Fx57-59.

**Comment by pintassilgo** [comment]
Just disabled (commented)
`-moz-binding: url("./xml/urlbarBindings_fx57.xml#urlbar-rich-result-popup") !important;`

And "solved". The other block related to that xml file may remain uncommented, it is not part of the problem.

The problem with commenting this line is that the suggestions list panel is enlarged to full width, but should inherit the width of the urlbar.

Tested after disabling all extensions. No problem using the same profile on Fx 56.0.2 with CTR instead of userChrome.css.

**Comment by Aris-t2** [comment]
I can look into 'urlbar-rich-result-popup' xml code of current Firefox, but can not promise anything yet.

**Comment by pintassilgo** [comment]
Seems that you need to put `this._invalidate();` inside `_openAutocompletePopup` body. It is present in the `_openAutocompletePopup` of current Firefox.

`urlbarBindings_fx57.xml#urlbar-rich-result-popup` does something more than set the popup width? I'm thinking of get rid of it and use a userChromeJS script:

```
document.getElementById('PopupAutoCompleteRichResult').__proto__._openAutocompletePopup = function _openAutocompletePopup(aInput, aElement) {
          if (this.mPopupOpen) {
            return;
          }

          var urlbarStyle = document.getElementById("urlbar").getBoundingClientRect();
          this.setAttribute("width", Math.round(urlbarStyle.width));

          this._invalidate();

          this.openPopup(aElement, "after_start", urlbarStyle.x, -1, false, false);
}
```

**Comment by Aris-t2** [comment]
Thanks for the info.

I assumed this part was related to creating "default" popup and popup width and was unrelated to this features "classic" needs. There are no errors without it and I see no difference when using it, but since it helps your case, I will include this in next update.
