### ISSUE TITLE
[Fx89+] Proton + close icons for general ui and tabs

### ISSUE THREAD

**Issue by motfis** [Aris-t2/CustomCSSforFx#353]
1. Describe the issue
Close icon css does not work properly on proton. On most cases it becomes vey small.

2. What should have happened instead?
normal size

3. Steps to reproduce the issue?
Change to any "close icon" css. if disabled, it's OK.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
<img width="452" alt="Capture2" src="https://user-images.githubusercontent.com/8572695/120390014-78a5ab80-c32d-11eb-9fd4-e5e196b71539.PNG">

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): y
- OS & OS version: w10 20h2
- OS theme (if not default): 
- DPI / HiDPI resolution: 150
- Firefox version: 89
- Firefox theme / lw-theme: 
- This projects 'settings' the issue occurs with:

**Comment by maryadavies** [comment]
I might add that if you have classic tabs, it will work, but that one has its own issues on proton for some reason. I'll post up another issue thread about it.

**Comment by Aris-t2** [comment]
Test recent pre releases. This issue should be gone. (At least it was in my tests ;-) )
