### ISSUE TITLE
Close, maximize and minimize buttons are off place, menubar isnt properly coloured when title bar is disabled

### ISSUE THREAD

**Issue by IcedFire1337** [Aris-t2/CustomCSSforFx#354]
Firefox close, maximize and minimize buttons are not in the correct place when title bar is disabled. They appear to the left and a bit above the navigation bar. The maximize and minimize buttons are overlapped by other elements of the UI. The colouring of the menubar is also a bit off.

The buttons should have appeared at the top left. The menubar should be completely coloured

I have tabs below nav bar enabled with the titlebar disabled

![image](https://user-images.githubusercontent.com/81553748/120424659-77569c00-c38a-11eb-8f58-49b5c2905a4f.png)

![image](https://user-images.githubusercontent.com/81553748/120424806-b4229300-c38a-11eb-8454-b6ce02bc0904.png)

Using latest the Version
on Windows 10
on Firefox developer edition 90
using the default firefox theme

**Comment by Aris-t2** [comment]
I can not reproduce this.

Could you test your active settings one by one to find the one causing issues. Default setup does not cause this for me.

**Comment by IcedFire1337** [comment]
My bad, i was using the one meant for Mac by accident. Changed and its fixed now. Only thing left is how a bit of the bar is not coloured 
![image](https://user-images.githubusercontent.com/81553748/120586832-e2b77100-c451-11eb-9a67-cddd62d8153d.png)

**Comment by Aris-t2** [comment]
Adding a color there is a bit tricky as it is not part of the actual menubar, but titlebar or the main window.

You could set a color to main window and see, if it helps:

```css
#main-window {
  background: #ddebf9 !important;
}
```

**Comment by IcedFire1337** [comment]
Yeah that worked perfectly. Thanks!
![image](https://user-images.githubusercontent.com/81553748/120642913-1e265f80-c493-11eb-9cb5-43721bb7a710.png)
