### ISSUE TITLE
[FX 89+]Classic tabs sorta works, but not..(Wrong tabs color/wierd issue with classic tabs and youtube/shape only shows on active tab)

### ISSUE THREAD

**Issue by maryadavies** [Aris-t2/CustomCSSforFx#356]
So I noticed a wierd issue when using classic tabs. 
![image](https://user-images.githubusercontent.com/34210914/120487093-a9183480-c383-11eb-9b57-901a2fc33c6f.png)
As you can see with Proton, and my theme, it looks funky when you highlight a tab (That highlight should be transparent). Also if you try to play a Youtube video, it REALLY looks ugly:
![image](https://user-images.githubusercontent.com/34210914/120487479-014f3680-c384-11eb-9e08-9c86bb8cf006.png)
Can there be a fix, please?

I'll add this is Windows 10, I haven't tried this on the Ubuntu box we have yet. (Have to wait until they push the update and I install the new version of this (that version isn't themed however. It's a subtile KH theme and I tend to be low key with my fandoms for reasons of my own.)

**Comment by Aris-t2** [comment]
Test recent pre releases. This issue should be gone. (At least it was in my tests ;-) )

**Comment by Aris-t2** [comment]
Check [3.2.2](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.2.2) release.
