### ISSUE TITLE
[Proton] How do I remove "new tab" button from context menu when right clicking existing tab?

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#360]
1. Describe the issue
The big guys at Mozilla screwed up again, adding option that makes user experience less pleasant

2. What should have happened instead?
No "new tab" in context menu

3. Steps to reproduce the issue?
Download Proton

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
Doesn't really apply does it

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): yes
- OS & OS version: Win 10, dunno
- OS theme (if not default): 
- DPI / HiDPI resolution: ?
- Firefox version: Proton? 90?
- Firefox theme / lw-theme: Default?
- This projects 'settings' the issue occurs with:  Recreation of 2007' era Firefox

**Comment by Nyekomimi** [comment]
This is small offtop, but want to mention it so Aris-t2 knows - Most recent update to CustomCSS fixed the invisible ctrl-f issue!

**Comment by marty60** [comment]
It was silly to put it there as the first option not to mention redundant. There's already several ways to open a new tab.

This is what used to remove it:

menuitem[label="New Tab"] {display: none !important; }
menuitem[label="New Tab"] + menuseparator { display: none !important; }

**Comment by Nyekomimi** [comment]
> 
> 
> It was silly to put it there as the first option not to mention redundant. There's already several ways to open a new tab.
> 
> This is what I used to remove it:
> 
> menuitem[label="New Tab"] {display: none !important; }
> menuitem[label="New Tab"] + menuseparator { display: none !important; }

Ty. Sadly, didn't work in my_userChrome.css
Tried copying all the my_userChrome.css code to end of userChrome.css and removing the usual import - didn't work either.

Moved it before other custom code (that will need revisiting as well - the code to remove "open image in new tab" no longer works) but that didn't work either.

Renamed "New Tab" in your code to "Nowa Karta", to check if it just needs changing to my language's version - didn't work either.

**Comment by marty60** [comment]
You can try this:

#tabContextMenu #context_openANewTab {
    display: none;
}

#tabContextMenu #context_openANewTab + menuseparator {
    display: none;
}

**Comment by Nyekomimi** [comment]
Works! Tyvm!

Is there any chance that you could examine rest of the custom code for me and figure how to re-remove the "open image in new tab" and again move the "view image" from plugin on top?

#page-action-buttons::before { display: -moz-inline-box; content: ""; height: 24px; width: 24px;
padding: var(--urlbar-icon-padding); fill: var(--lwt-toolbar-field-color, black);
fill-opacity: 0.6; -moz-context-properties: fill, fill-opacity;
background: no-repeat center url(chrome://global/skin/icons/arrow-dropdown-16.svg); opacity: 0; transition: opacity 150ms linear }
#page-action-buttons::before{ opacity: 1 }
.urlbar-input-box:not(:focus-within){ margin-inline-end: -24px; }
#urlbar-input:not(:focus-within){ padding-inline-end: 24px !important; }
.urlbar-input-box:focus-within ~ #page-action-buttons::before{ -moz-user-focus: normal }

.browserContainer > findbar { -moz-box-ordinal-group: 0; position: fixed !important;
border-top: none !important; margin-top: -1px !important; --toolbar-field-focus-border-color: #C0C0C0 }

@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); /* only needed once */


https://addons.mozilla.org/en-US/firefox/addon/view-image-context-menu-item/

**Comment by marty60** [comment]
You sure this doesn't work for you, it is for me but maybe it is language related:

menuitem[label="Open Image in New Tab"] {display: none;}
menuitem[label="Open Image in New Tab"] + menuseparator {display: none;}

**Comment by Nyekomimi** [comment]
Just checked. Sadly, nope.

**Comment by Nyekomimi** [comment]
Quick update
Found this code from old feedback I have received in past
menuitem[label="View Image"] {-moz-box-ordinal-group:0;}
menuitem#context-viewimage {-moz-box-ordinal-group:10;}

Result: "View Image" is on top of *last context group*
BUT the "View Image in new tab" moved on very bottom of said group.
![sunflower](https://user-images.githubusercontent.com/33688131/120697003-79fde200-c4ad-11eb-8dc9-fb867864e284.png)

**Comment by Nyekomimi** [comment]
Got compact solution from FirefoxCSS subreddit, 3 for 1!

> Move View Image to top:
> 
> 
> 
> #_0d20e3ac-ee5b-4db9-bd3f-8ed745f569a7_-menuitem-_view-image-context-menu-item {
> 
>     -moz-box-ordinal-group: 0 !important;
> 
> }
> 
> 
> 
> Remove Open Image in New Tab:
> 
> 
> 
> #context-viewimage { display: none !important;}
> 
> 
> 
> Remove New Tab from Context menu:
> 
> 
> 
> #context_openANewTab, #context_openANewTab + menuseparator {
> 
>     display: none !important;
> 
> }
Credit to clueless-nomad

**Comment by marty60** [comment]
You beat me to it, I was just going to post it. :) 

#context-viewimage  {
display: none;
}
 It's easy to find in the browser toolbox.
