### ISSUE TITLE
Display issue with tabs multiple lines

### ISSUE THREAD

**Issue by zissakos** [Aris-t2/CustomCSSforFx#361]
newest release v32, Firefox 89, with just one line in UserChrome.css

@import "./tabs_multiple_lines_fx81.css";

I am getting this:

![image](https://user-images.githubusercontent.com/24368712/120697998-b8e06780-c4ae-11eb-93ef-393a789a811c.png)

-> There is a blank tab row below the first tab row

Anyone else?

**Comment by montsaroffNoaa** [comment]
I am having a similar problem with the tabs at about half height.

**Comment by Aris-t2** [comment]
Please do not open new threads for already existing issues/discussions:
https://github.com/Aris-t2/CustomCSSforFx/issues/39

"This projects 'multiple tab lines' code is not yet compatible to Fx89+/Proton UI.
