### ISSUE TITLE
when typing in search box on new tab it automatically types in browser address field

### ISSUE THREAD

**Issue by dinkydogs** [Aris-t2/CustomCSSforFx#362]
1. Describe the issue: When I open a new tab and type in the search box it automatically starts typing in the browser address field instead of the search box. if I hit the home button then it allows me to type in the search box.
<img width="1385" alt="Screen Shot 2021-06-03 at 12 20 49 PM" src="https://user-images.githubusercontent.com/63877723/120701112-531cbd00-c467-11eb-9cb9-14ea2059cf4e.png">

2. What should have happened instead?: the text should have been filled out in the search box.

3. Steps to reproduce the issue?: open a new tab and type in search box.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post): my text should be in the circled area of my screenshot.

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): yes
- OS & OS version: macOS Big Sur and Mojave
- OS theme (if not default): 
- DPI / HiDPI resolution: 
- Firefox version: 89
- Firefox theme / lw-theme: 
- This projects 'settings' the issue occurs with:

**Comment by jscher2000** [comment]
This is a Firefox setting, not a CSS problem. For now there is a preference:

(1) In a new tab, type or paste **about:config** in the address bar and press Enter/Return. Click the button accepting the risk.

(2) In the search box in the page, type or paste **handoff** and pause while the list is filtered

(3) Double-click the **browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar** preference to switch the value from true to false

**Comment by dinkydogs** [comment]
awesome. worked perfectly. thank you for the help!
