### ISSUE TITLE
{FX 89]  /css/buttons/icons_custom_icons_noia.css" not correctly scaled

### ISSUE THREAD

**Issue by GaVenga** [Aris-t2/CustomCSSforFx#366]
(Firefox 89) 
Since 3.2.1pre 6 (tested) including 3.2.1v2
activating  "./css/buttons/icons_custom_icons_noia.css"
does not scale correctly the forward/backward/home/reload - buttons (much too small in x-axis, correct in y-axis).
I have done this work-arround:
installed Noia-Buttons 2.0.0 (merged userChrome.css).
On manjaro unstable (Gnome40) this looks good,
on Ubuntu 18.04 it looks ugly...

**Comment by Aris-t2** [comment]
Custom icon sets are not yet fully supporting Fx89+.

This will be done in a future update.

NoiaButtons 2.0.0 however already was updated for Fx89+usage.

**Comment by Aris-t2** [comment]
Check [3.2.2](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.2.2) release.
