### ISSUE TITLE
[Firefox 89+][Proton] +  The "more tools" list is too long and wide

### ISSUE THREAD

**Issue by hopalongrock** [Aris-t2/CustomCSSforFx#367]
The "more tools" list is now to long and wide.

Is it possible to made it "more compact" ?

![20210605 134919  Release 89 0 _ — Mozilla Firefox](https://user-images.githubusercontent.com/6840865/120891214-a299ef00-c607-11eb-850d-39b31289c801.jpg)

The same is true for Customize Toolbar + "Overflow Menu"

**Comment by Aris-t2** [comment]
There will be a new option to reduce the padding in menupopups on next update, but the width of the popup won't be changed.

Reduce bookmarks label length to reduce the width of that popup.

**Comment by hopalongrock** [comment]
Thanks!

Unfortunately I don't know, how to change the label of the addon buttons.
But even after I removed the addon with the longest label, the popup width didn't change.

![20210605 162630  Release 89 0 _ Add-ons Manager — Mozilla Firefox](https://user-images.githubusercontent.com/6840865/120895179-18a85100-c61c-11eb-9487-bb87b8344b6a.jpg)

**Comment by Acid-Crash** [comment]
> 
> 
> There will be a new option to reduce the padding in menupopups on next update, but the width of the popup won't be changed.
> 
> Reduce bookmarks label length to reduce the width of that popup.

@Aris-t2 
This is a great idea, kindly asking to not forget about padding for the Bookmark Menu (the one accessed via a separate toolbar button)

**Comment by Aris-t2** [comment]
Check [3.2.2](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/3.2.2) release.

**Comment by hopalongrock** [comment]
Thanks, works fine
