### ISSUE TITLE
tabs_multiple_lines_fx81 -> corrupted tab size

### ISSUE THREAD

**Issue by CoSoCo** [Aris-t2/CustomCSSforFx#370]
!!! READ THIS BEFORE OPENING A NEW ISSUE REPORT !!!

NO SUPPORT for
- custom code and/or code containing '@namespace' references (remove that useless stuff)
- outdated versions of CustomCSSforFx
- deprecated features of (legacy) add-ons (except the ones this repository is based on e.g. CTR and CTB)
- visual issues WITHOUT screenshots

INVALID REPORTS WILL BE CLOSED WITHOUT FURTHER NOTICE TO KEEP ISSUE AREA CLEAN.
By submitting a new issue you confirm having read and understood 'how to report a new issue'.
Thanks for your understanding.

-> use TEMPLATE at the bottom after reading everything on this page <-

SUPPORT AREA only for features THIS project provides
1. This is not a 'request' area for new stuff or legacy add-on features. Do not open a new issue about something this project does not offer. Instead join the 'General discussions, feedback, questions belong here' thread to chat and ask questions about what is or could be possible there.
2. Use available support threads:
- GENERAL TALK, FEEDBACK & QUESTIONS: --> https://github.com/Aris-t2/CustomCSSforFx/issues/308
- TABS BELOW CONTENT SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/33
- MULTIROW TABS SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/39
- ADD-ON BAR SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/73
- OLD SEARCH SUPPORT THREAD --> https://github.com/Aris-t2/CustomCSSforFx/issues/104
3. Read 'how to report issues properly' before posting a new issue.
--> https://github.com/Aris-t2/CustomCSSforFx/issues/4

----------------------------------

Add all information required in 1-5 and delete this line and everything above it before submitting.

1. Describe the issue
Tab items are too small and overlap.

2. What should have happened instead?
Tab items have normal size.

3. Steps to reproduce the issue?
Use FF 89 on Ubuntu with attached userChrome.css
Set to 5 lines in general_variables
(Additionally I wonder, why in general_variables the comment of `--tabs-lines` says, it is only for v2.css, but not for all taters.)

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
Yes!

5. System information
- latest CustomCSSforFx files (yes / no [no support, if 'no']): yes, v_3.2.1v2
- OS & OS version:  Ubuntu 20.04
- OS theme (if not default): Unity
- DPI / HiDPI resolution: 1680x1050
- Firefox version: 89.0
- Firefox theme / lw-theme: none
- This projects 'settings' the issue occurs with: 
tabs_multiple_lines_fx81
tabs below navigation toolbar Fx 65 v2

**Comment by CoSoCo** [comment]
[userChrome.css.zip](https://github.com/Aris-t2/CustomCSSforFx/files/6602983/userChrome.css.zip)
![CustomCSSforFx_corrupted_tabs_multiple_lines](https://user-images.githubusercontent.com/14809606/120900793-2a4b2200-c637-11eb-9339-38a43f80ddbd.png)

**Comment by Aris-t2** [comment]
See https://github.com/Aris-t2/CustomCSSforFx/issues/39

**Comment by CoSoCo** [comment]
Thanks for your hint. Version 3.2.2 has fixed the problem.
