### ISSUE TITLE
Menu Bar Icons with Firefox 89 Proton

### ISSUE THREAD

**Issue by LostSoul99** [Aris-t2/CustomCSSforFx#371]
I am using the latest version of CustomCSS released today.  Before Firefox 89 I could place Icons in the menu bar as shown in the first picture.  After updating to version 89 the Icons are no longer on the menu bar but along the left side as shown in the 2nd picture.  Is it because the Icons have changed there look in proton?  Is there anyway to change them back and get them to go back on the menu bar? I have been trying for hours now with no luck.  Hoping I am just missing an option.

Thanks for any help.

**Icons on Menu Bar**
![Icons Normal](https://user-images.githubusercontent.com/45321000/120909894-99c50f80-c63f-11eb-8d7b-dcf2f8b105b6.jpg)

**Icons on Left Side**
![Icons on side](https://user-images.githubusercontent.com/45321000/120909898-9d589680-c63f-11eb-9778-5217885247a9.jpg)

**Comment by Aris-t2** [comment]
Not sure what happend there, but CSS can not remove or move buttons from a toolbar.

Try to reset your toolbar config inside customizing mode and move the buttons again to menu bar.

**Comment by LostSoul99** [comment]
I should have mentioned I tried that.  With CSS disabled the menu bar will expand slightly when you go to place the icon on the menu bar.  With CSS enabled as soon as I let go of the Icon on the menu bar it snaps over to the left side as shown in the 2nd picture.  Could it be that the menu bar is not expanding to accept the icon so it puts it in another spot?

**Comment by Aris-t2** [comment]
Hard to tell what exactly causes the issue. Maybe creating a new browser profile (--> Portable Firefox) and testing without any custom tweaks would give a clue.
Afterwards reconfiguring custom CSS settings one by one might point to a file/code, that is responsible.

**Comment by Aris-t2** [comment]
@LostSoul99 

Could you reproduce the issue on a new browser profile using latest project files?

**Comment by LostSoul99** [comment]
Sorry I haven't had a chance yet, I will try tomorrow.

**Comment by LostSoul99** [comment]
I thought I read here somewhere to get tabs below bookmarks toolbar you needed to use this line with firefox 89 @import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css"; /**/

After downloading your new version and allowing each setting one by one I found the above code would move the Icons.  I then tried this line of code and now everything is good now.  The icons stayed on the menu bar.  @import "./css/tabs/tabs_below_navigation_toolbar_fx89.css"; /**/

Another quick question is there a way to move the tab line to the bottom of the tab instead of the top?  

Anyways thanks for your help

**Comment by Aris-t2** [comment]
You mean something like adding another border line on tabs bottom?

```css
.tabbrowser-tab[selected] .tab-content {
  border-bottom: 1px solid red !important;
}
```


`tabs_below_navigation_toolbar_fx65_v2.css` should only be used, if you also use "multiple tab lines" feature.

**Comment by LostSoul99** [comment]
I'm sort of a newb at this, not exactly sure where I am supposed to put that code

**Comment by Aris-t2** [comment]
New code always belongs at the bottom of your `userChrome.css` or `my_userChrome.css` file.

**Comment by LostSoul99** [comment]
Ok thanks, worked perfect
