### ISSUE TITLE
Notifications such as blocked pop ups not in the correct place

### ISSUE THREAD

**Issue by TsukiZero** [Aris-t2/CustomCSSforFx#375]
They are appearing above the Nav Bar rather than under Tab Bar (which was its old place and, before Firefox 89, was treated as "above the opened site")

-------------

1. Describe the issue
Notifications such as blocked pop ups not in the correct place

2. What should have happened instead?

3. Steps to reproduce the issue?

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]):
- OS & OS version: 
- OS theme (if not default): 
- DPI / HiDPI resolution: 
- Firefox version: 
- Firefox theme / lw-theme: 
- Proton enabled (yes / no): 
- This projects 'settings' the issue occurs with:

**Comment by Aris-t2** [comment]
We need a bit more context here. Please follow the rules on how to report bugs.

I edited your post for this. Add the missing details.

**Comment by Aris-t2** [comment]
I'm closing this for now.

Feel free to post a more detailed description here later.
