### ISSUE TITLE
context-navigation Text is too long in Chinese

### ISSUE THREAD

**Issue by laulguo** [Aris-t2/CustomCSSforFx#376]
1. Describe the issue
The context-navigation in Right click pop-up menu Text is too long in Chinese

2. What should have happened instead?
the refresh and bookmark should not so long

3. Steps to reproduce the issue?
Right click on the web page

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![无标题](https://user-images.githubusercontent.com/38545281/121163640-8b663600-c881-11eb-8d08-7ef742938bb8.png)

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]):Custom CSS tweaks for Firefox v3.2.4
- OS & OS version: Windows 10 Enterprise LTSC
- OS theme (if not default): default
- DPI / HiDPI resolution: 100%/1920x1080
- Firefox version: 89.0
- Firefox theme / lw-theme: default
- Proton enabled (yes / no): no

**Comment by Aris-t2** [comment]
Strange, the four labels should be aligned vertically, if "context_bfrsb_labels_*" settings are used.

Make sure you have `browser.proton.contextmenus.enabled` and` browser.proton.enabled` both set to `true` or both set to `false`.
Mixing true/false or false/true causes issues.

**Comment by laulguo** [comment]
setting browser.proton.contextmenus.enabled to false solve the problem
