### ISSUE TITLE
Changes of the colour codes in "default_tabs_bg_selected" are not reflected on screen

### ISSUE THREAD

**Issue by BigShultzy** [Aris-t2/CustomCSSforFx#377]
1. Describe the issue : --default_tabs_bg_selected: linear-gradient(to bottom,#FF8800,#FFCC99);  Any changes of the colour codes are not reflected on screen

2. What should have happened instead? - Colours should change. (all other colour changes work)

3. Steps to reproduce the issue? - Change colour codes in [custom_tab_color_settings.css]

4. SCREENSHOTS with/without this projects files (drag & drop images into this post) -n/a

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]): - custom_css_for_fx_v3.2.4
- OS & OS version: Win 8.1
- OS theme (if not default): default
- DPI / HiDPI resolution: 1920 x 1200
- Firefox version: 89
- Firefox theme / lw-theme: Apple Look Stainless Steel 2.0
- Proton enabled (yes / no): no, as I'm not sure how to enable it. 
- This projects 'settings' the issue occurs with: ?

**Comment by Aris-t2** [comment]
This preference was made for the default tabs of Fx 57-88.

I will look into it.

**Comment by Aris-t2** [comment]
Actually it works for me:

![image](https://user-images.githubusercontent.com/6013569/121221422-d4b88480-c885-11eb-96a4-e4d619ab8011.png)

**Comment by BigShultzy** [comment]
I will check all the changes I've made in userChrome to see if they make any difference.

**Comment by BigShultzy** [comment]
I loaded a fresh copy of [custom_tab_color_settings.css] and changed the colour and its all working now.
Thanks for your help.
