### ISSUE TITLE
CTR + Waterfox

### ISSUE THREAD

**Issue by xlovinglyx** [Aris-t2/CustomCSSforFx#378]
I can't upgrade pale moon 29.1.1 x64 because their admins decided to dump legacy support,
So installed waterfox legacy. But i'm facing issues & can't find the code to adjust that, if anyone
could provide me a code i could adapt by changing numeric values, that would help me a lot.
I'm on win7 x64.

In that first picture, i applied one of Aris css's to put tabs at bottom .. .

I'd like the fixes in css below in red:
1) removing the gap before tabs.
2) removing that virtual empty toolbar totally unneeded. 
3) removing the restart button from "inside the url bar on the far right.

![1](https://user-images.githubusercontent.com/53103638/121282337-99e03c00-c8d9-11eb-8aef-d076e5c21239.png)

Here's the perfect look in pale moon:
![2](https://user-images.githubusercontent.com/53103638/121254382-7520a000-c8aa-11eb-9805-0c04f3410207.png)

**Comment by Aris-t2** [comment]
Doesn't `Classic Theme Restorer` add-on still work with Waterfox Classic? CSS code provided on this project is not meant for Waterfox Classic. The mentioned CTR however should remove those mentioned line and space automatically in "tabs not on top" mode when using lw-themes.

1 

```css
#TabsToolbar .titlebar-spacer[type="pre-tabs"],
#TabsToolbar .titlebar-spacer[type="post-tabs"] {
  display: none !important;
}
```

2
You have to inspect the code using developer tools to find what causes this. I don't have Waterfox installed.

3
Do you really mean a restart button inside the urlbar? I know there is a reload/stop/go button there. Those you can remove.

```css
#reload-button, #stop-button,#urlbar-go-button{
  display: none !important;
}
```

**Comment by xlovinglyx** [comment]
Thanks for the removal of reload from the url bar, now i can add it as a custom button on the bar but i don't get the stop
button yet (reload/stop) in one button, interactive.

Also, i tried your latest ctr & i can't get link status redux inside the addon bar.. that worked in palemoon cause
that addon bar was part of the code ((

**Comment by xlovinglyx** [comment]
Ps: i finally fixed that stupid gab introduced by a style i had for palemoon, one of palemoon updates had changed
the position of tabs & i had this activated:

.urlbar-input-box, .ac-title, .ac-url-text {margin-left: 5px !important;}
#urlbar { min-height: 29px !important; }

#browser-bottombox { min-height: 23px !important; }
#addon-bar { min-height: 21px !important; }

I finally got rid of it.

**Comment by xlovinglyx** [comment]
I have to fix the centering of text in tabs now

**Comment by xlovinglyx** [comment]
& to replace the ugly waterfox icon, i tried this in stylem cause ctr doesn't provide a way to give our own icon,
& it didn't work either:


titlebar-buttonbox:url(data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHSZP/90mT//dJk//3SZP/90mT//dJk//3SZP/90mT//AAAAAAAAAAAAAAAAAAAAAAAAAAD+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4/wAAAAAAAAAAAAAAAAAAAAAAAAAAcsAA/3LAAP9ywAD//sS4//7EuP90mT//csAA/3LAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcsAA//7EuP/+xLj/dJk//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h77it4U2CAP9XkwD/V5MA/09oK//vuK3h77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h3t7e/9ra2v/X19f/1NTU/9HR0f/Ozs7/zMzM/8rKyv/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA77it4eHh4f+ZMS//lCUh/58hHv+9QzP/y1lH/8lWQP/MzMz/77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHk5OT/nDEn/5wXCv+sDwD/0lhG/+mCcf/ldV7/zs7O/++4reEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h5+fn/6dBOP+oEwP/xRsC/+2Lef/6r6H/+qWS/9HR0f/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA77it4enp6f+rKBr/wRQA/+Y3HP/+xLj//9vR//7Vx//U1NT/77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHr6+v/tBsU/9cUB//4V0H//tO///3Tvf/7ybD/19fX/++4reEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h7e3t/+vr6//p6en/5+fn/+Tk5P/h4eH/3t7e/9ra2v/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHvuK3h77it4e+4reHvuK3h77it4e+4reHvuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAPAPAACAAQAA8A8AAPw/AADwDwAA4AcAAOAHAADgBwAA4AcAAOAHAADgBwAA4AcAAPAPAAD//wAA//8AAA==) !important; }

#titlebar-buttonbox .titlebar-button .toolbarbutton-icon:url(data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHSZP/90mT//dJk//3SZP/90mT//dJk//3SZP/90mT//AAAAAAAAAAAAAAAAAAAAAAAAAAD+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4/wAAAAAAAAAAAAAAAAAAAAAAAAAAcsAA/3LAAP9ywAD//sS4//7EuP90mT//csAA/3LAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcsAA//7EuP/+xLj/dJk//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h77it4U2CAP9XkwD/V5MA/09oK//vuK3h77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h3t7e/9ra2v/X19f/1NTU/9HR0f/Ozs7/zMzM/8rKyv/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA77it4eHh4f+ZMS//lCUh/58hHv+9QzP/y1lH/8lWQP/MzMz/77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHk5OT/nDEn/5wXCv+sDwD/0lhG/+mCcf/ldV7/zs7O/++4reEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h5+fn/6dBOP+oEwP/xRsC/+2Lef/6r6H/+qWS/9HR0f/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA77it4enp6f+rKBr/wRQA/+Y3HP/+xLj//9vR//7Vx//U1NT/77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHr6+v/tBsU/9cUB//4V0H//tO///3Tvf/7ybD/19fX/++4reEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h7e3t/+vr6//p6en/5+fn/+Tk5P/h4eH/3t7e/9ra2v/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHvuK3h77it4e+4reHvuK3h77it4e+4reHvuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAPAPAACAAQAA8A8AAPw/AADwDwAA4AcAAOAHAADgBwAA4AcAAOAHAADgBwAA4AcAAPAPAAD//wAA//8AAA==) !important; }

#​titlebar-buttonbox .titlebar-button { list-style-image:url(data:image/png;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHSZP/90mT//dJk//3SZP/90mT//dJk//3SZP/90mT//AAAAAAAAAAAAAAAAAAAAAAAAAAD+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4//7EuP/+xLj//sS4/wAAAAAAAAAAAAAAAAAAAAAAAAAAcsAA/3LAAP9ywAD//sS4//7EuP90mT//csAA/3LAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcsAA//7EuP/+xLj/dJk//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h77it4U2CAP9XkwD/V5MA/09oK//vuK3h77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h3t7e/9ra2v/X19f/1NTU/9HR0f/Ozs7/zMzM/8rKyv/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA77it4eHh4f+ZMS//lCUh/58hHv+9QzP/y1lH/8lWQP/MzMz/77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHk5OT/nDEn/5wXCv+sDwD/0lhG/+mCcf/ldV7/zs7O/++4reEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h5+fn/6dBOP+oEwP/xRsC/+2Lef/6r6H/+qWS/9HR0f/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA77it4enp6f+rKBr/wRQA/+Y3HP/+xLj//9vR//7Vx//U1NT/77it4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHr6+v/tBsU/9cUB//4V0H//tO///3Tvf/7ybD/19fX/++4reEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvuK3h7e3t/+vr6//p6en/5+fn/+Tk5P/h4eH/3t7e/9ra2v/vuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO+4reHvuK3h77it4e+4reHvuK3h77it4e+4reHvuK3hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAPAPAACAAQAA8A8AAPw/AADwDwAA4AcAAOAHAADgBwAA4AcAAOAHAADgBwAA4AcAAPAPAAD//wAA//8AAA==) !important }

**Comment by Aris-t2** [comment]
Sorry, I do not use Waterfox, Palemoon, Basilisk and there is no support for CTR anymore. It was discontinued years ago.

CTR offers its own add-on bar incl. a "status item". Inside it add-ons used to place own items. If this does not work, you might want to reset your toolbar configuration and check, if that "status item" is somewhere to find in customizing mode.
If an add-on does not not add its content to that "status item", CTR can not do anything about it.

CTR did not modify back and forward buttons history popups. If a browser does not offer something another one did, CTR can not do anything about it.

CTRs add-onbar. Reduce margins and paddings using this code:
```css
#ctraddon_addon-bar * {
  padding: 0 !important;
  margin: 0 !important;
}
```

You can not replace browser icon on system level using CSS.
CTR allows you to use different icons inside main menu button.

**Comment by Janaue** [comment]
> r admins decided to dump legacy support,
> So installed waterfox legacy. But i'm facing issues

for PM, you can install https://github.com/JustOff/moon-tester-tool to install any addon

**Comment by Aris-t2** [comment]
This can be closed now, right?
