### ISSUE TITLE
SVG Strata Forward/Back Buttons

### ISSUE THREAD

**Issue by ChthonVII** [Aris-t2/CustomCSSforFx#379]
Here's an SVG of the strata forward/back buttons. (I renamed it to .svg.txt so github would upload it.) Looks good at 4K where the classic .png starts to get pixelated. Perhaps this can be custom_backforward_large_ff3_strata_v2?

I know this isn't an "issue," but it's too much of a hassle to clone the repo to make a single pull request. Sorry for githubbing wrong.

[bf_ff3_strataSVG.svg.txt](https://github.com/Aris-t2/CustomCSSforFx/files/6623345/bf_ff3_strataSVG.svg.txt)

**Comment by Aris-t2** [comment]
Thanks.

Already included in latest pre builds.

**Comment by Aris-t2** [comment]
Its not part of 3.2.5 release.
