### ISSUE TITLE
Making each tab a different color in FF 57

### ISSUE THREAD

**Issue by fiesata** [Aris-t2/CustomCSSforFx#38]
Hi Newbie here I've always relied on extensions and some about/;config tweaks to customize  Firefox 
Have managed to move tabs to bottom with bookmarks toolbar directly above

Could anyone provide the code to make each tab a different color as per colorful tabs extension for  Firefox 56 and before this will help my wife who has a vision problem 

Many thanks

**Comment by Aris-t2** [comment]
You can set different tab colors for active, default, hovered, unloaded, unread tabs and new tab / hovered new tab inside already present "custom_colors_for_squared_tabs.css" file.

Colorfultabs generated colors randomly with JavaScript, but CSS can't do that.
