### ISSUE TITLE
ctr add-on bar - my theme doesn't appear on it ?

### ISSUE THREAD

**Issue by xlovinglyx** [Aris-t2/CustomCSSforFx#382]
Is there a way to make it happen ? instead of having that plain light blue static color ?

**Comment by xlovinglyx** [comment]
it doesn't even appear on the find bar ((

**Comment by Aris-t2** [comment]
If a theme does not offer bottom image, it does not appear there.

Most recent themes only offer top images.

An by the way, this is not a support area for CTR.
