### ISSUE TITLE
Strange

### ISSUE THREAD

**Issue by xlovinglyx** [Aris-t2/CustomCSSforFx#383]
When back & forward buttons are populated & have been visited, whenever i right click on 
any of those buttons, the history part of the other button disappears & the list jumps to its new place.
I wish nothing jumped, & the bold actual link wouldn't appear either..

This never happened on palemoon (the aero background & green button appears on hovering only if i want to select it);

![x](https://user-images.githubusercontent.com/53103638/121784747-013a0c80-cbb6-11eb-8f81-14913b2fad52.png)

If i click on the back button now on waterfox, with ctr tweaks, i get those two images in half a second to a second of time,
& the links from the other forward button disappear:

![X1](https://user-images.githubusercontent.com/53103638/121784771-2f1f5100-cbb6-11eb-8f70-3f10f9167abc.png)

![X2](https://user-images.githubusercontent.com/53103638/121784774-32b2d800-cbb6-11eb-859e-acdc9a198ed0.png)

**Comment by Aris-t2** [comment]
There is no more support for CTR.
