### ISSUE TITLE
Ubo icon not centered in CTR addon-bar ((

### ISSUE THREAD

**Issue by xlovinglyx** [Aris-t2/CustomCSSforFx#384]
"Waterfox Legacy" V2021.06 + ublock origin v1.16.4.28

Hi,

With Classic Theme Restorer extention to obtain a bottom addon-bar,
there's a strange gap between The fish icon "Unplug extention" &
when pages are blocked the numbers appear behind "S3 translator icon (last one).

![x](https://user-images.githubusercontent.com/53103638/121764839-32c7bf00-cb47-11eb-9cdd-ccc2303903b7.png)

Could you provide me a css to slide ubo a little bit to the left,  & i'll tweak the value
to center it.

Thanks

**Comment by Aris-t2** [comment]
There is no more support for CTR.
