### ISSUE TITLE
Hotkeys not visible in the menu

### ISSUE THREAD

**Issue by milink** [Aris-t2/CustomCSSforFx#390]
I have activated the following options

@import "./css/buttons/buttons_on_navbar_windows_classic_theme_appearance.css"; /**/
@import "./css/buttons/icons_custom_icons_fx45.css"; /**/

and since Firefox v 89 I cannot see hotkey in the menu:
![obrazek](https://user-images.githubusercontent.com/1407696/122539377-d291bb00-d027-11eb-871b-f875e1975288.png)

**Comment by Aris-t2** [comment]
Are you sure this is caused by this projects files? The is no "option", that intentionally changes main menu buttons popup width.

How does the menu look without this projects files?

**Comment by milink** [comment]
I seems that it is related to Proton changes. Without custom chrome it look like this:

![obrazek](https://user-images.githubusercontent.com/1407696/122584194-59f82200-d05a-11eb-984d-fc329c8e5f09.png)

but as soon as I disable proton - browser.proton.enabled=true I get this:

![obrazek](https://user-images.githubusercontent.com/1407696/122584345-8ca21a80-d05a-11eb-9081-39d329b1dc6b.png)

Does it mean I have to wait if Mozilla correct this?

**Comment by Aris-t2** [comment]
I doubt Mozilla will correct this. Proton will be active by default in Fx91+ without the possibility to disable it.
