### ISSUE TITLE
[Win7 Aero][v3.2.8] Custom Tab Appearance not showing title text in unselected tabs

### ISSUE THREAD

**Issue by Silver-Nebula** [Aris-t2/CustomCSSforFx#391]
`/************************************************************************************************/`
`/* TABS - appearance and position ***************************************************************/`
`/************************************************************************************************/`
` `
`/* custom tab appearance - [only use one at a time] *********************************************/`
`@import "./css/tabs/classic_squared_tabs.css"; /**/`
`/* @import "./css/tabs/classic_squared_tabs_australized.css"; /**/`
`/* @import "./css/tabs/default_tabs_enhanced.css"; /**/ /* Fx89+ & Proton UI */`

The above is the default setting. If using either of the other two settings, the title text on unselected tabs becomes invisible.

Noticed this bug when switching from v3.2.1v2 to v3.2.8. Not sure when it was introduced.

**Comment by Aris-t2** [comment]
What theme?
Post a screenshot of your window.

**Comment by Aris-t2** [comment]
Since there was no response, I will close this one.

**Comment by Silver-Nebula** [comment]
System Theme 1.2. 

Screenshot below showing the Google and Twitter tabs with blank title text in the tab.

![Screenshot](https://user-images.githubusercontent.com/86513103/125878226-254021e5-9b58-4994-aae7-51c3da50ed10.jpg)

Changing to other theme fixes it. This problem is still present in 3.3.1.

**Comment by Aris-t2** [comment]
Does this happen with default OS theme too?

What options/code are you using to move tabs below navigation toolbar?

**Comment by Silver-Nebula** [comment]
> 
> 
> Does this happen with default OS theme too?
> 
> What options/code are you using to move tabs below navigation toolbar?

Default OS theme? Haven't messed with the OS, though this is happening on a Win7 machine.

For the code, it's in my original post where I pasted the section of concern. Anything besides the default option will cause the issue.

**Comment by Aris-t2** [comment]
Firefox 90 + Win7 Aero Glass + v.4.0.0pre

**classic_squared_tabs.css + tabs_below_navigation_toolbar.css**
![image](https://user-images.githubusercontent.com/6013569/126060775-e6a1a403-bc44-48dd-8c45-1ef4ce1b4cf8.png)

**classic_squared_tabs_australized.css + tabs_below_navigation_toolbar.css**
![image](https://user-images.githubusercontent.com/6013569/126060786-6f157459-2325-4b05-b5dd-418802d5844d.png)

**default_tabs_enhanced.css + tabs_below_navigation_toolbar.css**
![image](https://user-images.githubusercontent.com/6013569/126060798-4dadd897-55b9-4cac-b9d2-0cd6e045f550.png)

Test latest release of this projects files.

**Comment by Silver-Nebula** [comment]
Do I need to re-enable proton switches in about:config for this particular test with v4.0.0 pre?

**Comment by Aris-t2** [comment]
Yes

**Comment by Silver-Nebula** [comment]
Works but only when browser.proton.enabled=true. If false, tab title text is empty again.

Not a fan of how proton turns my URL and search bars from white to gray though...

**Comment by Aris-t2** [comment]
I totally forgot this, but Win 7 Aero mode did not offer dark tab text for inactive tabs, because top toolbars used a dark background color. With Proton this changed. Once Firefox 91 will be released Proton will stay, so keeping those switches already active might make sense. For the time being you can use this and disabled Proton.

```css
.tab-label {
  color: black !important;
}
```
