### ISSUE TITLE
Make tabs audio mute button always visible again (regression)

### ISSUE THREAD

**Issue by CoSoCo** [Aris-t2/CustomCSSforFx#392]
1. Describe the issue
Since some weeks I'm missing to see the audio mute button in tabs, it is only visible on mouse hover. I guess, this is since Proton.
As I'm using multi row tabs it is a big problem to find the tab, where the audio is coming from, as I have to hoover over all tabs in all rows.

2. What should have happened instead?
Please make tabs audio mute button always visible again.

3. Steps to reproduce the issue?
Nothing special.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
Please ask, if my explanation above is not enough

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]): yes
- OS & OS version:  Ubuntu 20.04
- OS theme (if not default): Unity desktop
- DPI / HiDPI resolution: 1680 x 1050
- Firefox version: 89.+
- Firefox theme / lw-theme: default
- Proton enabled (yes / no): I think so, I have nothing changed from distribution delivery state.
- This projects 'settings' the issue occurs with: multi row tabs + tabs below location bar

**Comment by Aris-t2** [comment]
That feature never was part of this projects files.

**Comment by CoSoCo** [comment]
So it was a feature of Firefox before V 89, and now it is gone.
Would you mind, to add this feature to you project please?

**Comment by RafalRambo** [comment]
@CoSoCo 
I have this scripts from @Speravir
Make file "my_userChrome.css" in Chrome folder and paste this script,
I dont't use multi row tabs and I don't know if it will work with that , you must check.

```
.tab-icon-stack:is([muted],[soundplaying],[activemedia-blocked]){
	grid-template-areas: "a s";
}
.tab-icon-overlay:is([muted],[soundplaying],[activemedia-blocked]){ grid-area: s; }
/*.tab-icon-overlay,.tab-icon-image{ opacity: 1 !important; }*/
.tab-icon-overlay {
	padding: 0 !important;
}
.tab-icon-overlay:hover {
	background: none !important;
}
.tab-icon-stack:is([soundplaying], [muted], [activemedia-blocked]) > * {
	opacity: 1 !important;
}
.tab-icon-overlay[soundplaying] {
	fill: #058B00 !important;/* var(--green-70) */
}
.tab-icon-overlay[muted] {
	fill: #D70022 !important;/* var(--red-60) */
}
.tab-icon-overlay[activemedia-blocked] {
	fill: #FFE900 !important;/* var(--yellow-50) */
}
```

**Comment by Speravir** [comment]
Just for reference:
> I have this scripts from @Speravir

See [my comment in #368](https://github.com/Aris-t2/CustomCSSforFx/issues/368#issuecomment-859216327).

**Comment by Aris-t2** [comment]
Added Speravirs solution to current release: https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by CoSoCo** [comment]
Thanks for the solution. It works as expected.
I think, you should mention the new `tab_audio_icon_fx89` to the lost of new features in the description of v3.2.9 release.
Additionally I would very much appreciate, if you would too add a variant with the coloured icons from @Speravir .

**Comment by Aris-t2** [comment]
3.3.0 will offer the mentioned colors for tab audio icon.
