### ISSUE TITLE
FF 91.0a1 - close tab and bookmarks not displayed

### ISSUE THREAD

**Issue by Marcosdw** [Aris-t2/CustomCSSforFx#393]
Hello,
See screenshots
Firefox 91a (2021-07-06)
CustomCSSforFx : 3.2.8

![Capture d’écran 2021-07-07 174021](https://user-images.githubusercontent.com/18121470/124789571-b3ad8700-df4a-11eb-8454-6d542bd52bc4.png)

![Capture d’écran 2021-07-07 093713](https://user-images.githubusercontent.com/18121470/124720223-352ff580-df08-11eb-882f-f68ed3f5e99e.png)

Sorry, I'm using Google Translator French / English

**Comment by Aris-t2** [comment]
I don't know which combination of settings and code you are using, but the default setup looks fine in my tests on Nightly.

![image](https://user-images.githubusercontent.com/6013569/124897021-316ea280-dfde-11eb-88fd-818936a0d2e4.png)

**Comment by Marcosdw** [comment]
@Aris-t2
close tab
browser.proton.enabled true or false?

On 91.0a1 (2021-07-08) 
browser.proton.enabled true or false
icon not displayed default setup
![Capture d’écran 2021-07-09 124242](https://user-images.githubusercontent.com/18121470/125066632-80d2d280-e0b3-11eb-94da-096175c67e61.png)

**Comment by Aris-t2** [comment]
This project does not restore appmenus icons (yet).

The initial question was about close tab icon and bookmarks, right?

browser.proton.enabled > true

**Comment by Marcosdw** [comment]
@Aris-t2 

Close icon tab displayed on 89.0.2 browser.proton.enabled > false
Close icon tab not displayed on 91.0a1 (2021-07-08)  browser.proton.enabled > false

Does Mozilla still changed parameters between 89 and 91?  

_Sorry, I'm using Google Translator French / English_

**Comment by Aris-t2** [comment]
Appmenu icons are now present with latest release: https://github.com/Aris-t2/CustomCSSforFx/releases

Make sure you have `browser.proton.enabled` set to `true` and all of this projects `close icons` settings (temporarily) disabled.

**Comment by Marcosdw** [comment]
Work fine
thank you ;)

**Comment by VcSaJen** [comment]
> I don't know which combination of settings and code you are using, but the default setup looks fine in my tests on Nightly.

Those "x" icons look too big for my taste (it wasn't like that in prev version). Is there a way to restore classic size of "x" icons?

**Comment by Aris-t2** [comment]
You were right about the default close icon size. 
Recent releases solve this issue..
