### ISSUE TITLE
Scroll bar width

### ISSUE THREAD

**Issue by canDry** [Aris-t2/CustomCSSforFx#394]
Before 89 there was a tweak that increased the width of the extremely narrow ff window scrollbar: 

`#toolbar-menubar[autohide="true"] ~ #TabsToolbar {padding-right: 100px !important;}
`
Does anyone have a tweak to increase the width?

Hoping this is the right forum to ask!

**Comment by Aris-t2** [comment]
You can not change scrollbar width value using plain CSS, but there are some tweaks one can do with CSS:
https://github.com/Aris-t2/CustomCSSforFx/issues/160

Not sure why your code targets #TabToolbar node, but the only time a scrollbar appears there, is when you are using multiple tab lines. This project files use a thin scrollbar there: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_multiple_lines_fx81.css#L41
