### ISSUE TITLE
Unable to open the zip file using Macintosh Archive Utility App

### ISSUE THREAD

**Issue by TW462** [Aris-t2/CustomCSSforFx#396]
1. Describe the issue
Unable to open the zip file using Macintosh Archive Utility App. It also had the same issue with 3.2.9 FYI.

2. What should have happened instead?
It should open the zip file and the folders and files within the zip files expand and are shown and editable

3. Steps to reproduce the issue?
Save the zip file to my download folder and expand the files and folders within the zip file

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![Screen Shot 2021-07-14 at 11 30 53 AM](https://user-images.githubusercontent.com/77515829/125675080-6cfa17b5-e060-48ac-b685-1d4726d1c07c.png)

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]): yes 3.3.0
- OS & OS version: Macintosh Big Sur & 11.4
- OS theme (if not default): 
- DPI / HiDPI resolution: 1680 x 1050
- Firefox version: 90
- Firefox theme / lw-theme: Default theme
- Proton enabled (yes / no): yes
- This projects 'settings' the issue occurs with:

**Comment by hopalongrock** [comment]
Similarly I can't extract on Windows 10 with unzip 6.0

I get similar messages for all files:
skipping: config/color_variables.css  need PK compat. v6.3 (can do v4.6)

I can extract with 7z.

This error appears since the version custom_css_for_fx_v3.2.9.zip, as I remember.

**Comment by Aris-t2** [comment]
I replaced the files with a less heavy zip compression offered by 7zip.
