### ISSUE TITLE
CustomCSSforFx v4.0.0 & what's next? The future of CustomCSSforFx

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#398]
This version is going to offer major changes as suggested by Speravir a while ago.

The main target will be Firefox 91, but all of this projects 'options' should work with Firefox 89 and 90 too, if all "Proton" switches are active inside about:config area.

**Phase I - old settings**
- Removal of all settings not compatible with Firefox 89-91+.
- Renaming remaining settings, so there won't be any _fx65, _fx75, _fx89 at least for a while.

**Phase II - code cleanup**
- Removal of unneeded code parts (I know there are still many very old code snippets inside this project)
- Replacing deprecated or unneeded rules/names with current ones (e.g. :-maz-any > :is, @media (-moz-proton) etc.)

**Phase III - getting ready**
- Testing
- Fixing

<strike>_For a while I will try to keep v4.0.0preX and v3.x.x in sync when it comes to fixes._</strike>
v4.0.0 is almost ready to replace v3.x.x builds.

Everybody can start using v4.0.0pre builds right away. Keep in mind most **settings will have to be reconfigured**, because option and file names got changed (and might still change with upcoming builds).

**_Do not use this on Firefox89/90, if Proton switches inside about:config are disabled._**

**Comment by Aris-t2** [comment]
Please test "[v4.0.0pre8](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.0.0pre)" and report, if something is not working, that did work in **v4.0.0pre7**.

Thanks in advance.

**Comment by GaVenga** [comment]
Wie bekomme ich das besser hin / How do I do it better:

![FF_2021-07-31 15-06-07](https://user-images.githubusercontent.com/49439346/127740879-4bdb8a61-3221-4221-ade7-78de3c2290ef.png)

**Comment by rebop** [comment]
I have not used Firefox since 56. I am now. I do not know what Proton is nor what switches nor why I want to do that. Can you point me to answers?

**Comment by Aris-t2** [comment]
@GaVenga 

It should look more like this:

![image](https://user-images.githubusercontent.com/6013569/128644919-59fd5656-8f36-4489-8b35-18702b82c7a8.png)

@rebop 

Mozilla uses "code" names for new Firefox designs:
Fx 29 - Australis
Fx 57 - Quantum
Fx 89 - Proton

For a few Firefox versions there are switches to revert those changes. Firefox 91 won't allow the corresponding switches ( still available in Fx 89 and 90) to revert "Proton" ui. If you have a clean new Fx89+ setup, you don't have to worry about Proton as v4.0.0 is ready for it.

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/issues/403

**Comment by rebop** [comment]
Thanks @Aris-t2. I am still playing with new FF to understand. I installed (wrong term :) Portable 88. It updated to 90.1. I am not seeing anything so different I would call it a new design. Can I check if it is disabled? And if it is not disabled and I go this route (likely), am I understanding that 4.0 will make the new FF Proton as if it were still an older version?

Once I understand  all the things on 3.2.2.1 (and go through your reply to me there - have not had time) I'll find time to start a clean install with 4.0 and hope I can get something that works for the future. I'll also want to see if there is an ESR version so if I do go that way, I will have some peace for a while.

Thanks.

**Comment by Aris-t2** [comment]
You don't see a "big" difference, because you are using this projects files.

Without the CSS inside chrome folder you get this:

Fx 88
![image](https://user-images.githubusercontent.com/6013569/128691685-8f77436d-0c95-4824-ba06-cc07228e8092.png)


Fx 90
![image](https://user-images.githubusercontent.com/6013569/128691701-5db6aaf5-2039-4a3e-8c88-816d4cc24982.png)


Also compare context menus, font sizes, icons etc.
