### ISSUE TITLE
Something wrong with compact menus 

### ISSUE THREAD

**Issue by Marvinoo** [Aris-t2/CustomCSSforFx#399]
**1. Describe the issue**
When I use [compact_menus_proton.css](https://github.com/Aris-t2/CustomCSSforFx/blob/master/fx60-90/css/generalui/compact_menus_proton.css), everything look as intended but the 'More tools' menu / _Browser Tools_ looks this weird > 

![image](https://user-images.githubusercontent.com/45720537/126037358-40af2090-91b0-4653-b551-feebec2ffcb2.png)

**2. What should have happened instead?**
It should look normal & compact like the parent menu >
![image](https://user-images.githubusercontent.com/45720537/126037597-cef33a95-629d-4a03-8a69-6cf0f211a99b.png)

5. System information
- latest CustomCSSforFx files (yes )
- Latest Windows 10 
- OS theme (if not default): 
- DPI / HiDPI resolution: 
- Firefox version: 91.0b3
- Firefox theme / lw-theme: Default Light 
- Proton enabled (yes / no): yes
- This projects 'settings' the issue occurs with:

**Comment by Aris-t2** [comment]
Try to disable whatever CSS you are using a test the most recent 4.0.0pre build.

![image](https://user-images.githubusercontent.com/6013569/126057981-540b8fb8-956f-4341-9cce-c92f97e3352d.png)
![image](https://user-images.githubusercontent.com/6013569/126058001-c86fc21f-4a6c-498f-9171-7f7328bcb58c.png)
