### ISSUE TITLE
Firefox 90 + CSS 3.3.2.1 Issues

### ISSUE THREAD

**Issue by rebop** [Aris-t2/CustomCSSforFx#401]
AS I mentioned in previous thread, I have undertaken redoing ALL my settings with your latest version. I do not know how anyone else does it, but it takes MANY hours for me to go through everything. If I had to guess, I have 8 hours into it now and was making great progress. I even fixed the tabs on bottom text and all tabs icon lowered, but cannot tell you exactly how :)

I am 2/3rds done and noticed the back button has stopped working! It definitely was working do some change today broke it. Forward works, back right click works. But the button while "lit" does nothing while pressed. At my wits end looking for why.

Would really appreciate help.

At this moment, only one other issue, but not done yet so will wait to see if anything more pops up. This is mission critical.

Thanks.

1. Describe the issue
Back button does nothing when pressed. Right click functions work.

2. What should have happened instead?
Returned to previous page

3. Steps to reproduce the issue?
Happens on any page

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]): yes
- OS & OS version: Win 7 final
- Firefox version: 90
- Firefox theme / lw-theme: 
- Proton enabled (yes / no): ??
- This projects 'settings' the issue occurs with:  Happy to supply anything you like. Does not seem to be my_userChrom nor userContent

**Comment by rebop** [comment]
OK, as usual, I post and I find something :) This is what is breaking it and this is code I got from you Aris a few generations ago. It was working until I changed something in userChrome. If you have ideas, please let me know. The "other" issue I alluded to is getting my forward back to look like they did in previous versions.

Thanks.

 #main-window:not([uidensity=compact]) #nav-bar #back-button + #forward-button::before,
#main-window:not([uidensity=compact]) #nav-bar #back-button + #forward-button:not([disabled="true"])::before,
#main-window:not([uidensity=compact]) #nav-bar #back-button + #forward-button[disabled="true"]::before {
  display: block !important;
  content: "" !important;
  width: 32px !important;
  height: 22px !important;
  -moz-margin-start: -28px !important;
  -moz-margin-end: -9px !important;
  border-radius: 10000px !important;
  position: relative !important;
}

**Comment by rebop** [comment]
Got it :) Time for sleep. Back when I am done. Configuring for new build.

Not sure how the above ever worked, but it did!

**Comment by Aris-t2** [comment]
I would suggest to use the latest v4.0.0 (pre 10) to rebuild your configuration. There are changes in almost every file and v4.0.0 will replace current 3.x.x in a few days just before Firefox 91 release.

**Comment by rebop** [comment]
Thanks. But I am so far into  this version I cannot stop now :( I have to
finish or be lost forever. Hope that makes sense.
 
Really, that many changes? It is so hard to redo when you version. Must be
an easier way.

  _____

**Comment by Aris-t2** [comment]
Switching between updates usually is no big deal, but one has to keep up with the releases.

V4 is a major rework of this projects files to match recent code updates. Additionally I followed a suggestion to drop everything not compatible with Firefox 91+, replace deprecated CSS rules and clean up some outdated code present in this project. Some of it is still from a pre-Fx 56 and 29 era.


You can read about this on releases page inside the v4.0.0 pre release.
