### ISSUE TITLE
[Regression bug] Container indicators clipping into bookmark bar

### ISSUE THREAD

**Issue by vaporwave9** [Aris-t2/CustomCSSforFx#402]
1. Describe the issue

![grafik](https://user-images.githubusercontent.com/64961250/128637393-d8286f2b-207a-43bb-9ce2-9b5bcc4d6922.png)
```
@import "./css/locationbar/megabar_expanding_breakout_disabled.css";
@import "./css/tabs/tabs_below_navigation_toolbar.css";
```

Please support the extra space needed by Firefox container indicators, such as used in:
https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

The colour coded strips are clipping into the bookmarks section.

2. What should have happened instead?

![grafik](https://user-images.githubusercontent.com/64961250/128637449-7b652233-20db-4408-8b51-3b6aad8a91ab.png)
```
@import "./css/locationbar/megabar_expanding_breakout_disabled.css";
@import "./css/tabs/tabs_below_navigation_toolbar_fx65_v2.css";
```
Worked fine before, hence I'm filing this as regression bug.

3. Steps to reproduce the issue?
Upgrade from previous CustomCSSforFx to 4.0.0pre10.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)

See above, I don't want to break my text flow.

5. System information
- latest CustomCSSforFx files: yes, 4.0.0pre10
- OS & OS version: Win 10 Pro 21H1
- OS theme: default
- DPI / HiDPI resolution: no
- Firefox version:  91.x
- Firefox theme / lw-theme: dark, compact
- Proton enabled: yes, it is required for colour bars to show at all
- This projects 'settings' the issue occurs with: unclear what is being asked

**Comment by Aris-t2** [comment]
I think you imported the wrong file.

Using "default tabs" you have to import `tabs_below_navigation_toolbar_defaults_tabs.css`.

(default config)
![image](https://user-images.githubusercontent.com/6013569/128640212-2276d5aa-9cde-4593-8378-0f386b78ca83.png)

(`tabs_below_navigation_toolbar_defaults_tabs.css` only)
![image](https://user-images.githubusercontent.com/6013569/128640262-49af37e3-af9f-40e8-b25f-9ab45c98c354.png)

**Comment by vaporwave9** [comment]
Yes you are correct!
I noticed the version numbers were gone from the nomenclature, but not that there was now a distinction between default tabs and whatever the other option does.
From your screenshots it seems to reduce toolbar size, which cause my problems.
Thank you, I will use the "try & error" method more carefully in the future before I open issues.
