### ISSUE TITLE
Tabs Too Tall, Overlapping Bookmarks, on HiDPI Monitor

### ISSUE THREAD

**Issue by ChthonVII** [Aris-t2/CustomCSSforFx#405]
1. Describe the issue
Tabs are way too tall with hidpi monitor. If set below nav bar, significantly overlap bookmarks.

2. What should have happened instead?
Tabs should be normal height, shouldn't overlap stuff.

3. Steps to reproduce the issue?
Upgrade to v 4.0.

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
![fubartabs4k](https://user-images.githubusercontent.com/19508863/129061644-8ff7bdf2-d9af-4053-8753-d2f28d8d60c4.jpeg)

5. System information
- latest CustomCSSforFx files (yes / no [support only for latest files]): yes
- OS & OS version: Linux, Debian stable
- OS theme (if not default): default
- DPI / HiDPI resolution: 4k, layout.css.devPixelsPerPx=1.6
- Firefox version: 91
- Firefox theme / lw-theme: default 
- Proton enabled (yes / no): yes
- This projects 'settings' the issue occurs with: seems to be anything

6. Other
Alignment issues with tabs below nav bar has been an ongoing thing, but this is a bigger usability problem than usual. In the past I've been able to dig around in the css and figure out what to tweak, but this time I'm stumped.
Tabs were very close to correct on my monitor out-of-the box with v3.24, if that's any help. (Looked like one extra pixel of space between bookmarks and tabs, not worth fixing.)

**Comment by Aris-t2** [comment]
Unfortunately I can not test such a configuration, sorry.

layout.css.devPixelsPerPx > 1.6 gives me a proper result (on Windows and Linux).

![image](https://user-images.githubusercontent.com/6013569/129064114-005d8664-e369-4ffb-b04e-211f3ceb8fd6.png)
![image](https://user-images.githubusercontent.com/6013569/129065194-b5f2ffc0-3670-47cd-8b12-056229b850c6.png)

Edit `tabs_below_navigation_toolbar.css` file and modify this block:

```css
#navigator-toolbox {
  position: relative;
  padding-bottom: calc( var(--tab-min-height_tnot) + 1px );
}
```

Change `padding-bottom: calc( var(--tab-min-height_tnot) + 1px );` to e.g. `padding-bottom: 50px !important;`.
Adjust `50px` to a more fitting value.

**Comment by Ransom77** [comment]
Hello Aris, hello guys,

I feel similar to ChthonVII.

But first, many thanks to Aris. With version 4.0.1 of CustomCSSforFx you have done an excellent job of getting around this idiotic “Proton” design.

I am one of those who managed to recreate the old FF3 Classic interface with CustomCSSforFx 3.2.0 until version FF90 – see here:

![Zwischenablage02](https://user-images.githubusercontent.com/66835201/129093360-97bc4c26-9f73-41d6-a19a-a82d7ec16b72.jpg)

With Aris’ new version CustomCSSforFx 4.0.1 and FF91 I almost manage – see here:

![Zwischenablage01](https://user-images.githubusercontent.com/66835201/129093411-f65f3ecd-4a93-4a64-939d-b0bbffb49f01.jpg)

What bothers me is the large cross as well as the higher tabs as well as the larger distances between the bookmarks. I have already activated or deactivated various entries in the userChrome.css, but had no success with it or only worsened the previous result.

With the almost good result, these settings have been changed from the downloaded original version of CustomCSSforFx 4.0.1.

Disabled:
@import "./config/general_variables.css";
@import "./config/color_variables.css";
@import "./css/buttons/buttons_on_navbar_classic_appearance.css";
@import "./css/buttons/icons_colorized.css";

Enabled:
@import "./config/color_variables_classic-grey.css";
@import "./css/buttons/icons_custom_icons_fx3.css";
@import "./css/buttons/custom_backforward_large_ff3.css";
@import "./css/tabs/tabs_below_navigation_toolbar.css";
@import "./css/generalui/close_icon_firefox3.css";

Greetings
Ransom77

**Comment by Ransom77** [comment]
Small addition:

For **layout.css.devPixelsPerPx** I have chosen the value **2.6**.

**Comment by Aris-t2** [comment]
Looks like the "close_icon_*" settings are not compatible with high layout.css.devPixelsPerPx values.

Please test this: [test.zip](https://github.com/Aris-t2/CustomCSSforFx/files/6971460/test.zip)

**Comment by ChthonVII** [comment]
test.zip solves the problem for me. Thank you for an amazing quick fix!

**Comment by Aris-t2** [comment]
Thanks for confirmation.

Next update will contain the fix.

**Comment by Ransom77** [comment]
test.zip has also solved (wonderfully) the problem with the large cross resp. the higher tabs  for me.

The thing with the bigger distances between the bookmarks I could solve by creating a my_userChrome.css and the corresponding code....

menupopup > menuitem,
menupopup > menu {
  padding-block: 0 !important;
}

Perfect work!

**Comment by Aris-t2** [comment]
4.0.2 is out.
We can close this now.
