### ISSUE TITLE
[SOLVED] Active Tab Button is bigger than the Tab line

### ISSUE THREAD

**Issue by speefak** [Aris-t2/CustomCSSforFx#406]
[solved] => https://github.com/Aris-t2/CustomCSSforFx/issues/406#issuecomment-903268401

Version : /ustomCSSforFx-master-1622645782

1. Active Tab Button is bigger than the Tab line

2. Active Tab button height was the same like the Tab Line

3. Update to FF 91

4. SCREENSHOTS with/without this projects files (drag & drop images into this post)
 https://postimg.cc/jwQ323wV

5. System information
FF 91 / CustomCSSforFx-master-1622645782

- OS & OS version: Debian 9
- OS theme (if not default): 
- DPI / HiDPI resolution: FHD
- Firefox version: 91.0
- Firefox theme / lw-theme: default
- Proton enabled (yes / no): no
- This projects 'settings' the issue occurs with: FF update to 91.0

**Comment by speefak** [comment]
https://speefak.spdns.de/mycloud/index.php/s/nFdakKQrdfDNYwJ

**Comment by Aris-t2** [comment]
If you are using default browser tabs, you have to use the corresponding tabs below navigation toolbar option `tabs_below_navigation_toolbar_default_tabs.css`. Is that the case?

**Comment by p1nkyy** [comment]
Need to enable Proton

**Comment by Aris-t2** [comment]
@speefak

Did it work?

**Comment by speefak** [comment]
Proton enabled - no change. 

I am not using default Browser Tabs. I changed the height value for the tabbar to save screenheight and get a smaler browser header. I dislike the trend to make GUIs touch compatible. Everything get bigger and the important things or centents gets smaller smaller. FF should offer a small theme / Interface - but they didnt do that so i modified the CSS files by try and error. With the last update the "value of selected tab" has changed. I searched the value using the FF Inspector ( F12 ) but i cant find it. So i have two options now : use the bigger tabbar ( active tab and tabbar = same height ) or live with the bigger active tab. If you have a tip where i can find the "active tab height value" this is the third option ;) 

At this point thanks to you for the great work of creation a customizeable FF GUI framework ;)

Screenhot : https://speefak.spdns.de/mycloud/index.php/s/cF7sWpEWrZfFgEe   ( upload on github doesnt work )

**Comment by speefak** [comment]
I got it ( due to very great documentation ) ;)

What i did to get the FF Header ( https://postimg.cc/VrjczFBp )

1. Load the latest Zip file : https://github.com/Aris-t2/CustomCSSforFx/archive/refs/heads/master.zip
2. enable all proton values in firefox config ( about:config => proton )
3. extract the content of the folder fx60-90 into the chrome directory
4. change / edit the ./image/folder-item.png file, replace window folder icon with OSX folder icons
5. change values in userChrome.css ( https://pastebin.com/5MYkiRib )

Issues:
1. moving tabs in tabline causes a temporary displacement while moving tab. When tabmoving is finished tabline looks fine again.
This is only affected when moving tabs, but for me it doesnt matter. If someone has a solution for this "bug" to get an "perfekt" configuration it will be fine - but not necessary. 

artis, do you have an CC address ( ADA/Cardano ) to spend some coins ? ;)

So thanks for Support and great work.

**Comment by Aris-t2** [comment]
> What i did to get the FF Header ( https://postimg.cc/VrjczFBp )

This result is also possible using files from "classic" folder (currently 4.0.3 release). "fx60-90" does not get any support since 4.x release.

> change values in userChrome.css ( https://pastebin.com/5MYkiRib )

I ported your setup to 4.0.3: https://pastebin.com/Zb4XXb7K
Test this one.

Report, if the issue is still present.

> aris, do you have an CC address ( ADA/Cardano ) to spend some coins ? ;)

I only have Paypal, see [Paypal me] link on main page: https://github.com/Aris-t2/CustomCSSforFx

**Comment by speefak** [comment]
I try to create a proton compact mode. The goal is to modify less as possible to avoid missconfiguration for further proton updates. 

where can i define the ...

... tabbar heigt ?
... the tab gab/distance ( want to reduce to 0 - no spacing between tabs )
... the tab size ( also pinned tabs ) 

https://postimg.cc/ZWTjPwrb

**Comment by Aris-t2** [comment]
Have you seen this?
https://github.com/Aris-t2/CustomCSSforFx/issues/334

**Comment by speefak** [comment]
Not Yet - but this is almost exactly for what i am searching for. 

when using proton compact mode ( standalone userChrome.css )  tabs are on top again. Change the FF compactmode switch by "browser.uidensity > 1" compresses the FF Header to my needs, custom Icons are shown, site favicon changes to loudspeacker when playing multimedia content.

I have only adjust the tabbar height in  "./css/tabs/tabs_below_navigation_toolbar_fx89.css"

from "--tab-min-height_tnot: 32px;" to "--tab-min-height_tnot: 25px;"

Result : https://postimg.cc/5HBm8Bbz

Only in private mode the selected tab has the odl big button style : https://postimg.cc/jLTtXKHJ - but never mind ;)


Thx 4 Support - you made my day ;)

**Comment by speefak** [comment]
`OS	          : Debian 10
FF version : 91.0.1
style           : proton compact, classic configureable
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

Install CSS framework

 download frameworkfile archiv: https://github.com/Aris-t2/CustomCSSforFx/archive/refs/heads/master.zip 
 extract content of "fx60-90" or "classic" folder into userconfig "chrome" directory ( classic folder recommend )

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

Setup firefox about:config modifications (https://github.com/Aris-t2/CustomCSSforFx/issues/334) :

 toolkit.legacyUserProfileCustomizations.stylesheets > true
 browser.proton.appmenu.enabled > true
 browser.proton.enabled > true
 browser.proton.tabs.enabled > true
 browser.uidensity > 1

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

set userChrome.css modifications (fx60-90 v3.3.2)  ( D/E <line> = (D)isable / (E)nable <linenumber>  ):

 enable borderless buttons ( addon list ): 	D 140 / E 137 	( @import "./css/buttons/button_padding_proton.css"; /**/ )
 enable old greyscaled buttons: 		        D 164 / E 178	        ( @import "./css/buttons/icons_custom_icons_old_chrome.css"; /**/ )
 disable/hide  hamburger icon: 			D 299 		        ( /*@import "./css/appbutton/appbutton_in_titlebar_fx74.css"; /**/ /* <-- label only */ )
 disable tab background color:			D 332 		        ( /*@import "./css/tabs/default_tabs_enhanced.css"; /**/ /* Fx89+ & Proton UI */ )
 move Tabs down below bookmark line:		E 376		        ( @import "./css/tabs/tabs_below_navigation_toolbar_fx89.css"; /**/ )
 show tab close icon only when hover:		D 462 / E 464	        ( @import "./css/tabs/tab_close_show_on_hover_only.css"; /**/ )

set userChrome.css modifications (classic v. 4.0.3)  ( D/E <line> = (D)isable / (E)nable <linenumber>  ):

 enable borderless B/W navigation buttons:	D 125 D 150 		 ( /* @import "./css/buttons/icons_colorized.css"; /**/ )
 diable hamburger button:			        D 234 D 235 / E 231 => Button invisible - empty buttun space incorrect
 restore proton tab button style			D 301			 ( /* @import "./css/tabs/classic_squared_tabs.css"; /**/ )
 move Tabs down below bookmark line:		E 325			 ( @import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/ )
 show tab close icon only when hover:		D 387 / E 389		 ( @import "./css/tabs/tab_close_show_on_hover_only.css"; /**/ )

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

adjust new TabToolBar size (fx60-90 v3.3.2) :

 change/add values in "./css/tabs/tabs_below_navigation_toolbar_fx89.css" :
 change => "--tab-min-height_tnot: 32px;" to "--tab-min-height_tnot: 25px;"
 add 	=> "#TabsToolbar:not(:-moz-lwtheme) =>   top: 85px;"

adjust new TabToolBar size (classic v4.0.3) :

 change/add values in "./css/tabs/tabs_below_navigation_toolbar.css" :
 change => "--tab-min-height_tnot: 32px;" to "--tab-min-height_tnot: 25px;"
 add 	=> "#TabsToolbar:not(:-moz-lwtheme) 	=>   top: 85px;		"
 add	=> "#tabbrowser-tabs			=>   margin-top: -5px;	"

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

TODO 
set old tab button style ( ESR style )
reduce tab button height.`

**Comment by speefak** [comment]
```
> OS	      : Debian 10
> FF version : 91.0.1
> style           : proton compact, classic configureable
> #----------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> Install CSS framework
> 
>  download frameworkfile archiv: https://github.com/Aris-t2/CustomCSSforFx/archive/refs/heads/master.zip 
>  extract content of "fx60-90" or "classic" folder into userconfig "chrome" directory ( classic folder recommend )
> 
> #----------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> Setup firefox about:config modifications (https://github.com/Aris-t2/CustomCSSforFx/issues/334) :
> 
>  toolkit.legacyUserProfileCustomizations.stylesheets > true
>  browser.proton.appmenu.enabled > true
>  browser.proton.enabled > true
>  browser.proton.tabs.enabled > true
>  browser.uidensity > 1
> 
> #----------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> set userChrome.css modifications (fx60-90 v3.3.2)  ( D/E <line> = (D)isable / (E)nable <linenumber>  ):
> 
>   enable borderless B/W nav buttons: 	D 140 / E 137 	( @import "./css/buttons/button_padding_proton.css"; /**/ )
>  enable old greyscaled buttons: 		        D 164 / E 178	        ( @import "./css/buttons/icons_custom_icons_old_chrome.css"; /**/ )
>  disable/hide  hamburger icon: 			D 299 		        ( /*@import "./css/appbutton/appbutton_in_titlebar_fx74.css"; /**/ /* <-- label only */ )
>  disable tab background color:			D 332 		        ( /*@import "./css/tabs/default_tabs_enhanced.css"; /**/ /* Fx89+ & Proton UI */ )
>  move Tabs down below bookmark line:	E 376		        ( @import "./css/tabs/tabs_below_navigation_toolbar_fx89.css"; /**/ )
>  show tab close icon only when hover:	D 462 / E 464	        ( @import "./css/tabs/tab_close_show_on_hover_only.css"; /**/ )
> 
> set userChrome.css modifications (classic v. 4.0.3)  ( D/E <line> = (D)isable / (E)nable <linenumber>  ):
> 
>  enable borderless B/W nav buttons:	        D 125 D 150 		 ( /* @import "./css/buttons/icons_colorized.css"; /**/ )
>  diable hamburger button:			        D 234 D 235 / E 231 => Button invisible - empty buttun space incorrect
>  restore proton tab button style			D 301			 ( /* @import "./css/tabs/classic_squared_tabs.css"; /**/ )
>  move Tabs down below bookmark line:	E 325			 ( @import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/ )
>  show tab close icon only when hover:	D 387 / E 389		 ( @import "./css/tabs/tab_close_show_on_hover_only.css"; /**/ )
> 
> #----------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> adjust new TabToolBar size (fx60-90 v3.3.2) :
> 
>  change/add values in "./css/tabs/tabs_below_navigation_toolbar_fx89.css" :
>  change => "--tab-min-height_tnot: 32px;" to "--tab-min-height_tnot: 25px;"
>  add 	=> "#TabsToolbar:not(:-moz-lwtheme) =>   top: 85px;"
> 
> adjust new TabToolBar size (classic v4.0.3) :
> 
>  change/add values in "./css/tabs/tabs_below_navigation_toolbar.css" :
>  change => "--tab-min-height_tnot: 32px;" to "--tab-min-height_tnot: 25px;"
>  add 	=> "#TabsToolbar:not(:-moz-lwtheme) 	=>   top: 85px;		"
>  add	=> "#tabbrowser-tabs			=>   margin-top: -5px;	"
> 
> #----------------------------------------------------------------------------------------------------------------------------------------------------------------
> 
> TODO 
> set old tab button style ( ESR style )
> reduce tab button height.
```

**Comment by speefak** [comment]
#!/bin/bash => only for GEDIT highlighting

OS	   : Debian 10
FF version : 91.0.1
style      : proton compact, classic configureable
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

Install CSS framework

 download frameworkfile archiv: https://github.com/Aris-t2/CustomCSSforFx/archive/refs/heads/master.zip 
 extract content of "fx60-90" or "classic" folder into userconfig "chrome" directory

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

Setup firefox about:config modifications (https://github.com/Aris-t2/CustomCSSforFx/issues/334) :

 toolkit.legacyUserProfileCustomizations.stylesheets > true
 browser.proton.appmenu.enabled > true
 browser.proton.enabled > true
 browser.proton.tabs.enabled > true
 browser.uidensity > 1

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

set userChrome.css modifications (fx60-90 v3.3.2):

 enable borderless buttons ( addon list ): 	D 140 / E 137 		( @import "./css/buttons/button_padding_proton.css"; /**/ )
 enable old greyscaled buttons: 		D 164 / E 178		( @import "./css/buttons/icons_custom_icons_old_chrome.css"; /**/ )
 disable/hide  hamburger icon: 			D 299 			( /*@import "./css/appbutton/appbutton_in_titlebar_fx74.css"; /**/ /* <-- label only */ )
 disable tab background color:			D 332 			( /*@import "./css/tabs/default_tabs_enhanced.css"; /**/ /* Fx89+ & Proton UI */ )
 move Tabs down below bookmark line:		E 376			( @import "./css/tabs/tabs_below_navigation_toolbar_fx89.css"; /**/ )
 show tab close icon only when hover:		D 462 / E 464		( @import "./css/tabs/tab_close_show_on_hover_only.css"; /**/ )

set userChrome.css modifications ( classic v. 4.0.3 ):

 enable borderless B/W navigation buttons:	D 125 D 150 		( /* @import "./css/buttons/icons_colorized.css"; /**/ )
 diable hamburger button:			D 234 D 235 / E 231	=> Button invisible - empty buttun space incorrect
 restore proton tab button style		D 301			( /* @import "./css/tabs/classic_squared_tabs.css"; /**/ )
 move Tabs down below bookmark line:		E 325			( @import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/ )
 show tab close icon only when hover:		D 387 / E 389		( @import "./css/tabs/tab_close_show_on_hover_only.css"; /**/ )

( D/E <line> = (D)isable / (E)nable <linenumber> )
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

adjust/reduce TabToolBar height (fx60-90 v3.3.2) :

 change/add values in "./css/tabs/tabs_below_navigation_toolbar_fx89.css" :
 change => "--tab-min-height_tnot: 32px;" to "--tab-min-height_tnot: 25px;"
 add 	=> "#TabsToolbar:not(:-moz-lwtheme) 	=>   top: 85px;"

adjust new TabToolBar size (classic v4.0.3) :

 change/add values in "./css/tabs/tabs_below_navigation_toolbar.css" :
 change => "--tab-min-height_tnot: 32px;" to "--tab-min-height_tnot: 25px;"
 add 	=> "#TabsToolbar:not(:-moz-lwtheme) 	=>   top: 85px;		"
 add	=> "#tabbrowser-tabs			=>   margin-top: -5px;	"

#----------------------------------------------------------------------------------------------------------------------------------------------------------------

TODO 
set old style tab button style ( ESR style )
reduce tab button height.
