### ISSUE TITLE
Bug [4.x.x,3.x.x] '!iportant' typos in (bookmarks_toolbar_above_navigation_toolbar_when_tab_not_top.css)

### ISSUE THREAD

**Issue by cbaumer0628** [Aris-t2/CustomCSSforFx#407]
Current (4.x.x,3.x.x) (bookmarks_toolbar_above_navigation_toolbar_when_tab_not_top.css) has typos of
"!iportant" (rather than "!important") on lines 8 and 14 that should be corrected.

![Bug  4 x x,3 x x  '!iportant' typos in (bookmarks_toolbar_above_navigation_toolbar_when_tab_not_top css)](https://user-images.githubusercontent.com/89098118/129780800-9940b6d6-b64f-4a85-ad30-c8b22b3f0cd9.png)

**Comment by Aris-t2** [comment]
This will be fixed on next update, thanks.

**Comment by Aris-t2** [comment]
4.0.3 release offer the fix now.

**Comment by cbaumer0628** [comment]
Aris,
Thanks very much for the quick turnaround on a fix for this issue!
 Chuck (cbaumer0628)
 
-----Original Message-----
