### ISSUE TITLE
Proton compact mode style - allready highly configureable 

### ISSUE THREAD

**Issue by speefak** [Aris-t2/CustomCSSforFx#408]
The Proton real-compact-mode is really compact ;). But customization is not able any more. So i created a simple proton compact mode focused on screen height and width in relation of tabtoolbar, tabs down below and simple borderless buttons for those who works with a lot of pinned tab and open tabs. 

<a href='https://postimg.cc/qzYXcMTt' target='_blank'><img src='https://i.postimg.cc/qzYXcMTt/Bildschirmfoto-von-2021-08-22-15-59-42.png' border='0' alt='Bildschirmfoto-von-2021-08-22-15-59-42'/></a>

Configuration HowTo : https://github.com/Aris-t2/CustomCSSforFx/issues/406#issuecomment-903268401
OSX folder icon file : https://i.postimg.cc/Ng9FxbpQ/folder-item.png?dl=1 ( replace ./image/folder-item.png )

TODO :
- remove hidden hamburger button empty space 
- set old style tab button style ( ESR style )
- reduce tab button height.

**Comment by Aris-t2** [comment]
Good job, but could you add your post to https://github.com/Aris-t2/CustomCSSforFx/issues/334 instead of this thread?

**Comment by speefak** [comment]
Really ? The "real compact mode" uses only the userChrome.css - My "compact mode" bases on the normal framework and needs all the other files. So these 2 Compactmodes are very different. If you wish to add the "Proton Compact Mode" to the "Real Compact Mode" i can do this - no problem but perhaps ths i little bit confusing for other users who dont know the difference.
