### ISSUE TITLE
version 4.0.4 Disables my_userChrome

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#412]
**1. Issue description:**
Installed version 4.0.4 this day. Edited userChrome.css file to match previous version 4.0.2pre2.  Inserted edited custom files which I have used for ever. Now my personal my_userChrome.css does not work.

**2. Steps to reproduce the issue:**
1 - tripled checked editing of userChrome.css file
2 - re-instated userChrome.css version 4.0.2pre2 - this works with my_userChrome.css

3. SCREENSHOT(S) of the issue (drag & drop images into this post):

4. about:config prefs (custom CSS files won't work, if these prefs are set to false)
- toolkit.legacyUserProfileCustomizations.stylesheets > true (**yes** ):
- browser.proton.enabled > true (**yes**):
- does the issue occur with latest CustomCSSforFx release (**yes**):

5. System information
- OS & OS version: macOS 10.15.7
- OS theme (if not default): 
- DPI / HiDPI resolution (e.g. 100%, 125%...): 
- Firefox version: 91.0.2
- Firefox (lw) theme (e.g. default, dark, 'theme name/link'): lw theme, normal density
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: my_userChrome.css not activating

[Archive version 4.0.4.zip](https://github.com/Aris-t2/CustomCSSforFx/files/7063808/Archive.version.4.0.4.zip)
[Archive 4.0.2pre2.zip](https://github.com/Aris-t2/CustomCSSforFx/files/7063805/Archive.4.0.2pre2.zip)

**Comment by ChasCB** [comment]
Further to my last post.

I can confirm that my own my_userChrome.css file works with **version 4.0.3 userChrome.css** file

**Comment by Aris-t2** [comment]
Look at the changes between https://github.com/Aris-t2/CustomCSSforFx/compare/4.0.3...4.0.4

userChrome.css received a new option and a couple of description changes. Nothing that should affect your tweaks.

**Comment by Aris-t2** [comment]
Backup your `chrome `folder and move all files out of it.

Setup [4.0.5](https://github.com/Aris-t2/CustomCSSforFx/releases) releases files and copy your `my_userChrome.css` file into the folder.

**Comment by ChasCB** [comment]
Well thank you so much Aris. 4.0.5 works with everything.

As Dr. Isaac Asimovt said; "_There have always been ghosts in the machine. Random segments of code that have grouped together to form unexpected protocols._"

Please keep up this excellent work that you and others do to make Firefox customisable for us users who like to play outside the box. I just wish Mozilla would listen more, instead of arbitrarily introducing changes that are not needed nor wanted.

Thanks again. 🍷
