### ISSUE TITLE
[Testing] Combining 'tabs below navigation toolbar' and 'tabs below navigation toolbar for default tabs' options + Photon-like squared tabs

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#413]
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.0.6pre1

- (new) photon like squared tabs (default_tabs_photon.css)
- (change) Windows/Linux: combined `tabs_below_navigation_toolbar.css` and `tabs_below_navigation_toolbar_default_tabs.css`: `tabs_below_navigation_toolbar.css` for both cases
- (change) Windows/Linux: combined `tabs_below_main_content.css` and `tabs_below_main_content_default_tabs.css`: combined `tabs_below_main_content.css` for both cases
- (change) macOS: combined `tabs_below_navigation_toolbar_macOS.css` and `tabs_below_navigation_toolbar_macOS_default_tabs.css`: `tabs_below_navigation_toolbar_macOS.css` for both cases
- (change) macOS: combined `tabs_below_main_content_macOS.css` and `tabs_below_main_content_macOS_default_tabs.css`: combined `tabs_below_main_content_macOS.css` for both cases

If you are using one of the listed "options" on Windows or Linux, please report whether they still perform the same way in 4.0.6pre builds as they did in 4.0.5 release or not:
- `tabs_below_navigation_toolbar.css` (+classic or default tabs)
- `tabs_below_main_content.css`  (+classic or default tabs)
- `tabs_below_navigation_toolbar_macOS.css` (+classic or default tabs)
- `tabs_below_main_content_macOS.css`  (+classic or default tabs)

(Make sure you are using the latest full 4.0.6pre package and not just the above files, because variables got added or updated inside 'classic squared tabs' files too for example.)

**Comment by droolio** [comment]
> (new) photon like squared tabs (default_tabs_photon.css)

This is much better, thank you! The appearance is somewhat different than FF 88 and what I previously had with CustomCSSforFx v3.x. This is what my bars look like now with v4.0.6pre1:

![Screenshot 2021-08-31 144841](https://user-images.githubusercontent.com/997518/131515220-d5e89cdb-06ea-4766-b0e2-3170ce664c11.png)

Tried replicating my 88 look in a VM by restoring a backup of my v3 CSS using a fresh install of 89 (proton disabled in about:config):

![Screenshot 2021-08-31 144612](https://user-images.githubusercontent.com/997518/131515911-056e2dc1-1a37-4812-bcdb-3e33877dddec.png)

The purple line on the active tab is probably coming from my theme (Rainbow Blur) and probably shouldn't be visible on the _sides_ of the active tab. There's also a thin dark line between the tab and bookmark bar (which always seems to happen with this theme and new CSS. :) ) As you mentioned, tab separator is also currently missing.

The bigger size isn't an issue although perhaps some configurability, and a little roundness on the top corners of tabs - as an option - would be excellent.

**Comment by Aris-t2** [comment]
The line was probably caused by the new code tweaks for "tabs below navigation toolbar" in 4.0.6pre1 when using lw-themes.
Check 4.0.6pre2.

**Comment by PorigonZ** [comment]
Using the version 4.0.6pre2 and "tabs below navigation toolbar" i get a black line between the tabs bar and the navigation toolbar.

![v2](https://user-images.githubusercontent.com/89427551/131571726-0002f820-2a4f-462a-8cf1-b761b0b47a29.png)

**Comment by droolio** [comment]
pre2 much better - no dark line between nav and tab bars for me, and we have separators which is great.

Active tab sides still have a solid purple line, which ideally shouldn't be there if remaining faithful to Photon.

![image](https://user-images.githubusercontent.com/997518/131588030-42e91360-7b34-48ca-a560-4b420e430496.png)

Oddly, this line doesn't exist on the left side of the first tab, which is next to a List All Tabs button on my bar.

![image](https://user-images.githubusercontent.com/997518/131588194-5345c6fe-f379-48ff-88f0-ecdb29b00eca.png)

**Comment by Aris-t2** [comment]
@PorigonZ @droolio 

Both issues should be gone in recent [4.0.6pre3](https://github.com/Aris-t2/CustomCSSforFx/releases).

**Comment by droolio** [comment]
Looks absolutely perfect, thank you for your efforts!

![image](https://user-images.githubusercontent.com/997518/131677416-14631baa-ff43-45fd-a6db-7db3f59a0ad8.png)

**Comment by PorigonZ** [comment]
I updated to version 4.0.6pre3 and it looks great with the "classic squared tabs" but testing with the "photon tabs" i noticed a thin line between the toolbar and tabs bar when the dark and light theme is used. I can't see the line using a colorful theme like "Firefox Alpenglow".

dark:
<img width="823" alt="dark" src="https://user-images.githubusercontent.com/89427551/131722686-34937c25-b3c6-43f1-8153-dbaebec32a4a.png">

light:
<img width="825" alt="light" src="https://user-images.githubusercontent.com/89427551/131722717-cd1895a1-9ec2-4a2c-8289-e2a8555c3bef.png">

color:
<img width="842" alt="color" src="https://user-images.githubusercontent.com/89427551/131722752-1f8fb284-3b00-4432-8a13-74d4a2440a19.png">

**Comment by Aris-t2** [comment]
Wondering how to reproduce this, because the line does not occur here.

Tested:
- Fx 91 release / 93 Nightly
- with/without bookmarks toolbar
- default light, dark and other themes
- devpix default and 125%

![image](https://user-images.githubusercontent.com/6013569/131739691-abd335a4-686d-4e81-9efc-20ab45aeaf0b.png)


@droolio
Does the line occur for you too, if you switch to default btw. built in dark or light themes?

**Comment by PorigonZ** [comment]
I figured out the cause of the issue. The line appear when the display scaling is set to 150% (wich one i use in the TV). Switching to 100% or 125% i don't have the line.

**Comment by Aris-t2** [comment]
I think Firefox miscalculates a padding value when using "Photon tabs" and 150%+ for some reason. Modifying that value fixed this for me. See [4.0.6pre4](https://github.com/Aris-t2/CustomCSSforFx/releases).

**Comment by droolio** [comment]
One new issue I just discovered with Photon style tabs is they don't work too well with the official 'Firefox Multi-Account Containers' add-on. Container tabs usually have coloured lines at the top of the tab, like so:

![image](https://user-images.githubusercontent.com/997518/131853081-f0427432-69bd-474d-b584-b146fe741cf7.png)

These colours are always present no matter the tab activity, and override browser theme colours - they seem to be slightly thicker lines as well (probably a line for the active tab and an always-on colour for containers just above it). On my bars (pre4) they're invisible - whether selected or not, and the purple active colour is completely overridden:

![image](https://user-images.githubusercontent.com/997518/131853791-c28a0e39-865a-4969-9434-7d4c39ca20c5.png)

This happens with default system theme as well:

![image](https://user-images.githubusercontent.com/997518/131854196-14baf995-8f9f-4a80-908b-be197b4341f3.png)

I know it's an add-on, but it's Mozilla's official container add-on for tabs and they were visible and working in FF 88 (and 89 with proton disabled). Is there any way to get them back?

**Comment by PorigonZ** [comment]
Version 4.0.6pre4 works great.

**Comment by Aris-t2** [comment]
I will restore the lines on next update. Till then you can add this to `default_tabs_photon.css`:

```css
.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
  margin: unset !important;
  background-color: var(--identity-icon-color) !important;
}
```

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.0.6 

Thanks for testing!
