### ISSUE TITLE
Titlebar in Firefox 92.0 does not show Windows selected color

### ISSUE THREAD

**Issue by noresk1** [Aris-t2/CustomCSSforFx#416]
When using Firefox 92.0 under Win10 Pro 20H2 the Titlebar does not show my preferred windows title bar color (as set in Windows Settings – see below*).
I am using Custom CSS tweaks v4.0.7 – the only 2 options I’ve changed is to enable "./config/color_variables_aero.css" and "./css/tabs/tabs_below_navigation_toolbar.css" (btw, I also tried v4.0.6 same config as v4.0.7 and get the same result…Titlebar color remains grey)
 
![image](https://user-images.githubusercontent.com/58830974/132889996-328e3aec-014a-4c01-aff2-fb332cb5d973.png)

When using Firefox 91.0.2 and Custom CSS tweaks v4.0.6, I am able to get color back on the Titlebar by disabling Proton (about:config browser.proton.enabled set to False). Before disabling Proton I had the same result as I now have with Firefox 92.0, a grey Titlebar.
 
![image](https://user-images.githubusercontent.com/58830974/132890071-950086c2-8359-4c5e-8f41-0813d4ef53f8.png)

This also yielded the green star for Favorites in the location bar as described and shown below (which may or may not be relevant).

*(Green is the inherited color from Win10 Settings - Colors options; Default Windows mode – Dark, Default app mode – Light, Transparency – On, Color selected – Meadow Green, Show accent colors on – Start, taskbar, etc. and  Title bars & window borders.)

The following Location bar info on Favorites star color may or may not be helpful.
Effects of enabling/disabling Proton on the Favorites star color in the Location bar.
When about:config browser.proton.enabled is set to True, then favorites in the location bar show up with a blue star and a light grey background
 
![image](https://user-images.githubusercontent.com/58830974/132890140-d947aee8-886e-47b7-a00d-396951193516.png)

When about:config browser.proton.enabled is set to False, then favorites in the location bar show up with a green star and a white background (presumably green is from the Windows Colors settings and what I hope can be re-established in the Titlebar for FF 92.0).
 
![image](https://user-images.githubusercontent.com/58830974/132890166-1bd702ea-fb8e-4dda-9f39-65f83f5be2ca.png)

**Comment by noresk1** [comment]
I should have elaborated that with FF 92.0 the Titlebar remains grey regardless whether Proton is set to True or False.

**Comment by Aris-t2** [comment]
You have to enable `top_toolbar_OS_accent_colors.css`.

**Comment by noresk1** [comment]
Excellent!...thought I had searched for all color keywords, but obviously missed that one.
Thanks!!!
