### ISSUE TITLE
tab_audio_icon_colorized.css code error

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#419]
**1. Issue description:**
tab_audio_icon_colorized.css  line 20 is missing # in front of the HEX colour number

**2. Steps to reproduce the issue:**
`fill: ff5a5a !important;`

should it not  be:  `fill: #ff5a5a !important;`

**5. System information**
**- OS & OS version:** macOS 10.15.7
**- Firefox version:** 92.0.0
**- Firefox Theme:** (lw) theme 
**- This projects userChrome.css/userContent.css 'settings' the issue occurs with:** tab_audio_icon_colorized.css

**Comment by Aris-t2** [comment]
Thanks.
