### ISSUE TITLE
[Lin][macOS][Fx57] userContent.css @import not working when e10s is enabled

### ISSUE THREAD

**Issue by Corben78** [Aris-t2/CustomCSSforFx#42]
This is just a hint, that the @import lines of userContent.css are ignored, when electrolysis (multiple content processes) is enabled in Firefox 57.

Workaround is to set `browser.tabs.remote.autostart.2` to `false` in `about:config`.

A bug report at mozilla has already been filed: [#1416184](https://bugzilla.mozilla.org/show_bug.cgi?id=1416184)

configuration:
- Ubuntu 16.04.3 LTS
- Firefox 57 (64 bit)
- light theme

**Comment by Aris-t2** [comment]
I can confirm this for the userContent style "top level image", but this projects alternative appearance settings for about:addons and about:preferences are working with and without electrolysis (multiple content processes).

**Comment by Corben78** [comment]
Looks like `@import` is also not working properly in `userChrome.css` for me. Wether e10s is enabled or not.
When I put the content of the css files I want to include (e.g. `tab_close_always_visible.css`, `tab_close_on_active_tab_only.css`, `tab_close_on_active_tab_only.css`, `tab_close_on_active_tab_only.css`) directly in the `userChrome.css` file, it's working.

**Comment by Aris-t2** [comment]
So the problem is Firefox/Mozilla, right? Nothing I can't change about then.

**Comment by Corben78** [comment]
Yeah, I think it's on Mozilla's side to fix this. As mentioned in the starting post, this is just a hint that `@import`might not work properly, if other's are stumbling over these issues and wonder.

**Comment by MarkRH** [comment]
One thing, make sure the top of userChrome.css doesn't have `@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");` in it or the `@import` won't work. Just in case anyone else reads this. I only mention it because I was importing Aris's stuff into my existing userChrome.css.

**Comment by grahamperrin** [comment]
> … `browser.tabs.remote.autostart.2` …

Lesser-known, I find this boolean easier (to toggle, without memorising any integer): 

`browser.tabs.remote.force-disable`

**Comment by Corben78** [comment]
Oh dear. I made a mistake.
The `@import` is working in `userChrome.css`.
I was commenting out lines with `//` instead of `/*`, as I thought this is for single line comments allowed.
Just realized when using `/*` all settings from `userChrome.css` are working. Mea culpa.

The issue for `userContent.css` is present on Firefox Quantum (57) for Linux though.

**Comment by Aris-t2** [comment]
So still no progress on this one.
It is more likely userContent.css support ends before that bug is fixed.

**Comment by Aris-t2** [comment]
Looks like the issue is fixed. 

Tested with:
Ubuntu 18.04
Firefox 60 (64 bit)

![ubuntu](https://user-images.githubusercontent.com/6013569/39968442-fd57cd52-56cc-11e8-8ebd-95061b622307.png)
