### ISSUE TITLE
"addons_manager_alternative_appearance.css": Color for preferences and help button

### ISSUE THREAD

**Issue by bege10** [Aris-t2/CustomCSSforFx#421]
1. Issue description:
With "addons_manager_alternative_appearance.css" I don't get the preferences and help button colored.
I had to add to the selector to have it work:
Line 455: `#preferencesButton img.sidebar-footer-icon`
Line 459: `#help-button img.sidebar-footer-icon`

I don't use all CSS files you provide and I load them with the script UserCSSLoader. So if this is only an issue here just close it. Maybe it is a general issue and the fix will work for others, too.

Additionally, there is an empty entry in Line 450:
```	
#preferencesButton,
#help-button {
		
}
```

**Comment by Aris-t2** [comment]
Looks like a default rule overrides the color set inside that file.

This should fix the issue.

```css
.sidebar-footer-icon {
  fill: unset !important;
}
```

**Comment by Aris-t2** [comment]
Latest release of CustomCSSforFx does include this fix.

**Comment by bege10** [comment]
Thank you, the buttons are colored again.

The empty entry mentioned in my OP is still there, now line 460 - 463
