### ISSUE TITLE
Addons page still buggy in compact mode (Firefox ESR 91.3.0)

### ISSUE THREAD

**Issue by SGvagon** [Aris-t2/CustomCSSforFx#423]
1. Issue description:
Addons page ( about:addons ) is till buggy in compact mode, sidebar floating over the addons and I can't click on anything. And on the top of the page is big blank space, so I must scroll down for addons.

2. Steps to reproduce the issue:
Resize Firefox to a smaller window.

3. SCREENSHOT(S) of the issue (drag & drop images into this post):
![about_addons_compact_mode_bug](https://user-images.githubusercontent.com/14125053/140475412-0eec5e83-336f-4e1d-b368-51c797b7ae1d.png)

4. about:config prefs (custom CSS files won't work, if these prefs are set to false)
- toolkit.legacyUserProfileCustomizations.stylesheets > true (yes / no): Yes
- browser.proton.enabled > true (yes / no): Yes
- does the issue occur with latest CustomCSSforFx release (yes / no): Yes

5. System information
- OS & OS version: Windows 7 Professional x64bit
- OS theme (if not default): I am using custom theme, but I have this issue on all default themes 
- DPI / HiDPI resolution (e.g. 100%, 125%...): 100%
- Firefox version: ESR 91.3.0
- Firefox (lw) theme (e.g. default, dark, 'theme name/link'): Default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: Nothing, everything about addons is on default.

**Comment by Aris-t2** [comment]
Looks like this to me:
![image](https://user-images.githubusercontent.com/6013569/140480663-e15fa14b-b1e9-4c2e-bcaa-0a1ffcbc2453.png)

**Comment by SGvagon** [comment]
Yes, but change size to a smaller window (activate compact mode) . It break like on my screenshot.

**Comment by Aris-t2** [comment]
Test this: [chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/7487829/chrome.zip)

**Comment by SGvagon** [comment]
Yea :) . Now it works :) . Thank you.

**Comment by Aris-t2** [comment]
4.1.2 went online yesterday ;-)
