### ISSUE TITLE
In Firefox 94 classic bookmarks menu popup opens with a delay

### ISSUE THREAD

**Issue by Bill-Jobss** [Aris-t2/CustomCSSforFx#425]
1. Issue description:

This code `@import "./css/buttons/bookmarks_menu_button_popup_classic_appearance.css";` does not work in Firefox 94.
I have managed to restore the classic bookmarks menu popup appearance with this code:

```
#PlacesToolbar .bookmark-item > menupopup {
	appearance: auto !important;
	border-radius: 0 !important;
}
arrowscrollbox.menupopup-arrowscrollbox {
	background: none !important;
	border-radius: 0px !important;
	border: none !important;
	box-shadow: none !important;
	margin: 0px !important;
	padding: 0px !important;
}
#PlacesToolbar menupopup > menuitem.bookmark-item,
#PlacesToolbar menupopup > menu.bookmark-item {
	appearance: auto !important;
	padding: 0px !important;
	margin-left: 0px !important;
	margin-right: 0px !important;
	min-height: 22px !important;
}
menuitem.openintabs-menuitem {
	padding: 0px !important;
	font-weight: bold;
	color: green !important;
}
#PlacesToolbar menupopup > menuseparator {
	appearance: auto !important;
	margin: 0px !important;
}
#PlacesToolbar menupopup > menuseparator::before {
	display: none !important;
}
#PlacesToolbar menu.bookmark-item > .menu-right {
	appearance: auto !important;
	list-style-image: none !important;
}
#PlacesToolbar menu.bookmark-item > menupopup {
	margin-top: -3px !important;
}
#PlacesToolbar menuitem > .menu-iconic-left,
#PlacesToolbar menu > .menu-iconic-left {
	padding: 0px 0px 0px 4px !important;
}
```

However, the popup menu opens with a notable (and irritating) delay. Notably slower than in Firefox 65.
First the shadow appears, and after a delay - the menupopup.
Is there an animation involved? I could not find it. Is there a way to speed it up?

2. Steps to reproduce the issue:
Add my code to userChrome.css, restart Firefox, navigate trough bookmarks menu with a mouse.

3. SCREENSHOT(S) of the issue (drag & drop images into this post):
Can not show a delay on a screenshot.

4. about:config prefs (custom CSS files won't work, if these prefs are set to false)
- toolkit.legacyUserProfileCustomizations.stylesheets > true (yes):
- browser.proton.enabled > true (tried both "true" and "false"):
- does the issue occur with latest CustomCSSforFx release (yes):

5. System information
- OS & OS version: Windows 7 Home Premium
- OS theme (if not default): default
- DPI / HiDPI resolution (e.g. 100%, 125%...): 100%
- Firefox version: 94.0.2 unbranded release
- Firefox (lw) theme (e.g. default, dark, 'theme name/link'): default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: default with my modifications

**Comment by Aris-t2** [comment]
This feature/option is not available for current Firefox. It is not present in current release versions for CustomCSSforFx either.
