### ISSUE TITLE
Are there any chances to revive ClassicThemeRestorer?

### ISSUE THREAD

**Issue by lokapal** [Aris-t2/CustomCSSforFx#427]
Hello!

Are there any chances to revive ClassicThemeRestorer for the NEW FF using Legacy Extension Loader https://github.com/xiaoxiaoflood/firefox-scripts ? DownThemAll and TabMixPlus are adapted already!

**Comment by BoomerangAide** [comment]
I can't really find what's what on xiaoxiaoflood github page, but if there's a possibility to revive old extensions, I would be interested in https://github.com/simonlindholm/toggle-gifs
Just tell me where I should propose that if it's possible to make such a proposal, as here is probably not the best place for that.

**Comment by lokapal** [comment]
> Just tell me where I should propose that if it's possible to make such a proposal, as here is probably not the best place for that.
It's obvious that you can ask the extension's author, https://github.com/simonlindholm to make the extension that is adapted to the new FF with xiaoxiaoflood addon.  The list extensions that are already adapted are the following one:
https://github.com/xiaoxiaoflood/firefox-scripts/tree/master/extensions

**Comment by mzso** [comment]
[**@lokapal**](https://github.com/lokapal) commented on [2021. nov. 23. 11:42 CET](https://github.com/Aris-t2/CustomCSSforFx/issues/427#issue-1061085834 "2021-11-23T10:42:38Z - Replied by Github Reply Comments"):
> ```
>  Hello!
> ```
> 
> Are there any chances to revive ClassicThemeRestorer for the NEW FF using Legacy Extension Loader [https://github.com/xiaoxiaoflood/firefox-scripts](https://github.com/xiaoxiaoflood/firefox-scripts) ? DownThemAll and TabMixPlus are adapted already!

At this point would be close to a 100% rewrite I suspect since everything in the FF theme changed.
It would be easier to write a new extension.

**Comment by Aris-t2** [comment]
Even, if we could get CTR to "run" again, most of the scripts (CSS and JS) are completely outdated.

I have no plans to revive CTR.
