### ISSUE TITLE
changing back/forward buttons

### ISSUE THREAD

**Issue by joefiesta** [Aris-t2/CustomCSSforFx#429]

**Comment by joefiesta** [comment]
I can't get the back/forward buttons to change. The new buttons are very "thin" font and I can't distinguish when one is highlighted.

my UserChrome (excluding comments) is:

    @import "./Aris_userChrome_4.1.1.css";
   @import "./tabs_below_navigation_toolbar_fx89.css";
   @import "./custom_backforward_large_ff2.css";

What am I doing wrong?

OS - Win7 Pro
FF v94
no special theme for either

Thanks.

**Comment by Aris-t2** [comment]
Make sure you are using the correct file and folder structure.

You need the content of `custom_backforward_large.css` file and the correct path to `bf_ff2.png`.

It would be good to start with the full package of the latest release.
