### ISSUE TITLE
[XBL DEPRECATION] - classic autocomplete popup, version numbers in add-on manager and old search will be gone 'soon'

### ISSUE THREAD

**Issue by ExE-Boss** [Aris-t2/CustomCSSforFx#43]
[XBL has been deprecated](https://mozilla.github.io/firefox-browser-architecture/text/0007-xbl-design-review-packet.html) and is [being replaced by WebComponents](https://mozilla.github.io/firefox-browser-architecture/text/0004-xbl-web-components.html), with ongoing work on this being tracked by [bug 1397874](https://bugzilla.mozilla.org/show_bug.cgi?id=1397874 "NEW - [meta] De-XBL") and [Are We XBL Still?](https://arewexblstill.com/).

This will break everything in [`/classic/xml/`](https://github.com/Aris-t2/CustomCSSforFx/tree/master/classic/xml).

**Comment by Aris-t2** [comment]
Thanks for the info. 

'Add-on number in add-on manager' and 'location bars classic autocomplete popup' will be gone then.

**Comment by Aris-t2** [comment]
I think we can close this after xbl deprecation already hit **_location bars classic autocomplete popup with two lined results_** and **_old search_**.
