### ISSUE TITLE
Problem with Tabs not on top

### ISSUE THREAD

**Issue by f-c-s** [Aris-t2/CustomCSSforFx#432]
Hello,

I have a problem with settings of "Tabs not on Top" on FF 91 ESR x64.

How to proper set options in css to get AdressBar on top ?
I try all combinations for this settings but without success, tabs are over address bar.

On FF 72 it worked fine (with the old version of this project).

Regards
Michal

**Comment by Aris-t2** [comment]
```css
/* - TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS / TABS NOT ON TOP *****************************/
/* [!] Note: only 'alt' works with multi-tab lines option. **************************************/
/* [!] Note: might require overriding url bars 'selection color' --> see corresponding area *****/
/* - Windows/Linux ******************************************************************************/
 @import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/
/* - macOS **************************************************************************************/
/* @import "./css/tabs/tabs_below_navigation_toolbar_macOS.css"; /**/
```

![image](https://user-images.githubusercontent.com/6013569/146685614-f954bb77-b84a-49ae-a1d7-60bace8762ed.png)

![image](https://user-images.githubusercontent.com/6013569/146685719-c77ff15e-20ea-4cc3-97aa-6491112e7554.png)

**Comment by f-c-s** [comment]
Hello,

Thanks, but it does not work.

For testing, I created a new profile, set the legancytoolkit and enable the line you are pointed (only this line).
The section in css file, which I downloaded, looks differ to yours.

/************************************************************************************************/
/* TABS TOOLBAR POSITION (not in titlebar / not on top) *****************************************/
/************************************************************************************************/

/* only use one at a time - below titlebar or below navigation and bookmarks toolbar ************/
/* - TABS BELOW TITLEBAR (Fx56-like) ************************************************************/
/* @import url(./css/tabs/tabs_below_titlebar_above_navigation_toolbar.css); /**/
/* - TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS (tabs not on top) *****************************/ 	/* <-- tabs not on top */
@import url(./css/tabs/tabs_below_navigation_toolbar.css); /**/
/* @import url(./css/tabs/tabs_below_navigation_toolbar_aero.css); /**/	/* <-- AERO colors */
/* @import url(./css/tabs/tabs_below_navigation_toolbar_transparent.css); /**/
/* @import url(./css/tabs/tabs_below_navigation_toolbar_aeroglass.css); /**/
/* @import url(./css/tabs/tabs_below_navigation_toolbar_classic_grey.css); /**/
/* @import url(./css/tabs/tabs_below_navigation_toolbar_classic_fx3.css); /**/
/************************************************************************************************/
/* - TABS BELOW MAIN CONTENT (tabs on bottom) - EXPERIMENTAL - DO NOT REPORT ISSUES! ************/
/* - requires one of the above 'tabs not on top' settings ***************************************/
/* @import url(./css/tabs/tabs_below_main_content.css); /**/  /* <--- EXPERIMENTAL */

![Schowek01](https://user-images.githubusercontent.com/39339468/146921926-afc9cb08-8edb-437a-8285-0c8c02431015.jpg)

[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/7754037/chrome.zip)

Regards
Michal

**Comment by Aris-t2** [comment]
Please run tests using the full release from here:
https://github.com/Aris-t2/CustomCSSforFx/releases

Open `userChrome.css` and edit only this line:
`/* @import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/`
to
`@import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/`

**Comment by f-c-s** [comment]
Hello,

Thank you, now it works fine.

Regards
Michal
