### ISSUE TITLE
Number of items on location bar

### ISSUE THREAD

**Issue by f-c-s** [Aris-t2/CustomCSSforFx#433]
Hello,

Have you any solution for increase the items number in location/address bar.

On your css, I enabled lines:
`
/* megabar/location bar background color - [only use one at a time] ******************************/
/* @import "./css/locationbar/urlbar_background_color.css"; /**/ /* default white background color */
/* @import "./css/locationbar/urlbar_background_color_dark.css"; /**/ /* force dark color for e.g. dark lw-themes */

/* popup content order/appearance - [only use one at a time] ************************************/
  /*   @import "./css/locationbar/ac_popup_megabar_title_and_url_50percent_width.css"; /**/
/* @import "./css/locationbar/ac_popup_megabar_url_and_title_50percent_width.css"; /**/
 @import "./css/locationbar/ac_popup_megabar_title_and_url_two_lines.css"; /**/
/* @import "./css/locationbar/ac_popup_megabar_url_only.css"; /**/

/* result menuitem settings/appearance **********************************************************/
@import "./css/locationbar/ac_popup_megabar_compact_results.css"; /**/
/* @import "./css/locationbar/ac_popup_megabar_searchwith_and_visit_items_hidden.css"; /**/
/* @import "./css/locationbar/ac_popup_megabar_suggest_label_hidden.css"; /**/
 @import "./css/locationbar/ac_popup_megabar_search_engines_hidden.css"; /**/
/* @import "./css/locationbar/ac_popup_megabar_result_highlighting_aero.css"; /**/
 @import "./css/locationbar/ac_popup_megabar_result_separator.css"; /**/`

It looks ok, but the number of items are only 8.

On version 72 FF I used the css made by:

https://www.jeffersonscher.com/gm/url-bar-tweaks.html

but on FF 91 it does not work.

For example my FF 72 (Win 7x64 with Classic Theme):

![Schowek02](https://user-images.githubusercontent.com/39339468/146983061-71967f1c-37bb-40e8-9c0a-bc18905ba4c4.jpg)

Regards
Michal

**Comment by Aris-t2** [comment]
You can use default browser preferences for this.
about:config > browser.urlbar.maxRichResults > 15

**Comment by f-c-s** [comment]
Hello,

Yes, I know this settings. 
I have set it into 20,

On my existing profile updated from 72 to 91, when I click on address bar, it looks like this:
![Schowek03](https://user-images.githubusercontent.com/39339468/147067983-19e5adbb-1135-4525-ab36-910b0aac2111.jpg)
There are only URLs (it's OK), but the list has only 8 items (not 20)

When I click the watch/history icon on this list, the list looks like this:
![Schowek04](https://user-images.githubusercontent.com/39339468/147068644-1174239d-4566-41cc-b0c2-0532d595ceea.jpg)
In this case the list is longer, but it contains mixed URLs and search results. 

When I use the new profile, and when I click on the address bar, there is no list. 
I have to type a letter on the address bar to show the list and the list seams to have mixed URLs and history.

![Schowek05](https://user-images.githubusercontent.com/39339468/147079339-52fe2044-9d87-45a7-85a1-7a2b7acfc698.jpg)

And after clicking on the watch/history icon (there is no change)

![Schowek06](https://user-images.githubusercontent.com/39339468/147079429-566d10ec-546c-4277-bd10-6f5b3fbc5f73.jpg)
 

The behaviour I have on FF 72 is:
- the list contains only URLs
- URLs are sorted by most visited
- the number of items is 30
- there is a scroll bar to view items not visible due to the height of items box 
It is the behaviour from FF 56 and earlier (classic)

Regards
Michal

Ps. I wish you Merry Christmas and Happy New Year.

**Comment by Aris-t2** [comment]
Thanks, I wish you a Merry Christmas and a Happy New Year too.

------


I don't think there is a CSS solution to change the number of results.

The list is also used by "search" / "search with" items you most likely have hidden using the projects CSS options.
But hiding them does not actually remove them.

**Comment by Aris-t2** [comment]
I will close this now. Feel free to comment here anyways. The system will notify me.
