### ISSUE TITLE
[FX 96] How to reduce menu bar drop-down line height. (resolved)

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#436]
1. Issue description:
I was wanting to change the menu bar drop-down item heights, such as the Bookmarks Menu item to be close together like the Bookmarks Toolbar dropdown. I tried looking at the project's options but didn't see anything.  Sorry if I missed something.

2. Steps to reproduce the issue:
Just click on a menu item. 

3. SCREENSHOT(S) of the issue (The drop-down on the left is the after-effect. The one of the right is before the change.):
![After & Before](https://i.imgur.com/qOdOGpc.png)

4. about:config prefs (custom CSS files won't work, if these prefs are set to false)
- toolkit.legacyUserProfileCustomizations.stylesheets > true (yes / no): Yes, true
- browser.proton.enabled > true (yes / no): Yes, true
- does the issue occur with latest CustomCSSforFx release (yes / no): Yes

5. System information
- OS & OS version:  Windows 10 21H2 64bit
- OS theme (if not default): Default I think
- DPI / HiDPI resolution (e.g. 100%, 125%...):  100%
- Firefox version: 96
- Firefox (lw) theme (e.g. default, dark, 'theme name/link'): default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: 

Anyway, here's the CSS I found to work (I commented out the :root part and the menus still seemed fine)

```
   /*** BEGIN Firefox 91 (August, 2021) ***/
   /*** Tighten up drop-down/context/popup menu spacing ***/
   /* from https://www.reddit.com/r/FirefoxCSS/comments/s1p8u5/firefox_96_messed_up_with_my_usercontentcss_and/ */

   menupopup > menuitem, menupopup > menu {
     padding-block: 3px !important;
   }
   /*
   :root {
     --arrowpanel-menuitem-padding: 4px 8px !important;
   }
   /**/

   /*** END Firefox 91 (August, 2021) ***/

```

**Comment by Aris-t2** [comment]
You can also enable `popup_compact_menus.css` and edit the values there, if the result is too compact.

**Comment by MarkRH** [comment]
Ahhh.. so that's the one that affects it.  I can play with it or just keep my change.  Thanks again. Will go ahead and close this.
