### ISSUE TITLE
suggestion: privacy stuff in readme.md

### ISSUE THREAD

**Issue by atomGit** [Aris-t2/CustomCSSforFx#438]
if you're going to suggest privacy enhancements in readme.md (which i think is great), i would humbly suggest linking to the [arkenfox user.js project](https://github.com/arkenfox/user.js) instead of providing a list of options

**Comment by atomGit** [comment]
ps: i figure the ratio of 'thanks' to 'hey, this is broke' is probably heavily slanted toward the latter, so i just wanted to say thanks!

that you have kept this project going, even after the google-wanna-be's at mozilla corporate screwed developers with several API changes, is pretty impressive and deserving of my respect

**Comment by Aris-t2** [comment]
Thanks, your words are much appreciated.
