### ISSUE TITLE
The separator line for pinned tabs is not displayed in default_tabs_photon.css 

### ISSUE THREAD

**Issue by Hobbix** [Aris-t2/CustomCSSforFx#440]
The separator line for pinned tabs is not displayed.

@import "./css/tabs/default_tabs_photon.css";

P.S. If you open a new browser window (without closing the first one, ctrl+N), then the separator bar appears (in a new window). What's the magic? 
Important! At the time of launching the browser, it already has open pinned tabs!

**Comment by Aris-t2** [comment]
Post a screenshot, I can not reproduce this.

![image](https://user-images.githubusercontent.com/6013569/149563668-af715a70-33c8-45dd-8c78-8f8f5dc4283a.png)
![image](https://user-images.githubusercontent.com/6013569/149563773-a9cb36d2-395d-4755-b6f9-6d6e8870770f.png)

**Comment by Hobbix** [comment]
Today I received an update to version 96.0.1 and the problem completely solved itself.
Most likely this problem was in version FF 96.0.0.

**Comment by Aris-t2** [comment]
Not sure why 96.0.1 would fix this, but I already had 96.0.1 installed when taking the screenshots.
