### ISSUE TITLE
Blue line in selected tab

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#441]
is the color of the line (in selected tab) forced blue? 
or can it be changed? 
i tried this code, 

tab.tabbrowser-tab vbox.tab-background[selected="true"] {
    box-shadow: 0 0px 0 1px rgba(0,0,0,0) !important;
    border: 0px !important;
    border-top: 2px solid red !important;
}

but it adds a line, it doesn't change the one that's already there.

![8CLp8ST](https://user-images.githubusercontent.com/33927879/149617572-f518b4f4-dd1f-4ead-8371-0e49c3b385ea.png)

**Comment by Aris-t2** [comment]
You can change the line color by editing the background-color rule.
Look here: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/default_tabs_photon.css#L60
