### ISSUE TITLE
Latest update botched my tabs

### ISSUE THREAD

**Issue by buh6173** [Aris-t2/CustomCSSforFx#442]
I just updated to Firefox 96.0.1, and now my tabs are all screwed up.

Here's how my tabs used to look (I was fortunate enough to randomly need to take footage of my browser yesterday):

![image](https://user-images.githubusercontent.com/1904875/149839881-b446213a-7b27-4257-9c82-39a1e943d02e.png)

And here's what it looks like now:

![image](https://user-images.githubusercontent.com/1904875/149839929-72befab3-ad4e-42a5-a751-158eee86669d.png)

What do I need to tweak to get it back to how it was?

**Comment by Aris-t2** [comment]
Tab issues got fixed by the latest update 9 days ago.
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.3

Use this thread for questions: https://github.com/Aris-t2/CustomCSSforFx/issues/417
