### ISSUE TITLE
Tabs in single row after upt of Firefox to 96.0.1 and CustomCSSforFx to master

### ISSUE THREAD

**Issue by FredM67** [Aris-t2/CustomCSSforFx#443]
I've backed up my old chrome folder, copy the new files.
Now, when I start Firefox, all my tabs are on a single row, even, on default, that should be 3 !!

**Comment by Aris-t2** [comment]
Are you using the full package?
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.3

Still works for fine on on 96 and 98 in my tests. Can you offer more details + screenshot?

_Use this, if tabs are still on top:_
**tabs_multiple_lines.css**
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L371

_Use this, if tabs should be below navigation toolbar:_
**tabs_below_navigation_toolbar_alt.css**
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L342
**tabs_multiple_lines.css**
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L371

**Comment by Aris-t2** [comment]
@FredM67 

Could you solve this issue?

**Comment by FredM67** [comment]
Well unfortunately not yet... I try next week.

**Comment by FredM67** [comment]
Hi,

Well, sorry for the huge delay.
I've just got Firefox update to 98.01 and "re-install" the full package.
Now, it's working fine but... I lost all my tabs 🙁

Fred


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : Aris ***@***.***>
Envoyé : jeudi 20 janvier 2022 13:25
À : Aris-t2/CustomCSSforFx ***@***.***>
Cc : Frédéric Metrich ***@***.***>; Author ***@***.***>
Objet : Re: [Aris-t2/CustomCSSforFx] Tabs in single row after upt of Firefox to 96.0.1 and CustomCSSforFx to master (Issue #443)


Are you using the full package?
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.3

Still works for fine on on 96 and 98 in my tests. Can you offer more details + screenshot?

Use this, if tabs are still on top:
tabs_multiple_lines.css
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L371

Use this, if tabs should be below navigation toolbar:
tabs_below_navigation_toolbar_alt.css
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L342
tabs_multiple_lines.css
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L371
