### ISSUE TITLE
Multirow Bookmarks partly covered because of new Tab height in FF 96.0.2

### ISSUE THREAD

**Issue by shiftF12ATwebDOTde** [Aris-t2/CustomCSSforFx#444]
Hello Aris t2

in the recent update to FF96.0.2
64bit
the Tabs have gotten a new height

so my multirow bookmarks are partly covered
it was only a bit before that update already, but i could still read the last line
now the last line is nearly fully covered by tab height

question
is it possible to insert a line into the userchrome to....:
a) set the height of the tabs?
b) set the height of the multirow bookmarks?
c) set the amount of lines opened for the multirow bookmarks?
d) set the height of the lines in multirow bookmarks?

thanks a lot for your help

shiftF12
![20220122_112328](https://user-images.githubusercontent.com/48584595/150634979-ac184beb-ed63-419e-87d9-fe6107036001.jpg)

**Comment by shiftF12ATwebDOTde** [comment]
/* for bookmarks_toolbar_multiple_lines.css /_fx66.css / _fx74.css */
  --bookmark_items_height: 23px !important; /* <- bookmark items - line height */
  --bookmark_items_lines: 5 !important; /* <- maximum amount of lines */
  

in general_variables.css
brought a good result
now all visible

still open : height of tabs 
much too high for me 
after update
so i will search here again if i find something

**Comment by Aris-t2** [comment]
Are you using the latest files?
https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by shiftF12ATwebDOTde** [comment]
again you made my day

many thanks

my hero
