### ISSUE TITLE
Dark theme and alternative appearance for addons/preferences

### ISSUE THREAD

**Issue by ZTHawk** [Aris-t2/CustomCSSforFx#445]
1. Issue description:
When enabling the default dark theme (also occurs on dark themes) and enabling "addons_manager_alternative_appearance" and/or "preferences_alternative_appearance" then the background is a transition from light grey to black and back to light grey.
Making the content hard to read.

I could fix the issue with this own CSS:
```
body > div#full {
	background: unset !important;
}
```

Tested also the "..._aero" versions. They make settings page almost unreadable.

2. Steps to reproduce the issue:
Enable the default dark theme.
Enable "addons_manager_alternative_appearance" and "preferences_alternative_appearance".

3. SCREENSHOT(S) of the issue (drag & drop images into this post):
N/A

4. about:config prefs (custom CSS files won't work, if these prefs are set to false)
- toolkit.legacyUserProfileCustomizations.stylesheets > true (yes / no): yes
- browser.proton.enabled > true (yes / no): yes
- does the issue occur with latest CustomCSSforFx release (yes / no): yes (4.1.3)

5. System information
- OS & OS version: Win10
- OS theme (if not default): 
- DPI / HiDPI resolution (e.g. 100%, 125%...): 100%
- Firefox version: 96.0.2
- Firefox (lw) theme (e.g. default, dark, 'theme name/link'): dark
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: "addons_manager_alternative_appearance" and "preferences_alternative_appearance"

**Comment by Aris-t2** [comment]
Thanks, I will look into that.

**Comment by Aris-t2** [comment]
Could you test latest pre build?
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.4pre

It should fix a few glitches and the dark theme issue.

**Comment by ZTHawk** [comment]
Hi. Yes that fixes the issues. Thank you.

Btw:
Maybe you should also change colors of the some colored icons. (Dark) Blue icons are hard to spot if dark theme is enabled.

**Comment by Aris-t2** [comment]
I think plugin icons blue color needs either to be a bit darker or to be replaced by a different color.

**Comment by Aris-t2** [comment]
Fixed.
