### ISSUE TITLE
CSS file in the tree has a space in the filename

### ISSUE THREAD

**Issue by JMGonk** [Aris-t2/CustomCSSforFx#446]
This is a packaging issue, I'm not sure if it is a functionality issue.

v4.0.9 introduced a toolbar setting './css/toolbars/tabs_toolbar_remove background_fog_win7.css'
Note the space between "remove" and "background".  userChrome.css references it with the space, so at least that is consistent, but what isn't consistent is that it is the only file in the package with a space in the filename.  Call me old-fashioned, but filenames with spaces (and other whitespace characters) in them are like little landmines on *nix OSes.

It also has no newline at the end of the file.

**Comment by Aris-t2** [comment]
You are right, the space should not be there.
I will "fix" this on next update.

**Comment by Aris-t2** [comment]
Fixed in 4.1.5 release.
