### ISSUE TITLE
Where are your instructions/examples for applying CSS exclusively for  Dev Tool panels

### ISSUE THREAD

**Issue by blachawk** [Aris-t2/CustomCSSforFx#447]
Not looking for custom code!

I just need to know where on your repo do you have examples about modifying CSS elements exclusively for FireFox Web Developer Tools panels.  Having trouble finding that.

**Comment by Aris-t2** [comment]
Sorry, but this project does not offer any CSS for developer tools and their areas and I actually can not offer any instructions on how to "inspect" developer tools.

In the past, when I was working on themes, I had to look through the CSS files inside the browser files.
They are stored inside omni.ja files. You can open them using WinRar.

**Comment by blachawk** [comment]
Many thanks for clarifying that and the tip!
