### ISSUE TITLE
Firefox window not draggable with tabs below navbar

### ISSUE THREAD

**Issue by rogerl50** [Aris-t2/CustomCSSforFx#449]
1. Issue description: Firefox window not draggable with tabs below navbar. MacOS Catalina, Firefox 97.0

2. Steps to reproduce the issue: Using standard 4.1.4 distro, uncomment the line @import "./css/tabs/tabs_below_navigation_toolbar_macOS.css"; /**/.

3. SCREENSHOT(S) of the issue (drag & drop images into this post):

4. about:config prefs (custom CSS files won't work, if these prefs are set to false)
- toolkit.legacyUserProfileCustomizations.stylesheets > true (yes / no): Yes
- browser.proton.enabled > true (yes / no): ***This preference does not seem to exist in my Firefox. **
- does the issue occur with latest CustomCSSforFx release (yes / no):

5. System information
- OS & OS version: MacOS Catalina 10.15.7
- OS theme (if not default): 
- DPI / HiDPI resolution (e.g. 100%, 125%...): Unknown
- Firefox version: 97
- Firefox (lw) theme (e.g. default, dark, 'theme name/link'): default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: See above. Out-of-the-box with one line uncommented.

**Comment by 2BeeOrNot** [comment]
If you turn off Title Bar in Customize Toolbar (View->Toolbars->Customize Toolbar...) and use tabs_below_navigation_toolbar_macOS.css you can't drag the FF window. Turn on Title Bar and you can drag the window.

If you don't like the title bar you can try tabs_below_navigation_toolbar.css but the traffic lights will be on the right instead of the left. Try this to put them back on the left:
.titlebar-buttonbox-container {
  right: unset !important;
  margin-top: 6px !important;
}

I like and use the title bar but I noticed this before you posted this issue. I tried tabs_below_navigation_toolbar.css to see what what the result would be. I noticed the traffic light were in the wrong place. Just for fun I tried to move the traffic lights back to the left. I think this is what I changed. Maybe @Aris-t2 can make a proper change for Mac users without a title bar and tabs below the navigation toolbar.

**Comment by rogerl50** [comment]
> If you turn off Title Bar in Customize Toolbar (View->Toolbars->Customize Toolbar...) and use tabs_below_navigation_toolbar_macOS.css you can't drag the FF window. Turn on Title Bar and you can drag the window.
> 
> If you don't like the title bar you can try tabs_below_navigation_toolbar.css but the traffic lights will be on the right instead of the left. Try this to put them back on the left: .titlebar-buttonbox-container { right: unset !important; margin-top: 6px !important; }
> 
> I like and use the title bar but I noticed this before you posted this issue. I tried tabs_below_navigation_toolbar.css to see what what the result would be. I noticed the traffic light were in the wrong place. Just for fun I tried to move the traffic lights back to the left. I think this is what I changed. Maybe @Aris-t2 can make a proper change for Mac users without a title bar and tabs below the navigation toolbar.

Thanks. I turned Title Bar on and that did indeed solve the problem. But as you say, perhaps there's a solution that allows both. I'll leave this open for the moment.

**Comment by rogerl50** [comment]
> I had to add a workaround to solve this on macOS. (Unfortunately other top toolbars stay draggable too)
> 
> Test latest build form here https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.5pre

Worked for me. Thanks.

**Comment by 2BeeOrNot** [comment]
Works but you can't select text to copy from a web page - FF window moves.

**Comment by 2BeeOrNot** [comment]
How about this:

#main-window[tabsintitlebar] toolbox#navigator-toolbox{
  -moz-window-dragging: drag !important;
}

Seems to work and I can select web page text to copy.

**Comment by Aris-t2** [comment]
Agreed, that is a better solution.

**Comment by Aris-t2** [comment]
I tried prior adding the workaround, but it did not offer the desired result. 
Does it for you?

**Comment by rogerl50** [comment]
I just turned title bar on and am using the 4.1.4 distribution with my customizing changes. Everything, including copying from a FF window and dragging tabs, seems to work fine. If that's where I end up, I'm happy.

**Comment by 2BeeOrNot** [comment]
Works for me as expected. 4.1.5pre4 plus `#TabsToolbar, #nav-bar, #PlacesToolbar { -moz-window-dragging: no-drag !important; }` in my_userChrome.css. Both with and without Title Bar checked.

**Comment by Aris-t2** [comment]
I confused now. Should `#main-window[tabsintitlebar]` be there or not?

**Comment by 2BeeOrNot** [comment]
Here: Yes
This enables dragging when not using the title bar but allows dragging anywhere in navigation area
`#main-window[tabsintitlebar] toolbox#navigator-toolbox{`
  `-moz-window-dragging: drag !important;`
`}`

Here: No
This disables dragging in the tab bar, nav bar and bookmarks bar when not using the title bar.
But I can still drag from tab bar, nav bar and bookmarks bar when using the title bar.
We are now inconsistent in where you can drag from.
`#main-window[tabsintitlebar] :is(#TabsToolbar, #nav-bar, #PlacesToolbar) {`
  `-moz-window-dragging: no-drag !important;`
`}`

I think it should be:
`#main-window[tabsintitlebar] toolbox#navigator-toolbox{`
  `-moz-window-dragging: drag !important;`
`}`

`:is(#TabsToolbar, #nav-bar, #PlacesToolbar) {`
  `-moz-window-dragging: no-drag !important;`
`}`

Like you have in 4.1.5v2. Where you can drag from is now consistent.

**Comment by Aris-t2** [comment]
Thanks for clarification.
I know what the code is supposed to do and how it works, but it refused to work as it should during my tests in my macOS VM.

**Comment by Aris-t2** [comment]
I think we can close this now, right?

Feel free to post here anyways, I will get a notification.
