### ISSUE TITLE
Google Chrome buttons

### ISSUE THREAD

**Issue by aleclarson** [Aris-t2/CustomCSSforFx#45]
Can you add support for a Google Chrome look?

I like their icon design more than Firefox.

**Comment by Aris-t2** [comment]
I can add the "Chrome" icons being previously part of Classic Toolbar Buttons add-on, but I have not plans to create a Chrome theme.

**Comment by aleclarson** [comment]
@Aris-t2 Thanks for the reply! Can you add a "theme" that replaces the button icons, but nothing else? I like the Firefox Quantum theme, but not the button icons. ❤️

**Comment by Acid-Crash** [comment]
Quick suggestion: you could also consider adding Chrome transition animations for hover states

**Comment by Aris-t2** [comment]
To be honest I don't like Chrome transitions and button effects in general.

**Comment by Acid-Crash** [comment]
Same here
But it would be nice to try them out (unless it requires major effort).

**Comment by Aris-t2** [comment]
I'm sorry, this project mainly focuses on stuff CTR and CTB previously offered. I have no plans to port any other browser ui elements.

**Comment by Aris-t2** [comment]
Old Google Chrome icons from Classic Toolbar Buttons add-on are now in 1.3.0 release.
