### ISSUE TITLE
[FX97] Location bar 50 percent, move visit so it's not covered up.

### ISSUE THREAD

**Issue by MarkRH** [Aris-t2/CustomCSSforFx#450]
1. Issue description:
When typing into the location (address bar) if the text or URL is long enough it covers over the "visit" below.  This is when I am using
`@import "./classic414/css/locationbar/ac_popup_megabar_title_and_url_50percent_width.css"; /**/`

It would be cool it if acted like the normal "visit" which moves to the right as you get to it.  This might not be something that is possible.

2. Steps to reproduce the issue:
Include the above in userChrome.css and type stuff in address bar.

3. SCREENSHOT(S) of the issue (drag & drop images into this post):
![image](https://user-images.githubusercontent.com/8035962/153732162-48a64c93-1945-4c49-b289-21d6ca4368af.png)

4. about:config prefs (custom CSS files won't work, if these prefs are set to false)
- toolkit.legacyUserProfileCustomizations.stylesheets > true (yes):
- browser.proton.enabled > true (yes):
- does the issue occur with latest CustomCSSforFx release (yes):

5. System information
- OS & OS version: Windows 10 Pro 21H2
- OS theme (if not default): Default
- DPI / HiDPI resolution (e.g. 100%, 125%...): 100%
- Firefox version: 97
- Firefox (lw) theme (e.g. default, dark, 'theme name/link'): Default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: 
`@import "./classic414/css/locationbar/ac_popup_megabar_title_and_url_50percent_width.css"; /**/`

**Comment by Aris-t2** [comment]
I tried to fix this in [4.1.5pre5](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.5pre), but there are cases this still fails.

>It would be cool it if acted like the normal "visit" which moves to the right as you get to it. This might not be something that is possible.

Unfortunately this would only be possible by not placing "action" tags were they are now horizontally at the start of popups second half (+/- a few percent).

**Comment by MarkRH** [comment]
Thanks for taking a look at it.  I'll wait and see how it behaves in 4.1.5.

**Comment by MarkRH** [comment]
Looks like
`@import "./classic415/css/locationbar/ac_popup_megabar_url_and_title_50percent_width.css"; /**/`

Does resolve the issue as a workaround by placing "visit" in the first half.  I'll go ahead and mark as resolved.
