### ISSUE TITLE
Buttons background color on bookmarks toolbar

### ISSUE THREAD

**Issue by Alexey71** [Aris-t2/CustomCSSforFx#463]
Hello. I used `buttons_on_bookmarks_toolbar_old_size_and_appearance.css`+`bookmarks_toolbar_bookmark_labels_hidden.css`+`bookmarks_toolbar_multiple_lines.css` v4.1.6  or v4.1.7pre1

How to fix the background color of icons when hovering the mouse?
`buttons_on_bookmarks_toolbar_old_size_and_appearance.css` broke background  color

This is what the color looks like without the modification:
![2022-04-06_112820](https://user-images.githubusercontent.com/10572914/161933431-3a6a9d9e-f898-4f52-af4c-23a322692f24.jpg)
![2022-04-06_114922](https://user-images.githubusercontent.com/10572914/161935613-caeabc4f-d488-4596-ae71-77dd72110bbf.jpg)

`buttons_on_bookmarks_toolbar_old_size_and_appearance.css ` broke background color
![2022-04-06_115149](https://user-images.githubusercontent.com/10572914/161935936-74e0a68e-1424-4138-b026-a9ca17698c2b.jpg)
![2022-04-06_114906](https://user-images.githubusercontent.com/10572914/161935963-340d5009-34bc-414c-98e3-10a8a7ddfc05.jpg)

System information
- OS & OS version: Windows 11
- DPI / HiDPI (e.g. 100%, 125%...): All
- Firefox version: 99.0
- Firefox theme (e.g. default, dark, 'theme name & link'): default dark
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: userChrome.css

**Comment by Aris-t2** [comment]
The rule `appearance: toolbarbutton !important;` uses default toolbar button appearance offered by OS/Firefox. The color is not set by the CSS code.
It looks like a bug on Win 11 dark theme, because the correct color is used on light theme (automatically) and this does not happen on Win 10 with dark theme.

**Comment by Aris-t2** [comment]
I suggest not to use `buttons_on_bookmarks_toolbar_old_size_and_appearance.css` on Win 11 for now.

**Comment by Alexey71** [comment]
Ok.
Is there any other way to reduce the distance between the tabs?

**Comment by Aris-t2** [comment]
Sure, if its only about the space, this should solve your issue:

```css
#personal-toolbar-empty-description,
#PersonalToolbar .toolbarbutton-1,
toolbarbutton.bookmark-item:not(.subviewbutton) {
  margin: 2px !important;
  padding: 1px 0px !important;
}
```
