### ISSUE TITLE
[Preferences] alternative appearance - embedded sanitized boxes in pop-ups

### ISSUE THREAD

**Issue by krystian3w** [Aris-t2/CustomCSSforFx#465]
1. Issue description:

    Sanitized pop-up has wrong color in dark theme on Windows 7

   https://github.com/Aris-t2/CustomCSSforFx/blob/8709f5c3a485b70fd3516b2ef50f36c055098c9c/classic/css/aboutpreferences/preferences_alternative_appearance.css#L282-L295

2. Does the issue occur with latest CustomCSSforFx release?

    4.1.7 pre 1 and pre 2

4. Steps to reproduce the issue:

    - enable dark theme on Firefox 95+ (I base on `layout.css.prefers-color-scheme.content-override`) - so fix may break still supported Firefox 91 ESR to Firefox 94
    - open firefox settings/preferences
    - open once of pop-up hidden under button: _change default_ colors... (general > apperance section), manage exceptions, clear data (privacy & security or history sections) or similar with "sanitized pop-up" or xhtml version of these embedded pop-up (Firefox 100+).

6. SCREENSHOT(S) of the issue (drag & drop images into this post):

    ![obraz](https://user-images.githubusercontent.com/35370833/162831450-8598f33d-c5fc-4651-a18a-76b1835cd645.png) | ![obraz](https://user-images.githubusercontent.com/35370833/162830157-3100d484-81a8-44d0-9d28-73f10b035af7.png)
    --- | ---
    FX 99 | FX 101

7. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?

    No, I use this with StyloaiX.

8. System information
    - OS & OS version: Windows 7 Pro, Aero enabled
    - DPI / HiDPI (e.g. 100%, 125%...): 100%
    - Firefox version: 99.0 (and reproduced in Firefox 101 portable)
    - Firefox theme (e.g. default, dark, 'theme name & link'): Dark or [Euskadi](https://addons.mozilla.org/firefox/addon/euskadi/ "https://addons.mozilla.org/firefox/addon/euskadi/") (image theme have light background on Firefox 101 Nightly, I will be sad if these became to stable on june 2022)
    - This projects userChrome.css/userContent.css 'settings' the issue occurs with: `preferences_alternative_appearance.css` - inverted color in lines.

---

I am bad with found duplicates, maybe still recommended is override in my_userChrome.css if daily use same theme:

 https://github.com/Aris-t2/CustomCSSforFx/issues/404#issuecomment-921755546
 https://github.com/Aris-t2/CustomCSSforFx/issues/404#issuecomment-921767240

But now we use other media without negation:

https://github.com/Aris-t2/CustomCSSforFx/blob/8709f5c3a485b70fd3516b2ef50f36c055098c9c/classic/css/aboutpreferences/preferences_alternative_appearance.css#L282

**Comment by Aris-t2** [comment]
Thanks for reporting.

Would switching 

```css
 	  background-color: white !important; 
 	  color: black !important; 
```
to
```css
 	  background-color: black !important; 
 	  color: white !important; 
```

solve the issue for you too?

**Comment by krystian3w** [comment]
Yes, but black generate too high contrast with grayish form mother background:

![](https://i.imgur.com/FM4hrOQ.png)

Also I checked Mozilla defined colors:

`var(--in-content-page-background)` - same like mother `#42414d` (Mozilla "named" as dark but not for contrast themes) or transparent (if 100% alpha are safe)

`var(--in-content-page-color)` - `#fbfbfe` (so for many people readable by `#ffffff`)

But I don't know genesis how old Firefox implemented (maybe 93+) - common.css or preferences.css.

---

I don't exclude forgotten active file with enforce more dark than gray.

**Comment by Aris-t2** [comment]
Is the issue still present in recent releases?

**Comment by krystian3w** [comment]
4.1.8+ works good with Moz://a definied colors.
