### ISSUE TITLE
How to remove new update popup?

### ISSUE THREAD

**Issue by q1k** [Aris-t2/CustomCSSforFx#467]
Issue description:
I don't want to update the browser, but the popup keeps appearing constantly.
![image](https://user-images.githubusercontent.com/7927176/164305735-c2137479-705c-46c0-959e-481803323567.png)

I can't find an option to not check for updates.
So how can I remove this popup?

**Comment by glennpc** [comment]
I haven't tried this, but it might work for you:

https://winaero.com/disable-updates-firefox-63-above/

**Comment by q1k** [comment]
Thanks, but I used css to hide the popup
```
panel#appMenu-notification-popup.popup-notification-panel.panel-no-padding[type="arrow"][noautofocus="true"][noautohide="true"]  {
    display: none;
}
```
I'm not sure if there would be any other consequences though.

**Comment by Aris-t2** [comment]
I think we can close this now, right?
