### ISSUE TITLE
[Fx102+] Misaligned panel when app button is in title bar

### ISSUE THREAD

**Issue by BowDown097** [Aris-t2/CustomCSSforFx#469]
1. Issue description:
The popout panel is misaligned when the app button in title bar setting is enabled in versions 102+ (possibly 101 as well, but 102+ for sure).

2. Does the issue occur with latest CustomCSSforFx release?
Yes

3. Steps to reproduce the issue:
- Enable the app button in title bar setting
- Click app button
- Panel is misaligned

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![image](https://user-images.githubusercontent.com/42720004/169199668-c083eab3-f00b-45cf-a682-e195b512e79e.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
Yes

6. System information
- OS & OS version: Artix Linux x86_64 
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 102
- Firefox theme (e.g. default, dark, 'theme name & link'): Matte Black https://addons.mozilla.org/en-US/firefox/addon/matte-black-v1
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: appbutton_in_titlebar, appbutton_in_titlebar_icon_only

This issue can be fixed by adding this style to both CSS files:
```css
panel[type="arrow"][side="top"], panel[type="arrow"][side="bottom"] {
  margin-inline: 0 !important;
}
```

**Comment by Aris-t2** [comment]
Thanks. I will add this on next update.

I could reproduce this issue on Windows and Linux.

**Comment by Acid-Crash** [comment]
Hi @Aris-t2 
Please be aware that the similar issue is present when
./css/appbutton/appbutton_on_navbar_start_position.css
is active

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.9 should take care of this, thanks.

**Comment by Aris-t2** [comment]
@Jee-Hex 
Thanks. Does [4.1.9v3](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.1.9 ) fix this for you?
