### ISSUE TITLE
buttons_on_navbar_classic_appearance - Buttons on BookmarkBar

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#47]
When toolbar button is placed in BookmarkBar it styling remains default.
![btb](https://user-images.githubusercontent.com/32600318/32910306-8fab1a76-cb11-11e7-8520-cae000bdc788.png)
Is it possible to replicate classic_appearance in smaller scale maybe for such buttons as well (without touching actual bookmarks styling).

**Comment by Aris-t2** [comment]
It should be possible.

**Comment by Acid-Crash** [comment]
I guess, without.
The idea is as follows:
Navigation buttons can be placed on actual navbar and on bookmarkbar.
But they are still remain navigation buttons even if they are mover to another bar.
If user enabled navbar_classic_appearance then moved button to bookmarkbar its styling should remain same (aka navbar_classic_appearance).
As for the Bookmarks that are on bookmarkbar - its styling should be configured by separate module (pretty sure that it is already present as an option in your code).

**Comment by Aris-t2** [comment]
I see it differently. This option styles buttons on navigation toolbar (like it did in Classic Toolbar Buttons add-on), not "buttons, that are on navigation toolbar by default, placed anywhere". By that logic that option would not cover any button still remaining in browser palette on first browser start.

 I will add another two options to also cover manebar and bookmarks toolbar later.

**Comment by Aris-t2** [comment]
Classic button appearance for menubar and bookmarks toolbar (buttons in bookmarks) is now in 1.3.0 release.

**Comment by Acid-Crash** [comment]
Oh there is a small bug with margins on bookmarkbar.
![btb1](https://user-images.githubusercontent.com/32600318/32964637-886602d2-cbdc-11e7-9de6-337a500d9ff3.png)
Guess that additional offset could solve that.

Currently following modules are enabled
@import url(./css/buttons/buttons_on_navbar_classic_appearance.css);
@import url(./css/buttons/buttons_on_navbar_squared_buttons_fx57.css);
@import url(./css/buttons/buttons_on_bookmarks_toolbar_classic_appearance.css);

**Comment by Aris-t2** [comment]
You are right, I will fix this on next update.

Use this till then:
```css
#PersonalToolbar .toolbarbutton-1{
  margin-left: 1px !important;
  margin-right: 1px !important;
}
```
