### ISSUE TITLE
Items in AddressBar 

### ISSUE THREAD

**Issue by f-c-s** [Aris-t2/CustomCSSforFx#470]
Hello,

I have just updated FF 72 into FF 91.9.1 ESR. 
I have installed the current version of your styles.
All works fine, you make a big good work. Many thanks.

In FF 72 the list contains about 30 items with scroll bar on the right side (the list which appears after click on address bar, not as a result for searching something).
But now the items in menu bar are reduced to 8. 

Is there a way to get the list bigger with more then 8 items ?

I enable the two line option:
 @import "./css/locationbar/ac_popup_megabar_title_and_url_two_lines.css"; /**/

Regards
Michal

**Comment by BoomerangAide** [comment]
Have you tried changing the value of browser.urlbar.maxRichResults in about:config?

**Comment by Aris-t2** [comment]
@f-c-s 
Did the suggestion by @BoomerangAide  solve your issue?
