### ISSUE TITLE
Popup behavior with FF100+

### ISSUE THREAD

**Issue by elhennig** [Aris-t2/CustomCSSforFx#473]
Is there a solution for popups closing and freezing with FF 100+? I have this with several addon popups on Linux and Windows and I would like to know, how to prevent this from happening

**Comment by Aris-t2** [comment]
Hi, does this happen with and/or without custom CSS code?

**Comment by elhennig** [comment]
Hi this happens with and without user chrome dir (using https://github.com/Aris-t2/CustomCSSforFx/issues) and only with FF 100+. Now i am back on FF ESR 91.x and the addons works as before

**Comment by Aris-t2** [comment]
This is probably a Firefox bug.

**Comment by elhennig** [comment]
Yes, very likely. 
So far i did not find any bug in FF that would address this, but I did not nvest too much time in the search either. So my question here was, if there is any known workaround in CustomCSSforFx for that.

**Comment by Aris-t2** [comment]
No, the is no CSS-solution for this. You might want to try creating a new profile without customizing anything to check, if the issue occurs again.

**Comment by Aris-t2** [comment]
We can close this for now. Nothing this project can do about the mentioned Firefox issue.
