### ISSUE TITLE
Upgrade for 102

### ISSUE THREAD

**Issue by Marcosdw** [Aris-t2/CustomCSSforFx#474]
Hello,

When think of updating for version 102.

Thanks

Marco

Sorry I use a French/English online translator

**Comment by Aris-t2** [comment]
v4.1.9 release was for 101/102+:
https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by Marcosdw** [comment]
custom_css_for_fx_v4.1.9v3.zip see detail on userchrome display: Current version: 4.1.9v2 ???

**Comment by Aris-t2** [comment]
Is something in particular not working on Firefox 102 for you?
