### ISSUE TITLE
Different indents at the beginning and at the end of the address bar.

### ISSUE THREAD

**Issue by Someone-G** [Aris-t2/CustomCSSforFx#478]
Different indents at the beginning and at the end of the address bar. The indents in the address bar on the left (before the "back" button) and on the right (after the "hamburger" button) are not the same.
![Снимок экрана (139)](https://user-images.githubusercontent.com/108881628/177828820-ebe91c94-ea28-4cb9-b5da-91a129616f27.png)

- Windows Embedded 8.1 Industry Pro. x64.
- Third party theme included. The problem persists with the default theme.
- 100%.
- 102.0.1 (x64).
- Light theme 1.2. The problem occurs when other themes are included. Restarting the browser does nothing.
- Should I list the changes made to userChrome.css?

**Comment by Aris-t2** [comment]
This will be fixed on next update.

Please use the general discussion thread for questions like that: https://github.com/Aris-t2/CustomCSSforFx/discussions/454

Or file an issue inside issues area.

**Comment by Aris-t2** [comment]
Forget the last comment... ;-)
