### ISSUE TITLE
Firefox profile on other drive don't seem to work for CustomCSSforFx

### ISSUE THREAD

**Issue by KroontjesPen** [Aris-t2/CustomCSSforFx#48]
Because of the ssd drive a have program data put in a map on a other HD.
Is it possible this can give problems in finding the right data.

 This
/* TABS TOOLBAR POSITION (not in titlebar / not on top) - only use one at a time ****************/
/* - TABS BELOW TITLEBAR (Fx56-like) ************************************************************/
/* @import url(./css/tabs/tabs_below_titlebar_above_navigation_toolbar.css); */
/* - TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS (tabs not on top) *****************************/
/* @import url(./css/tabs/tabs_below_navigation_toolbar.css);  */ 
@import url(./css/tabs/tabs_below_navigation_toolbar_aero.css);	/* <-- AERO colors */
/* @import url(./css/tabs/tabs_below_navigation_toolbar_transparent.css); */
/* @import url(./css/tabs/tabs_below_navigation_toolbar_aeroglass.css); */

And this
/* tab close icon settings - only use one at a time *********************************************/
/*@import url(./css/tabs/tab_close_always_visible.css);  */
@import url(./css/tabs/tab_close_on_active_tab_only.css);
/* @import url(./css/tabs/tab_close_show_on_hover_only.css); */
/* @import url(./css/tabs/tab_close_hidden.css); */
/* @import url(./css/tabs/tab_close_hidden_for_only_one_visible_tab.css); */
/* @import url(./css/tabs/tab_close_at_tabs_start.css); */

Don't works

**Comment by Aris-t2** [comment]
If Firefox can read your profile from another location, CustomCSSforFx should work fine. Make sure you extracted the code correctly into chrome folder.
The code in your post looks broken.

**Comment by KroontjesPen** [comment]
This are only the parts that I have changed Aris-t2. ;)

**Comment by KroontjesPen** [comment]
Maybe I have putting the [CSS], [image] en [xml] dir's on the wrong place.
They are in the main dir where also the [chrome] dir is placed
![quantum1](https://user-images.githubusercontent.com/5736105/32935985-b2dd39fa-cb72-11e7-9878-b9544f2554fd.png)
.

**Comment by Acid-Crash** [comment]
[css], [xml], [image] folders should be inside [chrome] folder.
Same applies to userChrome.css and userContent.css

**Comment by KroontjesPen** [comment]
Thanks Acid-Crash that was the solution.
Sorry that this was not clear to me.
