### ISSUE TITLE
Request: Arrange Address bar results by type

### ISSUE THREAD

**Issue by roaminghawk** [Aris-t2/CustomCSSforFx#49]
Hi,

I'm trying to sort the results you get when your start typing in the urlbar.
You get different types of entries.
type= "bookmark" for Bookmarks
type= "favicon" for History
type= "searchengine" for search suggestions.

Is there a way to arrange those results?

I played around with this code:

> 
 /*Address*/
  #PopupAutoCompleteRichResult richlistitem[type='visiturl'] {
    -moz-box-ordinal-group: 0!important;  }

  /*Opened tabs in bookmarks*/
  #PopupAutoCompleteRichResult richlistitem[type='action bookmark'] {
    -moz-box-ordinal-group: 1!important;  }

  /*Opened tabs*/
  #PopupAutoCompleteRichResult richlistitem[type='action favicon'] {
    -moz-box-ordinal-group: 2!important;  }

  /*Bookmarks*/
  #PopupAutoCompleteRichResult richlistitem[type='bookmark'] {
    -moz-box-ordinal-group: 3!important;  }

  /*History*/
  #PopupAutoCompleteRichResult richlistitem[type='favicon'] {
    -moz-box-ordinal-group: 4!important;  }

  /*Search suggestions*/
  #PopupAutoCompleteRichResult richlistitem[type='searchengine'] {
    -moz-box-ordinal-group: 5!important;  }

But then when using the keyboard is moves according to the default sort like this:

https://i.imgur.com/OcpqT79.mp4

Thanks.

**Comment by Aris-t2** [comment]
This kind of tweak does not work properly. Already tried it years ago.
Sometimes it even loses results.

**Comment by roaminghawk** [comment]
So no other workaround for it without an add-on?

**Comment by Aris-t2** [comment]
I did not investigate this any further.
