### ISSUE TITLE
Private mode window is broken, address bar is behind tab bar, tab bar is halfway up to the address bar.

### ISSUE THREAD

**Issue by VcSaJen** [Aris-t2/CustomCSSforFx#492]
1. Issue description:
On classic FF setting, private mode window is broken, address bar is behind tab bar, tab bar is halfway up to the address bar.

2. Does the issue occur with latest CustomCSSforFx release?
(Check here: https://github.com/Aris-t2/CustomCSSforFx/releases)
Yes (commit e04ad08)

3. Steps to reproduce the issue:

- Use those settings: [https://github.com/Aris-t2/CustomCSSforFx/compare/e04ad08...VcSaJen:CustomCSSforFx:bd17541](https://github.com/Aris-t2/CustomCSSforFx/compare/e04ad08...VcSaJen:CustomCSSforFx:bd17541)
- Open Private Window
- See that private mode window is broken, address bar is behind tab bar, tab bar is halfway up to the address bar.

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![PrivateBroken](https://user-images.githubusercontent.com/1311131/193310458-ff190ad8-9fe4-4a76-9073-fcc97b4d6e74.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
Yes

6. System information
- OS & OS version: Windows 10 21H1 19043.2006 Windows Feature Experience Pack 120.2212.4180.0
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 106.0b6
- Firefox theme: light
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: 
[https://github.com/Aris-t2/CustomCSSforFx/compare/e04ad08...VcSaJen:CustomCSSforFx:bd17541](https://github.com/Aris-t2/CustomCSSforFx/compare/e04ad08...VcSaJen:CustomCSSforFx:bd17541)

**Comment by Aris-t2** [comment]
Add this to your custom code:
		
```css
#private-browsing-indicator-with-label {
  display: none !important;
}
```

**Comment by VcSaJen** [comment]
Thanks. I also set `browser.theme.dark-private-windows` to `false`.

**Comment by Aris-t2** [comment]
I will add this change do next update.

**Comment by Aris-t2** [comment]
The change is part of the latest release now.

**Comment by Acid-Crash** [comment]
Hi @Aris-t2 
Not sure if this is intentional but the mentioned piece of the code is not added to the default

./css/generalui/private_mode_indicator_hidden.css

**Comment by Aris-t2** [comment]
You are right, it should be in that file too.
