### ISSUE TITLE
Pinned tabs off screen in 106.0

### ISSUE THREAD

**Issue by adam-olson** [Aris-t2/CustomCSSforFx#495]
1. Issue description:
Pinned tabs appear to have been shoved off the left side of the browser bar, only a small edge is visible.

2. Does the issue occur with latest CustomCSSforFx release?
(Check here: https://github.com/Aris-t2/CustomCSSforFx/releases)
Yes, 4.2.2Pre1

3. Steps to reproduce the issue:
When a tab is pinned, does not show on left of tab scroll arrow.

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![image](https://user-images.githubusercontent.com/45909856/196496555-e446221e-2d3b-4a26-a68c-ecb7ce399b75.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
(Custom CSS files will only work, if this pref is set to true!)
Yes

6. System information
- OS & OS version: WIndows 10 1809
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 106.0
- Firefox theme (e.g. default, dark, 'theme name & link'): default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: appears to occur default config from project

**Comment by Aris-t2** [comment]
Latest https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.2.2pre will improve this.

**Comment by adam-olson** [comment]
Great, looks like that fixed the issue.

**Comment by Aris-t2** [comment]
Good to hear.
