### ISSUE TITLE
ac_popup_url_and_title_50percent_width misses Switch tab selector

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#5]
Hi,
**ac_popup_url_and_title_50percent_width** module misses **Switch tab** selector in its code.
Because of this item Switch tab has bigger offset compared to others
![ac_popup_url_and_title_50percent_width](https://user-images.githubusercontent.com/32600318/31354826-88b62a74-ad40-11e7-8424-35fffe7db803.png)
I believe this issue can be fixed by adding **[actiontype="switchtab"]** in line 42, 50 and 56. 
Also there is a duplicated selector in those lines (**[actiontype="searchengine"]**)
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/locationbar/ac_popup_url_and_title_50percent_width.css

**Comment by Aris-t2** [comment]
Thanks for reporting. 
Will be fixed on next update.

**Comment by Acid-Crash** [comment]
fixed in 1.04
