### ISSUE TITLE
[Request] Tab Context Menu Cleanup

### ISSUE THREAD

**Issue by ImSpecial** [Aris-t2/CustomCSSforFx#50]
Hi, this menu is a little messy IMO, can there be some options to clean it up, to remove some of the listed items, I find these mostly to be all redundant, and get in the way of the more useful ones like, like **Undo Closed Tab**.

https://i.imgur.com/D6y5k7i.png

Some of my reasons;

Reload Tab = Hit F5 or Refresh button
Duplicate Tab = Middle click the Refresh button
Move to New Window = Drag the Tab off of Firefox
Send Tab to Device = What is this?
Reload All Tabs = I've never used this personally, I don't keep dozens of old tabs laying around.
Bookmark All Tabs... = ... indeed, seems like a good way to goof and annoy you.
Close Tabs to the Right = Middle-click them.

**Comment by Aris-t2** [comment]
I thinks this would be too much.
This would remove almost everything from tab context menu. Not everybody knows or uses the alternatives and sometimes these entries might become handy, if you already navigating the menu.

I agree stuff like "send to device" have to go optionally (it is about Firefox Sync - moving/syncing tabs between multiple devices [smartphones, tablets, PCs). In fact in my opinion all the Sync and 'send to device' menuitems are major Firefox bugs. If a user does not use Sync, they should not appear anywhere.

I could add on file something like "tab_context_configuration.css" where all those items are listed, but the user would have to change their visibility manually.

**Comment by ImSpecial** [comment]
Okay maybe my picture does make it out to be "too much" lol, but I would be fine with your  "tab_context_configuration.css" idea, you've always been very comprehensive with tweaks.

Mainly for me, since TabMixPlus is currently defunct, which allowed for curating of this stuff, I now have to rely on this menu to "Undo Closed Tab" unless I want to use the hotkey Ctrl+Shift+T, and miss-clicking almost any of them would be just an annoyance, what really bugs me is that clicking the tab and toolbar have different menus so muscle memory for this action gets messed with...

https://i.imgur.com/3uSqHSW.png
https://i.imgur.com/0DnqKss.png

**Comment by Aris-t2** [comment]
Regarding 'undo close tab'.
Aren't there also [WebExtensions on AMO for this in Firefox 57+](https://addons.mozilla.org/search/?q=undo+close+tab),

**Comment by Aris-t2** [comment]
New file is now in 1.3.0 release. Edit it to select what to hide from tab context menu.
