### ISSUE TITLE
FF v 107 multiple_tab_lines.css not going back to 1 line when multiple lines are not needed

### ISSUE THREAD

**Issue by burdo3417** [Aris-t2/CustomCSSforFx#504]

**Comment by Subdarub** [comment]
Workaround:

Go to about:config and set `layout.css.moz-box-flexbox-emulation.enabled` to `true`

**Comment by burdo3417** [comment]
Adding this line fixes the issue without changing "layout.css.moz-box-flexbox-emulation.enabled"

`box.scrollbox-clip[orient="horizontal"] {
  display: inline !important;
}
`

**Comment by Aris-t2** [comment]
This is part of 4.2.3 release from 24 days ago.

https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_multiple_lines.css#L91

**Comment by alwayslurking** [comment]
I had a problem, after upgrading to 107.0 and pulling my git checkout up-to-date, where all my windows had the same number of tab rows as the window with the *most* tab rows, and the layout.css.moz-box-flexbox-emulation.enabled workaround immediately resolved that.
