### ISSUE TITLE
Upper row in multiline tab cutted on top

### ISSUE THREAD

**Issue by riwarek** [Aris-t2/CustomCSSforFx#507]
1. Issue description:
When there are more than one row of tabs upper row is cutted on the top.

2. Does the issue occur with latest CustomCSSforFx release?
Yes.

3. Steps to reproduce the issue:
Open so many tabs to create second row.

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![obraz](https://user-images.githubusercontent.com/22499151/202757185-f4bdb258-c74c-4af5-b3ab-37cb4a150ac0.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
(Custom CSS files will only work, if this pref is set to true!)

6. System information
- OS & OS version: win10
- DPI / HiDPI (e.g. 100%, 125%...): all
- Firefox version: 107
- Firefox theme (e.g. default, dark, 'theme name & link'): default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with:  ???

**Comment by Aris-t2** [comment]
Test this: 

```css
#tabbrowser-tabs{
  margin-top: 1px !important;
}

```

**Comment by riwarek** [comment]
In tabs_multiple_lines.scc I see:
`#tabbrowser-tabs{
  min-height: unset !important;
  padding-inline-start: 0px !important
  }`
 When I change it to 
 `#tabbrowser-tabs{
  margin-top: 1px !important;
}`
nothing happens. Tabs are still cutted.

**Comment by Aris-t2** [comment]
Adding the code to the existing file moved the tabs 1px lower for me. Just test the latest v3 build.

https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by riwarek** [comment]
I tried to modify this in general variables. But in tabs_multiple_lines it works.css
Solved.

**Comment by Aris-t2** [comment]
Good to hear this could be solved.
