### ISSUE TITLE
Sidebar on hover problem

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#508]
### Discussed in https://github.com/Aris-t2/CustomCSSforFx/discussions/506

<div type='discussions-op-text'>

<sup>Originally posted by **Gnome16** November 18, 2022</sup>
I was happily using Custom CSS 3.2.8 with a few modifications for colours etc until today, when my FF must have updated itself (its now 107.0 64 bit on Windows). Now my sidebar, which shows my bookmarks, displays properly when in Hover mode but when I move away from the hover it leaves the left of the screen as a grey block and makes the overall display of the web page smaller.

Obviously this is a really old version of Custom CSS so I updated it to 4.2.3 without any of my modifications. I left everything as default and turned on just one extra option:

`@import "./css/generalui/sidebar_show_on_hover.css";`

But it's still the same problem! Any ideas what setting I should be looking for to correct this?</div>

**Comment by Aris-t2** [comment]
Update to the latest version (4.2.4).

**Comment by Gnome16** [comment]
Works great now. Thank you for such a quick fix!
