### ISSUE TITLE
Make commenting/uncommenting lines twice easier

### ISSUE THREAD

**Issue by unv-unv** [Aris-t2/CustomCSSforFx#51]
Currently to enable/disable specific option I need to add/remove comment both starter (/*) and finisher (*/). I suggest using comment terminator /**/ at the end of line so you need only to add/remove comment starter at the line start.

So instead of:

```
enabled option line
/* disabled option line */
```

It would look like:

```
enabled option line /**/
/* disabled option line /**/
```

**Comment by Aris-t2** [comment]
Sound indeed like something, that would make editing easier.

**Comment by Aris-t2** [comment]
Suggestion is now in 1.3.0 release.
