### ISSUE TITLE
BOOKMARKS TOOLBAR - MULTIPLE LINES is broken in 107.0

### ISSUE THREAD

**Issue by ziffusion** [Aris-t2/CustomCSSforFx#510]
1. Issue description:

BOOKMARKS TOOLBAR - MULTIPLE LINES is broken in 107.0. It causes the bookmarks area to span multiple lines, even if there are not enough bookmarks to make it happen.

2. Does the issue occur with latest CustomCSSforFx release?

Yes

3. Steps to reproduce the issue:

Enable the following in userChrome.css:

@import "./css/toolbars/bookmarks_toolbar_multiple_lines.css"; /**/

4. SCREENSHOT(S) of the issue (drag & drop images into this post):

![firefox](https://user-images.githubusercontent.com/341389/202829859-bc080c0a-7930-4247-a6fb-9897cedfd1fa.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?

Yes

6. System information
- OS & OS version: Windows 11 Pro 22H2
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 107.0
- Firefox theme (e.g. default, dark, 'theme name & link'):  default light
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: 
@import "./css/toolbars/bookmarks_toolbar_multiple_lines.css"; /**/

**Comment by Aris-t2** [comment]
I believe the "other bookmarks" item interferes somehow. This is still under investigation.

Try to add this to the end of `bookmarks_toolbar_multiple_lines.css`, if not already present.

```css
#personal-bookmarks #PlacesChevron {
  display: none !important;
}

#PlacesToolbar hbox[flex="1"] {
  display: flex !important;
}
```

**Comment by ziffusion** [comment]
Seems like setting the following in about:config to true fixes the issue as a workaround.

layout.css.moz-box-flexbox-emulation.enabled

**Comment by Aris-t2** [comment]
We can close this now. If something still does not work, just post here and I reopen the issue.
