### ISSUE TITLE
FF107:Searchbar text is wrongly right-aligned

### ISSUE THREAD

**Issue by CO-Windler** [Aris-t2/CustomCSSforFx#511]
I am using the searchbar with visible search engine names. Since Firefox 107.0 (on Linux and Win10) the text rows are right-aligned instead of left-aligned. Their icons are still correctly on the left side of that dropdown menu.

**Comment by Aris-t2** [comment]
Use recent test builds https://github.com/Aris-t2/CustomCSSforFx/releases and report back.
