### ISSUE TITLE
[Fx 107.0] Tabs toolbar with multiple lines - additional blank line problem

### ISSUE THREAD

**Issue by elektrocad** [Aris-t2/CustomCSSforFx#512]
1. Issue description:
With enabled tabs below navigation toolbar and tabs multiple lines, I get plus blank line below tabs. 

2. Does the issue occur with latest CustomCSSforFx release?
Yes (v4.2.4v3)

3. Steps to reproduce the issue:
Enable the following mods in userChrome.css:
@import "./css/tabs/tabs_below_navigation_toolbar_alt.css";
@import "./css/tabs/tabs_multiple_lines.css";

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![multiple_tabs_broken](https://user-images.githubusercontent.com/60972524/202868361-d4ef51ce-6193-4f9c-bd85-8d7648de9475.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
(Custom CSS files will only work, if this pref is set to true!)
Yes.

6. System information
- OS & OS version: Windows 10 21H2
- DPI / HiDPI (e.g. 100%, 125%...):  100%
- Firefox version: 107.0
- Firefox theme (e.g. default, dark, 'theme name & link'): Default grey.
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: 
@import "./css/tabs/tabs_below_navigation_toolbar_alt.css";
@import "./css/tabs/tabs_multiple_lines.css";

**Comment by Aris-t2** [comment]
Enable `layout.css.moz-box-flexbox-emulation.enabled` in `about:config`.

Currently there are multiple reports mentioning this pref is helping to restore the pre107 behavior.

**Comment by JohnDepon** [comment]
Unfortunately `layout.css.moz-box-flexbox-emulation.enabled` has a side-effect.
The menu bar gets aligned to center.

**Comment by elektrocad** [comment]
> Unfortunately `layout.css.moz-box-flexbox-emulation.enabled` has a side-effect. The menu bar gets aligned to center.

With v4.2.4v3 and "layout.css.moz-box-flexbox-emulation.enabled" -> no issue with menu bar align.

**Comment by Aris-t2** [comment]
@JohnDepon 

Does the issue still occur for you with current release or test builds?

(The issue was caused by tabs_below_navigation_toolbar_alt.css)

**Comment by Aris-t2** [comment]
I opened an issue for this issue here: https://github.com/Aris-t2/CustomCSSforFx/issues/517
It will stay open until Firefox 108 releases.
