### ISSUE TITLE
Incorrect layout for Tools-> Settings

### ISSUE THREAD

**Issue by Mastahh** [Aris-t2/CustomCSSforFx#514]
I just installed a new version: [4.1.8 for Fx91-100] for Firefox 107.0 (64Bit)
Screen resolution: 1920x1080, Scale: 125%, but with scale 100%, 150%, same issue
![image](https://user-images.githubusercontent.com/10340023/204217269-af368cce-975c-4cc7-9184-e785026beb71.png)

**Comment by Aris-t2** [comment]
Hi,

you installed the wrong version. 4.1.8 is for Fx 91-100 (like the label says in your post).

The latest one is 4.2.5: https://github.com/Aris-t2/CustomCSSforFx/releases
