### ISSUE TITLE
Tab width

### ISSUE THREAD

**Issue by Thalon77** [Aris-t2/CustomCSSforFx#515]
1. Issue description:

Something about the tabs width changed between V 4.23 I was using and V 4.25 I'm using now: the tabs now are very short (see attached screenshot), I'm sure something changed inside the latest CSS but I can't manage to find the problem.

2. Does the issue occur with latest CustomCSSforFx release?
(Check here: https://github.com/Aris-t2/CustomCSSforFx/releases)

Yes

3. Steps to reproduce the issue:

Using V 4.25 on Firefox V107.0, copied the old settings from the old CSS to the new one, i enabled @import "./css/tabs/tab_maxwidth.css" in userChrome.css and manually edited --tab_max_width inside general_variables.css to 250 as I did before (to give the tabs the usual pre Australis lenght).
I think a min width value now is needed (never used it before because the tabs needed only a max width edit to be OK for me) but I can't manage to activate it: the instructions inside general_variables tell me to enable min width somwere in the code but adding a "tab_min_width" line inside userChrome.css does nothing.

5. SCREENSHOT(S) of the issue (drag & drop images into this post):

See below

6. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
(Custom CSS files will only work, if this pref is set to true!)

7. System information
- OS & OS version: Win10
- DPI / HiDPI (e.g. 100%, 125%...): 
- Firefox version: 107.0
- Firefox theme (e.g. default, dark, 'theme name & link'): default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: V 4.25
- 
![Cattura](https://user-images.githubusercontent.com/33811707/204269408-90a01fea-43ba-48b8-bb5e-94700932a164.JPG)

**Comment by tfvlrue** [comment]
I encountered the same behavior with 4.2.5v3. It's caused by this change to css\tabs\tabs_below_navigation_toolbar.css:

```
#tabbrowser-tabs {
  width: 100vw;
}
```
became
```
#tabbrowser-tabs {
  width: unset;
}
```

I reverted the change by adding this to my_userChrome.css:
```
#tabbrowser-tabs
{
	width: 100vw !important;
}
```

Strangely, this change only seems to exist in v3 of the 4.2.5 release. The head revision of that CSS file hasn't changed since 4.2.2: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/tabs/tabs_below_navigation_toolbar.css

**Comment by Aris-t2** [comment]
To be honest the issue in #513 seems to be gone for me. 3 days ago I was able to reproduce it, but now it does not occur on Fx 108 beta or 109 Nightly builds, no matter which width value is used. 

Buttons on tabs toolbar do not get hidden in overflow mode anymore. Can anybody confirm?

```css
#tabbrowser-tabs {
  width: unset;
}
```

```css
#tabbrowser-tabs {
  width: initial;
}
```

```css
#tabbrowser-tabs {
  width: 100vw;
}
```

**Comment by Aris-t2** [comment]
@Thalon77 
I set `--tab_max_width: 250px` in `general_variables.css` and 50 for `browser.tabs.tabMinWidth` in `about:config` and tab width did behave the same as before during my tests independent of the `#tabbrowser-tabs { width: unset;}` discussion.

Maybe something went wrong by copying the "old" files?

**Comment by Thalon77** [comment]
@Aris-t2 The value to change in about:config is new to me, I imagine something changed in FF's code with V 107.
The width of the tabs instantly changes editing that but it stays at 50 even with a single open tab, it had a different behaviour before with my old settings, staying at 250 and gradually shrinking when the number of open tabs increased.
I can partially fix the problem by leaving 250 as new value in about:config but I have lost the auto shrink of the tabs and I don't know if it's a problem the new FF release has or if I can further edit your CSS setting to solve the problem.

**Comment by Aris-t2** [comment]
Not sure, if it helps to redo the setup, but try this:
- latest files [custom_css_for_fx_v4.2.5v5.zip](https://github.com/Aris-t2/CustomCSSforFx/releases/download/4.2.5/custom_css_for_fx_v4.2.5v5.zip)
- about:config > browser.tabs.tabMinWidth > 50
- userChrome.css > enable tab_maxwidth.css
- general_variables.css > --tab_max_width: 250px (already set)

"Autoshrink" works for me, but not as good as it did back then with old Firefox versions and add-ons like TabMixPlus or TabUtilities.

**Comment by tfvlrue** [comment]
v5 still has tiny tabs for me, unless I override the width of `#tabbrowser-tabs` to 100vw. It looks like the <tabs> element doesn't fill the parent <toolbar> (`#TabsToolbar`).

![2022-12-02 10_44_58-Tab width · Issue #515 · Aris-t2_CustomCSSforFx — Mozilla Firefox](https://user-images.githubusercontent.com/35318734/205331348-5a88f9eb-af27-4d86-93d4-76b7fbbbfc2f.png)

**Comment by Aris-t2** [comment]
Unfortunately Firefox 107 causes tons off issues, if `layout.css.moz-box-flexbox-emulation.enabled` pref is not set to `true`.

Set is to `true `to fix this issue until next major release.  The value does not matter once you are on Firefox 108.

**Comment by Aris-t2** [comment]
I opened an issue on that here: https://github.com/Aris-t2/CustomCSSforFx/issues/517
It will stay open until Firefox 108 releases.

**Comment by tfvlrue** [comment]
Aha. I set `layout.css.moz-box-flexbox-emulation.enabled` to true like you suggested, and the tab widths are back to normal now with v5 in Firefox 107. Thanks!

**Comment by hopalongrock** [comment]
Very short tabs in the toolbar in Fx 107

I found that the change of #tabbrowser-tabs causes this:

In v4.2.5 tabs_below_navigation_toolbar.css contained
#tabbrowser-tabs {
  width: 100vw;
}

Now v4.2.6 contains
#tabbrowser-tabs {
  width: 100%;
}

**Comment by tfvlrue** [comment]
> Very short tabs in the toolbar in Fx 107 I found that the change of #tabbrowser-tabs causes this: In v4.2.5 tabs_below_navigation_toolbar.css contained #tabbrowser-tabs { width: 100vw; } Now v4.2.6 contains #tabbrowser-tabs { width: 100%; }

Note the resolution above -- `layout.css.moz-box-flexbox-emulation.enabled` can be set to true for FF 107 to avoid this problem.

**Comment by hopalongrock** [comment]
Thanks, with this setting works fine.

**Comment by Aris-t2** [comment]
Unfortunately we can not keep `width: 100vw;` as it removes all buttons from tabs toolbar in Firefox 108+.
