### ISSUE TITLE
[Win][FxDev108b8] Items on the navigation bar get pushed into the overflow menu with the "foward button hide when disabled" userChrome other button setting enabled

### ISSUE THREAD

**Issue by murrty** [Aris-t2/CustomCSSforFx#516]
1. Issue description:
When `forward_button_hide_when_disabled.css` is enabled in `userChrome`, any additional buttons past the address bar (i believe) on the nav bar will automatically be pushed into the overflow menu.

2. Does the issue occur with latest CustomCSSforFx release?
(Check here: https://github.com/Aris-t2/CustomCSSforFx/releases)
Yes, The chrome files straight from v4.2.5v3 release with the only option changed is the problematic one. No other userchrome or usercontent files are added.

3. Steps to reproduce the issue:
Enable the `forward_button_hide_when_disabled.css` other button setting.

4. SCREENSHOT(S) of the issue (drag & drop images into this post):
![firefox more like fired fox lol get it](https://user-images.githubusercontent.com/10895809/204712487-396a6115-55c8-4b7c-9211-1f67e4f9bd7e.png)

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
(Custom CSS files will only work, if this pref is set to true!)
Yes

6. System information
- OS & OS version: Win10 (Additionally tested on 2 different VMs, one running Windows 10 and another running Windows 7, both incur the same issue)
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 108b8 - it started in b1.
- Firefox theme (e.g. default, dark, 'theme name & link'): it might be default since i use a custom windows theme.
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: userChrome.css -> forward_button_hide_when_disabled.css

Additional information:

* I am using the "Compact" density option.
* Every instance I tested had the issue occur on already used profiles as well as freshly created profiles all using the same release version.
* Thank you for maintaining these customization options.

**Comment by murrty** [comment]
A quick workaround (that may not be desirable for long term use) would be to replace `visibility: collapse !important` to `display: none !important;`. Something else may be interfering with the tweak, so more research into it may fix any other non-known bugs relating to it.

**Comment by Aris-t2** [comment]
This will be "fixed" on next update.

**Comment by Aris-t2** [comment]
Fixed on [4.2.6](https://github.com/Aris-t2/CustomCSSforFx/releases).
