### ISSUE TITLE
[Fx 107]: visual issues with many options // switch to Fx 108 as soon as possible

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#517]
If issues on Firefox **107** occur, try to set `about:config` > `layout.css.moz-box-flexbox-emulation.enabled` > `true`.

Keep in mind the above pref will cause other issues.

Firefox 108+ (beta) and 109+ (Nightly) are not affected.

If **Firefox 108+** is already in use, disable the preference again.
`about:config` > `layout.css.moz-box-flexbox-emulation.enabled` > `false`.

----------------------

Switch to Firefox 108 as soon as possible and forget Firefox 107.

**108 pre-release/candidates**
http://ftp.mozilla.org/pub/firefox/candidates/108.0-candidates/

**Comment by Thalon77** [comment]
I can also confirm that the workaround fixed that tabs problem I reported days ago.

**Comment by GaVenga** [comment]
BUT:
layout.css.moz-box-flexbox-emulation.enabled  > true
destroys the column width of boomarks and chronicle (the left column becomes very narrow)
Last working thing: V4.2.4v3

**Comment by Aris-t2** [comment]
@GaVenga 
I'm sorry, but there is no solution for this in Firefox 107.

The issue will be gone on Firefox 108 when `layout.css.moz-box-flexbox-emulation.enabled` is set to `false`.

**Comment by GaVenga** [comment]
The issue will be gone.....
Verified! Thank You.

**Comment by Aris-t2** [comment]
Fx 108 is out, so this thread can go to the archive.
