### ISSUE TITLE
Findbar on top not working in Firefox 107

### ISSUE THREAD

**Issue by xjz223** [Aris-t2/CustomCSSforFx#518]
Findbar on top not working with Firefox 107 using the latest v4.2.5 release with @import "./css/generalui/findbar_on_top.css"; /**/ enabled. If I disable that code the findbar will function normally at the bottom of the page. I prefer having the findbar at the top of the page because I use RoboForm password manager which will only place their toolbar at the bottom of the page. 

I did find a fix from this [link](https://support.mozilla.org/en-US/questions/1197650) that does enable the findbar on top and I simply put that code in my Custom CSS. The code for the fix I found is:

/* Move Find Bar above the page*/
.browserContainer > findbar {
  -moz-box-ordinal-group: 0;
}

**Comment by Aris-t2** [comment]
I can not confirm this. `findbar_on_top.css` works fine in my tests. It also uses the `-moz-box-ordinal-group: 0;` [rule](https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/generalui/findbar_on_top.css#L25), Try a new clean setup of this projects files.

![image](https://user-images.githubusercontent.com/6013569/205398071-9a7def89-5892-4c50-a73b-8333266d01f6.png)

**Comment by Aris-t2** [comment]
Any news on this?

**Comment by Aris-t2** [comment]
I think we can close this for now.
