### ISSUE TITLE
CTRL-F disappeared D:

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#519]
So, recently CTRL-F option is just not visible

I re-downloaded Aris-t2 (to ensure I have newest version), copied all my settings (that were possible to copy, as usual 1-2 disappeared) from old userChrome.css to new one.

It didn't fix the issue. Is ctrl-f the "findbar"? If yes, I use @import "./css/generalui/findbar_on_top.css"; /**/

**Comment by Aris-t2** [comment]
Not sure why this happens for you.

Try a clean new setup without restoring old files. Edit `userChrome.css` and enable `@import "./css/generalui/findbar_on_top.css"; /**/`

**Comment by Aris-t2** [comment]
There already is an open issue about this: https://github.com/Aris-t2/CustomCSSforFx/issues/518

**Comment by Nyekomimi** [comment]
Oh, sorry, thought you closed this.

Yep, it was scrap data - deleting all 3 folders and re-adding them helped.
![obraz](https://user-images.githubusercontent.com/33688131/206192474-2b9c3693-0ab9-442d-ac3e-4b479a5ad260.png)
