### ISSUE TITLE
Weird behavior of right-clicking back button after updating to newest version

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#520]
No custom code. Issue wasn't here before, only after I upgraded.

Issue 1: Instead of usual behavior (unlimited go-back) it caps out at around 20 pages of history. Makes it problematic if you read lot of short chapters and want to go back to search after finishing a story.

Issue 2 (potentially coupled with 1): You usually don't get to see 1 before resetting browser, because right-clicking the go-back button, pressing as low as possible leads to entire firefox freezing. At first I thought its memory leak due to game I had running, but just had it occur without any other stuff active... So it gotta be CSS problem

**Comment by Aris-t2** [comment]
If you remove everything from your "chrome" folder including this projects file, the issue is gone, right?

CSS does no touch browser history at all.

**Comment by Aris-t2** [comment]
I almost forgot, there actually is an option targeting back/forwared history popups: "back_and_forward_separated_history_popups.css". Do you have it enabled?

The goal is to split the forward items from back menu and the back items from forward menu. Maybe it causes issues with newer Firefox versions?

**Comment by Nyekomimi** [comment]
Hey, sorry about delay. Nope, it was disabled. Only thing in that category that's enabled is:

@import "./css/buttons/whatnew_button_always_hidden.css"; /**/

**Comment by Aris-t2** [comment]
Try to disable all settings one by one to find the one causing the issue for you.

**Comment by Aris-t2** [comment]
Any news here? I still can not reproduce your issue.
