### ISSUE TITLE
Search bar overboarding after updating FF to V 107

### ISSUE THREAD

**Issue by Thalon77** [Aris-t2/CustomCSSforFx#521]
1. Issue description:

Found another problem after updating FF to V107: my search bar (displayed near the address bar) has its icons overboarding (see attached screenshot, I have 10 search engines on it and the bottom row with the settings icon for the search engines is not displayed correctly).

2. Does the issue occur with latest CustomCSSforFx release?
(Check here: https://github.com/Aris-t2/CustomCSSforFx/releases)

Yes, using V 4.2.6.

3. Steps to reproduce the issue:

Select to display search engines on menu bar, have more than 8 search engines saved in Firefox.

4. SCREENSHOT(S) of the issue (drag & drop images into this post):

See below.

5. Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true'?
(Custom CSS files will only work, if this pref is set to true!)

Yes, also set layout.css.moz-box-flexbox-emulation.enabled to true.

6. System information
- OS & OS version: Win10 pro

- Firefox version: 107.0.1
- Firefox theme (e.g. default, dark, 'theme name & link'): Default
- This projects userChrome.css/userContent.css 'settings' the issue occurs with: 

![Cattura](https://user-images.githubusercontent.com/33811707/205608690-b6b9d38c-5400-4e82-b354-072c69302701.jpg)

**Comment by Aris-t2** [comment]
Does it also happen without any custom CSS files?
Which searchbar options have you enabled in `userChrome.css`?

**Comment by Aris-t2** [comment]
Looks like the pref `layout.css.moz-box-flexbox-emulation.enabled` is causing this.

**Comment by Aris-t2** [comment]
Things should be fine again once you install Firefox 108 and switch `layout.css.moz-box-flexbox-emulation.enabled` to `false`.

**Comment by Thalon77** [comment]
Yes, can confirm that too now that V 108 is out.
That rollback also fixed other minor cosmetic bugs in the GUI.
