### ISSUE TITLE
Conflicting colours in Library window

### ISSUE THREAD

**Issue by cxen** [Aris-t2/CustomCSSforFx#529]
1. Does the issue occur without any files inside /chrome/ folder?
This is definitely related to CustomCSS

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
In the Library/History/Downloads windows, the theme is not consistent in the toolbars, giving conflicting colors to the bar and buttons. This have been an issue for a long time but now the URL bars are affected with a similar issue, so I thought to check in with you,

Library window issue:
https://user-images.githubusercontent.com/46993334/207672503-b9d560a0-9d60-4aa4-9748-0fe32e10a20d.mp4

Main URL bar issue (no contrast or outline around URL and search boxes since FF 108):
![image](https://user-images.githubusercontent.com/46993334/207672520-b5c0b479-e10e-4c15-b58c-a6488c5fc4ae.png)

Bonus question:
How to disable the multirow tab bar scrollbar? (below bookmarks if it matters)

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes. Using 4.2.6 in FF 108

5. System information
- OS & OS version: Win10 22H2
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 108
- Firefox theme (e.g. default, build in light/dark, external theme + link): Default Dark 1.2
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'true' (Fx 107 only): Yes

**Comment by Aris-t2** [comment]
Honestly I do not know what is causing this for you.

Default setup of this projects files + default dark theme v1.2

![image](https://user-images.githubusercontent.com/6013569/207869790-aa431d26-d0b4-43d4-8457-e8d8d544bae1.png)

**Comment by Aris-t2** [comment]
Can somebody reproduce this on a clean new profile?

**Comment by Aris-t2** [comment]
Any news here?

**Comment by cxen** [comment]
I replicated the same behaviour on a different machine, clean Firefox install, clean profile.
I just used the chrome and content files from above. Could anyone check if I'm commenting out something that I shouldn't?

**Comment by Aris-t2** [comment]
The issue is caused by `tabs_below_navigation_toolbar_alt.css`, when a dark lw-theme is used.

Test [4.2.7v4](https://github.com/Aris-t2/CustomCSSforFx/releases).

**Comment by cxen** [comment]
> The issue is caused by `tabs_below_navigation_toolbar_alt.css`, when a dark lw-theme is used.
> 
> Test [4.2.7v4](https://github.com/Aris-t2/CustomCSSforFx/releases).

Yup, this fixed the Library toolbar and the URL boxes.
Thank you so much.

**Comment by Aris-t2** [comment]
Good to hear.
