### ISSUE TITLE
Alignment of Icons in Tab Bar

### ISSUE THREAD

**Issue by elhennig** [Aris-t2/CustomCSSforFx#533]
I run FF 102.6esr on Linux. Until last update from opensuse of this package I had icons on the tab bar which where aligned right while the tab where left aligned. No everything is left aligned an d the icons are added right of the most right tab. Is there a quick fix to revert to the previous behavior?

**Comment by Aris-t2** [comment]
Any screenshots?

Note: Buttons on tabs toolbar should be on the right by default.

**Comment by elhennig** [comment]
Yes, after an Update to FF 108 it works as usual. So the problem only occurred with the ESR version 102.6
