### ISSUE TITLE
Gray icons in the bookmarks menu

### ISSUE THREAD

**Issue by Thalon77** [Aris-t2/CustomCSSforFx#534]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so the issue report is most likely wrong here.

Specific to the custom CSS, can't work without it.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

This issue happened after updating firefox from V107 to V108, the bookmark and chronology icons I placed on the left side of the menu bar now have their aero effect applied only on their borders while the rest of the icon takes a dark grey appearance while selected (see screenshot).
Using noia grey general color style, aero style for icons, crystal icons set.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-

Yes, using V 4.2.7.

4. Screenshots showing the issue (drag & drop images into this post):

![Cattura](https://user-images.githubusercontent.com/33811707/208093098-dc17d9de-79a0-4e35-8912-7f3b0eb05974.png)

5. System information
- OS & OS version: Win 10
- DPI / HiDPI (e.g. 100%, 125%...): 
- Firefox version: 108.1
- Firefox theme (e.g. default, build in light/dark, external theme + link): Default
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes.
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'true' (Fx 107 only): No, no need.

**Comment by Aris-t2** [comment]
Test [4.2.7v3](https://github.com/Aris-t2/CustomCSSforFx/releases).

**Comment by Thalon77** [comment]
Can conferm it's fixed.

**Comment by Aris-t2** [comment]
Good to hear.
