### ISSUE TITLE
tabs_below_navigation_toolbar.css bug

### ISSUE THREAD

**Issue by 5Z-A** [Aris-t2/CustomCSSforFx#537]
Bug (typo?) in css\tabs\tabs_below_navigation_toolbar.css, line 32:
**width: 100%;**
should be:
**width: 100vw;**

--------------------

1. Does the issue occur without any files inside /chrome/ folder?
No.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
@import "./css/tabs/tabs_below_navigation_toolbar.css";

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes.

4. Screenshots showing the issue (drag & drop images into this post):
![01](https://user-images.githubusercontent.com/121047969/208489153-6948f132-65f1-4201-9007-91d0c7c74335.png)

5. System information
- OS & OS version: Windows 10 build 19044.2364 x64
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 107.0.1 x64
- Firefox theme (e.g. default, build in light/dark, external theme + link): default (Light 1.2)
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): yes

----------

After modifying the css\tabs\tabs_below_navigation_toolbar.css file:

![02](https://user-images.githubusercontent.com/121047969/208490622-5cd92380-7ef8-49aa-8166-cc50eed3ba72.png)

**Comment by Aris-t2** [comment]
Update to Firefox 108.x, the buggy Firefox 107 is not supported by this project.
One of the issues is the bug you mentioned for example.

If you must stay on Firefox 107, then using `width: 100vw;` instead of `width: 100%;` is fine.
