### ISSUE TITLE
NEW TAB and CLOSE TAB buttons missing

### ISSUE THREAD

**Issue by simoncarne** [Aris-t2/CustomCSSforFx#538]
I have selected both pof the following files but neither the "close" button nor the "new tab" buttons are appearing. 
@import "./css/tabs/tab_close_always_visible.css"; 
@import "./css/tabs/newtab_button_always_visible.css"; 

This problem began when my Firefox updated to 108 earlier today. No problem prior to that - been using your CSS for several years (many thanks!).

![image](https://user-images.githubusercontent.com/33954467/208963662-4a165bea-1346-47b6-b985-08cb8d3b8e89.png)

The gaps between the tabs (left and right) are also new today, following the update to Ff 108. I mention that in case it's relevant.

- Windows 10 (fully up-to-date)
- 125%: 
- Firefox 108.0 64-bit
- Firefox theme - default
- toolkit.legacyUserProfileCustomizations.stylesheets is set to TRUE
- layout.css.moz-box-flexbox-emulation.enabled is set to FALSE

**Comment by Aris-t2** [comment]
Do not use `newtab_button_always_visible.css` with `tabs_multiple_lines.css` or `tabs_multiple_lines_force_newtab_button_visibility.css` options.

Default setup + tabs_below_navigation_toolbar_alt.css + tabs_multiple_lines.css
![image](https://user-images.githubusercontent.com/6013569/208973264-8a518176-9e9a-467d-910d-fdc2099ccf3a.png)

Default setup + tabs_below_navigation_toolbar_alt.css + tabs_multiple_lines_force_newtab_button_visibility.css
![image](https://user-images.githubusercontent.com/6013569/208973444-527d4874-b415-43dc-98f5-3d94bcc41354.png)

tab_close_always_visible.css is active be default.

**Comment by Aris-t2** [comment]
I will add an incompatibility note to `userChrome.css`.

The option was made replace the 'new tab' tab with the button using default tab view.

![image](https://user-images.githubusercontent.com/6013569/208975879-a2eacd4e-401b-40ca-901b-01aab254a539.png)

**Comment by simoncarne** [comment]
Thank you for the speedy response above. I have reinstated the missing "new tab" button by switching to `tabs_multiple_lines_force_newtab_button_visibility.css`. But I still don't have the "tab close" crosses, which you say should be there by default. Any thoughts on why they might be missing? (As I mentioned above, they were present until today when my Firefox upgraded to version 108.)  
![Screenshot from Ffox with +](https://user-images.githubusercontent.com/33954467/208984361-70c52bda-329f-486e-883b-499d37bc248e.jpg)

**Comment by Aris-t2** [comment]
Have you any custom code besides the one from this project inside your chrome folder?

Try to disable the "options" inside `userChrome.css` one by one until the close button reappears. Afterwards post which one causes the issue, so I can look into it.

**Comment by simoncarne** [comment]
I have the MultiRow function from https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme (only the MutlRow, not the other theme functions).
I will follow your advice regarding turning off the options one by one (including the Izheil MultiRow) and report back on here when I have some news.
Many thanks

**Comment by Aris-t2** [comment]
Are you using the latest version of this projects files?

I'm asking, because you still have `tabs_multiple_lines_fx71.css` file. Support for *_fx71.css files was dropped in August 2021 (CustomCSSforFx 4.0.0 release).

[Update to the latest release](https://github.com/Aris-t2/CustomCSSforFx/releases) and recreate your config.

**Comment by simoncarne** [comment]
It looks I have got it sorted now. I had some old and new files muddled up. 
I will check it properly (hopefully on Friday) and confirm.

**Comment by simoncarne** [comment]
I have now checked and, although updating all the files has brought back the New Tab and Close Tab buttons as expected, I realise that I have lost my Bookmarks Toolbar. In order to get it back, I have to deselect `/css/tabs/tabs_below_navigation_toolbar.css`.
I attach two screenshots, one with tabs above navigation and one with tabs below which has the Bookmarks Toolbar missing. 
![Tabs-below-OFF](https://user-images.githubusercontent.com/33954467/209304642-0d4d6d65-25fe-4a33-9f5e-b995641408f7.jpg)
![Tabs-below-ON](https://user-images.githubusercontent.com/33954467/209304653-0844cf04-dd92-4b69-9b4c-60c9348fbd50.jpg)



I realise that this is moving away from the topic for this query, so I would be happy to create a new issue if you prefer.

**Comment by Aris-t2** [comment]
Its fine here. ;-)

The feature "multiple tab lines/rows" requires a different option for "tabs below navigation toolbar" feature: `tabs_below_navigation_toolbar_alt.css`

Your bookmarks toolbar will be back then.

-----
I know creating the desired configuration takes more and more times and different options, but Mozilla keeps changing stuff causing to create more complex workarounds.

**Comment by simoncarne** [comment]
It seems to be all sorted now. Many thanks. 
I appreciate your help on this and all that you do to make these options available for users.

**Comment by Aris-t2** [comment]
Good to hear.
