### ISSUE TITLE
FF 109.0 - Who thought this was a good idea? (new "Extensions" button)

### ISSUE THREAD

**Issue by ImSpecial** [Aris-t2/CustomCSSforFx#544]
![2023-01-16_12-49-57](https://user-images.githubusercontent.com/4022372/212762257-3638bc18-fb22-440c-85fb-dc8959a2c313.png)

Ta-da! What an amazingly new innovative feature by Mozilla once again, how do they keep coming up with these great new ideas yet have such poor market-share... A mystery we may never figure out.

Okay, sarcasm aside this new button seems to have appeared with 109, and also seems to be unmovable and no way to be hidden by normal means, which means CSS will have to solve it, can a kind guru help by hiding this button please?

**Comment by Acid-Crash** [comment]
Not sure how long will it last, but we can disable the new Extensions button
via about:config pref extensions.unifiedExtensions.enabled >> False

P.S. solution was found here
https://www.ghacks.net/2022/08/07/mozilla-is-working-on-a-single-extensions-button-for-its-firefox-web-browser/

**Comment by ImSpecial** [comment]
Well that did seem to work, lets hope that pref doesn't go away in my lifetime...

/rant - Why cannot they just add a visible option to just remove these sort of things, there's literally a "Customize Toolbar" menu, but it's so bar-bones in function.

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L330

(Already present since 4.2.2 release. )

**Comment by Aris-t2** [comment]
That "extensions" button is not a good idea, but it is part of chromes manifest v3 which is on by default since Firefox 109.
Other browsers offer this button too. 

Firefox already had an "overflow" menu for a long time, that could be used like this button.

Seems like another "they have it, we must have it too".

**Comment by ImSpecial** [comment]
Thanks Aris, going to close this now as it solved and pretty much moot at this point.

Gotta love their patch notes "ushers an exciting user interface change..." LOL. 

![2023-01-17_12-09-27](https://user-images.githubusercontent.com/4022372/212990406-103db1bc-8c00-4981-a994-441ccd12fb01.png)

**Comment by Aris-t2** [comment]
Very exciting. Saw people complain about this in the comments on many tech sites, that mentioned Fx 109 release.

**Comment by B00ze64** [comment]
That new AddOns button's menu does not scroll, so it only shows 1/3rd of all my addOns, and those that it does show do not have a custom menu (as opposed to those that I would want to see because they have a menu button). It's pretty useless as it is...

**Comment by Aris-t2** [comment]
Agreed. Devs don't test stuff like that very well. Most likely they assume the average user has 2-5 add-ons installed, where things work fine. They made it clear multiple time they don't care about power users.

I'm still wondering why they did not forked Chromium and called it Firefox.
