### ISSUE TITLE
[Fx109] A new location of tabs bar hides link/pagestatus badge(tooltip) after enabling [tabs_below_main_content.css] option.

### ISSUE THREAD

**Issue by alkoros** [Aris-t2/CustomCSSforFx#545]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
When enabling just one option (**userChrome.css (@import "./css/tabs/tabs_below_main_content.css";)**), the tabs bar (in a bottom of page) hides a link/page status badge/tooltip. Having clean default profile (/appdata/local/mozilla, /appdata/roaming/mozilla folders erased before fisrt run). Other setting default, not changed.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, release 4.2.8

4. Screenshots showing the issue (drag & drop images into this post):
Before and after applying, mouse cursor on "_Conversations moved to discussions_" label, leading link first visible on tooltip, but not after.
![screen1](https://user-images.githubusercontent.com/63870934/213111711-8c384a03-0703-4525-bc06-9df38a18e05c.png)
This issue not occur in previous Firefox 108.0.2 build.

5. System information
- OS & OS version: Windows 7 SP1 x64 (Version 6.1.7601), Windows 10 Enterprise x64 (Version 10.0.14393), Windows 10 LTSC x64 (Version 10.0.17763.1217)
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 109.0 (x86 + x64)
- Firefox theme (e.g. default, build in light/dark, external theme + link): default
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): Yes

**Comment by Aris-t2** [comment]
Check the current dev builds: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.2.9pre

**Comment by alkoros** [comment]
> Check the current dev builds: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.2.9pre
 custom_css_for_fx_v4.2.9pre1.zip - same issue
 custom_css_for_fx_v4.2.9pre4.zip - ok, no problem here.

**Comment by Aris-t2** [comment]
Fixed in [v4.2.9 release](https://github.com/Aris-t2/CustomCSSforFx/releases/).
