### ISSUE TITLE
[Firefox 109 + CustomCSSforFx 4.2.9+] - 'issues' with Fx 109 and CustomCSSforFx 4.2.9+ belong here

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#546]
### Test latest (developer) build/release _before_ posting: https://github.com/Aris-t2/CustomCSSforFx/releases

---------------

### Extensions button on navigation toolbar

If you want to hide the "new" extensions button on navigation toolbar, you can use the `about:config` switch `extensions.unifiedExtensions.enabled` or use the option `unified_extensions_button_hidden.css` inside `userChrome.css`, which was added to this project in 4.2.2 release back in October 2022.

**Comment by glennpc** [comment]
When using addonbar_move_bookmarks_toolbar_to_bottom.css the addonbar shows up when playing YouTube video in full screen.

I think it's this line of code causing it:

#browser,
#customization-container {
  margin-bottom: var(--addonbar_height) !important; 
}

**Comment by Aris-t2** [comment]
I exclude the code from fullscreen and fullscreen videos in next dev build. Follow the above link ;-)

**Comment by danielefranceschi** [comment]
tabs_below_main_content w/ fx 109 and latest dev release

![image](https://user-images.githubusercontent.com/16599499/214000866-4338b604-ffb0-4be1-be6b-8d9f723eab02.png)

**Comment by Aris-t2** [comment]
Make sure you are using the full release and only modify the line with `tabs_below_main_content.css` inside `userChrome.css`.

![image](https://user-images.githubusercontent.com/6013569/214080157-738c8f78-c421-4126-b7e4-b46434634844.png)

![image](https://user-images.githubusercontent.com/6013569/214080293-dcc2207b-7ba0-4d2c-89c0-95179bb0f21c.png)

**Comment by rbro** [comment]
In Windows, I set both ClearType and Font Smoothing to be off.  I'm running Firefox 109 with CustomCSSforFx v4.3.0.  When I turn on both addonbar_move_bookmarks_toolbar_to_bottom.css and addonbar_status_in_addonbar.css, the URL shows in the statusbar as if font smoothing is on.  If I try addonbar_status_in_addonbar.css from v4.2.5, then it renders correctly.

With addonbar_status_in_addonbar.css not enabled, text is correct (no font smoothing), though above the statusbar of course:
![1](https://user-images.githubusercontent.com/195605/215273672-c5a65207-89ce-4a17-95fc-c1d8f348ed1d.png)

With addonbar_status_in_addonbar.css enabled from v4.3.0, text has font smoothing:
![2](https://user-images.githubusercontent.com/195605/215273676-80358502-9cef-476b-86ee-81790c63b032.png)

With addonbar_status_in_addonbar.css enabled from v4.2.5, text is correct (no font smoothing).  There is though a thicker border above the text.
![3](https://user-images.githubusercontent.com/195605/215273687-6e6c16a4-8b34-4cd2-9129-2f0727530746.png)

Is there a way to show the URL with no font smoothing with v4.3.0?

Thank you for your help.

**Comment by Aris-t2** [comment]
@rbro 
I see what you mean, but the problem to be the text color there.

Test the new v2 build: https://github.com/Aris-t2/CustomCSSforFx/releases/
_(this also fixes the color for many lw-themes)_

```css
#statuspanel-label {
  color: inherit !important;
}
```

**Comment by rbro** [comment]
@Aris-t2
Thanks, it's still came through with font smoothing, but I realize now the problem was on my side.  I didn't have the about:config setting for gfx.text.disable-aa.  Changing it to true fixed it.

Thanks again for your help and building these customizations into Firefox.

**Comment by rbro** [comment]
@aris-t2
I'm having one other issue with bookmarks_toolbar_simulate_second_bm_toolbar.css.  I have "Bookmarks toolbar items" in the same row as my url bar.  When bookmarks_toolbar_simulate_second_bm_toolbar.css is disabled, I see my bookmark icons next to the url bar, but when I enable it, I get a blank row where it should be, but none of the icons are showing.  Is there something I need to do to tweak this?  Thanks.

**Comment by Aris-t2** [comment]
Try to reset your toolbar configuration in customizing mode and move bookmarks items to navigation toolbar.
Looks like this to me on Firefox 109-111:

![image](https://user-images.githubusercontent.com/6013569/215342830-45bb560e-eaac-40b4-884c-8b30fadcc796.png)
![image](https://user-images.githubusercontent.com/6013569/215342037-60c4803c-9ef5-4d67-b89d-5ed6a4837c78.png)
![image](https://user-images.githubusercontent.com/6013569/215342059-aee02ac3-1725-4f3e-98c3-e733b6010542.png)

**Comment by rbro** [comment]
Thanks, I had been using bookmarks_toolbar_simulate_second_bm_toolbar.css for this in prior versions.  Switching to use addonbar_extra_bookmarks_toolbar_below_navbar.css works great.  Is bookmarks_toolbar_simulate_second_bm_toolbar.css for something else?

**Comment by Aris-t2** [comment]
At some point in Fx80s/90s Firefox code changes required to use a different approach for all of this.
`bookmarks_toolbar_simulate_second_bm_toolbar.css` file is not part of this project anymore.

**Comment by rbro** [comment]
```bookmarks_toolbar_simulate_second_bm_toolbar.css``` is still in v4.3.0v3, or were you just keeping it there for users who haven't updated yet?  Either way, I'm good for now.  Thanks again.

**Comment by Aris-t2** [comment]
Forget what I said before. `bookmarks_toolbar_simulate_second_bm_toolbar.css` just needed an update for Fx 109+.
4.3.0v4: https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by rbro** [comment]
Perfect, thanks.  Is there a difference between ```addonbar_extra_bookmarks_toolbar_below_navbar.css``` and ```bookmarks_toolbar_simulate_second_bm_toolbar.css```?  Or do they effectively do the same thing?

**Comment by Aris-t2** [comment]
You are absolutely right. They do basically the same, I just forgot to update `bookmarks_toolbar_simulate_second_bm_toolbar.css`.

Many Fx versions ago `addonbar_extra_bookmarks_toolbar_below_navbar.css` was not required and only `bookmarks_toolbar_simulate_second_bm_toolbar.css` existed. Not sure why I kept both ;-)

**Comment by Ten2O** [comment]
Using "aeroblue" colors, only seems to be on the tab bar and not on the navbar?
![Control-V](https://user-images.githubusercontent.com/63513830/216499103-41b889c9-3986-410d-9895-e4d1810f321c.png)

**Comment by Aris-t2** [comment]
AeroBlue option  `@import "./config/color_variables_aero.css";` only works with browsers default theme (System theme - auto).
Did you disable `@import "./config/color_variables.css";` ?

Are you using this projects latest files?

**Comment by Ten2O** [comment]
> AeroBlue option `@import "./config/color_variables_aero.css";` only works with browsers default theme (System theme - auto). Did you disable `@import "./config/color_variables.css";` ?
> 
> Are you using this projects latest files?

Yes, yes, and yes.

**Comment by Aris-t2** [comment]
Not sure what exactly causes the issue on your end. Maybe the OS theme interferes somehow. The caption buttons on your screenshot don't seem to be the default ones, are they?

Try a clean setup of the latest files and only modify `tabs_below_navigation_toolbar.css` and the options seen on the screenshot.

![image](https://user-images.githubusercontent.com/6013569/216668836-3ab55132-e13b-49ce-b1a0-70a15266a2e3.png)
![image](https://user-images.githubusercontent.com/6013569/216668956-b295f63a-0d5c-4adb-b1d4-fce6e66e4231.png)

**Comment by Aris-t2** [comment]
I think we can close this. Everybody should be on Fx 110+ by now.
