### ISSUE TITLE
Bookmarks Toolbar is half-width with addonbar_move_bookmarks_toolbar_to_bottom.css enabled

### ISSUE THREAD

**Issue by pyksy** [Aris-t2/CustomCSSforFx#551]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so the issue report is most likely wrong here.

No.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

Fill Bookmarks Toolbar with bookmarks.
Enable ./css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css in userChrome.css.
Observe that the bookmark toolbar is only half width, with overflow icon at the middle.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-

The issue seems to be in current/css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css on line 81 in the latest release
https://github.com/Aris-t2/CustomCSSforFx/blob/60d33252343fa97916ee5a14f64e7d9b6e4e3618/current/css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css#L81
Replacing "50vw" with "unset" fixes the problem.

4. Screenshots showing the issue (drag & drop images into this post):

with "max-width: 50vw !important;":

![image](https://user-images.githubusercontent.com/9086962/214323872-9ddb59d1-e21c-4b0f-9201-0b739747f22d.png)

with "max-width: unset !important;":

![image](https://user-images.githubusercontent.com/9086962/214323945-4a35832a-6c6f-4fc9-9c7d-daa9d87d1756.png)

5. System information
- OS & OS version: Linux; Debian Unstable
- DPI / HiDPI (e.g. 100%, 125%...): 96 dpi
- Firefox version: 109.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): default
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): no

**Comment by Aris-t2** [comment]
Actually this happens on purpose. If there is no restriction bookmarks push (add-on) buttons out of the visible area.

If changing the value is a solution for you, you should keep it.
