### ISSUE TITLE
Window Contents cut in half for settings in menu

### ISSUE THREAD

**Issue by IIJohnnyRingoII** [Aris-t2/CustomCSSforFx#554]
Windows 10 Pro 22H2
Firefox 109.0.1
 Custom CSS for Firefox 109+
  Current version: 4.3.1

![image](https://user-images.githubusercontent.com/124267558/216331593-9891b32a-41ba-478b-a92c-871a1625a525.png)
![image](https://user-images.githubusercontent.com/124267558/216331697-c59572c6-a4ca-4fd6-85ac-2e4d274d7284.png)

**Comment by Aris-t2** [comment]
Test 4.3.1v2: https://github.com/Aris-t2/CustomCSSforFx/releases/

**Comment by IIJohnnyRingoII** [comment]
Thank you!  Both items that I pointed out as issues have been remediated.

![image](https://user-images.githubusercontent.com/124267558/216411077-dbe7db0e-758e-4078-9354-66d97057faff.png)

![image](https://user-images.githubusercontent.com/124267558/216411252-fe0319bc-b417-45f1-9cc0-acbabc4846e2.png)
