### ISSUE TITLE
Tabs Multi Line shows unneeded Scrollbar 

### ISSUE THREAD

**Issue by edeso** [Aris-t2/CustomCSSforFx#555]
1. Does the issue occur without any files inside /chrome/ folder?

NOPE

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

the issue appeared a while ago, after a firefox update. didn't note down which though.

using multilinetabs with smaller tabs for compactness results in Scrollbar shown always (see 4.). seems to be caused by a fixed css `height` attribute for the `.tab-label-container`. unsetting it as in the commented setting below spolves the issue. maybe it should be added to `tabs_multiple_lines.css` ?

```
@import "./custom_css_for_fx_v4.3.1v7/css/tabs/tabs_multiple_lines.css";

:root{
  --tabs-lines: 10;
  --tab_min_width_mlt: 100px;
  --tab_max_width_mlt: 200px;
  --tab-min-height_mlt: 24px; /* set own value here, if used without configuration files */
  --tab-min-height: 24px !important;
}

.tab-throbber, .tab-throbber-tabslist, .tab-icon-pending, .tab-icon-image, .tab-sharing-icon-overlay {
  height: 12px !important;
  width: 12px !important;
}

.tab-label-container {
  font-size: 11px;
  /* don't enforce height bigger than tab-min-height */
  /*height: unset !important;*/
}
```

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?

YES, latest release custom_css_for_fx_v4.3.1v7

4. Screenshots showing the issue (drag & drop images into this post):
![1line-before](https://user-images.githubusercontent.com/9976129/218094646-d3d2e4dc-d4f5-4fac-8670-be5f69f2ffac.JPG)
![before-3lines](https://user-images.githubusercontent.com/9976129/218094661-ef06e5eb-f958-4575-a8f5-1ae4b3bda4ee.JPG)
with `.tab-label-container {height: unset !important;}` set
![3lines-after](https://user-images.githubusercontent.com/9976129/218094674-4c2a0ebd-f6eb-4b64-83bb-be56020ece87.JPG)

5. System information
- OS & OS version:  Windows7/10
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 109.0.1
- Firefox theme (e.g. default, build in light/dark, external theme + link): build in dark
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': YES
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): YES

**Comment by Aris-t2** [comment]
Maybe changing dimension values or font sizes create a height miscalculation and show the scrollbar even where it is not required.

You can completely hide the scrollbar there:

```css
@-moz-document url(chrome://browser/content/browser.xhtml){
  scrollbox[part][orient="horizontal"]{
    scrollbar-width: none !important;
  }
}
```

**Comment by edeso** [comment]
good to know, but not my intention. scrollbar is needed is more tabs than `--tabs-lines` are open so that one can still scroll.

obviously the firefox default tab size is not supposed to be smaller cemented by the fixed `.tab-label-container` height. still, i don't see any technical necessity to enforce any height there, so unsetting it seems to be the most compatible solution.

however, just wanted to point it out. i can keep carrying it in my local css instead if you don't want to add it. just wanted to point it out.

btw. thanks so much for your work. using it for years now and like my firefox just so much better for it!

**Comment by Aris-t2** [comment]
I will add

**Comment by Aris-t2** [comment]
I will add this to `tabs_multiple_lines.css`:

```css
.tab-label-container {
  height: unset !important;
}
```

Have not seen any negative impact on other settings/configurations during my tests.

**Comment by edeso** [comment]
thanks again!
