### ISSUE TITLE
Forward/Back button too big when connected + round

### ISSUE THREAD

**Issue by ZTHawk** [Aris-t2/CustomCSSforFx#560]
When using "custom_backforward_connected" (all other settings default) then I have the following behaviour:
![grafik](https://user-images.githubusercontent.com/23618799/220447635-87b47840-0719-4850-8504-464c172208f5.png)

This started to happen with FF 108 or 109 (also happens with FF 110) while using CustomCSS 4.1.3.
Upgrading to 4.3.1v7 did not help.

**Comment by ZTHawk** [comment]
Possible fixes:
- Forward button (`.toolbarbutton-icon`)
  - add:
    - margin: 4px 0px 4px 0px !important
  - remove:
    - height: 100% important
- Back button (`.toolbarbutton-icon`)
  - remove:
    - height: 100% important

![grafik](https://user-images.githubusercontent.com/23618799/220456292-016329dd-140a-4f0c-9b76-7f42feaf06a3.png)

**Comment by Aris-t2** [comment]
Thanks, I will take care of this on next update.

Current dev build already offers the fix.
https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by Aris-t2** [comment]
Fixed in [v4.3.2](https://github.com/Aris-t2/CustomCSSforFx/releases/) release.

**Comment by ZTHawk** [comment]
This is not fixed with 4.3.2.
This is how it looks like now:
![grafik](https://user-images.githubusercontent.com/23618799/225130363-201e7670-9323-4d40-a066-d5ee440f3a32.png)

**Comment by Aris-t2** [comment]
That is very strange. I can not reproduce the issue seen on your screenshot.

Test compact/normal/touch modes on Firefox 110-113.

**Comment by ZTHawk** [comment]
I could identify the issue.
When enabling "forward_button_hide_when_disabled" then the forward button starts behaving differently.

**Comment by Aris-t2** [comment]
I found what was causing the issue.
Get 4.3.3v2: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.3.3

**Comment by ZTHawk** [comment]
It is fixed now. Thank you.
