### ISSUE TITLE
Latest nightly does not work with custom icons

### ISSUE THREAD

**Issue by owovin** [Aris-t2/CustomCSSforFx#563]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so the issue report is most likely wrong here.
No it does not

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Any Icon changing option now causes the entire sprite sheet to show up instead, either compacted or full on nightlys starting past 2023-02-22

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes

4. Screenshots showing the issue (drag & drop images into this post):
![1677086622](https://user-images.githubusercontent.com/26679713/220708071-058caed1-8af6-470f-9109-c4e51669299d.png)

5. System information
- OS & OS version:  Windows 10 LTSC
- DPI / HiDPI (e.g. 100%, 125%...):  100%
- Firefox version: Latest nightly at writing time (2023-02-22), checked with 2023-02-23 to see if it was not one off
- Firefox theme (e.g. default, build in light/dark, external theme + link): https://addons.mozilla.org/en-US/firefox/addon/c021/
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): Yes

if you dont take submissions from people on nightly, i understand :)

**Comment by Aris-t2** [comment]
Mozilla removed -`moz-image-region` rule in https://bugzilla.mozilla.org/show_bug.cgi?id=1817071

Since there won't be a replacement all images have to be extracted from icons sets and stored individually. 

I will keep this WIP in https://github.com/Aris-t2/CustomCSSforFx/issues/564

**Comment by Aris-t2** [comment]
Current [dev3](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.3.2pre) fixes all image images caused by deprecated  `-moz-image-region` rule .
