### ISSUE TITLE
[Firefox 112+] Mozilla removed -`moz-image-region` rule - icon sets are currently broken

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#564]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1817071

Settings currently affected by this change:
- custom icon sets for toolbar button options
- custom back/forward button options
- close icon options

Extracting all icons and pointing to them will take a while, so this will issue be marked as "WIP".

_Update_
Everything using `-moz-image-region` was changed in v4.3.2 dev3
- icon sets
- custom back/forward buttons
- close icons
- a few other icons/images

**Comment by Aris-t2** [comment]
In the end we have to switch to whatever Mozilla is currently using. So this time splitting image matrices into single images was the best option to go around this. A negative side effect the is the increased file size compared to what it was before. However, the archive only went from 500KB to 700KB ;-).

**Comment by ltsnow** [comment]
Works like a charm.  Thank you so much for fixing this so fast.  I use nightly more than I use the release and I really was missing the customized back-forward buttons.

BTW, you have the latest userChrome file mislabeled as 4.3.2dev instead of 4.3.3.  Thanks again.

**Comment by Aris-t2** [comment]
Such a step (using background position values) for image files containing 30+ images would be a big deal of work.

Anyways, I already split all of them, so there is no need for other solutions.

**Comment by Aris-t2** [comment]
Thanks for the note. Seems I overlooked `livemark-item.png`. Are those images even used by current Firefox?

Which graphic was it? I tried to remove images not used (or at least I thought so) by the available settings.

The "mix" icon set is indeed a combination of other sets. I will look into this.

**Comment by Aris-t2** [comment]
> It would be good, though, if you at least moved the old image files into [legacy](https://github.com/Aris-t2/CustomCSSforFx/tree/master/legacy) tree, when you finally publish v.4.3.2.

The images are part of the legacy tree already.
e.g. https://github.com/Aris-t2/CustomCSSforFx/tree/master/legacy/fx101-108/image

**Comment by Aris-t2** [comment]
[v4.3.2](https://github.com/Aris-t2/CustomCSSforFx/releases/) released.
