### ISSUE TITLE
Error in context menu

### ISSUE THREAD

**Issue by Roadfox-Master** [Aris-t2/CustomCSSforFx#567]
FF 110.0.1 64bit
Windows 8.1
custom_css_for_fx_v4.3.1

I use the context_bfrsb_labels_with_icons.css entry under generalui. Since version FF 110, the lines "Next, Previous, Reload and Bookmark the page" have been moved.
![Error_Kontext](https://user-images.githubusercontent.com/85829875/223039417-fe5f59db-f609-44ea-83b0-44046e975a54.jpg)

**Comment by Aris-t2** [comment]
This will be fixed on next update.

**Comment by Aris-t2** [comment]
Fixed in [v4.3.2](https://github.com/Aris-t2/CustomCSSforFx/releases/) release.

**Comment by nicolaasjan** [comment]
> Fixed in [v4.3.2](https://github.com/Aris-t2/CustomCSSforFx/releases/) release.

I have `custom_css_for_fx_v4.3.2hf2`, but in my Windows 7 VM it still looks like this (labels without icons):

![screenshot1](https://user-images.githubusercontent.com/14093220/226856575-be96f887-1c16-4381-b7d8-5bb30e238cba.png)

And in Nightly `113.0a1 (2023-03-21)` on Linux it's like this:

![screenshot2](https://user-images.githubusercontent.com/14093220/226858144-f0d35156-4402-4d75-ae2d-dc4b1ba052e3.png)

**Comment by Aris-t2** [comment]
Win 7 + Firefox 111 + [4.3.3 release](https://github.com/Aris-t2/CustomCSSforFx/releases/):

![image](https://user-images.githubusercontent.com/6013569/226992265-f38b214a-9df6-4466-8a25-e49f6c261797.png)

![image](https://user-images.githubusercontent.com/6013569/226992627-b9f7b9df-f9ec-48da-8d0d-f48dc9bc5bf7.png)

**Comment by Roadfox-Master** [comment]
If you use "context_bfrsb_labels_with_icons.css", this has problems when using "css/generalui/popup_compact_menus.css".

**Comment by Aris-t2** [comment]
Test this one:
[chrome1.zip](https://github.com/Aris-t2/CustomCSSforFx/files/11043658/chrome1.zip)

**Comment by nicolaasjan** [comment]
> If you use "context_bfrsb_labels_with_icons.css", this has problems when using "css/generalui/popup_compact_menus.css".

That was it. 😀️

Everything is OK now on both Linux and Windows 7 with version 4.3.3.

B.t.w., `popup_compact_menus.css` doesn't seem to do much, as far as I can see...

**Comment by migozz** [comment]
not working in 102 esr
