### ISSUE TITLE
Icons_custom_icons_cystal has icons_fx_firebird in the code

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#570]
I HOPE I CAN EXPLAIN THIS CORRECTLY - Thanks

There appears to be  **icons_fx_firebird** code in the **Icons_custom_icons_cystal.css** file

In the **Icons_custom_icons_cystal.css** file all the "**list-style-image: url**" are:

list-style-image: url("../../image/icons_fx_firebird/)

except for:

#back-button {
  list-style-image: url("../../image/icons_fx_crystal/back.png") !important;
}

#forward-button {
  list-style-image: url("../../image/icons_fx_crystal/forward.png") !important;
}

[https://github.com/Aris-t2/CustomCSSforFx/commit/f94c1b86983635ae5b6c17bacc34f509f8d142ef#diff-83ec82883545467cc9bc1de5f4ef385aa492a964fcd4f1a25d9ceaff347053f4]

1. Does the issue occur without any files inside /chrome/ folder? **NO**

2. Issue description, userChrome.css/**icons_custom_icons_crystal.css** 

3. The issue occurs with the most recent version of **CustomCSSforFx 4.3.2**

4. Screenshots showing the issue (drag & drop images into this post):

5. System information
- OS & OS version: **macOS 10.15.7 Catalina**
- DPI / HiDPI (e.g. 100%, 125%...): 
- Firefox version: **110.0.1**
- Firefox theme: **System Theme - Auto 1.3**
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': **YES**
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): **YES**

**Comment by Aris-t2** [comment]
Thanks for the note. I just posted a hotfix ([custom_css_for_fx_v4.3.2hf.zip](https://github.com/Aris-t2/CustomCSSforFx/releases)).
