### ISSUE TITLE
Add support for Photon style icons

### ISSUE THREAD

**Issue by Freemason-12** [Aris-t2/CustomCSSforFx#572]
I'm running latest firefox as of now (110) and I wanted to get back the old Photon style, especially icons, is there a way to do that?
I could not find support for it in this repo, is it planned?

**Comment by Aris-t2** [comment]
Not sure what you mean by photon icons, but this project offers many different icon styles. You can enable them in `userChrome.css`:

https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L176

Same applies to the tab style:

https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L542

**Comment by Aris-t2** [comment]
I will add icons from Firefox 88 on next update.

Most SVGs could be extracted from Fx88 files.

**Comment by Aris-t2** [comment]
Get [4.3.3](https://github.com/Aris-t2/CustomCSSforFx/releases/) release.

**Comment by Freemason-12** [comment]
> I will add icons from Firefox 88 on next update.
> 
> Most All SVGs could be extracted from Fx88 files. However download progress and reload animations will be used from current Firefox.

Thank you for the reply, and for the Photon styled icons too!
The only question is, will download progress and reload buttons are used from firefox 88?
