### ISSUE TITLE
Firefox logo on empty tab favicon

### ISSUE THREAD

**Issue by migozz** [Aris-t2/CustomCSSforFx#577]
1. Does the issue occur without any files inside /chrome/ folder?
no

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

- Set 'new tab' to empty page
- press 'new tab'
- there's a firefox logo instead of favicon

```
/* restore empty/missing tab favicon - [only use one at a time] *********************************/
@import "./css/tabs/missing_tab_favicon_restored_dotted.css"; /**/
```

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
yes

4. Screenshots showing the issue (drag & drop images into this post):
![fflogoactualexpected](https://user-images.githubusercontent.com/24635618/227459541-bc38d80f-fd6a-4e84-8461-0bd4ad05a94f.png)

5. System information
- OS & OS version: 7
- DPI / HiDPI (e.g. 100%, 125%...): 125
- Firefox version: 102 esr
- Firefox theme (e.g. default, build in light/dark, external theme + link): default
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): not present

**Comment by Acid-Crash** [comment]
I am not Aris-t2))) but I believe this is intentional

New tab = about:newtab which has its own favicon. 
So the missing_tab_favicon_restored_dotted.css will not work here
Also without CustomCSSforFx files it acts exactly the same (plain Firefox has Logo as a favicon for a new tab).

The task is more like you need to change favicon for a certain URL.

**Comment by migozz** [comment]
Why not create a new property?
https://support.mozilla.org/en-US/questions/1246646
https://www.reddit.com/r/FirefoxCSS/comments/kw043m/does_anyone_know_how_to_change_the_firefox/

I do not want a 'no icon', but the same as 'restore missing favicon'.

And why not? No one int'rest'd?

**Comment by Aris-t2** [comment]
You of course can use the code to linked above, if it works, but this is not what this projects preference was meant to achieve.

**Comment by tealkami** [comment]
Hi, could you **please** make a option to **Restore empty/missing tab favicon** will apply to "new tab page" too ?

or write some example, so everyone who search for it will find the solution to add to the css file
