### ISSUE TITLE
No "userChrome.css" or "userContent.css" files in my Profiles folder to edit.

### ISSUE THREAD

**Issue by Mugsy323** [Aris-t2/CustomCSSforFx#58]
The instructions for "CustomCSSfor Fx" say I must edit my userChrome.css and userContent.css files located among the Profiles for Firefox (reached using Shift+F2).

No such files exist _anywhere_ within my Firefox (v57) Profiles. Plenty of other css files, but not those two.

I downloaded the zip (which I found contains files by that name), but the instructions don't say exactly where they should be placed (I tried ".\skin\classic\" but it had no effect.)

Is every copy of Firefox supposed to already have these two css files? Apparently, some of us don't.

**Comment by Aris-t2** [comment]
Open  `about:support > Profile Folder > Open Folder`
(Now you see your profile folder)
Create a new folder called `chrome` there, if there is none.
Now extract the zip file there.
Done.

The instruction a clear on that one (see 1-3).
https://github.com/Aris-t2/CustomCSSforFx/#where-to-find-firefox-profile-folder-and-what-is-the-correct-location-for-user-styles

**Comment by Mugsy323** [comment]
Thanks. Steps 2 & 3 being under "MacOS" threw me.
