### ISSUE TITLE
[Custom tab colors + dark theme]  (Issue based on discussion 'Cant make colour changes')

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/CustomCSSforFx#586]
### Discussed in https://github.com/Aris-t2/CustomCSSforFx/discussions/582

<div type='discussions-op-text'>

<sup>Originally posted by **kkatee** April  7, 2023</sup>
So I had to update firefox today, which I generally avoid so I don't have to spend 2 hours getting the custom css just right again.

Almost everything is right, but I wanted to make some tweaks to the colours, but nothing I change seems to have any effect.

I have been editing the colours in config\color_vairables.css and in css\tabs\classic_squared_tabs.css and nothing I do seems to make any effect on the browser.</div>

**Comment by kkatee** [comment]
Thanks for responding.

I thought I did a fresh install before, but just to be sure I wiped the chrome folder and started from scratch with the latest version 4.3.5

Here are my tabs.

![image](https://user-images.githubusercontent.com/34851555/232174025-5dcaee78-0866-452a-93fd-dc014430ee0a.png)

I'm just trying to adjust the colours, but nothing I change seems to do anything.

**Comment by Aris-t2** [comment]
I found what causes the problem. You are using the default dark theme. For this to work specific variables have to be set, but their names might be confusing.

![image](https://user-images.githubusercontent.com/6013569/232227510-0800245a-562d-4555-8f5c-eafebfaff245.png)

The colors have to be set as gradients like on the screenshot.

**Comment by Aris-t2** [comment]
Anything new here?
Did the about info help?

**Comment by kkatee** [comment]
yes

**Comment by Aris-t2** [comment]
OK, this can be closed then.
