### ISSUE TITLE
[Fx112+ & custom icon sets - see #564] Top nav completely busted after update

### ISSUE THREAD

**Issue by buh6173** [Aris-t2/CustomCSSforFx#588]
While I can see that a new version has been released, I'm not fully clear on what I would need to update, so I'd like guidance before messing with the code myself.

This is what my top nav currently looks like:

![image](https://user-images.githubusercontent.com/1904875/232182751-6bb986c4-09f7-4d58-bf67-54eb4fa76cd7.png)

The back and forward buttons are completely bugged, and that clump of buttons to the right of search shouldn't be here.

**Comment by buh6173** [comment]
[userChrome (2).txt](https://github.com/Aris-t2/CustomCSSforFx/files/11238292/userChrome.2.txt)

Attached my userChrome as a text file, since I can't upload CSS files here.

**Comment by Aris-t2** [comment]
You have to at least replace the folders "css" and "icons" for the icons to be correct again. Due to a change by Mozilla image files containing multiple images had to be spit into single images.

Read the change log of [v4.3.2](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.3.2) and [this closed issue](https://github.com/Aris-t2/CustomCSSforFx/issues/564) for more info, but update to the latest release: [v4.3.5](https://github.com/Aris-t2/CustomCSSforFx/releases)

**Comment by buh6173** [comment]
I saw the changelog, but I'm unclear of what I need to do. Should I change the names of these folders?

**Comment by Aris-t2** [comment]
Just delete the old "css" and "image" folders and paste the ones from the latest release there.

**Comment by buh6173** [comment]
Now my navbar looks like this, with the tabs in the wrong part and they're colored wrong.

![image](https://user-images.githubusercontent.com/1904875/232260350-685cafc8-fad6-402b-8745-88bbf0d55a07.png)

**Comment by Aris-t2** [comment]
Most likely something went wrong.

Just start over with the latest release [v4.3.5](https://github.com/Aris-t2/CustomCSSforFx/releases) and redo the changes in `userChrome.css` one by one.

**Comment by buh6173** [comment]
I believe in a past update you produced a userchrome file that had what I needed; is it possible to fish out old issues to compare? Because I haven't altered it whatsoever since; the userchrome file is exactly what you provided, the only change should be the css/image folders.

**Comment by Aris-t2** [comment]
Use a tool like Notepad++. It has a "Compare" feature, where you can see two files side by side
The differences get highlighted.

**Comment by buh6173** [comment]
I have this enabled in my current:

 @import "./css/buttons/icons_custom_icons_old_chrome.css"; /**/

Is that a css that's no longer in the css folder?

There are many other little differences between the two files, and I don't know what are causing issues and what are just altered formatting. I uploading my userchrome in the second post of this issue.

**Comment by Aris-t2** [comment]
`icons_custom_icons_old_chrome.css` is still part of this.

Just copy & paste the content of the [latest release](https://github.com/Aris-t2/CustomCSSforFx/releases) into your chrome folder.

Compare both userChrome.css files, if needed.

**Comment by buh6173** [comment]
I have updated the latest release to the best of my capacity, and it is not working as intended.

![image](https://user-images.githubusercontent.com/1904875/232872158-4ee3a9bb-8156-4b0f-8f00-a0952be6d03f.png)

How do I get the tabs below my bookmarks?

For reference, here is my current UserChrome file:
[userChrome-temp.txt](https://github.com/Aris-t2/CustomCSSforFx/files/11265199/userChrome-temp.txt)

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L584

**Comment by buh6173** [comment]
That line shows up here in my code:

/* --------------------------------------------------------------
   TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS / TABS NOT ON TOP
   --------------------------------------------------------------

   [!] Note: only 'alt' works with multi-tab lines option.
   [!] Note: might require overriding url bars 'selection color' --> see corresponding area
*/

/* Windows/Linux */
 @import "./css/tabs/tabs_below_navigation_toolbar.css"; /*

/* MacOS */
/* @import "./css/tabs/tabs_below_navigation_toolbar_macOS.css"; /**/


/* Alternative for multi-lined tabs (Glitches might occur with inactive menubar!)
   [!] use option below for multiple tab lines support
*/

As you can see, it's not commented out, yet the tabs still are above everything. I tried commenting them again, and the same thing occurring.

**Comment by Aris-t2** [comment]
Remove/backup everything in your /chrome/ folder.

Extract zip files content to /chrome/ folder: 
[CSS.zip](https://github.com/Aris-t2/CustomCSSforFx/files/11283767/CSS.zip)


There is nothing else I can do or try in this case. There must be something wrong on your end.

**Comment by Aris-t2** [comment]
Sure, the userChrome.css is part of this:
![image](https://user-images.githubusercontent.com/6013569/233451805-173bf227-92fa-4c95-85ac-fac055610dd8.png)

**Comment by Aris-t2** [comment]
I already changed two settings from default inside the included userChrome.css file.

Tabs below bookmarks toolbar and the old chrome icon set, seen on your first screenshot.

**Comment by buh6173** [comment]
Sorry, one more question: ever since the last update, when I try to do basic math formulas in the search bar (i.e. "40/60"), it doesn't show me math results unless I type it as "40/60 =", whereas before it would. Is this a CSS thing, or a Firefox thing?

**Comment by Aris-t2** [comment]
CSS can only change the visual appearance, not browser functions.

Shouldn't math formulas point to your selected search provider? 

I did a quick test with Google, Bing and Yandex and "40/60" did offer correct results without adding a "=" to it.

**Comment by buh6173** [comment]
![image](https://user-images.githubusercontent.com/1904875/233857898-509a7a6b-6fcc-4332-bccb-5907d50cda13.png)

This is what I get. No clue what's causing this.

**Comment by hopalongrock** [comment]
Enable Hidden Secret Calculator in Mozilla Firefox Address bar

set preference
browser.urlbar.suggest.calculator
to TRUE

It works in search bar too.


![20230424 101441  ](https://user-images.githubusercontent.com/6840865/233939030-7ba1e681-f3cb-44c4-b5f4-a9c4e23dd8ec.jpg)
![20230424 101537  Window](https://user-images.githubusercontent.com/6840865/233939034-2fe57b02-1334-4bc7-a182-249277b0cf26.jpg)

**Comment by buh6173** [comment]
So that worked for the address bar, but not the search bar:

![image](https://user-images.githubusercontent.com/1904875/233944022-737ece16-4163-48a2-99ca-f4c3a36832ea.png)

![image](https://user-images.githubusercontent.com/1904875/233944146-d14f1b32-26c6-48a8-ab1f-40bb592309a8.png)

There don't appear to be any other calculator options in about:config.
