### ISSUE TITLE
Multiple lines add bookmarks (links)

### ISSUE THREAD

**Issue by Marcosdw** [Aris-t2/CustomCSSforFx#590]
Firefox: 112
Custom CSS Tweaks for Firefox v4.3.5

Hello,

In the multiple lines configuration (@import "./css/toolbars/bookmarks_toolbar_multiple_lines.css") I would like to leave the number of bookmarks free after the arrow.

![Capture d’écran 2023-04-17 150403](https://user-images.githubusercontent.com/18121470/232496573-0a558e5d-0a74-4651-86c8-60f633d505ef.png)

Thank you for your assistance

best regard

Marco

Sorry, I use a French English online translator

**Comment by Marcosdw** [comment]
Extend the number of bookmarks after the arrow

**Comment by Aris-t2** [comment]
Any news here?

**Comment by Marcosdw** [comment]
How not to limit the number of bookmarks

/* ----------------------------------
   BOOKMARKS TOOLBAR - MULTIPLE LINES
   ----------------------------------
   
   [!] only use one option at a time
   [!] the amount of visible bookmark items is limited internally to ~90-110 bookmarks

**Comment by Aris-t2** [comment]
You can not. This was hardcoded by Mozilla. Nothing we can do about.

90-110 was an approximate value back then, when this was fist written. It may differ now.

**Comment by Aris-t2** [comment]
Any news here?
Can this be closed now?
