### ISSUE TITLE
Bookmark Menu Drop Down items do not line up

### ISSUE THREAD

**Issue by AMGPilot** [Aris-t2/CustomCSSforFx#593]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Upgraded to 4.3.6 and now have an issue with bookmarks not lining up in the bookmarks menu drop down. They have a staircase effect going up from left to right.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes

4. Screenshots showing the issue (drag & drop images into this post):
![Bookmarks](https://github.com/Aris-t2/CustomCSSforFx/assets/33810954/674fa958-a222-4825-b1f8-e276fa34a9bd)

6. System information
- OS & OS version: Windows 10 Pro Version: 21H2
- DPI / HiDPI (e.g. 100%, 125%...): 100%
- Firefox version: 113.0 64bit
- Firefox theme (e.g. default, build in light/dark, external theme + link): 
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): Yes

**Comment by Aris-t2** [comment]
This is caused by `popup_compact_menus.css`.
Once you disable this option items are aligned "properly" again.

**Comment by AMGPilot** [comment]
Thank you very much for the quick reply. I prefer the compact bookmark menus, so I guess I will have to live with the alignment problem 😥
