### ISSUE TITLE
How exactly do i get the australis-like back button connected to search bar look?

### ISSUE THREAD

**Issue by masuyashi94** [Aris-t2/CustomCSSforFx#596]

**Comment by Aris-t2** [comment]
To get back/forward buttons connected to location bar, you need to place the buttons before location bar and enable this preference: https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L376

![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/20950e01-3489-4b26-bf22-74554a07134a)
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/bc5ef738-bd39-4670-b4f0-8182991346cf)



Use the discussion thread for questions like this in the future: https://github.com/Aris-t2/CustomCSSforFx/discussions/454

**Comment by Aris-t2** [comment]
We can close this now.
