### ISSUE TITLE
recentupdates_category_always_visible min-height issue

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#6]
Win10 Nightly58.
When entering about:addons and then clicking the **Recent Updates** button there is slight slide down effect.
I believe this is happening because of  min-height property.
According to other visible elements **min-height** should be set to 48px
![recentupdates_category_always_visible](https://user-images.githubusercontent.com/32600318/31356504-e1a2c952-ad46-11e7-8761-e54cb5af1199.png)
in module files
https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/css/aboutaddons/recentupdates_category_always_visible.css
**min-height** is set to 40px.
Guess this should be changed to 48px as the rest of the elements

**Comment by Aris-t2** [comment]
Thanks for reporting. 
Will be fixed on next update.

**Comment by Acid-Crash** [comment]
fixed in 1.04
