### ISSUE TITLE
Fix for support Firefox 102+ ESR

### ISSUE THREAD

**Issue by Shogo84** [Aris-t2/CustomCSSforFx#600]
1. Does the issue occur without any files inside /chrome/ folder?
no.

2. Issue description:
I found a solution for fixing support Firefox 102+ ESR.
I tested all versions, and fund out the last good version was 4.2.5v2.
So i checked what changed:
- in the new versions in tabs_below_navigation_toolbar.css in line 32: tabbrowser-tabs: **width: 100%**;
- i changed back to the older version: **width: 100vw;**
Then everything working fine, no small menu, no tearing, etc.
So it need to change back all **tabbrowser-tabs** tags to **vw**

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
yes

4. Screenshots showing the issue (drag & drop images into this post):

5. System information
- OS & OS version: W10pro
- DPI 100%, 125%
- Firefox version 102.0 - 102.11 
- Firefox theme: default, build in light/dark
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): not exists

**Comment by Aris-t2** [comment]
I've added the fixe to https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.2.8 release, because it is listed as the last one officially compatible with 102 ESR.

Post there again on this matter. Even if this is closed, I get an info about new posts.
