### ISSUE TITLE
Wrong icons in buttons_on_navbar_aero_appearance.css

### ISSUE THREAD

**Issue by riwarek** [Aris-t2/CustomCSSforFx#601]
Today I've made an update to new version of the script
```
  Custom CSS for Firefox 110+
  Current version: 4.3.6
```
When I try to use it with theese icons

`
@import "./css/buttons/buttons_on_navbar_windows_classic_theme_appearance.css"; /**/
`

I see
![obraz](https://github.com/Aris-t2/CustomCSSforFx/assets/22499151/b437ce05-a2d0-4726-96b5-d356932578c2)

I expect this rounded background should be present only when mouse pointer is hovering over the icon but now I see it constantly on all buttons. In previous versions this style wasn't affected with this.

**Comment by Aris-t2** [comment]
Fixed in 4.3.7.

Post here again, if there are issue with buttons_on_navbar_aero_appearance.css , even if this is closed.
