### ISSUE TITLE
The Aero theme of about:logins uses slightly darker blue colour than about:preferences & about:addons

### ISSUE THREAD

**Issue by Patricek0056** [Aris-t2/CustomCSSforFx#602]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
The Aero theme of `about:logins` uses different colour code than `about:preferences` & `about:addons`, which is resulting of darker blue colours in `about:logins`.

1. Import the `addons_manager_alternative_appearance_aero.css`, `addons_manager_alternative_appearance` and also `aboutlogins_alternative_appearance_aero.css`, and `aboutlogins_alternative_appearance.css` to userContent.css.
2. Now open the about:addons, and about:logins sites as tabs,
3. And then compare the colours.

#### Code inspection:
I've inspected, that the colour for `about:logins` is `#dbeaf9`, while the colour for `about:addons` and `about:preferences` is `#edf6ff`.

#### Expected results:
The `about:logins` should also use `#edf6ff` instead of `#dbeaf9`.

### 3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, I have the latest version installed.

### 4. Screenshots showing the issue (drag & drop images into this post):

About:addons background:
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/27646730-0d32-4fcc-a97f-6d8ca74a0fb2)

About:logins background:
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/1914da82-4e6b-4143-9793-6bbf45d90ec2)

### 5. System information
- OS & OS version: Windows 11 22621.1778 (64-bit)
- DPI / HiDPI: 100%
- Firefox version: v113.0.2 (64-bit)
- Firefox theme: Firefox UI Fix (https://github.com/black7375/Firefox-UI-Fix)
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): No

**Comment by Patricek0056** [comment]
I will immediately fill the other details

**Comment by Aris-t2** [comment]
Thanks for the note. This will be fixed on next release.

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.3.8test

**Comment by Patricek0056** [comment]
I'm closing this…

Oh, and you forgot to add a “Fixed” tag to this issue.
