### ISSUE TITLE
The extensions buttons, and Strata back & forward buttons with “buttons_on_navbar_aero_appearance.css” enabled in userChrome.css are glitched

### ISSUE THREAD

**Issue by Patricek0056** [Aris-t2/CustomCSSforFx#603]
### 1. Does the issue occur without any files inside /chrome/ folder?
- No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
- The extensions buttons, and Strata back & forward buttons are glitched with `buttons_on_navbar_aero_appearance.css` enabled in userChrome.css (See the screenshots).
- Well, the extensions navbar buttons didn't have drawn their borders correctly, and for Strata back & forward buttons, then there are three vertical lines (or Separators).

#### Expected results:
- The extensions buttons, and Strata back & forward buttons should be displayed normally.

### 3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
- Yes, I have the latest version (v4.3.7.).

#### Strata back & forward buttons, which have three vertical lines:
![Glitched Strata back forward buttons](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/b63695b0-cdff-4348-9db5-430fa8e2039d)

#### Here is how the Strata back & forward buttons should appear without these three vertical lines:
![Normal Strata back   forward buttons](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/76b0c589-42a4-4bf9-851c-0b4bb9ba9c68)

#### Here is an example, the QR Code extension navbar button which have glitched borders (Image is zoomed):
![Glitched extensions button](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/8e28a3da-b20d-48cc-91a0-e86c4315597b)

#### Here is how the navbar buttons should appear with correct borders (Image is zoomed):
![This is how the buttons should normally appear](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/095a8571-384e-40e6-a474-7bed0b1758c6)

### 5. System information
- OS & OS version: Windows 11 22621.1778 (64-bit).
- DPI / HiDPI: 100%
- Firefox version: Firefox v113.0.2.
- Firefox theme: Firefox UI Fix (https://github.com/black7375/Firefox-UI-Fix).
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes.
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): No.

**Comment by Aris-t2** [comment]
I could reproduce and fix the "aero appearance" glitch for toolbar buttons, but the one for connected "Strata" back/forward buttons does not occur for me on Fx 113 and 115.

Test https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.3.8test

**Comment by Patricek0056** [comment]
Thank you, I'm closing this.
