### ISSUE TITLE
The unclickable buttons with “buttons_on_navbar_classic_appearance.css”, or “buttons_on_navbar_classic_appearance_v2.css” enabled are not greyed out

### ISSUE THREAD

**Issue by Patricek0056** [Aris-t2/CustomCSSforFx#604]
### 1. Does the issue occur without any files inside /chrome/ folder?
- No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
- The unclickable buttons with `buttons_on_navbar_classic_appearance.css` enabled are not greyed out in the Navigation Toolbar (navbar).
- Also, the `buttons_on_navbar_classic_appearance_v2.css` is affected too.

#### Steps to reproduce:
1. Apply the `buttons_on_navbar_classic_appearance.css` to userChrome.css,
2. Install the [Global Media Controller](https://addons.mozilla.org/en-US/firefox/addon/mcx/) and add the button to Navigation Toolbar (navbar),
3. As you see, the Global Media Controller button is not greyed out.

#### Expected results:
- The unclickable buttons should be greyed out.

### 3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
- Yes, I have installed the latest version (v4.3.7).

#### The [Global Media Controller](https://addons.mozilla.org/en-US/firefox/addon/mcx/) button should be normally greyed out, but actually it isn't (Image is zoomed):
![Not greyed out button](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/4563b26c-b1ef-4d1c-b714-9f183c18f02f)

**NOTE:** Maybe the screenshot doesn't actually look like the `buttons_on_navbar_classic_appearance.css`, but I have applied the square corners from Firefox UI Fix.

### 5. System information
- OS & OS version: Windows 22621.1778 (64-bit).
- DPI / HiDPI: 100%
- Firefox version: Firefox v113.0.2
- Firefox theme: Firefox UI Fix (https://github.com/black7375/Firefox-UI-Fix).
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes.
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): No.

**Comment by Aris-t2** [comment]
Test https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.3.8test

**Comment by Patricek0056** [comment]
Is this your first test pre-release?

**Comment by Patricek0056** [comment]
Wait, it is intentional, that aero buttons doesn't have idle (unclicked, and unhovered) state empty?

**Comment by Patricek0056** [comment]
UPDATE 17:50 It is only partially affected, well, the greying out is not strong as in other toolbars, the icons are not greyed out correctly, can you consider fixing it? (Just ignore my third comment “Well, it is still affected in buttons_on_navbar_classic_appearance_v2.css”)

**Comment by Patricek0056** [comment]
> Yes. Only a hovered/clicked/active state is present.

But before this change, it was different.

**Comment by Patricek0056** [comment]
I'm closing this...
