### ISSUE TITLE
Firefox 117 - addonlists_show_buttons_instead_of_menu_popup.css - bug

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#610]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
When addonlists_show_buttons_instead_of_menu_popup.css is active on Addons page there is an unnecessary scrollbar
Steps to reproduce:
- activate addonlists_show_buttons_instead_of_menu_popup.css
- Go to about:addons and try clicking on the Settings button (gear icon)
- observe the popup styling

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes

4. Screenshots showing the issue (drag & drop images into this post):

With

![зображення](https://github.com/Aris-t2/CustomCSSforFx/assets/32600318/d4332dc6-7ae4-40eb-8562-de617b94323b)

Without

![зображення](https://github.com/Aris-t2/CustomCSSforFx/assets/32600318/27097f52-0b8c-463c-99ee-7f28a542150b)

5. System information
- OS & OS version: Win 10 x64
- DPI / HiDPI (e.g. 100%, 125%...): 100 
- Firefox version: default
- Firefox theme (e.g. default, build in light/dark, external theme + link): default
- Is 'about:config > toolkit.legacyUserProfileCustomizations.stylesheets' set to 'true': Yes
- Is 'about:config > layout.css.moz-box-flexbox-emulation.enabled' set to 'false' (Fx 108+): Yes (property is not present)

**Comment by Aris-t2** [comment]
This should help:

```css
addon-page-options panel-list {
  overflow-x: hidden !important;
}
```

**Comment by Acid-Crash** [comment]
Confirming.
This fixes the issue
