### ISSUE TITLE
Tabs on bottom with "System theme": tab scroll arrows disappear when focused

### ISSUE THREAD

**Issue by freonheat** [Aris-t2/CustomCSSforFx#611]
* Does the issue occur without any files inside /chrome/ folder?:  No
* Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

Enable tabs on bottom with:
@import "./css/tabs/tabs_below_navigation_toolbar.css";

It does move the tabs to the bottom.  However, if Firefox has focus, the tab scroll buttons disappear and only return if the Firefox window does NOT have focus.  It could be they are colored the same as the background with focus, making them seem invisible.  Not sure on that.  It does this with all other CustomCSSforFx set to their defaults. 

The problem does go away if a different, non-default theme (like Dark 1.2 or Light 1.2) is selected instead of the default "System theme - auto 1.3" is selected. 

* Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?  Yes

* Screenshots showing the issue (drag & drop images into this post):  Attached screenshots of focused and unfocused Firefox.
![focused](https://github.com/Aris-t2/CustomCSSforFx/assets/53980125/e1256946-6daf-4ae7-84d4-60187e313a37)
![unfocused](https://github.com/Aris-t2/CustomCSSforFx/assets/53980125/83c41c05-e6e9-4960-b215-c1b99dda6124)

6. System information
- OS & OS version: Linux Mint 21.2, Cinnamon
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): Default 1080P, no scaling.
- Firefox version: 116.0.2, vanilla from Mozilla (not Mint package)
- Firefox theme (e.g. default, build in light/dark, external theme + link):  Default Firefox "System theme - auto 1.3"

**Comment by Aris-t2** [comment]
The buttons/icons are actually there, but hardly visible on your screenshot.

Unfortunately you can not modify the colors of tab scroll arrows using this projects files or just userChrome.css. 

The other buttons on tabs toolbar can be made visible using this:

```css
#TabsToolbar-customization-target > toolbarbutton {
	color: red !important;
	fill: red !important;
	strike: red !important;
}
```

The workaround is an author CSS script using JavaScript: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/css_loader_author.uc.js

HowTo: https://github.com/Aris-t2/CustomJSforFx

```js
var my_code = `
	/* Paste any CSS code here. */
	/* Make sure your code is not inside any "@-moz-document / url / url-prefix" queries or it might not work. */
#tabbrowser-arrowscrollbox::part(scrollbutton-up), 
#tabbrowser-arrowscrollbox::part(scrollbutton-down) {
	color: red !important;
	fill: red !important;
	strike: red !important;
}
	`;
```

**Comment by freonheat** [comment]
Thanks for the info!  I guess it must be the theme color just was identical to the color they chose for the arrows!  I am glad it isn't a bug.
