### ISSUE TITLE
Missing buttons and weiard appearance

### ISSUE THREAD

**Issue by KimmoK00** [Aris-t2/CustomCSSforFx#614]
1. Does the issue occur without any files inside /chrome/ folder?
Yes

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Minimize, maximize, and close buttons do not appear correctly. After i use some other program or visit desktop or change FF window size, firefox looks weiard. This happens after FF 117.0 update. I changed these from the default settings:
config/color_variables_aero.css
buttons/buttons_on_navbar_glass_appearance.css
buttons/buttons_on_navbar_more_compact_mode.css
buttons/buttons_on_bookmarks_toolbar_aero_appearance.css
buttons/unified_extensions_button_hidden.css
appbutton/appbutton_in_titlebar_semi_transparent.css
tabs/tab_icon_inactive_tabs_lower_opacity.css
toolbars/bookmarks_toolbar_above_navigation_toolbar
toolbars/general_toolbar_colors_aeroglass_windows10_glass8.css
locationbar/compact_mode_reduce_fontsize.css

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes i use 4.4.1.v2

4. Screenshots showing the issue (drag & drop images into this post):

![FF117](https://github.com/Aris-t2/CustomCSSforFx/assets/34407632/e7a9a8c4-8f24-4754-bed4-7bc2ee9a956a)

5. System information
- OS & OS version: Win10 Pro 64bit
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 150%
- Firefox version: 117.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): Default

**Comment by Aris-t2** [comment]
Does the issue occur with DPI set to 100%?

Dies the issue occur with default OS theme?

**Comment by Aris-t2** [comment]
I think `general_toolbar_colors_aeroglass_windows10_glass8.css` causes the issue.

Most likely `-moz-default-appearance: -moz-win-borderless-glass !important;` is not supported by Firefox 117+ anymore.

**Comment by KimmoK00** [comment]
THANKS, you are right. I disabled this setting and Firefox works again.
