### ISSUE TITLE
tab_audio_icon_colorized stopped working with latest version

### ISSUE THREAD

**Issue by CrazieIvan** [Aris-t2/CustomCSSforFx#615]
1. Does the issue occur without any files inside /chrome/ folder?
...

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

-- Yesterday I updated from v4.1.6 to v4.4.1v2 because the latest FF update broke the padding on the bookmark toolbar, which seems to be fixed now.  
But now I can't set a custom color for the tab audio icon, like I had it with version v4.1.6 before.

Just like before, I have these two settings enabled under TAB SETTINGS in userChrome.css:
```
@import "./css/tabs/tab_audio_icon.css"; /**/
@import "./css/tabs/tab_audio_icon_colorized.css"; /**/
```

and then I set my preferred custom audio icon color in tab_audio_icon_colorized.css:
```
.tab-icon-overlay[soundplaying] {
   /*  fill: #058B00 !important;/* var(--green-70) */
  fill: #FFFF00 !important;/* var(--green-70) */
}
```
where FFFF00 is yellow instead of the default green.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-- Yes

4. Screenshots showing the issue (drag & drop images into this post):

-- I see the default green color instead of my custom one:
![default](https://github.com/Aris-t2/CustomCSSforFx/assets/69615600/6d45ebfb-8c06-4eca-8be5-de07d68a38f1)

For comparison here is the custom yellow I had with the old version v4.1.6
![yellow](https://github.com/Aris-t2/CustomCSSforFx/assets/69615600/9bfe3f9d-cf22-41c2-ba47-66b841ee93a9)

5. System information
- OS & OS version: **Win 10 x64 22H2 build 19045.3324**
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): **100%**
- Firefox version: **117.0 (64-bit)**
- Firefox theme (e.g. default, build in light/dark, external theme + link): **Dark 1.2**

Thanks!

edit:  A small clarification - I don't know in which version exactly this stopped working because I updated from a much older version.

**Comment by Aris-t2** [comment]
Did you modify the second group of rules too?
https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/css/tabs/tab_audio_icon_colorized.css#L26

There is one specific for dark LW-themes.

**Comment by CrazieIvan** [comment]
No, that seems to be a whole new block of code added there since the old version used, and I didn't even notice it.  I have no idea what any of it means though, so some help would be appreciated.  

I just want to know exactly what I need to modify to change the icon color, both for sound playing and sound muted, if possible.  Thanks!

**Comment by CrazieIvan** [comment]
Are you saying that the one I changed is the wrong one?  Or do I need to change multiple things?

**Comment by Aris-t2** [comment]
Colors in CSS can be used through color names or hex, rgba and hsla codes.

https://www.w3schools.com/tags/ref_colornames.asp
https://johndecember.com/html/spec/colorrgbadec.html
https://www.w3schools.com/html/html_colors_hsl.asp
