### ISSUE TITLE
Request: Setting to remove "Search History" from the History menu item.

### ISSUE THREAD

**Issue by Nicholas-Steel** [Aris-t2/CustomCSSforFx#616]
Is it possible to configure the contents of menus? If yes, can there be a setting added to remove the newly added "Search History" from the History menu item? I'm never going to use it.

The search functionality seems to be a recent feature of Firefox (v117?).

**Comment by Nicholas-Steel** [comment]
Thank you, that snippet works fine when I take advantage of the my_userChrome.css file mentioned at the end of userChrome.css

What would the syntax be for Synced Tabs option in the History Menu? I tried 

#appMenuSearchHistory,
#menu_searchHistory {
  display: none !important;
}

without success. Is there a place I can go to to see the relevant names/terminology for menu items?

**Comment by Aris-t2** [comment]
You can use browser devtools to inspect almost every item to look for names/ids/classes. The howto can be found on the main page: https://github.com/Aris-t2/CustomCSSforFx#how-to-find-item-ids-and-attributes

**Comment by glennpc** [comment]
@Nicholas-Steel Try this:

#sync-tabs-menuitem { display: none !important; }

That works for me.

**Comment by Nicholas-Steel** [comment]
It seems Firefox 143 has now rendered the supplied solutions out of date/non-working.
