### ISSUE TITLE
[CSS rules for AeroGlass removed in Fx 117+] Crashes with AeroGlass transparency (glass8.eu) [Workaround: Fx 115 ESR]

### ISSUE THREAD

**Issue by CO-Windler** [Aris-t2/CustomCSSforFx#617]
I am using "CustomCSSforFx-master_v4.3.4.zip" on an old Win10 together with AeroGlass by glass8.eu on my Thinkpad X61t.

Since the Firefox browser update to 117.0 the glass8.eu extension for toolbars again causes a fatal crash. Starting Firefox, its window appears frameless, incomplete and shrivels smaller (resizes itself) until it almost disappears. (I can only close it through taskbar.) Firefox is unusable when enabled.

So I had to disable it by commenting out this line:

/* @import "./css/toolbars/general_toolbar_colors_aeroglass_windows10_glass8.css"; /**/

Please fix this. Firefox looks terrible with default white Win8-style titlebar buttons and missing AeroGlass transparency effects.

The same crash already happened before with the browser update to 109.0.

see https://github.com/Aris-t2/CustomCSSforFx/issues/548

**Comment by CrazieIvan** [comment]
i can confirm, this setting breaks the UI using the latest version 4.4.1.  My browser doesn't really look different, but I can't drag windows with the mouse, and the standard buttons in the top right corner are missing (close, minimize, maximize).  I am able to close from the FF button on the left.

**Comment by Aris-t2** [comment]
Firefox 117+ does not support AeroGlass rules anymore. Therefore `general_toolbar_colors_aeroglass_windows10_glass8.css` and the Software Glass8 can not be used anymore.

Firefox 115 ESR should still be able to for a while.

**Comment by Aris-t2** [comment]
I've added a note about this to latest release. Nothing more I can do after Mozillas code changes.
[Custom CSS tweaks for Firefox v4.4.2](https://github.com/Aris-t2/CustomCSSforFx/releases)

**Comment by Aris-t2** [comment]
Does this preference help?
`about:config` > `browser.theme.windows.accent-color-in-tabs.enabled`
