### ISSUE TITLE
classic_squared_tabs problem in new firefox version.

### ISSUE THREAD

**Issue by Darlat** [Aris-t2/CustomCSSforFx#619]
1. Does the issue occur without any files inside /chrome/ folder?
No.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
With classic_squared_tabs (and the australized version too.):
When moving tabs around the padding/margin changes.
The problem seems to be that 118 adds a #tabbrowser-tabs[movingtab]{padding-bottom: 15px;margin-bottom: -15px} section since removing the padding and margin in my_userChrome fixes it.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes.

4. Screenshots showing the issue (drag & drop images into this post):
![1](https://github.com/Aris-t2/CustomCSSforFx/assets/15280788/818af2ee-3ea2-4447-aa67-6d9200d1a769)
![2](https://github.com/Aris-t2/CustomCSSforFx/assets/15280788/bca4eb71-bc8f-4b72-8050-f2f4e03cbb7a)

5. System information
- OS & OS version: Windows 10x64
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: 118.0.1
- Firefox theme (e.g. default, build in light/dark, external theme + link): Space Fantasy 1.0 (https://addons.mozilla.org/en-US/firefox/addon/space-fantasy/)

**Comment by Aris-t2** [comment]
I could fix this on my end by modifying `classic_squared_tabs.css` file.
Test this:  [tabs.zip](https://github.com/Aris-t2/CustomCSSforFx/files/12767474/tabs.zip)

**Comment by re11ding** [comment]
That fixed it for me!

**Comment by Aris-t2** [comment]
[Custom CSS tweaks for Firefox v4.4.2](https://github.com/Aris-t2/CustomCSSforFx/releases)
