### ISSUE TITLE
Firefox V57 Active Tab Color

### ISSUE THREAD

**Issue by bit-blit** [Aris-t2/CustomCSSforFx#62]
Referred here from ghacks...

Firefox 57 - would like to change the ACTIVE tab color (currently using the stock "Dark" theme). I know there is a blue bar above the active tab, but I really, REALLY, liked the way the active tab looked in Firefox 56 (solid blue). Any way to change this using CSS ? I want to keep the "Dark" theme, just change the color of the active tab - that's it. It should be able to be done using CSS, but I don't know how. Yeah, I'm a newb but WANT TO LEARN!

Thank you for your time....

**Comment by Aris-t2** [comment]
It is possible. This project contains a file to change active tabs background code, which also works for default tabs. Look for "custom_colors_for_squared_tabs_australized.css" inside tabs category, if you want to change active tabs color or for "custom_colors_for_squared_tabs.css", if you want to change all tabs.
You will have to edit the files and use the code you need.

In the future, if you have questions, use the general support thread like suggested inside new issue template. That way more users see your request and you probably get an answer faster.

This issue area is for reporting problems this projects file may cause.
https://github.com/Aris-t2/CustomCSSforFx/issues/41
