### ISSUE TITLE
tabs_below_nav / tabs_multiple_lines not playing together

### ISSUE THREAD

**Issue by Shdwdrgn** [Aris-t2/CustomCSSforFx#620]
1. Does the issue occur without any files inside /chrome/ folder? no
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
When using tabs_below_navigation_toolbar and tabs_multiple_lines together, the tabs are placed over the top of the other navigation components.  Toolbar does not expand to the required height.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Well I loaded the latest versions of each, is this question implying there are other files required that aren't mentioned in files I'm using?

4. Screenshots showing the issue (drag & drop images into this post):
I'll have to back out my changes and restart firefox to try and get this for you.

5. System information
- OS & OS version:  Debian Buster
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 1600x1200
- Firefox version: 115.3.0esr
- Firefox theme (e.g. default, build in light/dark, external theme + link): default

So the point of all this is to mention that the toolbar does not expand to match the size of the multiline tab area.  The fix for this is pretty straightforward, I just had to add the following:

`#navigator-toolbox {
        padding-bottom: calc(var(--tabs-lines) * var(--tab-min-height_mlt));
}`

Note that in an older version of this code (I was using it since FF68) a similar definition was made but appears to have been removed since then.  I'm not sure if this version might be more 'correct' for this problem?

`#main-window:not([chromehidden*="toolbar"]) #navigator-toolbox {
  padding-bottom: calc(0px + var(--tab-min-height_tnot)) !important;
}`

**Comment by Shdwdrgn** [comment]
Screenshot of toolbar
![tabs](https://github.com/Aris-t2/CustomCSSforFx/assets/7946628/40cb01b0-2b16-44f3-b764-96433aae171e)

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L652
https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L592

Are you using the correct options?

**Comment by Shdwdrgn** [comment]
Ah, I had no idea this file existed, seems like things have changed quite a bit since the old days.  I'll go through it later tonight and see what I need to configure to make use of this.  Thanks for the pointer!

**Comment by Shdwdrgn** [comment]
I finally had a chance to look into this again today.  After loading up your userChrome.css file, I went through and made sure the following were enabled...

```classic_squared_tabs.css
tab_close_always_visible.css
tabs_below_navigation_toolbar.css
tabs_below_navigation_toolbar_alt.css
tabs_multiple_lines_force_newtab_button_visibility.css
tabs_toolbar_adjustments.css```

The css files were moved to the folders specified in the userChrome file

**Comment by Shdwdrgn** [comment]
Sorry, clicked the wrong button!

**Comment by Shdwdrgn** [comment]
Oh I think I finally figured it out... `tabs_below_navigation_toolbar` I need to use only the alt version, NOT the regular version!  Looks like things are back to normal again.  Thanks for the pointers above!
