### ISSUE TITLE
[Location bar] issues with missing results within location bar popup

### ISSUE THREAD

**Issue by stampis** [Aris-t2/CustomCSSforFx#623]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
The recent changes to "ac_popup_megabar_title_and_url_two_lines" and "ac_popup_megabar_suggest_label_hidden"  (>4.4.2)
The addition of ".urlbarView-row[label]," makes it so that the first result in the locationbar is not shown,
If i for example type "tw" in the locationbar on version 4.4.1 the first suggested result is twitch.com, the second is Youtube, the third is PageX and the fourth is PageY, after updating to 4.4.2v2 it just shows Youtube, PageX, PageY as suggested, the first one is missing from the list.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes

4. Screenshots showing the issue (drag & drop images into this post):
![Locationbar](https://github.com/Aris-t2/CustomCSSforFx/assets/314742/14b0f326-5edd-46b2-a4c3-32b75a26ae9e)

5. System information
- OS & OS version: Win 10 x64
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: 118.0.1
- Firefox theme (e.g. default, build in light/dark, external theme + link):  dark

**Comment by Aris-t2** [comment]
Test v3: [custom_css_for_fx_v4.4.2v3.zip](https://github.com/Aris-t2/CustomCSSforFx/releases/download/4.4.2/custom_css_for_fx_v4.4.2v3.zip)

**Comment by stampis** [comment]
v3 fixed the issue in "ac_popup_megabar_title_and_url_two_lines"
But the problem occurs if you enable "ac_popup_megabar_suggest_label_hidden" this file remains unchanged in v3 compared to v2.

**Comment by Aris-t2** [comment]
Good we have an infinite amount of possible versions after 4.4.2 ;-)
