### ISSUE TITLE
Locationbar: "Search with ..." overlaps first history entry

### ISSUE THREAD

**Issue by ThiefMaster** [Aris-t2/CustomCSSforFx#624]
1. Does the issue occur without any files inside /chrome/ folder?
Not applicable, because the locationbar is styled differently without this project's CSS.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Using the same settings I had before in 4.1.2 (ie I took the new config files and disabled stuff I had disabled in the old version and enabled stuff I had enabled before): [userChrome.css](https://github.com/Aris-t2/CustomCSSforFx/files/12810045/userChrome.css.txt), [userContent.css](https://github.com/Aris-t2/CustomCSSforFx/files/12810046/userContent.css.txt)

4. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, latest release.

5. Screenshots showing the issue:
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/179599/4b6afe60-da68-4eb4-9ab3-14af755c87a7)

6. System information
- OS & OS version: Win 10 22H2
- DPI/HiDPI/scaling value: n/a (100%)
- Firefox version: 119.0b5
- Firefox theme: Dark 1.2

**Comment by Aris-t2** [comment]
This was fixed with v4.4.2.
