### ISSUE TITLE
[request?] [bug?] aero titlebar 

### ISSUE THREAD

**Issue by AbdAbd10** [Aris-t2/CustomCSSforFx#63]
is there a way to add the aero   titlebar option  so it can work with win7 or the aeroglass app

**Comment by Aris-t2** [comment]
I need more info about this request.

On Window 7 the Aero titlebar is there by default. On Windows 8 and 10 you need additional tools like Glass8 to create Aero transparency. Further more, you need to set own/custom window colors in Windows 10s window settings.

This is how it looks on Windows 7:
![aero](https://user-images.githubusercontent.com/6013569/32990083-29642438-cd23-11e7-8d8f-77d7fc030e8b.png)

**Comment by AbdAbd10** [comment]
i'm using win 10 with aeroglass or as u called it glass8 and i was using waterfox with the classic theme restorer add-on and there was an option in the toolbars section for it
![untitled](https://user-images.githubusercontent.com/13531611/32990796-aafafd9c-cd40-11e7-9840-8808b309a85f.jpg)
to make the browser titlebar transparency work

**Comment by Aris-t2** [comment]
While using that code is possible, it does not work as expected.

Titlebar gets transparent, but also unclickable. Not sure, if Glass8 can solve the issue, but in its current state this CTR feature is not suitable for this project.

Test it by adding this code to userChrome.css:

```css
#main-window:not([customizing]){
  background-color: transparent !important;
} 
```

Try to set titlebar colors in your Windows 10s customizing settings. Maybe it works with Glass8.

**Comment by AbdAbd10** [comment]
i tried the code and my firefox won't even open
![untitled](https://user-images.githubusercontent.com/13531611/32991666-bb34e096-cd50-11e7-86fe-1f155d34e034.jpg)

and i don't think it because of the windows 10s customizing settings
cause glass8 works with everything else even google chrome but not with firefox without the classic theme restorer add-on although i thought the new firefox has the same interface of google chrome so no need scripts to make it work but i guess it's not

**Comment by Aris-t2** [comment]
I don't think I can help you with this one. Looks like its not possible anymore, or at least not the way it was before.

**Comment by AbdAbd10** [comment]
no problem and thank you for your try and i hope u the best in your life
