### ISSUE TITLE
[macOS] [icons+text mode/text mode] Toolbar buttons lost background color

### ISSUE THREAD

**Issue by Anfaenger12345** [Aris-t2/CustomCSSforFx#630]
Toolbar buttons have changed

configured here: userChrome.css
<img width="788" alt="userChrome css" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/dfd07b18-fc4e-4880-9e1d-5ed5043c7160">

Firefox 118.0.2 with CustomCSSforFx 4.3.5
everything fine.
![1](https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/833af1dd-542c-4980-ae92-72ed11191da5)

Firefox 119 with CustomCSSforFx 4.4.3v2
Buttons wrong
<img width="481" alt="3" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/57334a15-8c39-4535-ba83-a1b3e5bcb768">

5. System information
- OS & OS version: Windows 11 & MacOS div. Versions
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 
- Firefox version: 119
- Firefox theme (e.g. default, build in light/dark, external theme + link):

**Comment by Aris-t2** [comment]
Have you tried to disable this option: https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/userChrome.css#L225

**Comment by Anfaenger12345** [comment]
thanks for the quick response
now yes :)

On MacOs 11.7.10:  in light mode, both are visible, but not visible when the button is pressed.
in dark mode the writing is not visible.
<img width="534" alt="Bildschirmfoto 2023-10-25 um 18 56 43" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/4f6858b8-2266-495a-87e6-2503c153dfb4">
![Bildschirmfoto 2023-10-25 um 19 29 15](https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/30b97f6a-8fe9-4fbf-b806-cf74e258f941)
<img width="452" alt="Bildschirmfoto 2023-10-25 um 18 57 19" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/d5c69406-71ae-4246-823e-799ee76b1527">


WIN11: both are visible, but not visible when the button is pressed.

**Comment by Aris-t2** [comment]
Test [v4.4.5 release](https://github.com/Aris-t2/CustomCSSforFx/releases/).

**Comment by Anfaenger12345** [comment]
win11 everything works fine 👍 

Mac os nothing works with this setting
<img width="627" alt="Bildschirmfoto 2023-10-29 um 12 30 16" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/0e310710-f9f7-4182-a511-3bd9c3e1aa45">


not right with this setting
<img width="681" alt="Bildschirmfoto 2023-10-29 um 12 30 41" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/1a9f73d4-7485-46cf-bec1-bc75228360b8">


<img width="421" alt="Bildschirmfoto 2023-10-29 um 12 07 29" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/5be6f90e-b1f2-4d92-ad66-5000ad82ec2a">

**Comment by Aris-t2** [comment]
Test this version:
[test_20231030912.zip](https://github.com/Aris-t2/CustomCSSforFx/files/13202271/test_20231030912.zip)

**Comment by Anfaenger12345** [comment]
thank you :)
just tested quickly:

bright mode macOS:
when moving the mouse over the button  the button changes color 👍, when you press it, it stays bright and doesn't change color anymore.
<img width="166" alt="Bildschirmfoto 2023-10-30 um 19 32 27" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/ca2521f9-6904-496c-9afb-cd82d3ad4b67">

dark mode macOS:
font white, otherwise like light mode
<img width="186" alt="Bildschirmfoto 2023-10-30 um 19 35 51" src="https://github.com/Aris-t2/CustomCSSforFx/assets/148944068/f598fe95-d74a-40fd-b74c-b6ecc791a16d">

**Comment by Aris-t2** [comment]
[4.4.6 release](https://github.com/Aris-t2/CustomCSSforFx/releases) will take care of this.

**Comment by Anfaenger12345** [comment]
many thanks
Everything is working fine again 👍👍👍

**Comment by Aris-t2** [comment]
Great to hear.
