### ISSUE TITLE
[OS dark theme] Firefox 119 Dark Mode Address Bar Coloring Issue

### ISSUE THREAD

**Issue by gashtal** [Aris-t2/CustomCSSforFx#631]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
I just got the Firefox 119.0 update and now the area around the address bar and the active tab do not follow the browser theme. I am using the Dark theme, but the aforementioned locations are all white. Settings Firefox to dark mode and using the attached userChrome file should be enough to replicate the problem. Issue might be related to #627.

[userChrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/13169003/userChrome.zip)

4. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, using v4.4.3v3.

5. Screenshots showing the issue (drag & drop images into this post):
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/27990818/d4c2f745-816a-4828-a818-e39bc18490aa)
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/27990818/cf85180b-46d4-407d-a107-6eb255dbf5a5)

6. System information
- OS & OS version: Windows 10 22H2
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: 119.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): Dark

**Comment by kandeefloss** [comment]
That's because the background color is hardcoded as almost white and doesn't care about the dark mode.
I've found at least two places:
- [general_toolbar_colors.css](https://github.com/Aris-t2/CustomCSSforFx/blob/5ec2ba4d7164f593c03365824028aa5e1214789f/current/css/toolbars/general_toolbar_colors.css#L7) (line 7-8)
- [tabs_below_navigation_toolbar.css](https://github.com/Aris-t2/CustomCSSforFx/blob/5ec2ba4d7164f593c03365824028aa5e1214789f/current/css/tabs/tabs_below_navigation_toolbar.css#L7)

**Comment by gashtal** [comment]
@kandeefloss Those lines do not seem to have been changed in years. This issue occurred starting with FF 119. It did not happen with older versions using the Dark theme.

**Comment by ingyrid** [comment]
![same same](https://github.com/Aris-t2/CustomCSSforFx/assets/136756708/762f1b98-c6a9-496f-85ce-3412d2677e2a)

I am experiencing the very same thing after updating to 119.

**Comment by iG8R** [comment]
Also Extensions, More tools... and Application menu began to suffer the same thing.

<img src="https://github.com/Aris-t2/CustomCSSforFx/assets/11407417/521a27f9-36e4-4a8e-aa42-ac307038f316" width="250">
<img src=" " width="250">

**Comment by paschott** [comment]
Same thing for me. Just upgraded to FF v119 and the address bar and such are off.  Assuming something changed w/ that version of Firefox.

**Comment by iG8R** [comment]
As a temporary measure, I added the following to `my_userChrome.css`:

```
:root:-moz-lwtheme {
  toolbar, panel {
    color-scheme: black !important;
  }
}
```

**Comment by gashtal** [comment]
> As a temporary measure, I added the following to `my_userChrome.css`:
> 
> ```
> :root:-moz-lwtheme {
>   toolbar, panel {
>     color-scheme: black !important;
>   }
> }
> ```

Doesn't to work in my case. :(

**Comment by Serpens66** [comment]
I had the same issue and it has to do with the "Theme" chosen for Firefox!

When you have the Theme **"System Theme automatic 1.3"** from Mozilla (and have system mode dark) the issue happens like in the screenshot from OP.
But when you instead choose the **"Dark 1.2"** from Mozilla, everything looks fine.
(don't know if these are the exact names for the themes, I only see their german name)

**Comment by gashtal** [comment]
> I had the same issue and it has to do with the "Theme" chosen for Firefox!
> 
> When you have the Theme **"System Theme automatic 1.3"** from Mozilla (and have system mode dark) the issue happens like in the screenshot from OP. But when you instead choose the **"Dark 1.2"** from Mozilla, everything looks fine (at least with my "userChrome.css" settings, did not test vanilla) (don't know if these are the exact names for the themes, I only see their german name)

Confirmed. The problem only happens with the "System" theme which automatically switches between light and dark system based on OS theme. If the "Dark" theme is chosen instead, problem goes away.

**Comment by Aris-t2** [comment]
> That's because the background color is hardcoded as almost white and doesn't care about the dark mode. I've found at least two places:
> 
> * [general_toolbar_colors.css](https://github.com/Aris-t2/CustomCSSforFx/blob/5ec2ba4d7164f593c03365824028aa5e1214789f/current/css/toolbars/general_toolbar_colors.css#L7) (line 7-8)
> * [tabs_below_navigation_toolbar.css](https://github.com/Aris-t2/CustomCSSforFx/blob/5ec2ba4d7164f593c03365824028aa5e1214789f/current/css/tabs/tabs_below_navigation_toolbar.css#L7)

Being "hardcoded" should not matter in this case. The code gets excluded for lw-themes. Meaning when using any theme the "hardcoded" colors get ignored.

The issue seen on all screenshots did not occur for me, because I am only testing the themes for mozilla.org and the dark Firefox theme.

We might be able to work around this using @media rules like:

```css
@media (-moz-toolbar-prefers-color-scheme: dark), (prefers-color-scheme: dark) {
		
}
```

and

```css
@media not (-moz-toolbar-prefers-color-scheme: dark), (prefers-color-scheme: dark) {
		
}
```

**Comment by Aris-t2** [comment]
Test [v4.4.5 release](https://github.com/Aris-t2/CustomCSSforFx/releases/).

**Comment by Aris-t2** [comment]
[4.4.6 release](https://github.com/Aris-t2/CustomCSSforFx/releases) will take care of this.
