### ISSUE TITLE
FF119 - Don´t show all tabs pinned when tab scrolling is active

### ISSUE THREAD

**Issue by Neewieedo** [Aris-t2/CustomCSSforFx#634]
Hi, 

with the current GIT version 4.4.4, the FF119 and active option "TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS"
there are problems with pinned tabs when many tabs are open and the arrows for scrolling appear.

![FF119_001](https://github.com/Aris-t2/CustomCSSforFx/assets/148935667/6ec88ff3-665d-4e5f-8cb0-9fc31c3f52b8)
![FF119_003](https://github.com/Aris-t2/CustomCSSforFx/assets/148935667/55250e21-7d5b-4a01-9404-e666f5030411)
![FF119_002](https://github.com/Aris-t2/CustomCSSforFx/assets/148935667/bbea7b7b-e7c1-4e30-aca5-94561b795544)

**Comment by Aris-t2** [comment]
Try to remove "Firefox view" button in customizing mode and report back.

**Comment by Neewieedo** [comment]
Thanks :-)
With removed "Firefox view - Button" it works

**Comment by Aris-t2** [comment]
Test [v4.4.5 release](https://github.com/Aris-t2/CustomCSSforFx/releases/).

**Comment by Neewieedo** [comment]
Big Thanks!
With v4.4.5 ist works also when Firefox-View-Button is active

**Comment by Aris-t2** [comment]
Great.
