### ISSUE TITLE
Firefox 122 - buttons_on_bookmarks_toolbar_old_size_and_appearance with dark themes

### ISSUE THREAD

**Issue by Darlat** [Aris-t2/CustomCSSforFx#642]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
With dark themes, buttons_on_bookmarks_toolbar_old_size_and_appearance causes bookmark bar items to have a black background, presumably because of the "appearance: auto !important;" portion, since if you remove it the items stop having a black background, removing it causes hover changes (on the bookmark items) to not function though.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes

4. Screenshots showing the issue (drag & drop images into this post):
![Dark Background Issue](https://github.com/Aris-t2/CustomCSSforFx/assets/15280788/34badcfe-df08-44eb-9f6a-96e6d8f6af66)

5. System information
- OS & OS version: Win 10x64 (10.0, Build 19045)
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100
- Firefox version: 122
- Firefox theme (e.g. default, build in light/dark, external theme + link): https://addons.mozilla.org/en-US/firefox/addon/space-fantasy/ and other dark themes.

**Comment by Aris-t2** [comment]
This will be fixed on next update.
