### ISSUE TITLE
Firefox 121+ - close_icon_red.css, addonlists_colorized_button_icons.css, addonlists_replace_button_labels_with_icons.css + Feature Requests..!

### ISSUE THREAD

**Issue by StavrosTsik** [Aris-t2/CustomCSSforFx#644]
@Aris-t2

Hello. I'm opening an issue, because of some incompatibility (I think !? :confused:) of latest's **CustomCSSforFx** version, specific **`css's`** I noticed, with Firefox 121 to 124+.

In **userChrome.css**:
- When using **"/css/generalui/_`close_icon_red.css"`_** together with **TabMixPlus** (and the Multi-row option), the "Close Tab" button is becoming invisible and looks small (similar to NoiaButtons issue).
![313502795-cb633912-e15c-4a90-b572-6e4735325ade](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/882e73c5-47d9-427e-9b46-c234206ec48f)
![Screenshot 2024-03-25 015154](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/e69da1e0-3ce6-4737-a16d-12e74f10c054)

- When I disable **_`"close_icon_red.css"`_**, the "Close Tab" button is restored and looks bigger.
![Screenshot 2024-03-25 014832](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/2c049fee-6bec-48a7-adc0-cb0440130b7f)

In **userContent.css**:
- When using **"/css/aboutaddons/_`addonlists_colorized_button_icons.css"`_** Firefox's icons are still displayed. Normal ?
![addonlists_colorized_button_icons](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/ec1bb537-f360-44d7-a1b0-2ef6c653cec2)

- When also using **"/css/aboutaddons/_`addonlists_replace_button_labels_with_icons.css"`_** Firefox's icons are also still displayed. Again. Normal ?
![addonlists_replace_button_labels_with_icons 2](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/b8307c55-2259-4a26-8c99-7f4a70b54344)

### Feature Request.:

1. Can the "Sync category and Page" be also hidden, using **userContent.css** ?
![Sync category and Page](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/c1838486-ed34-4a78-95c7-c080c1db3cd6)

2. Using **/css/tabs/_`tabs_multiple_lines_force_newtab_button_visibility.css`_**, the **"New Tab"** button isn't centered dynamically as the rows increasing. Can be "fixed" like it was fixed in "**NoiaButtons_v3.0.2"** ? (I was also referring to this feature [here](https://github.com/Aris-t2/CustomCSSforFx/discussions/606#discussioncomment-8578245))
![307537133-206d2a33-a084-4d7b-b455-5c7d44a86481](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/f9db7fe9-f8fb-4758-a351-28af413ab558)

System information
- OS & OS version: **Windows 11 Pro 23H2**
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): **3840x2160 - 175%.**
- Firefox version: **121, 122, 123 and 124**
- Firefox theme (e.g. default, build in light/dark, external theme + link): **Dark/Dark**

**Comment by Aris-t2** [comment]
1. I can add support for TMPs button ID for all "close icon" options like I did in NoiaButtons, but I can not test the results.
2. CustomsCSSforFx used browsers default icons for addon managers buttons icons. You are meant to use `addonlists_replace_button_labels_with_icons.css` together with `addonlists_show_buttons_instead_of_menu_popup.css`. The dark icons, when using dark theme are a bug. It will be fixed on next update.
3. Both "feature requests" will be part of next update.

**Comment by StavrosTsik** [comment]
Hello @Aris-t2.
After testing the new release, here are my findings:

> * When using **"/css/generalui/_`close_icon_red.css"`_** together with **TabMixPlus** (and the Multi-row option), the "Close Tab" button is becoming invisible...

> 1. I can add support for TMPs button ID for all "close icon" options like I did in NoiaButtons, but I can not test the results.

Unfortunately the issue still persists. :cry::worried::disappointed:


> 2\. CustomsCSSforFx used browsers default icons for addon managers buttons icons. You are meant to use `addonlists_replace_button_labels_with_icons.css` together with `addonlists_show_buttons_instead_of_menu_popup.css`. The dark icons, when using dark theme are a bug. It will be fixed on next update.

Resolved.!! :thumbsup::+1::relaxed:



> 3\. Both "feature requests" will be part of next update.

From both requests, unfortunately the **"Sync"** category still remains visible. I enabled **`sync_category_always_hidden.css`** in **`userContent.css`** but does nothing.! :disappointed:


**Tested all on Firefox version: 121 through 124.0.2**

- P.S:  As a feature request, can **`"Add-ons Support"`** link in **Add-ons page** also be hidden ? It's useless and unnecessary.. :confused:
![Add-ons page](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/a9a82f0f-af27-4b03-bca1-585d77d73cea)

**Comment by StavrosTsik** [comment]
Hello @Aris-t2.
I've tested the new **v4.5.0** release and it's close to eliminate all issues:

> * When using **"/css/generalui/_`close_icon_red.css"`_** together with **TabMixPlus** (and the Multi-row option), the "Close Tab" button is becoming invisible...

> 1. I can add support for TMPs button ID for all "close icon" options like I did in NoiaButtons, but I can not test the results.

The issue still persists. :cry::worried::disappointed:

> From both requests, unfortunately the **"Sync"** category still remains visible. I enabled **`sync_category_always_hidden.css`** in **`userContent.css`** but does nothing.!

Fixed.!! :thumbsup::+1::relaxed:

> * P.S:  As a feature request, can **`"Add-ons Support"`** link in **Add-ons page** also be hidden ? It's useless and unnecessary..

Fixed at a 50% level. I enabled **`addons_support_always_hidden.css`** in **`userContent.css`**. When on **"Extensions & Themes"** page is hidden, as it should be but when on **"Firefox Settings"** page it's showing again:

**"Extensions & Themes"** page:
<img width="155" alt="Extensions   Themes" src="https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/034e61db-96b0-4706-9b80-be576ce35fff">


**"Firefox Settings"** page:
<img width="172" alt="Firefox Setting Page" src="https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/fbd6d679-ac47-4f90-a9fe-44d6d23ec990">

**Tested on Firefox version: 124.0.2**

**Comment by Aris-t2** [comment]
Run some tests with this build:
[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/14968115/chrome.zip)

Addons support was hidden by the corresponding option. Browser settings require an own one.

(Not sure, but it might help to solve the close icon issue too.)

**Comment by StavrosTsik** [comment]
> Run some tests with this build:

Happy to report:

> Addons support was hidden by the corresponding option. Browser settings require an own one.

Fixed.!! (**Add-ons Support** link in Add-ons page 100% hidden) :thumbsup::+1::relaxed:

> (Not sure, but it might help to solve the close icon issue too.)

Finally this test build fixed the issue.!! :thumbsup::+1::relaxed:
![Close Tab](https://github.com/Aris-t2/CustomCSSforFx/assets/96174036/7fd4f772-288d-46ad-8e04-6a92e2321128)

**Safe to say the reported isuses as FIXED.!!**

Thanks a lot @Aris-t2 👍 👍 


P.S Should I wait for an **"official v4.5.1"** release ???

**Comment by Aris-t2** [comment]
No, need to wait.

**Comment by StavrosTsik** [comment]
Hi @Aris-t2 
One last question. Could you tell me how to make the size of **"Close Tab"** button of the above picture (arrow showing), a little bit bigger but does not affect the close button on tabs ?

Thanks..

**Comment by StavrosTsik** [comment]
Thanks for the provided snippets. Should I add one of them in **`my userChrome.css`** _**or**_ that code already exists somewhere in the project’s various **`css’s`** ? (I don’t want any conflict)
