### ISSUE TITLE
Can't get the titlebar to display the title [as in "New Tab-Firefox"].

### ISSUE THREAD

**Issue by aamodpandey** [Aris-t2/CustomCSSforFx#645]
Firefox 115. Windows 7 x64 with Classic theme.
It does appear while the window is being maximised, though.
The in-private window retains black background. 
![Capture](https://github.com/Aris-t2/CustomCSSforFx/assets/83859194/07510a29-64c4-4bc2-bbcf-1654248afdb2)

**Comment by Aris-t2** [comment]
Which version of "CustomCSSforFx" are you using?

This CSS-feature was removed a long time ago, because it failed to work with recent Firefox versions back then. 

The JS replacement should still work: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/tab_label_in_titlebar.uc.js

**Comment by aamodpandey** [comment]
> Which version of "CustomCSSforFx" are you using?

Your Feb-10 release version.


> This CSS-feature was removed a long time ago, because it failed to work with recent Firefox versions back then.

I wasn't aware of this. That should work. Thanks!

**Comment by Aris-t2** [comment]
JSs scripts work up to the latest Nightly build.
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/49e70b22-acc8-4b48-a210-59f852e459d5)

Your issue might not be related to custom scripts or styles at all. The screenshot shows default OS titlebar, right?
(The one you enable in customizing mode.)
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/78a6b309-2b16-432f-9b24-e83eff13fc9b)

If JS scripts refuse to work, try to setup CustomJSforFx again. Don't forget to clear startup cache: 
https://github.com/Aris-t2/CustomJSforFx?tab=readme-ov-file#scriptstartup-cache-must-be-deleted-after-every-change

**Comment by aamodpandey** [comment]
> JSs scripts work up to the latest Nightly build. ![image](https://private-user-images.githubusercontent.com/6013569/319683674-49e70b22-acc8-4b48-a210-59f852e459d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTk2ODgsIm5iZiI6MTcxMjI1OTM4OCwicGF0aCI6Ii82MDEzNTY5LzMxOTY4MzY3NC00OWU3MGIyMi1hY2M4LTRiNDgtYTIxMC01OWY4NTJlNDU5ZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTkzNjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc3YmU0MjlhMmZlMzQxZjQ1ZjlkZWI1ZGU1MDIxZWZhNWU4MWJkNGI0ZjVlMDFmMjAyMmQ0MjdkMjM0OTZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rB_ub-ogDtwKmGKG-ivc8NJ4K_JGjC7-JyD7E-qiMsA)
> 
> Your issue might not be related to custom scripts or styles at all. The screenshot shows default OS titlebar, right? (The one you enable in customizing mode.) ![image](https://private-user-images.githubusercontent.com/6013569/319684336-78a6b309-2b16-432f-9b24-e83eff13fc9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTk2ODgsIm5iZiI6MTcxMjI1OTM4OCwicGF0aCI6Ii82MDEzNTY5LzMxOTY4NDMzNi03OGE2YjMwOS0yYjE2LTQzMmYtOWIyNC1lODNlZmYxM2ZjOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTkzNjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQyNzBkYTJmZjY0YTZmZjRiNzg2NmNiMmJmMThhOTc3YWM1YzgyZTAzYTMwMDllY2Y2NDg0OTVlMWNhNWExOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vsqdYNzYabpQRYVVqHnV8G2CNfozxnwixDtAUu53YOE)
> 
> If JS scripts refuse to work, try to setup CustomJSforFx again. Don't forget to clear startup cache: https://github.com/Aris-t2/CustomJSforFx?tab=readme-ov-file#scriptstartup-cache-must-be-deleted-after-every-change

That was already a mozilla thing. Got applied instantly. Can't believe they keep making software dumber.

**Comment by aamodpandey** [comment]
![Capture](https://github.com/Aris-t2/CustomCSSforFx/assets/83859194/e9ef5cc4-fda1-
![Capture2](https://github.com/Aris-t2/CustomCSSforFx/assets/83859194/77819392-c8ae-4d75-992c-5e3f6753959b)
4253-a467-af40878867e9)

Now this is just beautiful. You can upstream the code for this new tab page I did if you want.

**Comment by aamodpandey** [comment]
Can you get sites to be pinned somewhere on the toolbar, just like apps on taskbar?

**Comment by Aris-t2** [comment]
Firefox does not offer the possibility to move bookmarks out of the "bookmarks item"
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/b6bac871-a313-43f8-be2a-08d1097c8482)

You can modify https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/about_button_generic.uc.js script and force it to load a page you want. Therefore you would have to create an own button for every page you want to move to your toolbar.

```js
// text

(function() {

try {
	
  Components.utils.import("resource:///modules/CustomizableUI.jsm");
  ChromeUtils.importESModule("resource:///modules/CustomizableUI.sys.mjs");
  const sss = Components.classes["@mozilla.org/content/style-sheet-service;1"].getService(Components.interfaces.nsIStyleSheetService);
  
  const button_label = "About Button (generic)"; // add label here
  
  CustomizableUI.createWidget({
	id: "button_to_url_XYZ", // button id
	defaultArea: CustomizableUI.AREA_NAVBAR,
	removable: true,
	label: button_label, // button title
	tooltiptext: button_label, // tooltip title
	onClick: function(event) {
		
	  const win = Components.classes["@mozilla.org/appshell/window-mediator;1"]
		.getService(Components.interfaces.nsIWindowMediator)
		.getMostRecentWindow("navigator:browser");
		
      if(event.button=='0') {
		try {
		  
		  	win.gBrowser.selectedTab = win.gBrowser.addTrustedTab('https://www.google.com'); // add own url here
		  
		} catch (e) {}
	  }   
	},
	onCreated: function(button) {
	  return button;
	}
		
  });
  
  // style button icon
  const uri = Services.io.newURI("data:text/css;charset=utf-8," + encodeURIComponent('\
	\
	  #about-button-gen .toolbarbutton-icon {\
		list-style-image: url("chrome://global/skin/icons/defaultFavicon.svg"); /* icon / path to icon */ \
		fill: dimgray; /* icon color name/code */\
	  }\
	\
  '), null, null);
  
  sss.loadAndRegisterSheet(uri, sss.AGENT_SHEET);
  
} catch (e) {
	Components.utils.reportError(e);
};

})();
```

**Comment by aamodpandey** [comment]
Right. So much for being a "corporation".
