### ISSUE TITLE
How to remove "Firefox Suggest" ?

### ISSUE THREAD

**Issue by Henu3duka** [Aris-t2/CustomCSSforFx#646]
FF 124.0.1, FF 115.9.1
CustomCSS v4.4.9
FF shows "Firefox Suggest" on first line in dropdown search in megabar. I dont use any search features. How to remove it, I dont found it in userChrome.css.
My config about MEGABAR:
[megabar.txt](https://github.com/Aris-t2/CustomCSSforFx/files/14917328/megabar.txt)

**Comment by glennpc** [comment]
Go to Tools >>> Settings >>> Search

Uncheck "Suggestions from Firefox"

![suggest](https://github.com/Aris-t2/CustomCSSforFx/assets/54756104/cca58564-a16c-433c-9441-a6ba7617780b)

**Comment by mozo78** [comment]
> Go to Tools >>> Settings >>> Search

>Preferences>>> Settings >>> Search

**Comment by Henu3duka** [comment]
Many Thanx :) I have FF ESR 159.9.1
I don’t have any checkboxes under “Search engines”, there’s nothing under it at all.
I only have History, Bookmarks and Shortcuts and thay are checked, Tabs and Search engines are not.

**Comment by Henu3duka** [comment]
I have found it! 
about:config
browser.urlbar.groupLabels.enabled = false

Thanks to all :)
