### ISSUE TITLE
Border between navigation toolbar and tabs toolbar

### ISSUE THREAD

**Issue by Hobbix** [Aris-t2/CustomCSSforFx#647]
See default_tabs_photon_alt.css
```
/* border between navigation toolbar and tabs toolbar */
:root:not([lwtheme])  #nav-bar {
  box-shadow: 0 calc(-1 * var(--tabs-navbar-shadow-size)) 0 color-mix(in srgb, currentColor 20%, transparent) !important;
}

:root[lwtheme] #nav-bar {
  box-shadow: unset !important;
}
```
This code no longer works for FF126+?
It looks like FF126+ now uses **--tabs-navbar-separator-color** and **--tabs-navbar-separator-style** for this?

**Comment by Aris-t2** [comment]
Thanks for the note. Most tab settings are affected. I will post new files soon.

**Comment by Aris-t2** [comment]
Test 4.5.2 release: https://github.com/Aris-t2/CustomCSSforFx/releases/

**Comment by Hobbix** [comment]
I'm using a custom light theme and for some reason this code doesn't work for me. I still see the pale gray line under the active tab.
```
/* Fx 110+ - remove line below active tab */
#nav-bar:not([tabs-hidden="true"]) {
  position: unset !important;
}
```
This code removes the line between the navigation bar and the tab bar, but it removes the line from all tabs (active and inactive)
```
/* Fx 126+ */
:root[lwtheme] #nav-bar {
  border-top: 0px !important;
}
```

The solution from this thread worked for me: https://github.com/Aris-t2/CustomCSSforFx/issues/552#issuecomment-1410813138
It removes the line only on the active tab. On inactive tabs the line is displayed.
```
/* Fx 126+ - remove line below active tab (custom light theme)  */
#TabsToolbar #tabbrowser-arrowscrollbox {
  margin-top: 1px !important;
  margin-bottom: -1px !important;
}
```

**Comment by Aris-t2** [comment]
Every few Firefox releases Mozilla devs go crazy and change code for navigation toolbars border. It either a fixed border color, a background-image or a box shadow, that gets added or removed, causing all of this projects options to require fixes. 

I did a few tests yesterday before uploading 4.5.2 release, but my tests only covered "my default" cases, other configurations might of course require additional or different approaches.

Good to hear you could solve this.
