### ISSUE TITLE
Combining tabs below navigation with tab appearance causes issues

### ISSUE THREAD

**Issue by Garbman** [Aris-t2/CustomCSSforFx#649]
1. Does the issue occur without any files inside /chrome/ folder?
No.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Enabling "tabs_below_navigation_toolbar_higher_navbar_positon.css" (or any of the two other variants of it) with any of the following: "classic_squared_tabs.css", "classic_squared_tabs_australized.css", "default_tabs_photon.css" causes misalignment issues. This only appears to happen if the title bar in firefox's settings is disabled.  
Turning on "tabs_below_navigation_toolbar_higher_navbar_positon.css" causes the window control buttons to be slightly lower than expected when firefox is maximized but any other buttons and address bar function normally.
Adding any of the before mentioned css that alter the appearance of the tabs causes the address bar to be cut off (exclusive to squared_tabs and squared_tabs_australized), the buttons only work if the cursor is at a specific spot below them and the window controls get shoved off their spot even more. 
I don't know what Mozilla decided to change on their end but combining these two css options used to work on FF123 and older.  On FF125 I used "default_tabs_photon_alt.css" instead of the regular version but it otherwise worked as intended. Now on FF126 none of the alternate tab appearances work properly if paired with the option to move the tabs down.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes. Tested with a fresh install of 'v4.5.2v2'.

4. Screenshots showing the issue (drag & drop images into this post):
"tabs_below_navigation_toolbar_higher_navbar_positon.css" + disabled title bar
![1](https://github.com/Aris-t2/CustomCSSforFx/assets/12104512/4d5d8a1e-ee3f-47d0-82e0-f6183c189697)
"tabs_below_navigation_toolbar_higher_navbar_positon.css" and "classic_squared_tabs.css" + disabled title bar
![3](https://github.com/Aris-t2/CustomCSSforFx/assets/12104512/b8e515cf-6127-4ee8-8394-a3b15511f05a)
![2](https://github.com/Aris-t2/CustomCSSforFx/assets/12104512/3c04c2af-69e6-4c5e-8b01-610ea59f5877)
"tabs_below_navigation_toolbar_higher_navbar_positon.css" and "classic_squared_tabs.css" + enabled title bar
![4](https://github.com/Aris-t2/CustomCSSforFx/assets/12104512/60e153b3-cd32-4584-b008-44db5c8e79c6)

6. System information
- OS & OS version:  Windows 10
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100% scaling 1080p
- Firefox version: 126
- Firefox theme (e.g. default, build in light/dark, external theme + link): tested with default light theme and Arc Dark by Afnan Khan

**Comment by Aris-t2** [comment]
Test this: 
[CSS.zip](https://github.com/Aris-t2/CustomCSSforFx/files/15391319/CSS.zip)

**Comment by Garbman** [comment]
That works, thanks for the quick fix.
Cheers!
