### ISSUE TITLE
Youtube strongly unusable after they released new update; this CSS seems to be culprit

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#650]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Can't use scroll wheel over new Youtube UI (Except top bar + video recommendations), also Youtube looks weird compared to Clean FF (checked in Developer mode too)
Note: Below file is .css, change extension back to read
[userChrome - Copy.xls](https://github.com/Aris-t2/CustomCSSforFx/files/15389590/userChrome.-.Copy.xls)

And yes, checked with any other stuff turned off (uBlock, RemoveYoutubeDislike etc)

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes

4. Screenshots showing the issue (drag & drop images into this post):

5. System information
- OS & OS version: Windows 10
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): Default
![obraz](https://github.com/Aris-t2/CustomCSSforFx/assets/33688131/adc3c405-f465-448b-afbc-24c73c4344ab)
Compared to dev mode version
![obraz](https://github.com/Aris-t2/CustomCSSforFx/assets/33688131/986c30ed-32f4-47ab-a75e-c2187fc1acb5)

- Firefox version: 126.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): Default

**Comment by Aris-t2** [comment]
There is no CSS within this projects files that modifies Youtube directly.

However, changing your browsers toolbar height by increasing/decreasing toolbar/buttons sizes, might cause Youtube to calculate different page dimensions based on the available vertical screen space.

**Comment by Nyekomimi** [comment]
It's a brand new issue, apparently Youtube has rolled out a new UI.

I figured I'd mention it since it is an issue - Maybe you could add size
spoofing to prevent such wrong scaling?

**Comment by Aris-t2** [comment]
Unfortunately this project is not about styling websites, sorry.

**Comment by CT-ABT** [comment]
Try [YouTube Redux](https://addons.mozilla.org/addon/youtube-redux/).
