### ISSUE TITLE
Navigation bar is hidden and overridden by suggestions when trying to type

### ISSUE THREAD

**Issue by CaptainKishimoto** [Aris-t2/CustomCSSforFx#652]
1. Does the issue occur without any files inside /chrome/ folder?
No.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
Navigation bar is hidden and overridden by suggestions when trying to type.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes

4. Screenshots showing the issue (drag & drop images into this post):
![image](https://github.com/Aris-t2/CustomCSSforFx/assets/33742546/c7f7e041-c3f0-44f6-8765-915ce7e182f7)

5. System information
- OS & OS version: W10
- Firefox version: 126.0
- Firefox theme (e.g. default, build in light/dark, external theme + link):

**Comment by Aris-t2** [comment]
Which settings do you have enabled besides `ac_popup_megabar_title_and_url_two_lines.css`?

Upload your chrome folder here as a zipped file. (Just drag and drop zip into your answer)

**Comment by yurikhan** [comment]
I got a similar thing when I first started Firefox 126 on an earlier version of CustomCSSforFx; updating fixed the issue.

**Comment by CaptainKishimoto** [comment]
> Which settings do you have enabled besides `ac_popup_megabar_title_and_url_two_lines.css`?
> 
> Upload your chrome folder here as a zipped file. (Just drag and drop zip into your answer)

[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/15410999/chrome.zip)

Also it should be latest version of CustomCSS

**Comment by CaptainKishimoto** [comment]
I removed the file (and also removed the code to enable it) and it still happens.

**Comment by Aris-t2** [comment]
I've tested your files and the most recent files inside CSS folder are from 2022!

After replace them with current files, everything worked again.

Remove/backup everything from chrome folder, extract latest release there (https://github.com/Aris-t2/CustomCSSforFx/releases ), restore userChrome.css.
