### ISSUE TITLE
[urlbar_background_color.css] Issues with "Windows Apps Dark Mode"

### ISSUE THREAD

**Issue by Lyhtande** [Aris-t2/CustomCSSforFx#653]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
If I switch Windows to display apps in dark mode, the text in the address bar and in the small search bar is white and I can't read it.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Version: 4.5.2
Yes

4. Screenshots showing the issue (drag & drop images into this post):
![dark mode](https://github.com/Aris-t2/CustomCSSforFx/assets/44006120/0cfdfa44-df25-4179-bb3d-2d2a95b6e1d8)

5. System information
- OS & OS version: Windows 11, version 23H2
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: 126.0.1 (64-Bit)
- Firefox theme (e.g. default, build in light/dark, external theme + link): none

**Comment by Aris-t2** [comment]
Default setup does not cause this for location and searchbar for me.
(Same test environment)

You probably have some other code enabled.

**Comment by Aris-t2** [comment]
The issue was caused by `urlbar_background_color.css`. Test this:
[CSS.zip](https://github.com/user-attachments/files/15846622/CSS.zip)

**Comment by Aris-t2** [comment]
Anything new here?
Is the issue still present in v4.5.4?
https://github.com/Aris-t2/CustomCSSforFx/releases/

**Comment by Lyhtande** [comment]
Hello @Aris-t2,
sorry for my late reply.
Yes thank you this fixed the issue.
But I still have an issue with the back button, when using the dark theme:
![back-button](https://github.com/user-attachments/assets/0af9e762-d08d-42c1-a52a-41ce742867e1)

**Comment by Aris-t2** [comment]
This will be fixed on next update.

**Comment by Lyhtande** [comment]
> This will be fixed on next update.

Thank you!
