### ISSUE TITLE
The "buttons_on_navbar_aero_appearance.css" glitches in some areas

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#657]
### 1. Does the issue occur without any files inside /chrome/ folder?
- No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
- The "buttons_on_navbar_aero_appearance.css" can sometimes glitch on some buttons. I noticed, that it showed unwanted outlines on the Fx3 strata back & forward buttons. Also, it creates a diverged/double outline on the "Open applications menu" button.

### 3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
- Yes, as of writing I have the latest CustomCSSforFx .zip archive downloaded.

#### Unwanted square outline on the strata back button:
![Unwanted outline on strata back button](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/5acc5df6-dd37-4e2a-b1a9-9d8d4d41d282)

#### Unwanted square outline on the strata forward button:
![Unwanted outline on strata forward button](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/26d6b95c-ce3a-491e-87e4-2e7e781859dd)

#### Diverged/double outline on the "Open applications menu" button:
![Unwanted outline on applications menu button](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/b6a8e249-dc8d-4aa4-8cf3-b2ed957277b5)

### 5. System information
- OS & OS version: Windows 10 Pro 22H2 19045.4529 (64-bit)
- DPI/HiDPI/scaling value: 100%
- Firefox version: v127.0.0
- Firefox theme: https://github.com/black7375/Firefox-UI-Fix

**Comment by Aleksandra0056** [comment]
Here's a copy of my userChrome.css file:
[userChrome.txt](https://github.com/user-attachments/files/15845704/userChrome.txt)

**Comment by Aleksandra0056** [comment]
It also creates two unwanted outlines on the Orange app button (but it's very badly visible):
![Unwanted outline on orange app button](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/c6e00960-cd85-4fbd-8467-9531b4424b30)

(appbutton/appbutton_in_titlebar_label_and_icon.css)

**Comment by Aris-t2** [comment]
Test this build: 
[CSS.zip](https://github.com/user-attachments/files/15846389/CSS.zip)

**Comment by Aleksandra0056** [comment]
> Test this build: [CSS.zip](https://github.com/user-attachments/files/15846389/CSS.zip)

Okay, I tested and the double outline of the three lines app menu disappeared:
![The double outline disappeared](https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/d8846d38-e32a-42bc-b83a-1054b76ac751)

However, the Orange icon app menu still has an unwanted outline circle in it. And strata back & forward buttons still show unwanted outlines when hovered. But I can't take screenshots since these outlines extremely quickly disappear, and even my screenshot tool can't capture them.

**Comment by Aris-t2** [comment]
After the fixes, I used your `userChrome.css` file and added `appbutton_in_titlebar_label_and_icon.css` to it. The mentioned issues are gone in my tests.


https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/1c9b05c4-2d7e-4d21-80d0-0fd35387ba0d

**Comment by Aleksandra0056** [comment]
> After the fixes I used your `userChrome.css` file and added `appbutton_in_titlebar_label_and_icon.css` to it. The mentioned issues are gone in my tests. Did you replace your CSS folder with the one from the zip file above?
> vid.mp4

I replaced the CSS directory and all the issues I reported are gone. However, since I'm using Firefox UI Fix (which implements icons in almost all menus), then the "History menu" & "List all tabs" menu icons have unwanted outlines too.

#### Furthermore, I'm posting a recording of this problem:
https://github.com/Aris-t2/CustomCSSforFx/assets/69351811/0164a56d-1bd8-4316-b387-84b6c7930372

**Comment by Aris-t2** [comment]
[CSS.zip](https://github.com/user-attachments/files/15856663/CSS.zip)
This should help.

**Comment by Aleksandra0056** [comment]
> [CSS.zip](https://github.com/user-attachments/files/15856663/CSS.zip) This should help.

Thank you, it's now fixed. If I find any issue (even minor), then I will report it since I'm a detailist.

**Comment by Aleksandra0056** [comment]
Wait, it isn't fixed. I found that extensions to have double outlines.

**Comment by Aris-t2** [comment]
[CSS.zip](https://github.com/user-attachments/files/15857269/CSS.zip)

**Comment by Aleksandra0056** [comment]
> [CSS.zip](https://github.com/user-attachments/files/15857269/CSS.zip)

It is now almost fixed, but it again shows an outline under icons of List all tabs & History menu, but it is not opaque as was in CSS.zip v1, so it's barely visible.

**Comment by Aris-t2** [comment]
I did not notice it before, but after clicking on those submenu buttons something appeared ;-)
This should fix it:
[CSS.zip](https://github.com/user-attachments/files/15858138/CSS.zip)

**Comment by Aleksandra0056** [comment]
> I did not notice it before, but after clicking on those submenu buttons something appeared ;-) This should fix it: [CSS.zip](https://github.com/user-attachments/files/15858138/CSS.zip)

Okay, now I don't see any issues on my UI. I think, that it can be closed.

**Comment by Aris-t2** [comment]
Good, the changes will be part of next update.

**Comment by Aleksandra0056** [comment]
> Good, the changes will be part of next update.

Thank you! If I find any issues in future, then I will report them since I'm a strong detailist.
