### ISSUE TITLE
Compact context menu cannot be applied to about:downloads

### ISSUE THREAD

**Issue by CT-ABT** [Aris-t2/CustomCSSforFx#659]
**1\. Does the issue occur without any files inside /chrome/ folder?**

No.

**2\. Issue description, `userChrome.css` / `userContent.css` ‘settings’ the issue occurs with and steps to reproduce the issue:**

While `./css/generalui/popup_compact_menus.css`, `./css/generalui/popup_compact_menus_squared.css`, and `./css/generalui/popup_menus_space_before_label.css` is enabled, the context menus behave expectedly on normal pages, settings pages, about:config, about:debugging, about:performance, about:profiles, about:processes, about:cache, about:memory, about:mozilla, about:buildconfig, etc, with probably only one exception: about:downloads, which appears to be not affected by the css as screenshot attached below.

**3\. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?**

Yes, it occurs on 4.4.2 applied to Firefox 115 ESR and on the latest 4.5.3 that applied to Firefox 128.

**4\. Screenshots showing the issue:**

The problem:
![aboutdownload](https://github.com/Aris-t2/CustomCSSforFx/assets/30417426/1c3cc4fa-f9d1-449e-ae6f-12c896197add)

Compared to where the css is perfectly effective:
![normalcontextmenu](https://github.com/Aris-t2/CustomCSSforFx/assets/30417426/84ceac86-3707-42cb-a35f-85ae2c2f6b31)

**5\. System information**
- OS & OS version: Windows (Server 2022 / 11 LTSC 24H2);
- DPI/HiDPI/scaling: 200%;
- Firefox version: 115 / 128b5;
- Firefox theme: Default.

**Comment by Aris-t2** [comment]
Add these to your `userContent.css` file:

```css
 @import "./css/generalui/popup_compact_menus.css"; /**/
 @import "./css/generalui/popup_compact_menus_squared.css"; /**/
 @import "./css/generalui/popup_menus_space_before_label.css"; /**/
```

`about:downloads` requires css being loaded from there.
Same applies to other custom css, if it has to appear on `about:downloads`.

**Comment by CT-ABT** [comment]
Wow, thanks a lot! That was quick!
