### ISSUE TITLE
[tabs not on top] [light theme] Tab buttons not always visible

### ISSUE THREAD

**Issue by toad01** [Aris-t2/CustomCSSforFx#66]
Describe the issue

Tab scroll/Open a new tab/List all tabs buttons not always visible when 'tabs below' selected

What should have happened instead?
In Classic version 1.2.7 they are visible (but not pretty!).
Visible in all versions when using Dark Theme

Steps to reproduce the issue?
Install Classic version 1.2.9 > 1.3.2.1
Edit userChrome.css to contain single line @import url(./css/tabs/tabs_below_navigation_toolbar.css);

Select Light Theme. None of the above buttons are visible.
Select Default Theme. New tab button not visible.

System information
OS: Windows 7 x64
OS version: 
OS theme: 
DPI / HiDPI resolution: 
Firefox version: 57
Firefox theme: Light
Settings this issue occurs with: Latest Classic version using Tabs below combined with Light Theme

**Comment by toad01** [comment]
Problems appears to be with latest version of tabs_below_navigation_toolbar.css

**Comment by Aris-t2** [comment]
Check 1.3.3

**Comment by toad01** [comment]
That's fixed it! Many thanks, that was quick.

Thank you for all you efforts in making these tweaks available for Firefox 57, it has helped make a great browser even better.

**Comment by Aris-t2** [comment]
Good to hear.
