### ISSUE TITLE
my_userChrome.css not working after update to version 4.5.4

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#660]
Installed the latest **version 4.5.4** after using the previous **version 4.4.7** since its release.

I have selected all the same @import files as in version 4.4.7 but now find that my own **my_userChrome.css** not longer operates.

As soon as I switch back to version 4.4.7 all is good again.

**Comment by Aris-t2** [comment]
Nothing changed for `my_userChrome.css` inside `userChrome.css` file for ages.

![image](https://github.com/Aris-t2/CustomCSSforFx/assets/6013569/e4ea51b3-98e1-4023-b11c-a515d8438f22)

**Comment by ChasCB** [comment]
Thank you Aris, all good now. I shouldn't jump to quick.

It took me hours going through my code for the latest release and I finally found the error. It was a missing closure */ and a miss spelling of a css file after editing because after all these years I have finally edited out all the unwanted code in your release as well as deleting all the unwanted css files. ☹️🤪

**Question:** Is it advisable to create my own css files from my own my_userChrome code and then merge those new files into your package and do away with my own my_userChrome. I would place it into a ***********separate area********** of your code.

**Comment by Aris-t2** [comment]
Its up to you. Both works.

You can put your code inside userChrome.css, my_userChrome.css or inside a different file (folder/drive) and link to it.

This is helpful, if you want run tests with different Firefox versions/setups.

`@import "file:///H:/CSS/userChrome.css";`
