### ISSUE TITLE
"tabs_below_main_content.css" fullscreen issue. Tabs disappear and add-on menus get stuck, when mouse moves to menubar [macOS]

### ISSUE THREAD

**Issue by dead-line** [Aris-t2/CustomCSSforFx#662]
**1. Does the issue occur without any files inside /chrome/ folder?**
- No.

**3. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:**
 
- When "tabs_below_main_content.css" is active, and Firefox is fullscreen: If the mouse moves to the macOS menubar the tabs will disappear.
  
- If there is an add-on menu open, and the mouse moves to the menubar, the add-on menu will close and not be able to re-open. The arrow keys also stop working when this happens. Closing and re-opening the browser window "fixes" it.
  
- Issue occurs in fresh Firefox install, with just one add-on installed, and only "tabs_below_main_content.css" active.

**4. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?**
 - Issue occurs with the latest release, [v4.5.4](https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.5.4)

**5. Screenshots showing the issue (drag & drop images into this post):**
- https://www.youtube.com/watch?v=Ezc4u6ZiwWA
- If another form of showcase is needed, please let me know

**6. System information**
- OS & OS version: MacOS 14.4.1
- Firefox version: 128.0
- Firefox theme (e.g. default, build in light/dark, external theme + link): Dark

Thank you for maintaining this project.

**Comment by joefiesta** [comment]
I should like to point out one minor symantics error.  
I believe dead-line is talking about Firefox in a MAXIMIZED WINDOW.  Firefox's FULLSCREEN (F11 shortcut key for windows) does not show tabs, caption, location bar, etc. etc.

**Comment by Aris-t2** [comment]
Unfortunately I can not move tabs toolbar out of the top area, when Firefox is in fullscreen overflow mode. Browsers reserved bottom area is still kind of present, but tabs toolbar get moved to the top anyway. In your video it is hidden behind bookmarks toolbar.

I did some tests and tabs toolbar becomes visible again, but only inside browsers top area (when Firefox is in fullscreen overflow mode).

Workaround to have a visible tabs toolbar on top:
[CSS.zip](https://github.com/user-attachments/files/16390858/CSS.zip)
