### ISSUE TITLE
[question] Is it possible to remove the browser name from the titlebar?

### ISSUE THREAD

**Issue by rado84-github** [Aris-t2/CustomCSSforFx#663]
Hi. A user on a forum told me that you can do anything with CSS, so I decided to come and ask: ss it possible to remove the browser name from the titlebar with CSS?
At the moment the titlebar displays "tab name - Mozilla Firefox". I want it to become only "tab name", if that's possible. If it matters, the desktop is Cinnamon 6.2.0. I already have userContent.css and userChrome.css with some content in them and the browser name removal is the last customization I've wanted to make for years but I've had no luck with that so far.

**Comment by Aris-t2** [comment]
The OS titlebar is controlled by the OS and can not be modified with CSS.
