### ISSUE TITLE
Activity Throbber shouldn't have outline when "buttons_on_navbar_aero_appearance.css" is enabled

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#664]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
- I know, that **CustomJSforFx** is a different project, but it's also maintained by you, so I'm reporting this issue here since it relates to the mentioned .css file and not the Activity Throbber itself.
- When I have Activity Throbber put on the navigation toolbar while `buttons_on_navbar_aero_appearance.css` is enabled, then the Activity Throbber button has an outline which shouldn't happen since it's a static and unclickable button.

#### Steps for reproduction:
1. Make sure, that `activity_throbber.uc.js` from CustomJSforFx is put into the scripts loader,
2. Make sure, that `buttons_on_navbar_aero_appearance.css` is imported in userChrome.css,
3. Put Activity Throbber in the navigation toolbar (navbar),
4. Hover over the Activity Throbber button,
5. The button has an outline.

#### Proposed solution:
Remove the outline for Activity Throbber since it shouldn't have an outline since it's only a static and unclickable button.

### 3. Does the issue occur with the most recent version of CustomCSSforFx?
Yes, I have the latest version (v4.5.4).

### 4. Screenshots showing the issue:
![Activity throbber have outline](https://github.com/user-attachments/assets/6a871b6b-e023-4e5a-9956-8b05364782e9)

### 5. System information
- OS & OS version: Windows 10 22H2 19045.4717
- OS architecture: x64
- DPI/HiDPI/scaling value: 100%
- Firefox version: Firefox v128.0.3
- Firefox architecture: x64
- Firefox theme: **Activist – Soft** (https://addons.mozilla.org/en-US/firefox/addon/activist-soft/) + **Firefox UI Fix** (https://github.com/black7375/Firefox-UI-Fix)

**Comment by Aris-t2** [comment]
Test this: 
[CSS.zip](https://github.com/user-attachments/files/16499816/CSS.zip)

**Comment by Aleksandra0056** [comment]
It's still happening. Maybe I have imported additional some CSS files on my userChrome.css. I will check it, disable and try again.

**Comment by Aris-t2** [comment]
Didn't for me at first, but after a test today I can confirm this.
Here is the next potential fix.
[CSS.zip](https://github.com/user-attachments/files/16515062/CSS.zip)

**Comment by Aleksandra0056** [comment]
> Didn't for me at first, but after a test today I can confirm this. Here is the next potential fix. [CSS.zip](https://github.com/user-attachments/files/16515062/CSS.zip)

It's now fixed. The Activity Throbber no longer has an outline
