### ISSUE TITLE
The "buttons_on_navbar_aero_appearance.css" makes container tabs menu icons disappear

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#665]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue Description:
- When I'm hovering over the menu icons in the "New Container Tab" menu (which is located under the List All Tabs button), then the menu icons systematically disappear.
- These menu icons are part of Firefox UI Fix. However, the problem isn't in Firefox UI Fix since it's caused by the `buttons_on_navbar_aero_appearance.css` itself, so that's why I'm reporting it here.

### 3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, I have the latest version (v4.5.4).

### 4. Screenshots showing the issue:

Screenshots wouldn't be practical, so I have a video instead (re-upload):

https://github.com/user-attachments/assets/c705d02f-dcc0-41e1-9a2b-bac536fce25e

### 5. System information
- OS & OS version: Windows 10 22H2 19045.4717
- DPI/HiDPI/scaling value: 100%
- Firefox version: v128.0.3
- Firefox theme: Firefox UI Fix - https://github.com/black7375/Firefox-UI-Fix

**Comment by Aleksandra0056** [comment]
I'm apologising, that it isn't visible on the attached video, so I would record it again and re-upload it with menus.

**Comment by Aris-t2** [comment]
Test this: 
[CSS.zip](https://github.com/user-attachments/files/16499816/CSS.zip)

**Comment by Aleksandra0056** [comment]
Yes, it's fixed, so it can be closed:

https://github.com/user-attachments/assets/5b9d4b9c-70a1-40eb-8c62-830e6f9c4fcb
