### ISSUE TITLE
Mouse wheel does not work for web content scrolling after FF ESR 115 and last CCSSfFx

### ISSUE THREAD

**Issue by Amad22** [Aris-t2/CustomCSSforFx#666]
Hello
After I updated to FF ESR 115.13.0esr (64 bit) and then to latest CCSSfFx (to a new FF user profile), 
the mouse wheel does not work anymore for scrolling in the FF web content.
I think this issue is known and the solution is easy, but I cannot find the solution anywhere.
Win 10 Pro 64-bit 22H2 b.19045.4651 
CCSSfFx set almost as their default, only with some small changes (multiline tabs, hamburger at start of navbar, dark blank page).
Thank you for any idea how to correct before I switch back to ESR 102.

**Comment by Aris-t2** [comment]
CSS does not affect browsers scrolling ability or mouse wheel.

**Comment by Amad22** [comment]
Thank you for the reply. You has been right. The problem was about X-Mouse application. After FF update, the FF probably changed something about page scrolling, X-Mouse app could not scroll in FF then (but in another apps the scrolling worked normally). After X-Mouse app update, the scrolling in FF works already.
