### ISSUE TITLE
Search Bar effectively dead in FF 129.0?

### ISSUE THREAD

**Issue by ImSpecial** [Aris-t2/CustomCSSforFx#667]
I'm referring too this bar right here!

![dead](https://github.com/user-attachments/assets/0f9ba423-e530-4964-a461-559deb26216b)

Updated this morning to FF 129.0 only to find that interacting with this does nothing now, clicking any of the "icon" does nothing, middle clicking them "should" open a tab in the respective site, and search for the term in the field if one is in there, but now does nothing, the only function that still seems to work if when you hover over the field box and do "Ctrl+Mouse Wheel" to scroll through the different engines.

Please tell me there is a workaround/fix for this! :/

**Comment by Aris-t2** [comment]
Works fine here with and without any custom code. Test a new browser profile (or in Portable Firefox).

**Comment by MarkRH** [comment]
Just wanted to comment that the additional Search Bar still works fine for me with Firefox 129.0.  I am using v4.5.4 of this project's CSS.  I am using Windows 10 Pro as far as the OS goes.

**Comment by ImSpecial** [comment]
What the heck! I played around with it a bit more now and it seems I cannot click on the icons to make them work when the field is EMPTY, but with something in there, a blank space, word, whatever, they work... I guess this issue is sorta solved... :/

(This behavior is slightly changed as I would always middle click those to open said site page and now I cannot unless a search term in filled in...)

I'm gonna close and just bury my head in the sand.

Thanks for confirming it was just me though!
