### ISSUE TITLE
When update is available, then App button can have green dot on it

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#668]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description:
I first noticed this on Nightly. When an update is available the green dot appears on the custom App button (in my case `appbutton_in_titlebar_icon_only.css` specifically).

It shouldn't appear, because it doesn't fit to the custom App button design.

### 3. Does the issue occur with the most recent version of CustomCSSforFx?
Yes, I have the latest version (v4.5.4).

### 4. Screenshots:
![Screenshot 2024-08-08 160602](https://github.com/user-attachments/assets/ed9bd808-e2fb-4789-af28-e308f04f6ced)

### 5. System information:
- OS & OS version: Windows 10 22H2 19045.4717
- OS architecture: 64-bit
- DPI/HiDPI/scaling value: 100%
- Firefox version: Firefox v131.0 Nightly
- Firefox architecture: 64-bit

#### Firefox theme:
- Rosa, pink (https://addons.mozilla.org/en-US/firefox/addon/rosa-pink/)
- Firefox UI Fix (https://github.com/black7375/Firefox-UI-Fix)

**Comment by Aleksandra0056** [comment]
Honestly, it's annoying to try to reproduce since it only appears when an update is available, so I recommend Nightly for reproducing this issue.

**Comment by Aleksandra0056** [comment]
Or putting that green dot in a more suitable and visible location is an even better solution than what I originally proposed.

I agree with the solution from v4.5.5 although you at least could notice this is fixed, but thanks for fixing anyway.

Also, I think, that the green dot should be replaced with a dedicated green dot image with multiple colour shades which is more suitable for the old pre-Australis design of the app button instead of using a single green colour shade (flat design) dot element. But that's a thing for another issue.

**Comment by Aris-t2** [comment]
The result should have looked like this (like it did in he past):
![image](https://github.com/user-attachments/assets/33c3b1db-948d-4f08-a7cb-a00ff29bdc4e)

**Comment by Aleksandra0056** [comment]
> The result should have looked like this (like it did in he past): ![image](https://private-user-images.githubusercontent.com/6013569/358840322-33c3b1db-948d-4f08-a7cb-a00ff29bdc4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MjE0NzMsIm5iZiI6MTcyMzkyMTE3MywicGF0aCI6Ii82MDEzNTY5LzM1ODg0MDMyMi0zM2MzYjFkYi05NDhkLTRmMDgtYTdjYi1hMDBmZjI5YmRjNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTg1OTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE0NTgzOTI1NzliMTNkZTZkMDMzZTExNTcyNzFiMmQ1MWQzYzU0ZWI2Mjk1MWYzZjJlMzJlNmUyNjMxNzdiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H2-0mpbir3KGpL7qpg9tKx81PDvy1Hpm8LBBdljEst0)

I will reply tomorrow since I forgot to screenshot the fixed App button icon only before the update was downloaded and absence of its screenshot would be bad for comparison of "App button with icon only" and "App icon with label and arrow".

**Comment by Aleksandra0056** [comment]
Okay, I will now show a comparison of update label behaviour in "App button with icon only" and "App icon with label and arrow" as I promised. But I want to repeat, that the resolution is already good, so there is no need for changes.

App button with icon only (with a green dot):
![Screenshot 2024-08-18 170144](https://github.com/user-attachments/assets/aca1d3d3-c603-451b-919b-f2e81a06c593)

App icon with label and arrow (with a green update icon):
![Screenshot 2024-08-17 185653](https://github.com/user-attachments/assets/2d6223c1-233e-48c4-9080-426d55afd2e3)
