### ISSUE TITLE
The `appbutton_in_titlebar.css` has an oddly placed blue outline on the arrow icon when `buttons_on_navbar_aero_appearance.css` is enabled

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#671]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
The `appbutton_in_titlebar.css` has an oddly placed blue outline on the arrow icon when `buttons_on_navbar_aero_appearance.css` is enabled.

Remove this oddly placed blue outline from the arrow icon on `appbutton_in_titlebar.css`.

#### Steps to reproduce:
1. Enable the `appbutton_in_titlebar.css` and `buttons_on_navbar_aero_appearance.css` to userChrome.css,
2. Restart Firefox,
3. Now hover over the title bar App button,
4. The oddly placed blue outline will appear.

### 3. Does the issue occur with the most recent version of CustomCSSforFx?
Yes, I have the latest version 4.5.5.

### 4. Screenshots showing the issue (drag & drop images into this post):
![Screenshot 2024-08-17 185958](https://github.com/user-attachments/assets/3e4d0c73-0562-45c6-a68e-fe6ddd3072b1)

### 5. System information
- OS & OS version: Windows 10 22H2 19045.4780
- DPI/HiDPI/scaling value: 100%
- Firefox version: Tested on Nightly (v131.0.0), but it probably also affects Release (v129.0.1)
- Firefox theme: Firefox UI Fix - https://github.com/black7375/Firefox-UI-Fix

**Comment by Aris-t2** [comment]
Does this help?
[CSS.zip](https://github.com/user-attachments/files/16646022/CSS.zip)

**Comment by Aleksandra0056** [comment]
Yes, it's fixed:
![Screenshot 2024-08-17 205722](https://github.com/user-attachments/assets/ec8aaa05-5bc1-41dd-b428-4652c113d2fa)

**Comment by Aleksandra0056** [comment]
I'm closing this as completed since it was fixed by the attached CSS.zip file.
