### ISSUE TITLE
[macOS] [icons+text mode/text mode] DarkMode MacOS. Toolbar buttons

### ISSUE THREAD

**Issue by Anfaenger12345** [Aris-t2/CustomCSSforFx#672]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.

no

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

DarkMode MacOS, buttons move the whole bar and are displayed incorrectly 
LightMode is all fine

```css
/* -------------------------------------
   Navigation toolbar buttons appearance
   -------------------------------------
   [!] only use one option at a time
   [!] good for Dark themes: buttons_on_navbar_classic_appearance_dark.css
   [!] good for Dark themes: buttons_on_navbar_glass_appearance.css
*/
@import "./css/buttons/buttons_on_navbar_classic_appearance.css"; /**/
/* @import "./css/buttons/buttons_on_navbar_classic_appearance_v2.css"; /**/
/* @import "./css/buttons/buttons_on_navbar_classic_appearance_dark.css"; /**/		
/* @import "./css/buttons/buttons_on_navbar_aero_appearance.css"; /**/
/* @import "./css/buttons/buttons_on_navbar_windows_classic_theme_appearance.css"; /**/
/* @import "./css/buttons/buttons_on_navbar_glass_appearance.css"; /**/
/* @import "./css/buttons/buttons_on_navbar_osx_appearance.css"; /**/


/* ------------------
   TOOLBAR TEXT MODES
   ------------------  
   [!] only use one option at a time
*/
@import "./css/toolbars/toolbar_mode_icons_and_text.css"; /**/
/* @import "./css/toolbars/toolbar_mode_text.css"; /**/
```

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-

Yes, sice version 126 of Firefox

4. Screenshots showing the issue (drag & drop images into this post):

https://github.com/user-attachments/assets/70c5b7d1-f56a-4d8e-8be6-f6bcb71d60bb

https://github.com/user-attachments/assets/6cb6dad0-299f-4875-b0ac-946e083e5dbf

5. System information
- OS & OS version: MacOS 14.6.1
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 
- Firefox version: 129.0.2.   since 126
- Firefox theme (e.g. default, build in light/dark, external theme + link):

**Comment by Aris-t2** [comment]
This will be fixed on next release.
