### ISSUE TITLE
In Full Screen mode some items are permanently hidden (even when we leave this mode)

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Aris-t2/CustomCSSforFx#673]
When we use  `@import "./css/tabs/tabs_below_navigation_toolbar.css";` and we go to Full Screen mode then some items (like some buttons or search bar go to the overflow button). In addition, when we leave this mode, the default state is not restored (we have to restart the browser to get proper state).

Screen without Full Screen mode:
![image](https://github.com/user-attachments/assets/273abb0b-b0be-4cfd-b46b-567d6661be83)

Screen with Full Screen mode:
![image](https://github.com/user-attachments/assets/0f898559-ba18-4c4c-b581-eb04315b5bba)

Screen after leaving Full Screen mode (some buttons or search bar still sitting in the overflow button):
![image](https://github.com/user-attachments/assets/7fdce7e8-3815-4e9d-b529-ce597954e6fc)

Is there any way to not modify Nav Bar when we use `@import "./css/tabs/tabs_below_navigation_toolbar.css";`  and enter/exit to/from Full Screen mode? I would except that this Nav Bar will look identical in both modes (don't hide anything).

I use:
CustomCSSforFx 4.5.5
Firefox 129.0.2 (64-bit)
Theme: https://addons.mozilla.org/en-US/firefox/addon/pinstripe-blue/
`browser.search.widget.inNavBar` << set to true in about:config
`@import "./css/toolbars/menubar_in_fullscreen_mode.css";` << use also this
Windows 11

**Comment by Aris-t2** [comment]
Which screen resolution are you using? I can't reproduce this on my system.

Does this happen, if you are using default theme?

**Comment by Aris-t2** [comment]
Any news about the issue?

**Comment by Aris-t2** [comment]
Since there was no response for month I'm closing this.

**Comment by ArkadiuszMichalski** [comment]
@Aris-t2 Sorry for the lack of response, I had a long break from PC. I went back to this and the problem still persists in version 4.7.1. But now after exiting F11 the buttons go back to their correct positions. I have determined that the reason for this is this rule:

https://github.com/Aris-t2/CustomCSSforFx/blob/08bb6f6c88b888e4fa9ea77a766742231f1c0fc7/current/css/tabs/tabs_below_navigation_toolbar.css#L125-L127

I added the following rules to my file and everything is OK:

```css
#main-window:is([tabsintitlebar],[customtitlebar])[sizemode="fullscreen"] #navigator-toolbox #PanelUI-button {
  visibility: visible;
}

#main-window[sizemode="fullscreen"] #nav-bar {
	padding-inline-end: 0px !important;
}
```
