### ISSUE TITLE
System theme in dark mode - Tabs are light

### ISSUE THREAD

**Issue by clau-bucur** [Aris-t2/CustomCSSforFx#675]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes

4. Screenshots showing the issue (drag & drop images into this post):
5. 
![image](https://github.com/user-attachments/assets/4d364f53-19a3-4e05-8dfc-fb4c1f4fc077)
![image](https://github.com/user-attachments/assets/3e76c825-04b0-4124-b543-29638286d73c)

With the Dark theme, the tabs are showing as expected:
![image](https://github.com/user-attachments/assets/83e69d58-9647-4f5f-89cd-1d0b34663c92)
![image](https://github.com/user-attachments/assets/ec98fd02-ed3d-42bc-9c09-242ca73d8d73)

6. System information
- OS & OS version: Windows 11
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100%
- Firefox version: 129.0.2
- Firefox theme (e.g. default, build in light/dark, external theme + link): System theme - auto with Windows in Dark mode.

**Comment by Aris-t2** [comment]
This will be fixed in next release.
