### ISSUE TITLE
Extension buttons have significantly larger outlines than core buttons on "buttons_on_navbar_aero_appearance.css"

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#681]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
- Extension buttons have significantly larger outlines than core buttons on `buttons_on_navbar_aero_appearance.css` CSS modification on both "hovered" and "clicked" states.
- My solution is to make extension buttons to use the same size of outline as core buttons.
- With the term core button I mean, a button which is by default included in Firefox (like Reload, Back, History, etc...)

#### Steps to reproduce:
1. Put `buttons_on_navbar_aero_appearance.css` to userChrome.css,
2. Open Firefox,
3. Hover at any core button on the navbar to see its outline size,
4. Hover at any extension on the navbar to see its outline size,
5. You will see, that the outlines of the extension buttons are larger than the core buttons.

### 3. Does the issue occur with the most recent version of CustomCSSforFx?
Yes, I have the latest version (v4.5.6)

#### Both extension (left) and core (right) buttons on the hovered state:

![Both hovered](https://github.com/user-attachments/assets/379b730e-7f67-4bc2-8975-1815dd9c45a3)

#### Both extension (left) and core (right) buttons on the clicked state:

![Both Clicked](https://github.com/user-attachments/assets/293b1bd8-2896-4446-9892-6eaf9eb2ee45)

NOTE: The used extension is called [Go Up](https://addons.mozilla.org/en-US/firefox/addon/go-up-button/)

### 5. System information:
- OS & OS version: Windows 10 19045.4894 (64-bit)
- DPI/HiDPI/scaling value: 100%
- Firefox version: Firefox Release v130.0.1 (64-bit)
- Firefox theme: [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix) + [Activist – Soft](https://addons.mozilla.org/en-GB/firefox/addon/activist-soft/)

**Comment by Aris-t2** [comment]
This will be fixed on next update.

**Comment by Aleksandra0056** [comment]
Okay, in release 4.5.7 it behaves correctly, so I'm closing this too.
