### ISSUE TITLE
Update from version 4.1.2

### ISSUE THREAD

**Issue by Nemo1985** [Aris-t2/CustomCSSforFx#684]
Hello, today I updated my Firefox version from 128.2.0 to 128.3.0 and until today everything worked "fine" but the new update has broken the address bar results. I took the chance to update to the latest version of Custom CSS but I noticed there are some differences between the old version and the new one. I'm asking for help to restore the "old layout", the two mayor differences I'm noticing are:
1) The tab bar is thinner
2) There is a black bar on the bottom which wasn't present with the old layout.
3) The text and dimension when I open context menus seem bigger.

I took two screenshots of the new version and old one:
![new](https://github.com/user-attachments/assets/a8aff706-ece9-4aa9-8528-9c317a7da189)
![old](https://github.com/user-attachments/assets/ab4b6920-99fd-4219-8f75-df29869576b2)

Can anyone please guide me of how I can completely restore the old layout?

Thank you very much.

**Comment by Aris-t2** [comment]
1. You are using default setup with classic squared tabs (1st screenshot) vs default tabs (2ns screenshot).
2. Maybe you enabled `addonbar_move_bookmarks_toolbar_to_bottom.css` ?
3. Not sure, what happened here. Default appearance looks like this:
![image](https://github.com/user-attachments/assets/0860af7d-e602-4448-88b7-8fc7aa187100)
or this with `context_bfrsb_icons_colorized.css` and `context_bfrsb_labels_with_icons.css` enabled
![image](https://github.com/user-attachments/assets/165252ff-992f-4b3a-8f99-91c0d8e03833)
The menu can even look like this with` popup_compact_menus.css` and `popup_menus_space_before_label.css`:
![image](https://github.com/user-attachments/assets/a7ab205c-c4f5-4d1a-a06f-2973b6b9780d)

**Comment by Nemo1985** [comment]
Thank you very much for the quick and complete answer.
1) It's weird because I ticked the same options on both old and new version, first screenshot is the new version, the second the old one. Can you please tell me which option I should enable?
Old version: https://pastebin.com/anQ4nA15
New Version: https://pastebin.com/iMGvWgUC
2) You were right the option was enabled on both versions but probably it didn't work on the old one. Solved.
3) I enabled `popup_compact_menus.css` and `popup_menus_space_before_label.css` but apparently the icons are still broken?
![new2](https://github.com/user-attachments/assets/d4b27cff-32e9-44a5-8675-8254cb8fbbee)

**Comment by Aris-t2** [comment]
Please do not mix files from different versions. Only test the latest release without any changes besides the option(s) you are testing.

`popup_compact_menus.css` + `popup_menus_space_before_label.css` + `context_bfrsb_labels_with_icons.css` + `context_bfrsb_icons_colorized.css`

![image](https://github.com/user-attachments/assets/098ba2f6-dc17-4275-adea-350c4b2b4c3c)

**Comment by Nemo1985** [comment]
Thank you, I took the chance to update from v4.5.7 to v4.5.8.
This is how it is with the old (mixed) version: https://imgur.com/a/wylWNP8
This is how it looks with the v4.5.8 and the popup_compact_menus.css + popup_menus_space_before_label.css + context_bfrsb_labels_with_icons.css + context_bfrsb_icons_colorized.css options: https://imgur.com/a/3GA0NbF

Unlucky the context menu is still broken (I think it may something due to some extension I use?) and the top bar with the tabs is thinner.

**Comment by Aris-t2** [comment]
No issue with Fx 128.3esr.
![image](https://github.com/user-attachments/assets/d890b4a6-ba15-4670-823f-9051559c92d3)

And you compared default tabs and classic squared tabs again.

**Comment by Nemo1985** [comment]
I'm sorry you are right, there were those differences now the context menu works fine labels and icons.
The only issue is the thinner tab bar, I tried to compare the differences between the old classic_squared_tabs.css and the new one but I was unable to understand what I need to change (if possible) to have back the thicker bar tab.

**Comment by Aris-t2** [comment]
I think we can close this now. Feel free to reopen, if needed.
