### ISSUE TITLE
All custom back and forward buttons show an unneeded outline when holding a left-click on greyed-out back/forward when `buttons_on_navbar_classic_appearance.css` is imported from userChrome.css

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#685]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
When I hold left-click on any CustomCSSforFx custom back and forward button, then it shows the outline even if the outline shouldn't normally appear under custom back and forward buttons.

#### Expected results:
The outline should not appear under custom back and forward buttons.

#### Steps to reproduce:
1. Enable `buttons_on_navbar_classic_appearance.css` in `userChrome.css`
2. Enable also any custom back and forward CSS file
3. Open Firefox
4. Left-click and hold the cursor on the back/forward buttons (but only in a greyed-out state)
5. The outline from `buttons_on_navbar_classic_appearance.css` shows under these buttons.

#### Affected CSS files:

<details>
<summary>Click to expand...</summary>

- custom_backforward_large_ff2.css
- custom_backforward_large_ff3.css
- custom_backforward_large_ff3_strata.css
- custom_backforward_large_ff3_strata_orange.css
- custom_backforward_large_ff3_strata_red.css
- custom_backforward_large_ie8.css
- custom_backforward_large_ie9.css
- custom_backforward_large_kempelton.css
- custom_backforward_large_noia.css
- custom_backforward_small_ff3.css
- custom_backforward_small_ff3_strata.css
- custom_backforward_small_ff3_strata_orange.css
- custom_backforward_small_ff3_strata_red.css
- custom_backforward_small_ie8.css
- custom_backforward_small_ie9.css
- custom_backforward_small_kempelton.css

</details>

### 3. Does the issue occur with the most recent version of CustomCSSforFx?
Yes, I have the latest version (v4.5.7)

#### One of affected Back buttons:
![Back](https://github.com/user-attachments/assets/896e9ddb-9f59-4f36-94c1-c963121d8adb)

#### One of affected Forward buttons:
![Forward](https://github.com/user-attachments/assets/9a313058-bba1-40c5-8dc4-e1cb14eadd93)

### 5. System information:
- OS & OS version: Windows 10 19045.4894 (64-bit)
- DPI/HiDPI/scaling value: 100%
- Firefox version: Firefox 131.0.0 (64-bit)
- Firefox theme: [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix)

**Comment by Aris-t2** [comment]
Do a clean setup and only enable `custom_backforward_large_ff3_strata.css`.

This issue does not occur in my tests unless you import files in the wrong order in an own `userChrome.css`.
It is important to import `custom_backforward_large_ff3_strata.css` after `buttons_on_navbar_classic_appearance.css`.

![image](https://github.com/user-attachments/assets/ff3a0a90-98d0-4834-8841-28379c475e49)
![image](https://github.com/user-attachments/assets/5417e339-6ea5-479f-84de-44c8a5b1bfc3)

**Comment by Aleksandra0056** [comment]
I can't find the comment you published in this issue, but I still decided to reply.

#### Here is my order of imported CSS files:

![Screenshot 2024-10-04 193216](https://github.com/user-attachments/assets/a67c79e3-f431-4681-8ee4-77dc86b8b910)

I will try to reproduce it in a clean installation in Windows Sandbox VM and after results, I will reply...

**Comment by Aris-t2** [comment]
Found the issue, it will be fixed on next update.

**Comment by Aleksandra0056** [comment]
> Found the issue, it will be fixed on next update.

Okay, thanks.

**Comment by Aleksandra0056** [comment]
I tested all listed back/forward button variants after the release of version 4.5.8 and everything is fixed, so I can close this issue as completed.
