### ISSUE TITLE
Custom Titlebar colors no longer work

### ISSUE THREAD

**Issue by geist22** [Aris-t2/CustomCSSforFx#686]
I am using "TABS BELOW NAVIGATION AND BOOKMARKS TOOLBARS"
`@import "./css/tabs/tabs_below_navigation_toolbar.css"; /**/`
or
`@import "./css/tabs/tabs_below_navigation_toolbar_alt.css"; /**/`

Previously, I could set the colors in the Titlebar in `config\general_variables.css` with:

```
  /* for top_toolbar_colors.css and top_toolbar_colors_v2.css */
  --top_toolbars_background: #4a5659 !important;
  --top_toolbars_background_inactive: #ffffff !important;
  --top_toolbars_text: #ffffff !important;
  --top_toolbars_text_inactive: #999999 !important;
```

A couple months ago, a Firefox update (I don't know which one exactly) broke this and these edits no longer have any effect. My Titlebar is always white, and a slightly darker white while the window is inactive:

![ff1](https://github.com/user-attachments/assets/320eb829-c755-40e7-9270-e8a5c76610db)

I have managed to find a workaround to get some of the desired look back by adding this to `my_userChrome.css`:

```
#navigator-toolbox {
	background-color: #4a5659 !important;
}
```

![ff2](https://github.com/user-attachments/assets/52282ac0-c0c4-4f8f-b671-eb13329a34c0)

But this changes for both active and inactive windows, and doesn't cover the color of the icons on the top right.

**Comment by Aris-t2** [comment]
Still works for me on Firefox 131.

![image](https://github.com/user-attachments/assets/fbca911d-2b29-40a9-91bc-def6a1b56e5d)
![image](https://github.com/user-attachments/assets/59e571bc-5019-4909-81d5-7ee174d9a65c)

**Comment by geist22** [comment]
Oh, I was missing this `@import` in my config. Must have missed to add it during an update...

With this it's working.
