### ISSUE TITLE
Several problems with context menus when `generalui/popup_items_hover_appearance_aero.css` is enabled

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#687]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description:
I found several problems with `generalui/popup_items_hover_appearance_aero.css` in context menus.

#### Problems I found:
- The regular grey hover outline still appears underneath the aero hover outline in the bookmarks menu and content context menu.
- Menu icons from Firefox UI Fix disappear in the bookmarks menu, content context menus and toolbar right-click menus (This is not an issue of Firefox UI Fix, because Firefox UI Fix renders these menu icons correctly. The `popup_items_hover_appearance_aero.css` itself is causing their disappearance).

#### Expected behaviour:
- The regular grey hover outline should not appear at all.
- The menu icons should not disappear.

### 3. Does the issue occur with the most recent version of CustomCSSforFx?
Yes, I have the latest version v4.5.8.

#### The first video shows the disappearing icons and unwanted grey outlines appearing underneath the aero outlines in the content context menu:

https://github.com/user-attachments/assets/2ff286d8-fe7c-40c2-9e3d-0e421b053496

#### The second video shows another disappearing icons and unwanted grey outlines appearing underneath the aero outlines in the bookmarks menu:

https://github.com/user-attachments/assets/0d9360f5-8811-4796-960b-f22db05b37cd

#### The third video shows even more disappearing icons and unwanted grey outlines are also appearing underneath the aero outlines in the toolbar right-click menus:

https://github.com/user-attachments/assets/983bd2a7-1676-4fc8-a3f1-e3e90ee668b9

### 5. System information:
- OS & OS version: Windows 10 19045.4894
- OS architecture: 64-bit
- DPI/HiDPI/scaling value: 100%
- Firefox version: 131.0.0
- Firefox architecture: 64-bit
- Firefox theme: [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix)

**Comment by Aris-t2** [comment]
Please run all your tests with this projects files only (no Firefox UI fix and no custom "other" code).

None of the above mentioned issues are present in my tests.

The icons in context menu are not present in browsers default config. The first video shows the missing icons issue only affects icons added by Firefox UI fix or other custom code. Default extension icons are not affected, right?

**Comment by Aris-t2** [comment]
https://github.com/user-attachments/assets/5b29f695-f8db-4df8-a49d-5ce8f767eba1

**Comment by Aleksandra0056** [comment]
Yes, default extension icons aren't affected. You're right, that it's related to Firefox UI Fix, but the CustomCSSforFx is causing this problem because Firefox UI Fix renders these icons correctly.

I reported a similar problem in past, here it is https://github.com/Aris-t2/CustomCSSforFx/issues/657#issuecomment-2170618379

Here is the result in clean Firefox:

![image](https://github.com/user-attachments/assets/e56c5c01-dbf9-47dd-8329-72d724b3a350)

**Comment by Aris-t2** [comment]
Sorry, but this won't be fixed. The "Aero effect" happens through the CSS rule `background-image`https://github.com/Aris-t2/CustomCSSforFx/blob/master/current/css/generalui/popup_items_hover_appearance_aero.css#L16.

If other/custom code uses the same rule to add icons, there will be a conflict like this.

**Comment by Aleksandra0056** [comment]
Okay, I will try to fix it on my Firefox myself by disabling some settings or something.

But thank you for responding to my issue.

**Comment by Aleksandra0056** [comment]
Since this can't be fixed, I'm closing this issue as not planned.
