### ISSUE TITLE
The `toolbars/addonbar_status_in_addonbar.css` appears in bookmarks toolbar instead of add-on bar

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#688]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description:
I noticed, that `toolbars/addonbar_status_in_addonbar.css` appears in the bookmarks toolbar instead of the add-on bar which is very weird because it shouldn't behave like this.

#### Expected results:
The `toolbars/addonbar_status_in_addonbar.css` should appear on the left of the add-on bar.

#### Steps to reproduce:
1. Put a line `@import url("css/toolbars/addonbar_status_in_addonbar.css");` to `userChrome.css`,
2. Restart Firefox,
3. Hover at some URL,
4. You will see, that the status appears in the bookmarks toolbar instead of the add-on bar.

### 3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, I have the latest version v4.5.8.

### 4. Screenshots showing the issue (drag & drop images into this post):

![image](https://github.com/user-attachments/assets/074248df-bbe6-4e24-8837-008777b21028)

### 5. System information:
- OS & OS version: Windows 10 19045.4894
- OS architecture: 64-bit
- DPI/HiDPI/scaling value: 100%
- Firefox version: 131.0.0
- Firefox architecture: 64-bit
- Firefox theme: [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix)

**Comment by Aris-t2** [comment]
This is the correct behavior.

That option is part of the largen option group to "simulate" the addon bar. Therefor `addonbar_move_bookmarks_toolbar_to_bottom.css` has to be active. Otherwise it would not make sense.

![image](https://github.com/user-attachments/assets/c2ca9558-a8fe-4ac7-bd19-64560bea1b45)

**Comment by Aleksandra0056** [comment]
Okay. Apologising, I didn't know about that.
