### ISSUE TITLE
The `generalui/set_as_desktop_background_menuitems_hidden.css` CSS feature isn't disabling the respective separator

### ISSUE THREAD

**Issue by Aleksandra0056** [Aris-t2/CustomCSSforFx#690]
### 1. Does the issue occur without any files inside /chrome/ folder?
No.

### 2. Issue description:
I noticed, that the `generalui/set_as_desktop_background_menuitems_hidden.css` CSS feature isn't disabling the respective separator in the image content right-click context menu leading to doubled separators.

#### Expected results:
The `generalui/set_as_desktop_background_menuitems_hidden.css` CSS feature should also disable the respective separator.

#### Steps to reproduce:
1. Add the `@import url("css/generalui/set_as_desktop_background_menuitems_hidden.css");` line to userChrome.css file,
2. Restart the Firefox browser,
3. Go to any website which contains at least one non-SVG image,
4. Right-click on any image,
5. You will see doubled separators in the context menu.

#### userChrome.css file:

<details>
<summary>Click to expand...</summary>

/*= Import Lepton stylesheet (Chrome) ==============================*/
@import url("css/leptonChrome.css");

/*= CustomCSSforFx importing =======================================*/
/* @import url("css/toolbars/addonbar_status_in_addonbar.css"); */
@import url("css/appbutton/appbutton_in_titlebar_icon_only.css");
@import url("css/buttons/buttons_on_navbar_classic_appearance.css");
@import url("css/buttons/buttons_on_bookmarks_toolbar_classic_appearance.css");
@import url("css/buttons/buttons_on_bookmarks_toolbar_classic_appearance_items.css");
@import url("css/buttons/custom_backforward_large_ff3_strata.css");
@import url("css/generalui/close_icon_red.css");
@import url("css/generalui/popup_items_hover_appearance_aero.css");
@import url("css/generalui/set_as_desktop_background_menuitems_hidden.css");
@import url("css/locationbar/ac_popup_megabar_result_highlighting_aero.css");
@import url("css/locationbar/identitybox_labels_hidden.css");
@import url("css/locationbar/identitybox_padlock_icon_arrow.css");
@import url("css/locationbar/identitybox_replace_search_icon_with_globe.css");
@import url("css/locationbar/urlbar_icons_aero_appearance.css");
@import url("css/locationbar/urlbar_restore_visible_border.css");
@import url("css/locationbar/zoom_button_hidden.css");
@import url("css/tabs/missing_tab_favicon_restored_globe_v2.css");
@import url("css/tabs/tab_close_hidden_for_only_one_visible_tab.css");
@import url("css/tabs/tab_throbber_green.css");

/*= Icons tweaks ===================================================*/

/* Menu-bar icons */
#menu_HelpPopup_reportPhishingtoolmenu {
  --menuitem-image: url("../icons/toolbar/warning.svg") !important;
}

#feedbackPage {
  --menuitem-image: url("../icons/toolbar/feedback.svg") !important;
}

#helpSafeMode {
  --menuitem-image: url("../icons/toolbar/tsht.svg") !important;
}

#troubleShooting {
  --menuitem-image: url("../icons/toolbar/tsht_m.svg") !important;
}

#fileMenu-restart-item {
  --menuitem-image: url("../icons/toolbar/restart.svg") !important;
}

/* Panel and menu icons */

#context-viewpartialsource-selection,
#context-viewsource {
  --menuitem-image: url("../icons/toolbar/code.svg") !important;
}

#appMenu-bookmarks-button {
  list-style-image: url("icons/toolbar/bkm_empty.svg") !important;
}

#appMenu_feedbackPage {
  list-style-image: url("icons/toolbar/feedback.svg") !important;
}

#appMenu_helpSafeMode {
  list-style-image: url("icons/toolbar/tsht.svg") !important;
}

#appMenu_troubleShooting {
  list-style-image: url("icons/toolbar/tsht_m.svg") !important;
}

#appMenu_menu_HelpPopup_reportPhishingtoolmenu {
  list-style-image: url("icons/toolbar/warning.svg") !important;
}

/* Toolbar icons*/

#home-button {
    list-style-image: url("icons/toolbar/spd_dial.svg") !important;
    -moz-image-region: auto !important;
}

#reload-button {
    list-style-image: url("icons/toolbar/reload_2arrows.svg") !important;
    -moz-image-region: auto !important;
}

/*= Menu-bar tweaks ================================================*/

/* Disable spacer in menu-bar */
#toolbar-menubar > spacer {
  display: none !important;
}

/* Hide the menu-bar */
#menubar-items { 
  display: none !important; 
}

/*= Tab-bar tweaks =================================================*/

/* Close Tab button size */
#TabsToolbar .tabbrowser-tab .tab-close-button {
  width: 16px !important;
  height: 16px !important;
  padding: 2px !important;
}

/*= Extensions icons tweaks ========================================*/

/* Go Up */
toolbarbutton[id*="080395d5-2f2d-44ff-8320-79747016b5d4"] .toolbarbutton-icon {
 list-style-image: url("icons/extensions/1.svg") !important; }

and: toolbarbutton[id*="080395d5-2f2d-44ff-8320-79747016b5d4"] .toolbarbutton-icon {
 list-style-image: url("icons/extensions/1.svg") !important; }

/* Reload button */
toolbarbutton[id*="96999337-8b64-424f-92a7-259f1faf930b"] .toolbarbutton-icon {
 list-style-image: url("icons/extensions/2.svg") !important; }

and: toolbarbutton[id*="96999337-8b64-424f-92a7-259f1faf930b"] .toolbarbutton-icon {
 list-style-image: url("icons/extensions/2.svg") !important; }

/* Stop button */
toolbarbutton[id*="ca48401e-96a5-47ea-8009-7c2f62efe060"] .toolbarbutton-icon {
 list-style-image: url("icons/extensions/3.svg") !important; }

and: toolbarbutton[id*="ca48401e-96a5-47ea-8009-7c2f62efe060"] .toolbarbutton-icon {
 list-style-image: url("icons/extensions/3.svg") !important; }

/* VPS Button */
toolbarbutton[id*="mpopp-view-page-source"] .toolbarbutton-icon {
 list-style-image: url("icons/toolbar/code.svg") !important; }

and: toolbarbutton[id*="mpopp-view-page-source"] .toolbarbutton-icon {
 list-style-image: url("icons/toolbar/code.svg") !important; }

</details>

### 3. Does the issue occur with the most recent version of CustomCSSforFx?
Yes, I have the latest version v4.5.8.

### 4. Screenshots showing the issue:

![Screenshot 2024-10-06 124941](https://github.com/user-attachments/assets/6e890043-e2ef-4a86-a24e-7fe3b19d7474)

### 5. System information:
- OS & OS version: Windows 10 19045.4894
- OS architecture: 64-bit
- DPI/HiDPI/scaling value: 100%
- Firefox version: 131.0.0
- Firefox architecture: 64-bit
- Firefox theme: [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix)

**Comment by Aris-t2** [comment]
This will be fixed on next update.

**Comment by Aleksandra0056** [comment]
Okay, it's fixed after the update to v4.5.9. Closing...
