### ISSUE TITLE
Set to 580px. That's just perfect now! You are a true wizard. Many thanks!!!

### ISSUE THREAD

**Issue by 9jkh** [Aris-t2/CustomCSSforFx#693]
Set to 580px. That's just perfect now! You are a true wizard. Many thanks!!!

_Originally posted by @9jkh in https://github.com/Aris-t2/CustomCSSforFx/discussions/606#discussioncomment-10163534_

**Comment by 9jkh** [comment]
Note, posting as a new issue, since you are unlikely to see my reply in the original location.

Hi Aris, not sure if you can help with this, but I ran a command suggested by someone, and others, with whom I have high confidence, to deal with an issue in my Dosdude Catalina 10.15.7 where Firefox was crashing on first open. The command I used fixed that issue, but has introduced some ill effects in that Firefox.

The CSS above was working perfectly until I ran this command, but now the settings in my Firefox 128.3esr are once again way out of proportion, and that CSS now has no effect. Can you possibly suggest something that will maybe have a stronger effect?
![Screenshot 2024-10-12 at 1 58 28 PM](https://github.com/user-attachments/assets/80505885-71ba-44b7-a39a-bd2799fdd0e9)

**Comment by Aris-t2** [comment]
https://github.com/Aris-t2/CustomCSSforFx/discussions/606#discussioncomment-11055040
