### ISSUE TITLE
UserContent.css > preferences_alternative_appearance_v2.css

### ISSUE THREAD

**Issue by click-click** [Aris-t2/CustomCSSforFx#696]
I just migrated from firefox 115 ESR To 128 ESR and the checkboxes in Settings have disappeared. **preferences_alternative_appearance_v2.css** seems be the culprit here. If I disable it, the checkboxes are back, but it's no longer compact and the icons are not like they were in v115. Background shade different too.

1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here. No for missing checkboxes

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue: @import "./css/aboutpreferences/preferences_alternative_appearance_v2.css"; /**/

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
yes  custom_css_for_fx_v4.5.9

4. Screenshots showing the issue (drag & drop images into this post) 
![v115](https://github.com/user-attachments/assets/b9bef581-ce62-4d79-bffb-22f5794b6a7a)
![v128e](https://github.com/user-attachments/assets/7d6aac7f-55a8-4d43-87d5-54882509713a)
![v128](https://github.com/user-attachments/assets/c27f5bce-2a8b-4af2-bd06-03f311693f41)

5. System information
- OS & OS version:  Microsoft Windows [Version 10.0.22631.4317]
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...):  125%
- Firefox version: 128,3,1
- Firefox theme (e.g. default, build in light/dark, external theme + link): System theme — auto 1.3

**Comment by Aris-t2** [comment]
Open `preferences_alternative_appearance_v2.css` and remove these lines of code;

```css
	checkbox .checkbox-check {
	  appearance: unset  !important;
	  box-shadow: unset !important;
	}

	radio .radio-check {
	  appearance: unset !important;
	  box-shadow: unset !important;
	}
```

**Comment by click-click** [comment]
Should I have put this in the discussion section? A big thanks for the solution. That works well.
![v128css](https://github.com/user-attachments/assets/0a6b0d9e-be0a-4cae-bf4c-88869f4b0da9)

**Comment by Aris-t2** [comment]
Not needed, next update will fix this.

**Comment by Aris-t2** [comment]
Fixes on latest release.
