### ISSUE TITLE
[Firefox 133+] tabs below toolbar does not working anymore

### ISSUE THREAD

**Issue by Omnibrain007** [Aris-t2/CustomCSSforFx#697]
Hi,

The code for tabs below toolbar does not working anymore with new version 133.0b1 on Win10
The tabs are on top again with latest beta update before with version 132 all is fine.

CSS -  "tabs_below_navigation_toolbar_alt.css"

**Comment by Aris-t2** [comment]
Test `tabs_below_navigation_toolbar_fx133.css` instead. It also works with `tabs_multiple_lines.css` on Firefox 133.

**Comment by Omnibrain007** [comment]
Just tested. It works with 133. thx
The only thing is that it does not work anymore  with 132, 
so I have to wait with this css until later my other Firefox updating on the release channel. ;)

**Comment by Aris-t2** [comment]
Sadly we have to play around with different file versions again, because Fx 133 changes too much.

**Comment by Aris-t2** [comment]
Fixed on latest release(s).
