### ISSUE TITLE
133.0b1: Address bar becomes huge when starting to type something

### ISSUE THREAD

**Issue by ThiefMaster** [Aris-t2/CustomCSSforFx#698]
> Does the issue occur without any files inside /chrome/ folder?

No.

> Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

[userChrome.css.txt](https://github.com/user-attachments/files/17559477/userChrome.css.txt)

Just start typing something in the address bar.
As soon as you start typing something, it becomes big and hides everything else.

> Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?

Yes, updated to the latest release v4.5.9 before reporting this.

> Screenshots showing the issue (drag & drop images into this post):

![image](https://github.com/user-attachments/assets/29e57d02-f041-4b31-9061-f30fd8fd1191)
![image](https://github.com/user-attachments/assets/51595525-d662-42eb-9095-4f3124e9dfa0)

6. System information
- OS & OS version: Win 10
- Firefox version: 133.0b1
- Firefox theme: Default dark

**Comment by Aris-t2** [comment]
Disable `megabar_expanding_breakout_disabled.css` for now. Next update will deal with this by offering a new Fx133+ compatible option `megabar_expanding_breakout_disabled_fx133.css`.

**Comment by Aris-t2** [comment]
In case you did not see this yet, the bug was fixed: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.6.0

**Comment by ThiefMaster** [comment]
Thanks! (even though I didn't notice any change when I started using your workaround, so even using that was fine for me)
