### ISSUE TITLE
smaller_tab_width_in_overflow_mode and pinned tabs

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#7]
After module is enabled in pinned tabs part of title becomes visible.
![smaller_tab_width_in_overflow_mode](https://user-images.githubusercontent.com/32600318/31356834-26e30e40-ad48-11e7-9465-8870b9c008ff.png)
I believe that pinned tabs shouldn't have any title name after module is enabled.

**Comment by Aris-t2** [comment]
Thanks for reporting. 
Will be fixed on next update.

**Comment by Acid-Crash** [comment]
fixed in 1.04
