### ISSUE TITLE
[Firefox 132] Pinned tab width increased

### ISSUE THREAD

**Issue by R8s6** [Aris-t2/CustomCSSforFx#701]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.
Yes, however this issue might be caused by `CustomCSSforFx` being "incompatible" or perhaps not recognizing a new value in firefox v132, as the increased space is more of a personal preferences than being a bug.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
The width of pinned tabs increased after I upgraded firefox to v132.
This results in fewer tabs shown on the tab bar.
I tried to change value of min width to 1:  `--tab_min_width: 1;` in `tab_maxwidth.css`, but it has no effects.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes, tested on `custom_css_for_fx_v4.5.9`

4. Screenshots showing the issue (drag & drop images into this post):
![](https://i.imgur.com/N0GfyCI.png)

The space between each pinned tabs used to be less than what's shown above.

5. System information
- OS & OS version:  Arch, upgraded to 2024-11-04
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...):  96dpi with 200% scale
- Firefox version: 132.0
- Firefox theme (e.g. default, build in light/dark, external theme + link):  default + builtin light/dark, all the same

Not a breaking/urgent issue, but it'd be awesome it if the pinned tab width could be reduced to a customized value.

Thank you so much for the hard work!

**Comment by Aris-t2** [comment]
Tab content padding got changed a bit, you can adjust it with 

```css
.tab-content {
  padding: 0 8px !important;
}
```

This has nothing to do with tab width values.

**Comment by R8s6** [comment]
thank you so much, that did it!

I'd just like to clarify for anyone else who stomps upon this thread, that the file to be edited is `my_userChrome.css`.

Thanks again and case closed.
