### ISSUE TITLE
Audio Icon Problem since FF132

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#702]
Using Aris-t2 default tab_audio_icon_colorized and tab_audio_icon with classic_squared_tabs I have three problems since FF132

Three Things:
1 - I would like to have the Audio icon present in all Tabs that have Audio/Video whether they are playing or not.
2 - when I pause audio/video content the audio icon disappears after 5 seconds. I would like it to just change colour on pause no matter the tab it is in and remain visiable.
3 - Increase the gap between the Favicon and the Audio icon - refer picture

![Screen Shot 2024-11-07 at 14 53 16](https://github.com/user-attachments/assets/624e0041-1f44-42b9-9f5e-7f33af9ddebc)

5. System information
- macOS 10.15.7
- Firefox version: 132.0.1
- Firefox theme default Light

**Comment by ChasCB** [comment]
After playing around with this some more I actually do not mind the new FF HD default audio icon. So I have stopped using tab_audio_icon_colorized entirely. But I am still left with my original 3 problems/help requests.

1 - I would like to have the Audio icon present in all Tabs that have Audio/Video whether they are playing or not.

2 - when I pause audio/video content the audio icon disappears after 5 seconds. I would like it to just change to pause no matter the tab it is in and remain visible.

3 - Increase the gap between the Favicon and the Audio icon - refer picture

**Comment by joefiesta** [comment]
I would also like to add:
1.   when the tab is MUTED, the icon also disappears quickly.   It is thus impossible to tell which, if any, tabs are actually playing audible content.  

where does Firefox get these lame-brained ideas?

**Comment by ChasCB** [comment]
I have dug around in the about:config and came across this setting:

browser.tabs.delayHidingAudioPlayingIconMS 3000

This setting controls the time that the audio icon is present, therefore this may partially help my questions 1 & 2.

So how do you turn this setting off, so then the icon will always be there ?

**Comment by Cobinja** [comment]
Maybe this can be used as a starting point. It restores the behavior from some time ago, with the audio icon on the end of the tab for tabs with audio. In this form, the icon is hidden when no audio is playing.
```
:root{
  --inline-tab-padding: 0.6rem;
}

.tab-icon-stack {
  position: absolute !important;
  top: 0px !important;
  height: 100% !important;
  width: calc(100% - 1.5 * (var(--inline-tab-padding))) !important;
  display: flex !important;
  align-items: center !important;
  justify-content: space-between !important;
}

.tab-label-container {
  margin-left: calc(2 * var(--inline-tab-padding) + 8px) !important;
}

.tab-icon-stack:is([muted],[soundplaying],[activemedia-blocked]) ~ .tab-label-container label {
  width: calc(100% - 4 * (var(--inline-tab-padding)) + 20px) !important;
  overflow: hidden !important;
}

.tab-icon-overlay {
  padding: 0 !important;
  background-color: transparent !important;
  border: none !important;
}

.tab-icon-stack:is([soundplaying], [muted], [activemedia-blocked]) > * {
  opacity: 1 !important;
}

```

**Comment by ChasCB** [comment]
Thank you but the problem has now been solved. Pls refer to this post: [(https://github.com/Aris-t2/CustomCSSforFx/discussions/606#discussioncomment-11245577)]

**Comment by Aris-t2** [comment]
The fix is part of latest release:
https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.6.0
