### ISSUE TITLE
more compact tabs toolbar in "tabs_below_navigation_toolbar_fx133.css"

### ISSUE THREAD

**Issue by Omnibrain007** [Aris-t2/CustomCSSforFx#705]
Hi,
I am using the "tabs_below_navigation_toolbar_fx133.css" standalone together with the "compact mode" of firefox.
But for me the height of the tabs toolbar is too big. 
With the last versions of this css, I managed to reduce the height of the tabs toolbar. But with this new version 133 I'm at the end with my little knowledge of css ;) 

Is it possible to easily reduce the height of the TabsToolbar? 

![grafik](https://github.com/user-attachments/assets/e349ade3-1ecf-488c-aeb2-b2d3d53d784d)

**Comment by joefiesta** [comment]
I tried the "compact mode" for FF,  (ff 130.0.2),  Config file setting and setting DENSITY in "customize toolbar".   Neither changed anything.  I have to presume some Aris CSS code I have is overriding this.    I really like the idea  that customize mode will reduce the HUGE spacing in the built-in Firefox menus.  Awwww

**Comment by Aris-t2** [comment]
Fx133: default tabs + tabs_below_navigation_toolbar_fx133.css + normal mode
![image](https://github.com/user-attachments/assets/36290ebc-1f53-413f-ac0d-032579a75144)

Fx133: default tabs + tabs_below_navigation_toolbar_fx133.css + compact mode
![image](https://github.com/user-attachments/assets/dfb1aada-1d32-444f-a343-cc8d84d1bdcd)

You can try this code in addition to reduce the size even more:
```css
:root {
	--tab-min-height: unset !important;
}
```
![image](https://github.com/user-attachments/assets/a80f5bbc-e12d-4133-82e6-cde08537ee48)

**Comment by Omnibrain007** [comment]
thanks, last version with additional code is fitting for me. 
Perhaps you can implement this code optional or for compact mode only in your exisitng css.  
Could be helpful also for others who wants to have more compact toolbars. ;)

**Comment by p1nkyy** [comment]
Hi, I have the opposite problem, I feel like my tab's height is too small

https://puu.sh/Kjrmv/42f06fe653.png

And the font in my address bar is too small as well.

![image](https://github.com/user-attachments/assets/ea4b2a13-af63-4f2b-937d-6293c6d64e10)

Which option to tweak please? Thanks before.

I implemented the multirow and I would like the + new tab button to be right next to the last tab. Is this possible?

**Comment by Aris-t2** [comment]
If you are using this projects `tabs_multiple_lines.css` file, the + (new tab) position stays (right after last tab).

You can remove the box shadow from active tab using this:

```css
.tab-background:is([selected], [multiselected]) {
  box-shadow: unset !important;
}
```

**Comment by p1nkyy** [comment]
Got it, can pls help with my slightly cut off menu bar as well?

![image](https://github.com/user-attachments/assets/516569af-fccb-4b42-943e-ffb008981180)

**Comment by Aris-t2** [comment]
This will be fixed on next update.

Open `tabs_below_navigation_toolbar_fx133.css` and remove this code

```css
#main-window[sizemode="maximized"] #toolbar-menubar {
  margin-top: -5px !important;
}
```

**Comment by Aris-t2** [comment]
Fix is online on recent release.
