### ISSUE TITLE
Extra Tab Bar below actual Tab Bar with fx133.css

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#709]
tabs_below_navigation_toolbar_fx133.css now places and extra tab bar below actual tab bar

![Screen Shot 2024-11-28 at 14 30 58](https://github.com/user-attachments/assets/de17b984-10d7-4ef6-9ba3-e57f9a6c9df4)

**Comment by Aris-t2** [comment]
Run tests on a clean new profile using this projects latest release without any other custom code.

**Comment by ChasCB** [comment]
OK - Do Not know what is going on here but did as you suggested with a clean profile - that did not fix the issue
BUT
I reverted back to tabs_below_navigation_toolbar.css from release 4.5.4 on existing profile (pre clean profile) which I was using upto and including FX132 and all ok now, no ghost tab bar.

Very strange 🤷‍♂️

**Comment by ChasCB** [comment]
tabs_below_navigation_toolbar_fx128-132.css fixes this issue

Thanks again Aris for all the work you do.
