### ISSUE TITLE
Style for Firefox mix toolbar missing

### ISSUE THREAD

**Issue by Speravir** [Aris-t2/CustomCSSforFx#71]
I used the Firefox mix toolbar with the addon. Now, the image for the toolbar is existent, but there is no style I could apply this.

**Comment by Aris-t2** [comment]
Its the default one `@import url(./css/buttons/icons_custom_icons.css);`

**Comment by Speravir** [comment]
Oops, sorry that I missed this.

**Comment by Aris-t2** [comment]
No problem.
