### ISSUE TITLE
Menu bar cuts off when in fullscreen

### ISSUE THREAD

**Issue by Nyekomimi** [Aris-t2/CustomCSSforFx#711]
1. Does the issue occur without any files inside /chrome/ folder?
No, it appeared when I changed userChrome.css to newest one.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
When using settings (attaching settings file) below, text on menu bar is partially cut off when in full screen. Issue does not exist in non-maximized window.

Settings: [userChrome.txt](https://github.com/user-attachments/files/17945734/userChrome.txt)

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Yes, I downloaded it today.

4. Screenshots showing the issue (drag & drop images into this post):

![aris1](https://github.com/user-attachments/assets/cabe89c5-0266-4900-844d-2838cc6da7b5)
![aris2](https://github.com/user-attachments/assets/9c1316f0-b18f-4c44-a53f-aadd0d0a6a79)

5. System information
- OS & OS version: Win10, not sure
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 100?
- Firefox version: Autoupdated (selecting post-133 in new script fixed some issues so its 133 or later)
- Firefox theme (e.g. default, build in light/dark, external theme + link): Default I think

**Comment by Aris-t2** [comment]
Check this https://github.com/Aris-t2/CustomCSSforFx/issues/705#issuecomment-2506404934

**Comment by Nyekomimi** [comment]
It solved the problem, tyvm.
