### ISSUE TITLE
After upgrade to v.133 there's a line below the menu bar

### ISSUE THREAD

**Issue by mozo78** [Aris-t2/CustomCSSforFx#712]
Hello,
It's actually a question for a code to remove this line which appeared when upgraded to v.133 with the tabs below bookmark toolbar.
Thank you and excuse me if I borked something with the rules, it's not intentional.

----------------------------------

Add all information required in 1-5 and delete this line and everything above it before submitting.

1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.
I don't know for I have many mods.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
It's always there, no matter the settings.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes.

4. Screenshots showing the issue (drag & drop images into this post):
![Screenshot_2024_28_11_13_0](https://github.com/user-attachments/assets/e6d20cf5-2ea2-4fd3-ace2-ce4cb94a2a82)

5. System information
- OS & OS version:  Arch Linux
- Firefox version: 133
- Firefox theme (e.g. default, build in light/dark, external theme + link): Brushed Metal XP https://addons.mozilla.org/en-US/firefox/addon/brushed-metal-xp/

**Comment by Aris-t2** [comment]
I can not get the line to appear during my tests, share you userChome.css file.

**Comment by mozo78** [comment]
Thanks for the directions! I found it - an old referal to this code:
https://pastebin.com/FbSAnRc1
After I removed it, I don't see a difference so it's obviously needless.
Thank you once again and I'm sorry for bothering you!
