### ISSUE TITLE
The tab line is the same color as the theme after upgrade to v.133

### ISSUE THREAD

**Issue by mozo78** [Aris-t2/CustomCSSforFx#713]
Hello,
I will send a screenshot below for I don't know how to explain what the problem is exactly. Prior 133 the empty tab line where there's no tabs looked like this:
![Screenshot from 2024-11-28 13-12-31](https://github.com/user-attachments/assets/9452b49f-0533-4dd2-bfda-4e59e216b21a)
As you can see, it's a little darker than the main theme and is very appealing for my eyes. Now with v.133 the darker section disappeared completely:
![Screenshot_2024_28_11_13_21](https://github.com/user-attachments/assets/975af56b-7530-4e59-8113-0aecaaec6bfb)

How can I turn it back?
Thank you very much for your hard work!

Add all information required in 1-5 and delete this line and everything above it before submitting.

1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.
Yes.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
It's always there, no matter the settings.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-
Yes.

4. System information
- OS & OS version:  Arch Linux
- Firefox version: 133
- Firefox theme (e.g. default, build in light/dark, external theme + link): Brushed Metal XP https://addons.mozilla.org/en-US/firefox/addon/brushed-metal-xp/

**Comment by Aris-t2** [comment]
Not sure, if there is something different on Linux, but tabs toolbar should look the way it looks on your Fx133 screenshot.

Its like this for me on Fx 128 ESR and on Fx 133-135 too.

![image](https://github.com/user-attachments/assets/010a07ec-04a1-43a4-8440-8844da4b8726)

**Comment by mozo78** [comment]
Thank you for your reply!
Is there a way to darken it a bit?

**Comment by Aris-t2** [comment]
Try this

```css
:root[lwtheme][style*='--lwt-header-image'] #TabsToolbar {
  background: rgba(0,0,0, 0.2) !important;
}
```

**Comment by mozo78** [comment]
It's working great, thank you very, very much! You're great as always!
