### ISSUE TITLE
Menubar alignment, close icon size

### ISSUE THREAD

**Issue by m4n8tpr4** [Aris-t2/CustomCSSforFx#715]
1. Does the issue occur without any files inside /chrome/ folder?
No

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:
After an FF update some time ago, there is space between the menu bar and the tabs. I see the vertical distance is determined by the window minimize/fullsize/close icons, so either some function that reduces those icons' size or padding was lost, or the vertical alignment of the menu items changed from middle to top.
I have appbutton hidden & all appbutton settings disabled, menubar enabled, default vertical tab placement.

4. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
Current version: 4.6.2 v2; unfortunately can't remember from which version the issue appeared

5. Screenshots showing the issue (drag & drop images into this post):
![FF133_menubar](https://github.com/user-attachments/assets/347d4c17-eac7-47fe-9892-f51cd00a5864)

6. System information
- Windows 10
- DPI 100%
- Firefox version: 133.0
- Firefox theme: default

**Comment by m4n8tpr4** [comment]
> You can increase the padding between menubar items an top window corner using this:
> 
> ```css
> #main-menubar {
>   padding-top 2px !important;
> }
> ```

Thank you! In which file should I add this? general_variables.css?

Alternatively, is there a way to resize the window minimize/fullscreen/close icons? I found settings/.css for the tab close icons, but not the window top right icons. (If this would be a new feature rather than something I missed I'll move this to Discussions.)

**Comment by skaw847** [comment]
where did you find this?

**Comment by m4n8tpr4** [comment]
> where did you find this?

I'm no pro at coding. I just ran several Google searches, and finally found multiple threads in other forums where changing the titlebar min/max/close buttonbox for various reasons was discussed. From there on it was trial & error.

**Comment by Aris-t2** [comment]
Custom / additional code is meant to be added to the bottom of `userChrome.css` or `my_userChrome.css`.
