### ISSUE TITLE
Firefox 133 - Tabs toolbar when placed at the bottom overlaps the main content of the page

### ISSUE THREAD

**Issue by Retifff** [Aris-t2/CustomCSSforFx#718]
1. Does the issue occur without any files inside /chrome/ folder?  
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.

No, because in pure Firefox there is no tab layout at the bottom.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

@import "./css/tabs/tabs_below_main_content.css"; /**/ /* for Firefox 133+ */

Tabs toolbar when placed at the bottom overlaps the main content of the page. In previous versions of Firefox (132 and below) this was not the case.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?  
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-

Yes. 4.6.6.

4. Screenshots showing the issue (drag & drop images into this post):

![image](https://github.com/user-attachments/assets/78b6a819-24bb-40d5-ae16-e2be1ffe0bff)

5. System information  
OS: Windows 10, 22H2, build 19045.4780
DPI: 125% and 200%
Firefox 133.
Theme Light

Sorry for my English.

**Comment by Aris-t2** [comment]
This and some other issue with the "option" will be fixed on next release.

**Comment by Aris-t2** [comment]
Release 4.6.7 should take care of this matter.
https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by Retifff** [comment]
Thank you very much, everything is great now!
