### ISSUE TITLE
[Waterfox 6.5.2/Firefox 128 ESR] Private Mode Indicator Hidden Without Config Set

### ISSUE THREAD

**Issue by IdrisQe** [Aris-t2/CustomCSSforFx#719]
1. Does the issue occur without any files inside /chrome/ folder?
-> If it does, it might be a Firefox bug not related to this projects files, so "the issue report" is most likely wrong here.

It does not.

2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:

The Private Mode Indicator is hidden despite having that config commented out.

3. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?
-> Check here: https://github.com/Aris-t2/CustomCSSforFx/releases <-

It is occuring with v4.6.7, which is the current release.

4. Screenshots showing the issue (drag & drop images into this post):

With CSS:
![withcss](https://github.com/user-attachments/assets/cdec0d9c-7982-4db8-8d97-8a8980da2c3c)
Without CSS:
![withoutcss](https://github.com/user-attachments/assets/b945d413-2a89-4b7c-90a9-a5680e49d7bf)
The relevant config:
![file](https://github.com/user-attachments/assets/e96159e5-0f7f-4e9e-b822-7675817dbc14)

5. System information
- OS & OS version: Windows 10 22H2
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 110%
- Firefox version: Waterfox 6.5.2, based off of Firefox 128 ESR
- Firefox theme (e.g. default, build in light/dark, external theme + link): 
External Theme:
https://addons.mozilla.org/en-US/firefox/addon/microsoft-edge-light/

**Comment by Aris-t2** [comment]
If you really need this space wasting indicator with classic squared tabs, you can enable it using this:

```css
#TabsToolbar #private-browsing-indicator-with-label {
  display: flex !important;
}
```

**Comment by Aris-t2** [comment]
Test 4.6.8 release: https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by IdrisQe** [comment]
> If you really need this space wasting indicator with classic squared tabs, you can enable it using this:
> 
> ```css
> #TabsToolbar #private-browsing-indicator-with-label {
>   display: flex !important;
> }
> ```

I find it useful personally as it's more readable at a glance than the text in the titlebar but also not as in-your-face as using an entirely different theme.

Thanks for the code! (That said, that code made it permanently visible, even in non-private windows)
So here's a version for anyone still using 4.6.7 who wants a temporary fix (also bonus code to hide the text portion):

```
#main-window[privatebrowsingmode="temporary"] #TabsToolbar #private-browsing-indicator-with-label {
  display: flex !important;
}
#private-browsing-indicator-with-label > label {
  display: none;
}
```

And thanks for fixing it in 4.6.8 - I get not liking it, but there's already the "hide private indicator" setting in userchrome so it's odd that it was disabled even with that setting commented.
