### ISSUE TITLE
[Win][Fx133]: Addonbar and Bookmark toolbar items breaks the URL address bar position

### ISSUE THREAD

**Issue by rddim** [Aris-t2/CustomCSSforFx#721]
**1. Does the issue occur without any files inside /chrome/ folder?**
-> No

**2. Issue description, userChrome.css/userContent.css 'settings' the issue occurs with and steps to reproduce the issue:**

When I enable `./css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css` and move the `Bookmarks toolbar items` under the URL address bar, the address bar is moving up and overlap the tabs. The issue start with FF 133.

1. Start with a fresh new profile of FF and activate `toolkit.legacyUserProfileCustomizations.stylesheets`
2. In `userChrome.css` enable **only** `@import "./css/toolbars/addonbar_move_bookmarks_toolbar_to_bottom.css"; /**/`
3. Customize the toolbar by moving the `Bookmarks toolbar items` under the URL address bar

**4. Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?**
-> Yes

**5. Screenshots showing the issue (drag & drop images into this post):**
![ff_addonbar](https://github.com/user-attachments/assets/6ce84840-deb1-488a-a24c-3bab77db2dd4)

**6. System information**
- OS & OS version: Windows 10 IoT Enterprise LTSC 2021 (64-bit), 21H2, 19044.1288
- DPI/HiDPI/scaling value: 100%
- Firefox version: 133.0.3
- Firefox theme: default (automatic dark by OS)

**Comment by Aris-t2** [comment]
Test 4.6.9 release https://github.com/Aris-t2/CustomCSSforFx/releases

**Comment by rddim** [comment]
4.6.9 fix the address bar, but there is a regression. The `>>` show more bookmarks are in the middle of the screen, i.e. not at the end.
![ff_bookmarks](https://github.com/user-attachments/assets/8aae657c-7f46-4bdf-af14-47dcdfa47d1c)

**Comment by Aris-t2** [comment]
The regression should be gone in 4.6.9v2: https://github.com/Aris-t2/CustomCSSforFx/releases/tag/4.6.9
