### ISSUE TITLE
[macOS][ac_popup_result_font_size.css] font size too small

### ISSUE THREAD

**Issue by ChasCB** [Aris-t2/CustomCSSforFx#725]
Fx = 133.0.3
macOS = 15.2

After having just upgraded to a new Mac mini M4 and 34" screen and done a complete erase and install (not Migration Assistant) I was going through all my Fx settings, after manually bringing over the Fx profile, CustomCSSforFx 4.6.9 and my own userChrome css and noticed that all is good except the ac_popup_result_font_size.

![Screenshot 2024-12-25 at 14 31 21](https://github.com/user-attachments/assets/3b968eb7-a770-4324-b5ea-b79011482a95)

The screen shot does it no justice but if you compare the urlbar font size with the ac_popup_result_font_size then it is very large at by 25% more.

Now I have never altered the font size in this drop down from its current 10px in **ac_popup_result_font_size.css** or **general_variables .css**

Having tried to rectify this by entering a smaller font size in both those files with not resulting change.

The only userChrome.css I have for this area is:

`/*********************************************/
/* ac_popup_megabar appearance time limit */
/*********************************************/

@keyframes delayed-hide {
    from {
    visibility: visible;
    height: auto;
}
    to {
    visibility: collapse;
    height: 0;
  }
}
#urlbar[open] > .urlbarView {
    animation: delayed-hide 0s linear 4s 1 forwards;
}`

**Comment by Aris-t2** [comment]
Try to disable `ac_popup_result_font_size.css` and see, if the default font size offers a better result.

**Comment by ChasCB** [comment]
Thank you that worked.
Merry Christmas 🎄 and have a fabulous New Year 🍾
