### ISSUE TITLE
[Page context menu] CSS for removing items (share code here)

### ISSUE THREAD

**Issue by qusielle** [Aris-t2/CustomCSSforFx#76]
There is a cool manual to remove waste items from context menus: https://www.reddit.com/r/firefox/comments/7dvtw0/guide_how_to_edit_your_context_menu/
Could you include this to your project?
And thank you so much for your custom css! This is why i returned to FF.

**Comment by Aris-t2** [comment]
There are about **94 items** inside that context menu, if you count menuitems, menus and separators (excluding installed add-ons).

The mentioned list only covers the parts for "page context" and "link context" and misses the rest: media/video, images, marked text etc.
I'm not going to include the full list, but also not only some part of it, sorry.

**Comment by stonecrusher** [comment]
Aris is right, it covers just roughly 1/3 of the menu items available.
But it covers the most common / annoying items and would have been helpful to me, too,  as I had to inspect everything by myself to find the right selectors.

Maybe we could provide the link to the tutorial on "Other projects"? If the reddit post is not updated, I'm seriously thinking about opening that as GitHub project, providing a rudimental substitute for MenuWizard addon.

**Comment by Aris-t2** [comment]
The first and third are basically ports of CTR options.

The second one is there, because its a stupid Firefox issue to show this item when sync is not used.

A file to manage all 94 entries of page context menu would be 580 lines long. I doubt anybody would like to go through that amount of code to just find a specific item.

**Comment by stonecrusher** [comment]
>  I doubt anybody would like to go through that amount of code

Of course it will be divided in blank context menu, link context menu, image context menu, video context menu and so on.

**Comment by Aris-t2** [comment]
Feel free to create those files.

**Comment by stonecrusher** [comment]
For sure it's not complete (e.g. I couldn't reach any dictionary and spellchecking related context menus) but should be enough for the moment to cover most of the possible items.

Feel free to copy and adapt.

https://github.com/stonecrusher/simpleMenuWizard

**Comment by userOperaFF** [comment]
@stonecrusher Possible hide disactive options (gray "`#6D6D6D`")?

![obraz](https://user-images.githubusercontent.com/33114475/33525719-a1e5f522-d835-11e7-84f6-e8530a7020a1.png)

**Comment by stonecrusher** [comment]
@userOperaFF Yes, I've made an update to [simpleMenuWizard](https://github.com/stonecrusher/simpleMenuWizard).

But in this case, it's actually just one line in userChrome.css to hide all disabled items:

```CSS
#mainPopupSet menuitem[disabled="true"] { display: none !important; }
```

**Comment by userOperaFF** [comment]
Possible hide double lines in link right click menu, textarea/input right click menu? Maybe hide some menuitem.

link right click menu | textarea/input right click menu
---|---
![obraz](https://user-images.githubusercontent.com/33114475/33631262-5954c96a-da0a-11e7-905b-01ff72d8a8c1.png "link right click menu") | ![obraz](https://user-images.githubusercontent.com/33114475/33631294-73f868c6-da0a-11e7-9c1b-523766a4ecfc.png "textarea/input right click menu")

**Comment by stonecrusher** [comment]
I don't know where you have those separators from. Between Inspect Element and Block element is just one separator for me and no further item.

From the sourcecode the only things that might be in between are
```CSS
#context-media-eme-separator,
#context-media-eme-learnmore  /* Learn more about DRM... */
   { display:none !important; }
```
You can try that code, see if it helps.
Otherwise it's something you changed or from addons. Try to disable each respectively and see what happens.

I guess both uBlock and bitwarden add a separator.

**Comment by userOperaFF** [comment]
```
