### ISSUE TITLE
If E10 is disabled, some image links don't load in Private Mode

### ISSUE THREAD

**Issue by passerby5** [Aris-t2/CustomCSSforFx#79]
**Issue:**
If E10 (multi-process mode) is disabled with this CSS, when browsing in Private Mode you'll sometimes run across image links that don't work.

This issue occurs even with the default ini in the CSS package.

**Steps to Reproduce**

Disable E10 by setting the following about:config entries:
    browser.tabs.remote.autostart = false
    browser.tabs.remote.autostart.2 = false

Restart the browser and it will then be in single-process mode.

Open a New Private Window.

Test this link: http://images.chinahighlights.com/allpicture/2015/04/c731d2f9505047759943d1b9.jpg

Nothing will happen. It will still look like you're on a New Private Tab.

**Comment by Aris-t2** [comment]
This is obviously a Firefox bug as there are no multiple different ways to write CSS for non-E10s and E10s mode.
