### ISSUE TITLE
[about:config] old about:home / about:newtab

### ISSUE THREAD

**Issue by userOperaFF** [Aris-t2/CustomCSSforFx#83]
**`browser.newtabpage.activity-stream.enabled`** _= false_

![image](https://user-images.githubusercontent.com/33114475/33552571-abf48bd0-d8f5-11e7-971e-29f9d8039b00.png) |
![image](https://user-images.githubusercontent.com/33114475/33552580-b2ae6dce-d8f5-11e7-8698-ed309e00c350.png)
--- | ---

Possible show buttons _"luncher"_ of `about:home`:

![image](https://user-images.githubusercontent.com/33114475/33552736-560e02b8-d8f6-11e7-8179-00a8dee04557.png) |
--- |

---

When disable by Mozilla, I do not know.

Bugs with `dark_appearance.css`.

**Comment by Aris-t2** [comment]
I will tweak the code a bit for that case and also add on option to make the "launcher" visible, if browser.newtabpage.activity-stream.enabled is set to false.

**Comment by Aris-t2** [comment]
-> 1.4.6

**Comment by userOperaFF** [comment]
Good 👍
