### ISSUE TITLE
 [Firefox (Nightly)] restart add-on/script speeds up testing userChrome modifications

### ISSUE THREAD

**Issue by Pizzapops** [Aris-t2/CustomCSSforFx#85]
I realize this may be inappropriate here but... Testing and modifying the Chrome css files requires a lot of restarting Firefox. Exiting and restarting Firefox was a nuisance. All of the restart addons on the Firefox add-ons site were labeled incompatible. Shift-F2 and type "restart" seemed to be my only option. Yesterday, I began digging through my FEBE backups trying various restart apps/versions. I did find one that works, **Restart by Schuzak** version 1.2.8. It provides a icon that that works, a menu bar option (under File) and a keyboard option, Alt-FR.

**Comment by Aris-t2** [comment]
Using legacy add-ons only works on Nightly. What do you have in mind when you are talking about userChrome mods?

**Comment by stonecrusher** [comment]
Alternatively you can edit your code directly in the developer console `ctrl + shift + alt + i` (needs to be [enabled once](https://github.com/Aris-t2/CustomCSSforFx#how-to-find-item-ids-and-attributes)).
In the tab "Style editor" you will find all .css files that are currently applied. Sometimes it needs 1 or 2 seconds to refresh, but changes will take place immediately without restart (except adding `@imports`; can be done with the button at the top left).

**Comment by userOperaFF** [comment]
Or script bash/bath/VBA (kill firefox and open new process) and shortcut.

Powershell is to slow.

**Comment by WagnerGMD** [comment]
That's right a lot and that's bad... (because I believe too, they could create one button to restart Firefox).
At least one little good news : another way exist on the page : **about:profiles**. It might help if you aren't aware about.

**Comment by Aris-t2** [comment]
Thanks for the 'about:profiles' note. I will add it to the readme.

**Comment by WagnerGMD** [comment]
You're welcome @Aris-t2.

**Comment by rayman89** [comment]
Also shift + f2 and type restart

**Comment by userOperaFF** [comment]
@rayman89  read:

>Shift-F2 and type "restart" seemed to be my only option.

To slow for @Pizzapops

**Comment by Pizzapops** [comment]
**[Sporif](https://gist.github.com/Sporif/ad6e917d87787491538bac80d3c8918c)** posted a javascript for a "_Moveable Restart Button for Firefox_" on **GitHub**Gist. I haven't tinkered with it yet. My javascript knowledge is minimal. Sporif is working on [Firefox Quantum compatible userChrome.js](https://github.com/Sporif/firefox-quantum-userchromejs).

**Comment by Aris-t2** [comment]
I adopted this useChrome.js method (->1) for my "scrollbar" tweaks a while ago.
https://github.com/Aris-t2/Scrollbars

One can do a lot of stuff after importing user scripts start working incl. additional toolbars and buttons. You can find many scripts here https://github.com/ardiman/userChrome.js including a movable restart button.

**Comment by Pizzapops** [comment]
@Aris-t2 
Sporif's script works fine. There seems to be a conflict with Schuzak's Restart but disabling that Legacy add-on fixed the problem. My translator is going to get a workout when I check out all of Ardiman's scripts.

**Comment by userOperaFF** [comment]
Add info when modified work without XBL (for the future).

**Comment by krystian3w** [comment]
https://luke-baker.github.io/chrome/Buttons_restart.uc.js - work longer than XBL or this also use XBL?

**Comment by Aris-t2** [comment]
The "XBL" talk was about the different methods custom JavaScripts get loaded by Firefox.

The scripts are independent of XBL.

**Comment by krystian3w** [comment]
Possible work this script without <ins>userChrome.xml</ins> from /xml/ (I have no idea how put here - this a long ago.) - when delete buttons "restart" are gone.
<details>
  <summary><kbd>/chrome/xml/userChrome.xml</kbd></summary>

```html
<?xml version="1.0"?>
<!-- Copyright (c) 2017 Haggai Nuchi
Available for use under the MIT License:
https://opensource.org/licenses/MIT
 -->

<!-- Run userChrome.js/userChrome.xul and .uc.js/.uc.xul/.css files  -->
<bindings xmlns="http://www.mozilla.org/xbl">
    <binding id="js" extends="chrome://global/content/bindings/toolbarbutton.xml#menu">
        <implementation>
            <constructor><![CDATA[
                if(window.userChromeJsMod) return;
                window.userChromeJsMod = true;
                
                var chromeFiles = FileUtils.getDir("UChrm", []).directoryEntries;
                var xulFiles = [];
                var sss = Cc['@mozilla.org/content/style-sheet-service;1'].getService(Ci.nsIStyleSheetService);
                
                while(chromeFiles.hasMoreElements()) {
                    var file = chromeFiles.getNext().QueryInterface(Ci.nsIFile);
                    var fileURI = Services.io.newFileURI(file);
                    
                    if(file.isFile()) {
                        if(/(^userChrome|\.uc)\.js$/i.test(file.leafName)) {
                            Services.scriptloader.loadSubScriptWithOptions(fileURI.spec, {target: window, ignoreCache: true});
                        }
                        else if(/(^userChrome|\.uc)\.xul$/i.test(file.leafName)) {
                            xulFiles.push(fileURI.spec);
                        }
                        else if(/\.as\.css$/i.test(file.leafName)) {
                            if(!sss.sheetRegistered(fileURI, sss.AGENT_SHEET))
                                sss.loadAndRegisterSheet(fileURI, sss.AGENT_SHEET);
                        }
                        else if(/^(?!(userChrome|userContent)\.css$).+\.css$/i.test(file.leafName)) {
                            if(!sss.sheetRegistered(fileURI, sss.USER_SHEET))
                                sss.loadAndRegisterSheet(fileURI, sss.USER_SHEET);
                        }
                    }
                }
                
                setTimeout(function loadXUL() {
                    if(xulFiles.length > 0) {
                        document.loadOverlay(xulFiles.shift(), null);
                        setTimeout(loadXUL, 5);
                    }
                }, 0);
            ]]></constructor>
        </implementation>
    </binding>
</bindings>
```

</details>

<details>
  <summary><kbd> /chrome/userChrome.js </kbd></summary>

```js
// Copyright (c) 2017 Haggai Nuchi
// Available for use under the MIT License:
// https://opensource.org/licenses/MIT

// Set "useLionFullScreen" in the same way that it's done in
// chrome://browser/content/browser-fullScreenAndPointerLock.js
XPCOMUtils.defineLazyGetter(FullScreen, "useLionFullScreen", function() {
    return false;
});


// start button

(function() {
	if(location != 'chrome://browser/content/browser.xul') 
        return;
    
	try {
		CustomizableUI.createWidget({
			id: 'restart-button',
			type: 'custom',
			defaultArea: CustomizableUI.AREA_NAVBAR,
			onBuild: function(aDocument) {			
				var toolbaritem = aDocument.createElementNS('http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul', 'toolbarbutton');
                toolbaritem.onclick = event => onClick(event);
				var props = {
					id: 'restart-button',
					class: 'toolbarbutton-1 chromeclass-toolbar-additional',
					label: 'Restart',
					tooltiptext: 'Restart (with middle click userChrome.js cache is emptied)',
					style: 'list-style-image: url(chrome://browser/skin/sync.svg)'
                };		
				for(var p in props)
					toolbaritem.setAttribute(p, props[p]);				
				return toolbaritem;
			}		
		});
	} catch(e) {};		
    
    function onClick(event) {
        if(event.button == 1)
            Services.appinfo.invalidateCachesOnRestart();
        else if(event.button == 2) 
            return;

        let cancelQuit = Cc["@mozilla.org/supports-PRBool;1"].createInstance(Ci.nsISupportsPRBool);
        Services.obs.notifyObservers(cancelQuit, "quit-application-requested", "restart");
        if(!cancelQuit.data) 
            Services.startup.quit(Services.startup.eAttemptQuit | Services.startup.eRestart);
    }
})();

// end button

// start menu

(function() {
	if(location != 'chrome://browser/content/browser.xul')
    return;

  const text = "Restart";
  const icon = "list-style-image: url(chrome://browser/skin/sync.svg)";

  try {
    CustomizableUI.createWidget({
      id: 'restart-button',
      type: 'custom',
      defaultArea: CustomizableUI.AREA_NAVBAR,
      onBuild: function(aDocument) {
        var toolbaritem = aDocument.createElementNS('http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul', 'toolbarbutton');
        toolbaritem.onclick = event => restartNow(event);
        var props = {
          id: 'restart-button',
          class: 'toolbarbutton-1 chromeclass-toolbar-additional',
          label: text,
          tooltiptext: text,
          style: icon
        };
        for(var p in props)
          toolbaritem.setAttribute(p, props[p]);
        return toolbaritem;
      }
    });
  } catch(e) {};
  
  function restartNow(event) {
    if(event.button == 1)
      Services.appinfo.invalidateCachesOnRestart();
    else if(event.button == 2) 
      return;

    let cancelQuit = Cc["@mozilla.org/supports-PRBool;1"].createInstance(Ci.nsISupportsPRBool);
    Services.obs.notifyObservers(cancelQuit, "quit-application-requested", "restart");
    if(!cancelQuit.data) 
      Services.startup.quit(Services.startup.eAttemptQuit | Services.startup.eRestart);
  }

  // Hamburger menu entry
  var menupanelexit = document.getElementById("appMenu-quit-button");
  var menupanelrestart = document.createElement("toolbarbutton");
  menupanelrestart.setAttribute("id","appMenu-restart-button");
  menupanelrestart.setAttribute("class","subviewbutton subviewbutton-iconic");
  menupanelrestart.setAttribute("label",text);
  menupanelrestart.setAttribute("style",icon);
  menupanelrestart.onclick = event => restartNow(event);
  menupanelexit.parentNode.insertBefore(menupanelrestart, menupanelexit);

  // File menu entry
  var menufileexit = document.getElementById("menu_FileQuitItem");
  var menufilerestart = document.createElement("menuitem");
  menufilerestart.setAttribute("id","menu_FileRestartItem");
  menufilerestart.setAttribute("label",text);
  menufilerestart.setAttribute("accesskey","R");
  menufilerestart.addEventListener("command", restartNow, false);
  menufileexit.parentNode.insertBefore(menufilerestart, menufileexit);

})();

//end menu

```

</details>

**Comment by Aris-t2** [comment]
This project here is not about userChrome.js and your userChrome.xml/userChrome.js are not from my linked "scrollbars" page, so I can not say anything about them or how they work.

Look at what https://github.com/Aris-t2/Scrollbars offers for methods 1 and 2 and decide which one you prefer. Read all instructions on the main page.

Method 1 imports new user scripts through /chrome/userChrome/userChrome.xml file
```
load_js_script("custom_scrollbars.uc.js");
load_js_script("my_script.uc.js");
```

Method 2 imports new user scripts through /chrome/ userChrome.js file ->
```
userChrome.import("/userChrome/custom_scrollbars.uc.js", "UChrm");
userChrome.import("/userChrome/my_script.uc.js", "UChrm");
```

**Comment by krystian3w** [comment]
OK, I found what load xml to works buttons:

```css
toolbarbutton#alltabs-button {
    -moz-binding: url("./../xml/userChrome.xml#js");
}

**Comment by Aris-t2** [comment]
It is not deprecated yet, but Mozilla plans it for the (near?) future.

**Comment by krystian3w** [comment]
Ok 👌

**Comment by Aris-t2** [comment]
**Restart button script - working in Firefox 62**

If Firefox should use only custom script, there is way without userChrome.js loading code from inside **config.js**. Otherwise use code inside a **restart.uc.js** or similar with userChrome.js.


.\firefox\defaults\pref\config-prefs.js

```
pref("general.config.obscure_value", 0);
pref("general.config.filename", "config.js");
```

.\firefox\config.js
```
//
(function() {

try {
  Components.utils.import("resource:///modules/CustomizableUI.jsm");
  CustomizableUI.createWidget({
	id: "uc-restart",
	defaultArea: CustomizableUI.AREA_NAVBAR,
	removable: true,
	label: "Restart",
	tooltiptext: "Restart",
	onClick: function() {
	  var {Services} = Components.utils.import("resource://gre/modules/Services.jsm", {});
	  var cancelQuit   = Components.classes["@mozilla.org/supports-PRBool;1"].createInstance(Components.interfaces.nsISupportsPRBool);
	  var observerSvc  = Components.classes["@mozilla.org/observer-service;1"].getService(Components.interfaces.nsIObserverService);
			
	  observerSvc.notifyObservers(cancelQuit, "quit-application-requested", "restart");
		
	  if(cancelQuit.data) return false;
			
	  Services.startup.quit(Services.startup.eRestart | Services.startup.eAttemptQuit);
	},
	onCreated: function(button) {
	  button.style.listStyleImage = 'url("chrome://browser/skin/reload.svg")';
	  return button;
	}
		
  });
} catch (e) {
	Components.utils.reportError(e);
};

})();

```

**Comment by Acid-Crash** [comment]
Hi @Aris-t2.
Just tried your **Restart button script - working in Firefox 62** script for the first time.
Works like a charm.
Quick question: is it possible to amend restart button inside app/hamburger button (just before regular exit button)?

**Comment by Aris-t2** [comment]
Have't tried that yet. The code was a modification of a "Quit" button from German camp-firefox forums, where I switched the "quit" code with restart code.

The even button is not fixed to left clicks only.

**Comment by hopalongrock** [comment]
It works great in Firefox 60 and 61 beta

**Comment by Acid-Crash** [comment]
@Aris-t2 
button.style.transform='scaleX(-1)'; produced i bug when button is pinned to overflow menu
![image](https://user-images.githubusercontent.com/32600318/40357992-8e8bf096-5dc6-11e8-9922-4d3d89693d1a.png)

**Comment by Aris-t2** [comment]
If someone wants to customize the icon:
`button.style.listStyleImage = 'url("chrome://browser/skin/reload.svg")';`
--> replace 'chrome://browser/skin/reload.svg' with a different icon / patch to icon
`button.style.color = 'red';`
--> replace 'red' with a different color name / code
`button.style.transform='scaleX(-1)';`
--> remove, if icon and button should not be "mirrored" (solves problem in overflow menu)

**Comment by Aris-t2** [comment]
If someone wants to customize the icon:
`list-style-image: url("chrome://browser/skin/reload.svg");`
--> replace 'chrome://browser/skin/reload.svg' with a different icon / path to icon
`fill: red;`
--> replace 'red' with a different color name / code
`transform: scaleX(-1);`
--> remove, if icon should not be "mirrored"

**Comment by krystian3w** [comment]
Fantastic, I have now two buttons and newest should alive disable `-moz-binding`.


I will miss the buttons under the <kbd>F10</kbd> > `File` and `PanelUI-button` (appbutton) dropdown lists.

**Comment by Aris-t2** [comment]
Looks I was wrong about items not being possible to add to Firlemenu or PanelUI-button. The scripts require userChromeJS setup and only don't work with my "config.js" shortcut.

**Comment by Aris-t2** [comment]
Looks I was wrong about items not being possible to add to Filemenu or PanelUI-button. The scripts require userChromeJS setup and only don't work with my "config.js" shortcut.

This script add a "Restart" menutiem to "File" menu: https://github.com/Endor8/userChrome.js/blob/master/addrestartbutton/addRestartButton.uc.js

**Comment by Aris-t2** [comment]
Looks I was wrong about items not being possible to add to Filemenu or PanelUI-button. The scripts require userChromeJS setup and only don't work with my "config.js" shortcut.

This script add a "Restart" menutiem to "File" menu: https://github.com/Endor8/userChrome.js/blob/master/addrestartbutton/addRestartButton.uc.js

**Comment by Aris-t2** [comment]
I modified the above linked "Restart" item script for "File" menu and "Application" menu. It works fine with Firefox 60+ and has to be used with userChromeJS ([like shown here for example](https://github.com/Aris-t2/Scrollbars)).

```javascript
// Restart item script for Firefox 60+ by Aris
//
// left-click on restart item: normal restart
// middle-click on restart item: restart + clear caches
// right-click on restart item: no special function
//
// based on 'addRestartButton.uc.js' script by Alice0775
// restart code from Classic Theme Restorer add-on
// invalidate caches from Session Saver add-on

var {Services} = Components.utils.import("resource://gre/modules/Services.jsm", {});

var RestartMenuFileAppItems = {
  init: function() {

	label = "Restart";

	filemenuitem = document.createElement("menuitem");
	filemenuitem.setAttribute("label", label);
	filemenuitem.setAttribute("id","fileMenu-restart-item");
	filemenuitem.setAttribute("key", "R");
	filemenuitem.setAttribute("insertbefore", "menu_FileQuitItem");
	filemenuitem.setAttribute("onclick", "if (event.button == 0) {RestartMenuFileAppItems.restartApp(false);} else if (event.button == 1) {RestartMenuFileAppItems.restartApp(true)};");
	filemenuitem.setAttribute("oncommand", "RestartMenuFileAppItems.restartApp(false);");
	document.getElementById("menu_FileQuitItem").parentNode.insertBefore(filemenuitem,document.getElementById("menu_FileQuitItem"));

	appmenuitem = document.createElement("toolbarbutton");
	appmenuitem.setAttribute("label", label);
	appmenuitem.setAttribute("id","appMenu-restart-button");
	appmenuitem.setAttribute("class","subviewbutton subviewbutton-iconic");
	appmenuitem.setAttribute("key", "R");
	appmenuitem.setAttribute("insertbefore", "appMenu-quit-button");
	appmenuitem.setAttribute("onclick", "if (event.button == 0) {RestartMenuFileAppItems.restartApp(false);} else if (event.button == 1) {RestartMenuFileAppItems.restartApp(true)};");
	appmenuitem.setAttribute("oncommand", "RestartMenuFileAppItems.restartApp(false);");
	document.getElementById("appMenu-mainView").firstChild.insertBefore(appmenuitem,document.getElementById("appMenu-quit-button"));

	var sss = Components.classes["@mozilla.org/content/style-sheet-service;1"].getService(Components.interfaces.nsIStyleSheetService);

	// style button icon
	var uri = Services.io.newURI("data:text/css;charset=utf-8," + encodeURIComponent('\
		\
		  #appMenu-restart-button {\
			list-style-image: url("chrome://browser/skin/reload.svg"); /* icon / path to icon */ \
		  }\
		  #appMenu-restart-button .toolbarbutton-icon {\
			transform: scaleX(-1); /* icon mirroring */\
			color: red; /* icon color name/code */\
		  }\
		\
	'), null, null);
	  
	sss.loadAndRegisterSheet(uri, sss.AGENT_SHEET);
	
  },

  restartApp: function(clearcaches) {
 
	  var cancelQuit   = Components.classes["@mozilla.org/supports-PRBool;1"].createInstance(Components.interfaces.nsISupportsPRBool);
	  var observerSvc  = Components.classes["@mozilla.org/observer-service;1"].getService(Components.interfaces.nsIObserverService);

	  if(clearcaches) {
		Components.classes["@mozilla.org/xre/app-info;1"].getService(Components.interfaces.nsIXULRuntime).invalidateCachesOnRestart();
	  }

	  observerSvc.notifyObservers(cancelQuit, "quit-application-requested", "restart");

	  if(cancelQuit.data) return false;

	  Services.startup.quit(Services.startup.eRestart | Services.startup.eAttemptQuit);

  }

}

RestartMenuFileAppItems.init();

```

**Comment by Aris-t2** [comment]
Just tested "method 2" from "Scrollbars" repository on a new browser/profile configuration and everything still works fine in Firefox 60+.

Repeat the steps mentioned here: https://github.com/Aris-t2/Scrollbars#method-2---files-for-firefox-installation-folder-and-firefox-profile-folder

Use short files names without spaces like:
```
\chrome\userChrome\restart_button.uc.js
\chrome\userChrome\restart_items.uc.js
```

Make sure file names are imported correctly `\chrome\userChrome.js`:
```
userChrome.import("/userChrome/restart_button.uc.js", "UChrm");
userChrome.import("/userChrome/restart_items.uc.js", "UChrm");
```

If required, try to clean your script cache: https://github.com/Aris-t2/Scrollbars#scriptstartup-cache-must-be-deleted-after-every-change

**Comment by hopalongrock** [comment]
Hello Aris,

I followed all  your advice and found that the "Failed to read the configuration file" error was caused by that I accidentally omitted the first (empty) line of config.js before trying.

Now the restart items and the button appear and work fine - it was not enough to delete the startupCache folder, I had to delete the the whole local profile.

**Comment by Acid-Crash** [comment]
Hi @Aris-t2.
Found an interesting bug with Restart button in AppButton (method2).
When I open "Cusomize" (From AppButton or ContextMenu) Restart item multiplies.
![image](https://user-images.githubusercontent.com/32600318/41104522-3ea4b094-6a74-11e8-8e90-c87438791791.png)


BTW. Have I understood correctly that userChrome.js method will stop working/deprecated by Mozilla at some point (when compared to config.js)?

**Comment by Aris-t2** [comment]
I fixed the above code, so it won't be duplicating the items anymore.

userChrome.js achieved using config.js will stay. The deprecation affects the xml binding way of implementing this (aka "method 1" in scrollbars repository).

**Comment by Acid-Crash** [comment]
@Aris-t2. Thx for the fix.
Earlier you have mentioned that Restart item for AppButton isn't possible with config.js. Is this statement still valid or something has changed?

**Comment by Aris-t2** [comment]
I could not get it to work that way. It seems the script needs a certain level of access to the main window which it only gets after userChromeJS is loaded. There might be a way to combing some stuff, but I have to run some tests first.

**Comment by aabatpurdue** [comment]
You don't need to worry about shift + f2 much longer.  See [mozilla](https://developer.mozilla.org/en-US/docs/Tools/GCLI)

**Comment by Aris-t2** [comment]
@aabatpurdue 
I shared my modified restart script because of that deprecation.

Those *+#§ at Mozilla removed developer toolbar, because _according to them_ "this feature was barely used" and those, who used it, mainly used it to restart the browser. Its actually a nobrainer to conclude people need a restart button, but they are way too focused on their "everything has to be restartless" stuff and therefore everything has to work without a restart... even if it does not.

**Comment by aabatpurdue** [comment]
You could change "even if" to "even when".

I found a page somewhere that implied they had nobody to maintain it and, of course, they couldn't put out the money to hire someone.  As the saying goes "money, money, money, the root of all evil" or something like that (:-}).

**Comment by Aris-t2** [comment]
Cleaned up thread/discussion!

**Comment by Pizzapops** [comment]
@Aris-t2 

I have been using Luke Baker's restart with Nuchi's XML file with both FxQ61 & FxQ62. Since XML is a Mozilla Dodo bird, I started switch over to your method 2. It works fine with FxQ61 and Ice Dragon59 but I can not get it to work with Nightly62. The App/firefox files and Chrome files are set up exactly  the same as the earlier FxQ versions. I tried several profiles and some Chrome folder variations with no luck. I did a clean FxQ62 portable install. Only the App files were added and  the Chrome folder with necessary Restart files. Still not working.

Did Mozilla screw up java-script on Nightly or did I miss something?

**Comment by Aris-t2** [comment]
@Pizzapops 
Something got changed or "fixed" in Fx62, so an error inside "method 2" scripts and "restart items" script occurred.

Use the [updated code above](https://github.com/Aris-t2/CustomCSSforFx/issues/85#issuecomment-394647463) for the restart items and the updated ["method 2" (v1.0.4a) from scrollbars project](https://github.com/Aris-t2/Scrollbars/releases/tag/1.0.4).

**Comment by Pizzapops** [comment]
@Aris-t2 
Thanks as always for the quick fix.

**Comment by refriedfood** [comment]
I followed your instructions with method two and I could get it to work. Unltimately I'd like to use it with FF portable. Its structure is pretty much the same, but either way I couldn't get the "restart" option to even show up in the file menu.

**Comment by Acid-Crash** [comment]
@refriedfood.
Hi, I do successfully use Restart script on FF Nightly portable (Windows).
You need to do the following:
FirefoxPortableNightly\App\firefox64\defaults\pref\
Update channel-prefs.js
FirefoxPortableNightly\App\firefox64\
Add here config.js

FirefoxPortableNightly\Data\profile\chrome\
Add userChrome.js and userChrome folder

startupCache (needs to be cleared) folder is here FirefoxPortableNightly\Data\profile\startupCache\

**Comment by refriedfood** [comment]
I did that, too. I don't know what magic you're doing, but I certainly don't have the same spell you do.

**Comment by Pizzapops** [comment]
@refriedfood 
Click on [ItWorks](https://www.dropbox.com/s/mqno6pe57swztp6/FoxQPortableNightly.zip?dl=0) and click Download. It is a clean FXNightly.zip with only JS added and has nine functioning scripts including left sidebar. Follow @Acid-Crash 's directions and clear startupCache before starting Nightly for the first time. Change the default profile in ** about:profiles** to the profile that is included. Be careful not to delete any profiles used by other copies of Nightly.

**Comment by refriedfood** [comment]
That did it. What was missing was a proper config.js in FirefoxPortable\App\Firefox64

So:
**FirefoxPortable\App\Firefox64\**config.js
**FirefoxPortable\Data\profile\chrome\**userChrome.js
\_ `userChrome.import("/userChrome/restart_button.uc.js", "UChrm");
userChrome.import("/userChrome/restart_items.uc.js", "UChrm");`
Must be in userChrome.js
**FirefoxPortable\Data\profile\chrome\userChrome\**userChromeJS.js & userChromeJSutilities.js & restart_items.uc.js & restart_button.uc.js
Cleared **FirefoxPortable\Data\profile\startupCache**

Got it. Great job, and thank you!
Now if I could just get the search bar to stick on the current engine I've selected each time so I don't have to type and then click the engine each time.

**Comment by krystian3w** [comment]
https://mail.mozilla.org/pipermail/firefox-dev/2018-March/006249.html -
if someone was looking for what happened to Firefox Command Line for Developers.

**Comment by bendover22** [comment]
Don't know if this has been mentioned, but I add a bookmark for "about:profiles" to the bookmark toolbar.  It has options to **restart normally & restart w/ addons disabled.**  It's very fast for me.
I keep the bookmarks toolbar hidden & instead add the "open bookmark" icon to the navbar.

I name the bookmark "Restart Fx".  It only takes clicking the bookmark icon, then hovering Bookmarks Toolbar item - where it shows any BM that you added to the BM toolbar.

**Comment by Aris-t2** [comment]
If you use custom js scripts, you can place a button on your toolbar.
I use _restart_button.uc.js_ with my "dev" profile: https://github.com/Aris-t2/CustomJSforFx/tree/master/scripts

**Comment by vladaurosh** [comment]
Hi Aris-t2.
I am not able to add this to FF 68. 
I added this into chrome/userChrome.js
userChrome.import("/userChrome/restart_button.uc.js", "UChrm");
userChrome.import("/userChrome/restart_items.uc.js", "UChrm");

Then I added script from [this link](https://github.com/Aris-t2/CustomCSSforFx/issues/85#issuecomment-394647463) into userChrome/restart_items.uc.js 

What should I add into userChromeJS.js file? 

I created defaults/pref/config-prefs.js and added:
pref("general.config.obscure_value", 0);
pref("general.config.filename", "config.js");
pref("general.config.sandbox_enabled", false);

And config.js as well with:
```
const Cu = Components.utils;
try {
  Cu.import("resource://gre/modules/Services.jsm");
  Cu.import("resource://gre/modules/osfile.jsm");
  if (!Services.appinfo.inSafeMode) {	
	Services.scriptloader.loadSubScript(
	  OS.Path.toFileURI(OS.Path.join(OS.Constants.Path.profileDir,
		"./chrome/userChrome/userChromeJS.js")), this, "UTF-8");	
  };
} catch(e) {};
```

What am I missing here? 

Thanks,

**Comment by Aris-t2** [comment]
Please keep the JS talk inside the corresponding area of the CustomJSforFx repository: https://github.com/Aris-t2/CustomJSforFx/issues/4

Everything you need to know is written on the main page of that repository: https://github.com/Aris-t2/CustomJSforFx/

I recommend to test M2 with a clean new Fx profile.

**Comment by vladaurosh** [comment]
Thanks Aris-t2, will do.
I cleared script/startup cache, and it works now.

**Comment by vladaurosh** [comment]
Looks like new FF broke this. :(
File menu is not horizontal and missing Restart.

**Comment by Aris-t2** [comment]
Test a new profile, make sure you have updated CSS files, JS methods and JS scripts, if you are using them. Also check if this pref is set correctly:
'about:config > toolkit.legacyUserProfileCustomizations.stylesheets > true'

**Comment by hopalongrock** [comment]
I have the same issue with FF 69 and 70 beta.
Based on Aris's comment I downloaded and copied the files from CustomJSforFx, Method 2, the restart scripts from here.  Now I have 3 program folders and 4 profiles, all have this problem. The interesting thing is that the restart button works fine.
Maybe the restart_items.uc.js script is causing it.

**Comment by Aris-t2** [comment]
Try to setup a new test profile and make sure you are cleaning the corresponding cache folder.

All scripts work up to Fx 71 Nightly.

**Comment by Aris-t2** [comment]
Future script talk can be done within the script repository:
https://github.com/Aris-t2/CustomJSforFx

**Comment by krystian3w** [comment]
This may work https://addons.mozilla.org/firefox/addon/restart_browser/

but need test to anti-malware in code (`Moz://a` maybe failed).
