### ISSUE TITLE
[Win10][Fx59] square tab loading animation change

### ISSUE THREAD

**Issue by Pizzapops** [Aris-t2/CustomCSSforFx#87]
Somewhere in the last few versions the loading animation of **classic_squared_tabs.css** has changed from:

`/*====tab loaded full animation====*/
:root {
--tab-loading-fill: #ff8c00 !important;
} `

to

`/* loading animation */
/* #TabsToolbar:not(:-moz-lwtheme) .tabbrowser-tab:not([visuallyselected=true]) {
  --tab-loading-fill: #ff8c00 !important;
}`

Changing the color seems to have no effect, remains blue. I usually change to a Firefox orange, EB9E47.
Is this theme related?

**Comment by Aris-t2** [comment]
I will update the code used inside classic_squared_tabs.css on next update, so setting another loading animation color works again.

**Comment by Aris-t2** [comment]
Get 1.5.0

**Comment by Pizzapops** [comment]
Neither 1.5.0 or 1.5.0.1 (same sq tab file) worked for me. I did find a workaround but I don't know what else it may effect.

Line 14      Change color value to desired color
Line 14      Change **--tab-loading-fill_st** to **--tab-loading-fill**
Line 187  Change **--tab-loading-fill_st** to **--tab-loading-fill**
Line 191  Change **--tab-loading-fill_st** to **--tab-loading-fill**

**Comment by Aris-t2** [comment]
Don't know, but for me changing files root value does the trick, e.g.:
```css
:root {
  --tab-loading-fill_st: red !important;
}
```

**Comment by Aris-t2** [comment]
Any luck?

**Comment by Pizzapops** [comment]
I switched to 1.5.1 and only changed the one line in square tabs as instructed. The animation was still blue, not red as edited. When I get a chance, I will try it with a new profile.

**Comment by Aris-t2** [comment]
Are you sure you edit the correct file? There are two:
classic_squared_tabs.css
classic_squared_tabs_australized_aero.css

Which OS are you testing on?

**Comment by Pizzapops** [comment]
Only edited classic_squared_tabs. I also keep an unedited version of the file in the tabs folder. One one is active at a time. OS is Win10Pro. I will do a new FxQ59 portable install on my laptop tomorrow and will try with no other additions to profile except for your customCSS.

**Comment by Aris-t2** [comment]
Win10FCU + Fx59Nightly 2017.12.12 + CustomCSSforFx 1.5.1 + color mod in classic_squared_tabs.css
![1](https://user-images.githubusercontent.com/6013569/33911747-94089076-df93-11e7-9564-fa83d46a46a0.png)

**Comment by Aris-t2** [comment]
Did you have any luck?
On recent releases 1.5.2+ you only need to edit /config/general_variables.css file to change default animations color used by classic squared tabs. "Default squared tabs" are not affected by this change.

**Comment by Pizzapops** [comment]
I no luck with my laptop, Win64Pro, neither 12/13FxQ64 portable or12/13FxQ32 (installed)  could override the blue fill. Both used new CustomCSS 1.5.1. with no add-ons or themes.

Updating my desktop to 12/14 broke my access to http and https and required config security tweaks. I updated to CustomCSS 1.5.2 and made my normal modifications.  I am using an additional line in **classic_squared_tabs.css** to get my desired orange tab fill.

`:root {

  --classic_squared_tabs_tab_height: 26px;
  --tab-loading-fill: #EB9E47 !important; **<===**
  --classic_squared_tabs_tab_default_loading_icon_color: #EB9E47 !important; */
  --classic_squared_tabs_active_tab: linear-gradient(to top,#f9f9fa,#f9f9fa,#f9f9fa);
  --classic_squared_tabs_hovered_tabs: linear-gradient(to top,#cac7c1,#d5d2cc,#e8e6e2);`

According to the css I should not be getting orange fill. I found using **--tab-loading-fill** as a text color for my sidebar gives me orange text. Using **--classic_squared_tabs_tab_default_loading_icon_color** gives me blue text. I don't understand it.

**Comment by Aris-t2** [comment]
I don't know why it is not working for you.

In 1.5.1 changing
```css
:root {
  --tab-loading-fill_st: orange !important;
}
```
in `classic_squared_tabs.css` did the trick.

In 1.5.2 changing
```css
:root {
  --classic_squared_tabs_tab_default_loading_icon_color: orange !important;
}
```
in `general_variables.css` works for me.

![324](https://user-images.githubusercontent.com/6013569/34062272-010a9462-e1ec-11e7-8281-305f9af5217e.png)

Backup your chrome folder and extract this archive there:
[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/1564126/chrome.zip)

**Comment by Pizzapops** [comment]
general_variables.css works for me now. I inactivated line 12 in classic_squared_tabs.css, **classic_squared_tabs_tab_default_loading_icon_color** and it still works. Changing it there seems to have no effect. Is it necessary? Sorry for dragging this on for a week.

**Comment by Aris-t2** [comment]
The variables inside `general_variables.css` are for controlling everything in a central place. The variables inside the actual files like in `classic_squared_tabs.css` are for backup only. If someone only uses lose files without everything else this project provides the variables are still able to do their job.
The `!important;` inside general configuration files is required for every variable to override the default/backup ones.
