### ISSUE TITLE
identitybox_colors - .extensionPage

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#9]
When identitybox_colors module is enabled, there is no styling changes for extension page.
![extensionpage](https://user-images.githubusercontent.com/32600318/31459930-618f5a9a-aecd-11e7-97ee-847af6a63a8d.png)
I believe this can be fixed by adding .extensionPage class to that file

**Comment by Aris-t2** [comment]
Thanks for the heads up. ".extensionPage" class will be handled the way .chromeUI is on next update.

**Comment by Acid-Crash** [comment]
fixed in 1.06
