### ISSUE TITLE
Nightly 59.0a1 > mark HTTP as insecure > identitybox_colors.css

### ISSUE THREAD

**Issue by Acid-Crash** [Aris-t2/CustomCSSforFx#90]
Mozilla added a configuration switch to Firefox 59 (currently available on the Nightly channel) that marks any HTTP site as insecure in the web browser.
security.insecure_connection_icon.enabled:true

When this is enabled there is a padlock on HTTP sites
https://i.paste.pics/c3060dd03cc1e2591b66ba7cd9091a8d.png
This padlock lacks styling introduced by module identitybox_colors.css

**Comment by userOperaFF** [comment]
Maybe disable this icon and comment in forms:

`signon.autofillForms.http`, **true**
`security.insecure_field_warning.contextual.enabled`,  **false**
`security.insecure_password.ui.enabled`,  **false**
 `security.insecure_connection_icon.enabled`, **false**

Add in tweak section.

**Comment by Aris-t2** [comment]
They basically added another class ".notSecure" which can use same rules ".insecureLoginForms" does.

This will be "fixed" on next update for identity box colors and padlock icon options.

**Comment by Aris-t2** [comment]
-> 1.5.2.1

**Comment by Acid-Crash** [comment]
Confirming. It is fixed now

**Comment by krystian3w** [comment]
https://www.ghacks.net/2018/02/14/firefox-60-new-not-secure-indicator-preferences/

**Comment by Aris-t2** [comment]
The changes within this projects files remain working in Firefox 60 Nightly.
