### ISSUE TITLE
[non-default OS theme] Toggling menubar causes toolbar jumping

### ISSUE THREAD

**Issue by Speravir** [Aris-t2/CustomCSSforFx#92]
In issue #88 you wrote
> In the "default configuration" without changing anything tabs jump into titlebar, if menubar is not present, and jump below it, if it is. Maybe there is a special case with some OS theme / DPI value. Open a new issue and describe the OS configuration the jump occurs with. Add screenshots of "before the jump occurs" and "after it occurs".

OK, I have Windows 7 (64bit) with default DPI settings (96dpi). In Fx 57 I have
- the window titlebar hidden (browser default).
- tabs below navigation and bookmarks bar (but above content).
- navbar on top, but `tabs_below_navigation_toolbar_higher_navbar_positon.css` and its siblings deactivated.
- appbutton in titlebar which stays thanks to your recent change (version 1.4.9) in position if the menubar is activated.

When I activate the menu, there is a slight jump for tabs, and the content window gets a bit bigger. I noticed that only the bookmarks toolbar changes slightly its height:
![menubar inactive](https://user-images.githubusercontent.com/899244/34065507-a56eb0ae-e202-11e7-847b-2209d5b592a9.png) ![menubar active](https://user-images.githubusercontent.com/899244/34065506-a54406e2-e202-11e7-857f-970e9594e188.png)

Bookmark toolbar related styles I have activated:
- `buttons_on_bookmarks_toolbar_old_size_and_appearance.css`
- `bookmarks_smaller_more_bookmarks_icon.css`
- `bookmarks_toolbar_old_height.css`
- `bookmarks_toolbar_multiple_lines.css`

I already had it forgotten, but now see again that I also have `buttons_on_menubar_toolbar_classic_appearance.css` activated.

_Update:_
Ooh, just for testing I changed the tabbar style, and noticed with `tabs_below_titlebar_above_navigation_toolbar.css` (this was the only change) the jump occurs in (exactly?) the other direction:
![menubar inactive](https://user-images.githubusercontent.com/899244/34066061-b48ceb76-e209-11e7-8264-7693f7d5aa05.png) ![menubar active](https://user-images.githubusercontent.com/899244/34066060-b46521f4-e209-11e7-8aed-804a208f0a4e.png)

Also I noticed when switching between the image files that there is small line on the left main border below the appbutton when the menu is active. I didn’t notice this until now, so I could live with it, but it’s slightly strange anyway.

And I realized that this may be of relevance, too – I have also activated these styles:
- `toolbars_old_padding.css`
- `tabs_toolbar_adjustments.css`
- `navbar_more_compact_mode.css`

**Comment by Aris-t2** [comment]
Can you test these files?
[chrome.zip](https://github.com/Aris-t2/CustomCSSforFx/files/1564464/chrome.zip)

I did not know you were testing with "tabs below navigation toolbar" enabled.

**Comment by Aris-t2** [comment]
Check latest release 1.5.2.3.

**Comment by Speravir** [comment]
> Check latest release 1.5.2.3.

Now it still jumps, but for both styles in same direction, i.e. for `tabs_below_titlebar_above_navigation_toolbar.css` there seems to be no change.

I scented (? right word?) it would be difficult, hence I hesitated to open the issue.

**Comment by Aris-t2** [comment]
The "jumps" might be hard to track. They do not occur on my system anymore neither with `tabs_below_titlebar_above_navigation_toolbar.css` nor with `tabs_below_navigation_toolbar.css`.

![123](https://user-images.githubusercontent.com/6013569/34075310-bc85f71e-e2c2-11e7-8bf5-cd189eb29fb0.png)

I've tested the same configuration you have.

We could try one more thing. Create a new Portable Firefox setup, add this projects files to it and make sure the issue occurs. Then compress the whole new Portable Firefox folder and post a link here (Dropbox, Zippyshare, Mega will do). Make sure there is no personal data inside that setup anywhere.

**Comment by Speravir** [comment]
@Aris-t2, oh … my … God, I didn’t expect it in this area:

> Create a new Portable Firefox setup, add this projects files to it and make sure the issue occurs.

On preparing I noticed it worked here, as well, with the default theme. So I activated it on my home profile, too, and had to notice the issue was also gone there. So you should be able to see it yourself when activating a light theme (I tested with several themes).

Confer screenshots, first a copy from above, then with default theme (changed by css rules from your collection; daily changed desktop background image accidentally with very blue sky):
![appearance with light theme](https://user-images.githubusercontent.com/899244/34065507-a56eb0ae-e202-11e7-847b-2209d5b592a9.png) ![appearance with default-theme](https://user-images.githubusercontent.com/899244/34083029-4fe5b58e-e369-11e7-8d58-77c5a13d9a5d.png)

So it seems to be something with `:-moz-lwtheme`.

**Comment by Aris-t2** [comment]
I probably should have paid more attention to your first comment about having `buttons_on_menubar_toolbar_classic_appearance.css` activated. That means you have button there.

Buttons on menu toolbar increase its height what moves all toolbars below it up and down depending on its visibility. I don't think there is anything to fix as the jumping only exists, because of the buttons there independent of the theme, default or lw-theme.

Shrinking buttons would not be an option, would it?

```css
#toolbar-menubar toolbarbutton .toolbarbutton-icon {
  padding: unset !important;
  margin: unset !important;
  width: 16px !important;
  height: 16px !important;
}
```

**Comment by Speravir** [comment]
>I probably should have paid more attention to your first comment about having `buttons_on_menubar_toolbar_classic_appearance.css` activated. That means you have button there.

No, I had this intention when I activated it, but did not add anything until now. _(I also hoped for a future potential addition of the tab title like in the addon Hide Caption Titlebar Plus)_ That’s also the reason why I wrote I had forgotten it.

I could live with it, if you would add a warning for this style that it causes a menubar with a bigger height and slight jump with appbutton in toolbar activated, but on the other hand this does not explain the difference between default theme and lightweight theme as shown above.

**Comment by Aris-t2** [comment]
For me there is no difference between default theme and lw-themes when it comes to menubars height with or without appbutton and/or "other" buttons on menubar.

**Comment by Speravir** [comment]
I updated my latest posting above which has screenshots. I tested with several themes, but of course not all of them. :-) But for all I tested I still see the small jump, cf. default (copy from above) and the light theme I usually have active (it’s by the way [Warm Brushed Metal](https://addons.mozilla.org/firefox/addon/warm-brushed-metal/)).

![appearance with default-theme](https://user-images.githubusercontent.com/899244/34083029-4fe5b58e-e369-11e7-8d58-77c5a13d9a5d.png) ![apperarance with lwtheme](https://user-images.githubusercontent.com/899244/34137116-71ff9e04-e469-11e7-9127-af0b02191ade.png)

And this does not change if I deactivate `buttons_on_menubar_toolbar_classic_appearance.css` (I let it deactivated from now until potentially needed).

**Comment by Aris-t2** [comment]
I think this is a different story and not related to the topic "Bookmarks toolbar changes slightly its height if **_menubar_** is activated".

Backup and remove everything you have in `chrome` folder and repeat the test. ;-)

You will see the ui jumps by default when toggling lw-themes, because some ui border get removed, which are not required once a lw-theme is active.

**Comment by Speravir** [comment]
Yes, you are right. I noticed this myself, but too late.

But there is also a difference _with_ menubar, cf. https://www.xup.in/dl,12542733/Video_20171219-190415.mp4/ (video will be deleted after some time).

**Comment by Aris-t2** [comment]
Test this with the default window theme.

**Comment by Aris-t2** [comment]
I have tested this on Windows 7 AeroGlass default theme and Windows 8 default OS themes and on both menubar visibility has no impact on toolbars/menubars height.

**Comment by Speravir** [comment]
Oh … my … god. You can remove the question mark in your changed title – it _is_ caused by the non default OS theme! If I had guessed this I wouldn’t have started this issue thread. So we had much noise about almost nothing, sorry for the trouble.

**Comment by Aris-t2** [comment]
Well, the issue template is exactly for these kind of cases. ;-)

> System information
> OS & OS version: 
> **_OS theme:_** 
> DPI / HiDPI resolution: 
> Firefox version: 
> Firefox theme: 
> Settings this issue occurs with: 


Feel free to close this issue, if it is "solved" in general.

**Comment by Speravir** [comment]
> Well, the issue template is exactly for these kind of cases. ;-)

Yeah, I’m embarrassed.
