### ISSUE TITLE
open library windows with a button

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#93]
is possible to open the library window with a button?

<a href='https://postimg.org/image/j5zl8ya81/' target='_blank'><img src='https://s8.postimg.org/j5zl8ya81/Cattura.png' border='0' alt='Cattura'/></a>

or also the window history (ctrl+shift+H)

like the bookmars button (ctrl+shift+b).

**Comment by Aris-t2** [comment]
No, CSS can not do that.
Please use the general support thread for questions like this as mentioned inside issue template.
