### ISSUE TITLE
[Windows classic OS theme] black text color in the dark blue menu bar not visible

### ISSUE THREAD

**Issue by HugoBo-SS** [Aris-t2/CustomCSSforFx#95]
black text color in the dark blue menu bar not visible

**Comment by Aris-t2** [comment]
Screenshots?
OS?
Anything from the issue template?

**Comment by HugoBo-SS** [comment]
Win 7 x86
classic
1600x1200
57.0.2
standart
![2017-12-20_010735](https://user-images.githubusercontent.com/23690012/34181198-5e22f26e-e522-11e7-9ef3-88a5f719a6b9.jpg)
In the light theme and dark theme font white (ok)

**Comment by Aris-t2** [comment]
OK, Windows Classic OS theme was the culprit.
Check "custom_css_for_fx_v1.5.3.1.zip" file in releases area.

**Comment by HugoBo-SS** [comment]
Now everything is all right. Thank you. :)
