### ISSUE TITLE
No issue, only big thanks

### ISSUE THREAD

**Issue by mazesy** [Aris-t2/CustomCSSforFx#96]
CustomCSSforFx is a great accomplishment and a work in progress.
When I moved to Firefox 57 I was most happy to discover this work which I now follow and which allows a considerable amount of GUI tweaking I never would have thought possible until now.

Be thanked, Aris-t2

For whom may be interested, a 1-line css which simply sets a dark shade at the bottom of the navigator toolbox, simply to distinguish what on the screen is part of the Firefox GUI and what belongs to the Website :=)

```
/* 3D SHADE BUT NOT IN FULLSCRREEN */
#navigator-toolbox:not([inFullscreen="true"]) {position: relative !important; box-shadow: 0 6px 4px -4px #000 !important;}
```
Read you later!

**Comment by Aris-t2** [comment]
Thanks.
Continue here: https://github.com/Aris-t2/CustomCSSforFx/issues/88
