### ISSUE TITLE
color url bar: can I insert this?

### ISSUE THREAD

**Issue by gabri25ele** [Aris-t2/CustomCSSforFx#97]
https://www.reddit.com/r/FirefoxCSS/comments/7dkhuh/color_your_url_bar_based_on_website_security/

**Comment by Aris-t2** [comment]
You can add that code to the bottom of the userChrome.css.

Please do not open "new issues" for questions like that. Use the general support thread, that is also mentioned inside the issue template.

https://github.com/Aris-t2/CustomCSSforFx/issues/88
